import {createCore,heading,syncHeading,q,escape,svg,uniqueId,asStrings,makeOverlay,type FoundationConfig,type FoundationOptions,type FoundationController,type FoundationValue} from '../core.ts';
import {continuumArt} from './art.ts';
import {attachCalendarMotion} from './calendar-motion.ts';
import {parseDate,dateText,validDate} from '../date.ts';
export {parseDate,dateText,validDate};
export function renderDate(o:FoundationOptions):string{return heading(o)+`<div class="ff-date-fields"><input data-date="0" type="${o.mode==='time'?'time':o.mode==='datetime'?'datetime-local':'date'}" aria-label="${escape(o.label)}"><span data-date-separator ${o.mode==='range'?'':'hidden'}>—</span><input data-date="1" type="date" aria-label="${escape(o.label)} 終了日" ${o.mode==='range'?'':'hidden'}><button type="button" data-calendar-toggle class="ff-icon-button" aria-label="カレンダーを開く" ${o.mode==='time'?'hidden':''}>${svg('calendar')}</button></div><div class="ff-floating ff-calendar" data-calendar><div class="ct-calendar-envelope" aria-hidden="true"><i></i><i></i><i></i></div><div class="ct-calendar-mast"><div class="ct-calendar-identity"><span data-ct-date-caption>日付を選択</span><strong data-ct-date-number>—</strong></div><div class="ct-calendar-scene" aria-hidden="true"></div></div><header class="ff-calendar-header"><button type="button" data-month="-1" aria-label="前の月">‹</button><strong data-month-title aria-live="polite"></strong><button type="button" data-month="1" aria-label="次の月">›</button></header><div class="ff-weekdays" aria-hidden="true">${['月','火','水','木','金','土','日'].map(d=>`<span>${d}</span>`).join('')}</div><div class="ct-calendar-page"><div class="ct-calendar-sheet" aria-hidden="true"></div><div class="ff-calendar-grid" data-calendar-grid role="grid" aria-label="日付を選択"></div></div><footer><button type="button" data-today>今日</button><span>LOCAL DATE</span><button type="button" data-date-clear>クリア</button></footer></div><span class="ff-date-message" data-date-message role="status"></span>`;}
export function mountDate(root:HTMLElement,config:FoundationConfig,options:FoundationOptions={}):FoundationController {
 function normalize(value:FoundationValue,o:FoundationOptions):FoundationValue {const values=asStrings(value);if(o.mode==='time'){const text=String(value??'');return /^\d\d:\d\d$/.test(text)&&Number(text.slice(0,2))<24&&Number(text.slice(3))<60?text:'';}if(o.mode==='datetime'){const text=String(value??''),date=text.slice(0,10);return validDate(date,o)&&/^\d{4}-\d\d-\d\dT\d\d:\d\d$/.test(text)&&Number(text.slice(11,13))<24&&Number(text.slice(14,16))<60?text:'';}
  const dates=values.filter(v=>validDate(v,o));return o.mode==='range'?dates.slice(0,2).sort():dates[0]??'';
 }
 const c=createCore(root,config,options,normalize);root.classList.add('sop-continuum');if(!root.querySelector('.ct-calendar-mast'))root.innerHTML=renderDate(c.options);
 const inputs=[q<HTMLInputElement>(root,'[data-date="0"]'),q<HTMLInputElement>(root,'[data-date="1"]')],panel=q<HTMLElement>(root,'[data-calendar]'),toggle=q<HTMLButtonElement>(root,'[data-calendar-toggle]'),grid=q(root,'[data-calendar-grid]');panel.id=uniqueId('sop-calendar');panel.setAttribute('role','dialog');panel.setAttribute('aria-label',c.options.label??'日付');toggle.setAttribute('aria-controls',panel.id);toggle.setAttribute('aria-haspopup','dialog');
 const motion=attachCalendarMotion(root,panel,c);c.cleanup(()=>motion.destroy());
 const first=asStrings(c.data)[0];let cursor=parseDate(first?.slice(0,10)??'')??new Date(),view=new Date(cursor.getFullYear(),cursor.getMonth(),1,12);const overlay=makeOverlay(c,panel,toggle,'bottom',q<HTMLElement>(root,'.ff-date-fields'));
 function choose(text:string){if(c.options.disabled||c.options.readOnly||!validDate(text,c.options))return;cursor=parseDate(text)!;view=new Date(cursor.getFullYear(),cursor.getMonth(),1,12);let next:FoundationValue=text;
  if(c.options.mode==='range'){const old=asStrings(c.data);next=old.length!==1?[text]:[old[0],text].sort();}else if(c.options.mode==='datetime'){const old=String(c.data??'');next=text+'T'+(old.includes('T')?old.split('T')[1]:'12:00');}
  c.send(next);if(c.options.mode!=='range'||asStrings(next).length===2){overlay.hide();motion.hide();toggle.focus();}else paint();
 }
 function paint(){const restoreFocus=grid.contains(document.activeElement);const start=new Date(view.getFullYear(),view.getMonth(),1,12),offset=(start.getDay()+6)%7,values=asStrings(c.data).map(v=>v.slice(0,10)),today=dateText(new Date());
  q(panel,'[data-month-title]').textContent=`${view.getFullYear()} / ${String(view.getMonth()+1).padStart(2,'0')}`;
  grid.innerHTML=Array.from({length:6},(_,row)=>`<div role="row">${Array.from({length:7},(_,col)=>{const day=new Date(start);day.setDate(1-offset+row*7+col);const text=dateText(day),valid=validDate(text,c.options),selected=values.includes(text),between=values.length===2&&text>values[0]&&text<values[1];return `<span role="gridcell" aria-selected="${selected}"><button type="button" data-day="${text}" tabindex="${text===dateText(cursor)?0:-1}" aria-label="${text}" ${text===today?'aria-current="date"':''} ${!valid?'disabled':''} data-outside="${day.getMonth()!==view.getMonth()}" data-selected="${selected}" data-between="${between}">${day.getDate()}</button></span>`;}).join('')}</div>`).join('');
  if(!grid.querySelector('button[tabindex="0"]:not(:disabled)'))grid.querySelector<HTMLButtonElement>('button:not(:disabled)')?.setAttribute('tabindex','0');if(restoreFocus&&overlay.open)grid.querySelector<HTMLElement>('button[tabindex="0"]:not(:disabled)')?.focus();overlay.position();motion.layout();
 }
 const hide=()=>{overlay.hide();motion.hide();};
 const show=()=>{if(c.options.disabled||c.options.readOnly||c.options.mode==='time')return;paint();overlay.show();motion.show();grid.querySelector<HTMLElement>('[tabindex="0"]')?.focus();};
 c.sync=reason=>{syncHeading(c);const o=c.options,values=asStrings(c.data);inputs.forEach((input,i)=>{input.hidden=i===1&&o.mode!=='range';input.type=o.mode==='time'?'time':o.mode==='datetime'?'datetime-local':'date';input.disabled=!!o.disabled||input.hidden;input.readOnly=!!o.readOnly;input.required=!!o.required;input.setAttribute('aria-label',`${o.label??'日付'}${o.mode==='range'?i?' 終了日':' 開始日':''}`);input.min=o.mode==='datetime'&&o.minDate?o.minDate+'T00:00':o.mode==='time'?'':o.minDate??'';input.max=o.mode==='datetime'&&o.maxDate?o.maxDate+'T23:59':o.mode==='time'?'':o.maxDate??'';if(o.name)input.name=o.mode==='range'?`${o.name}[${i}]`:o.name;else input.removeAttribute('name');input.value=values[i]??'';});
  toggle.hidden=o.mode==='time';toggle.disabled=!!o.disabled||!!o.readOnly;q<HTMLElement>(root,'[data-date-separator]').hidden=o.mode!=='range';if(o.disabled||o.readOnly||o.mode==='time')hide();motion.sync(c.options,asStrings(c.data));if(reason==='options'||reason==='reset'||reason==='value'){const selected=parseDate(values[0]?.slice(0,10)??'');if(selected){cursor=selected;view=new Date(selected.getFullYear(),selected.getMonth(),1,12);}}paint();
 };
 inputs.forEach((input,i)=>c.on(input,'change',()=>{const value=input.value;if(c.options.mode==='range'){const dates=asStrings(c.data);dates[i]=value;c.send(dates);}else c.send(value);q(root,'[data-date-message]').textContent=value&&!asStrings(c.data).includes(value)?'選択できる範囲の日付を指定してください。':'';}));
 c.on(toggle,'click',()=>overlay.open?hide():show());c.on(grid,'click',event=>{const b=(event.target as Element).closest<HTMLElement>('[data-day]');if(b)choose(b.dataset.day!);});
 panel.querySelectorAll<HTMLButtonElement>('[data-month]').forEach(b=>c.on(b,'click',()=>{view=new Date(view.getFullYear(),view.getMonth()+Number(b.dataset.month),1,12);cursor=new Date(view);paint();motion.turn(Number(b.dataset.month));}));
 c.on(grid,'keydown',event=>{const e=event as KeyboardEvent;if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Home','End','PageUp','PageDown'].includes(e.key))return;e.preventDefault();const active=(e.target as HTMLElement).dataset.day;const date=parseDate(active??'')??cursor;const weekday=(date.getDay()+6)%7;const delta:Record<string,number>={ArrowLeft:-1,ArrowRight:1,ArrowUp:-7,ArrowDown:7,Home:-weekday,End:6-weekday};if(e.key==='PageUp'||e.key==='PageDown'){date.setDate(1);date.setMonth(date.getMonth()+(e.key==='PageUp'?-1:1));}else date.setDate(date.getDate()+delta[e.key]);
  const direction=['ArrowLeft','ArrowUp','Home','PageUp'].includes(e.key)?-1:1;let attempts=0;while(!validDate(dateText(date),c.options)&&attempts++<366)date.setDate(date.getDate()+direction);if(!validDate(dateText(date),c.options))return;const previousMonth=view.getMonth();cursor=date;view=new Date(date.getFullYear(),date.getMonth(),1,12);paint();if(view.getMonth()!==previousMonth)motion.turn(direction);grid.querySelector<HTMLElement>(`[data-day="${dateText(cursor)}"]`)?.focus();});
 c.on(q(panel,'[data-today]'),'click',()=>choose(dateText(new Date())));c.on(q(panel,'[data-date-clear]'),'click',()=>{if(c.options.disabled||c.options.readOnly)return;c.send(c.options.mode==='range'?[]:'');overlay.hide();motion.hide();toggle.focus();});
 c.on(document,'pointerdown',event=>{if(overlay.open&&!root.contains(event.target as Node))hide();},{capture:true});c.on(root,'focusout',event=>{if(root.contains((event as FocusEvent).relatedTarget as Node))return;queueMicrotask(()=>{if(!c.dead&&!root.contains(document.activeElement))hide();});});c.on(document,'keydown',event=>{const e=event as KeyboardEvent;if(e.key==='Escape'&&overlay.open){e.preventDefault();e.stopPropagation();overlay.hide();motion.hide();toggle.focus();}},{capture:true});
 c.show=show;c.hide=hide;c.sync('initial');return c;
}
