from pathlib import Path
import json,hashlib
p=Path(__file__).parent;m=json.load(open(p/'review-input-7.json'));assert all(hashlib.sha256(Path(f).read_bytes()).hexdigest()==h for f,h in m['sourceHashes'].items())
primary=json.load(open(p/'measurements-7.json'));native=json.load(open(p/'measurements-native-7.json'));react=json.load(open(p/'measurements-react-7.json'));focused=json.load(open(p/'measurements-focused-7.json'));assert [len(primary),len(native),len(react),len(focused)]==[20,20,44,24];assert not any(r.get('error')or r.get('errors')or any(not c['pass']for c in r.get('checks',[]))for r in native+react)
notes={592:'計数盤と候補の独立した列はAとして成立。エラー再試行の縦3行だけ修正。',596:'投函口の厚みと返答紙の上端折返し/下の紙端が成立し、通常の候補カードから素材差が生まれた。',599:'棚板/棚受け/支柱を保持し、選択説明/NOTEは5.599:1へ改善。',601:'二列の編集索引と番号/分類の余白欄が成立。狭幅で情報単位を一列へ。選択補助文字5.669:1、二重focusも解消。',608:'資料名/説明/コードのカード構成を保持。長い非同期エラーはroot222pxでも折返す。',609:'低い行と識別子の密度を保持。長い非同期エラー切れを解消。',610:'書名先行の読み順を保持。長い見出し/エラーは狭幅LTR/RTLで収まる。',612:'検索計器と候補のフォーカス面を横に分離し、狭幅は縦接続。色や角記号だけではない構造差が成立。',615:'名称/説明/shortcutの実欄で台帳構造が成立し、hover文字移動0px・選択補助文字5.875:1。未選択連番と分類札が残存。',616:'側壁の奥の索引紙と手前の取手付き前板が実際に重なり、引出しの内外が明確。前板文字の濃さも改善。'}
finds={n:[]for n in notes}
finds[592]=[{'kind':'error_retry_layout','description':'新2列gridで再試行ボタンが52pxの計数列へ入り、「再／試／行」と縦3行になる。320px viewport、portable root222px / gallery249px双方でbutton52×93.39px、文字幅14px・高さ63.59px。操作は実行できるが通常の短い操作名の読み方を崩す。','recommendation':'再試行を全幅または本文列へ置き、短いlabelが一行で読める幅を確保。長い任意labelも折返し可能にする。','evidence':['measurements-native-7.json','evidence-7/radar-window-search-portable-native-error-narrow.png','evidence-7/errors-sheet-1.jpg']}]
finds[615]=[{'kind':'record_number_visibility','description':'実連番として使う::beforeにshared baseのopacity0/scale(.98)が残り、選択行だけopacity1となる。01だけ表示し、後続の02/03等は未選択時に消える。gallery/portable実画像とcomputed値で確認。','recommendation':'連番のopacity/transform/重なり順を明示固定し、hover解除・再進入でも全記録番号を表示。','evidence':['measurements-focused-7.json','evidence-7/sheet-ledger-command.jpg','src/shared/workbench/base.css:78']},{'kind':'contrast','description':'分類札CREATE/NAVIGATE/PREFERENCESは12px・600、文字#7a6b53 / 面#e1ceaaで3.356:1。gallery/portableの通常/hover/解除で同値。disabled候補ではない。','recommendation':'分類文字を面に対して4.5:1以上へ。','evidence':['contrast-summary-7.json','measurements-7.json','evidence-7/ledger-command-portable-rest.png']}]
parts=[]
for r in primary[:10]:
 n=r['number'];parts.append({'id':r['id'],'number':n,'verdict':'changes_required'if finds[n]else'pass','note':notes[n],'findings':finds[n],'evidence':[f'evidence-7/sheet-{r["id"]}.jpg','measurements-7.json','measurements-native-7.json','measurements-react-7.json','contrast-summary-7.json'],'reviewed':{'round':7,'actualGallery':True,'portable':True,'hoverEntryExitReentry':True,'narrow320LongRTL':True,'forcedReduced':True,'native':True,'react4Formats':True,'ABVisualComparison':True}})
coverage={'primaryRows':20,'nativeChecks':sum(len(r.get('checks',[]))for r in native),'reactPartsFormats':40,'reactChecks':sum(len(r.get('checks',[]))for r in react),'runtimeErrors':0,'sourceHashesMatched':100,'lowHeightFocusedConditions':24,'imagesViewed':['10 primary sheets (120 states)','2 React sheets (20 images)','native error sheet (10 images)','3 commands low-height manual-bottom close images','A search3 and command2 normal close images'],'pendingRequiredMeasurements':[],'limitations':['Chromiumの指定状態での検査であり無欠陥保証ではない。','初回whole-option低height判定は長い候補全体がviewportを越えて失敗する。追加24条件で手動の末尾到達を確認し、到達不能とは判定しない。','React長文の全組合せは未実行。同作者CSSのgallery/portableで実査。','Aの構造改善と、2件の再現する表示不整合を区別。']}
(p/'review-7.json').write_text(json.dumps({'batch':'B019','round':7,'overall':'changes_required','parts':parts,'coverage':coverage},ensure_ascii=False,indent=2)+'\n')
(p/'hash-verification-final-7.json').write_text(json.dumps({'sourceHashesMatched':100,'mismatches':[]},indent=2)+'\n')
lines=['# B019 round 7 独立再検査','','8 pass / 2 changes_required。差戻しはR592とR615。作者/共有ソースは編集していない。','','| ID | 判定・根拠 |','|---|---|']+[f'| R{x["number"]} | {x["verdict"]}: {x["note"]} |'for x in parts]
lines+=['','R592の再試行は52pxの計数列で縦3行。R615は未選択連番opacity0と分類札3.356:1を修正する。台帳の別欄、光学の二面、編集索引の二列、引出しの内外など、Aの再設計はBと比較して構造差を確認した。','','native328確認、React4形式×10件132確認が成功。旧長文エラー/見出し切れ、旧hover16px移動を解消。command低height24条件は末尾まで手動到達し、旧whole-item判定を不具合扱いしない。作者100 hashは最終保存時も一致。必須計測の未完なし。詳細は[review-7.json](review-7.json)。']
(p/'review-7.md').write_text('\n'.join(lines)+'\n');print('B019 r7 saved:8 pass 2 changes_required')
