import {createCore,choiceValue,heading,syncHeading,q,escape,svg,asStrings,uniqueId,type FoundationConfig,type FoundationOptions,type FoundationController} from '../core.ts';
import {presentationSpring} from '../../presentation-spring.ts';
import {createMaterialScene,revealSurface} from './art.ts';
import {resonanceOverlay} from './overlay.ts';
export function renderRadio(o:FoundationOptions):string {return `<fieldset class="ff-choice-set"><legend data-ff-label>${escape(o.label)}</legend><p data-ff-description class="ff-description">${escape(o.description)}</p><div class="ff-choices" data-choices></div></fieldset>`;}
/** Native radios remain the source of truth; presentation follows the committed selection. */
export function mountRadio(root:HTMLElement,config:FoundationConfig,options:FoundationOptions={}):FoundationController {
 root.classList.add('sop-resonance');const c=createCore(root,{...config,multiple:false},options,(v,o)=>choiceValue(v,{...o,multiple:false}));if(!root.querySelector('[data-choices]'))root.innerHTML=renderRadio(c.options);
 const body=q(root,'[data-choices]'),group=uniqueId('rs-radio');let key='';const scenes=new Map<HTMLElement,ReturnType<typeof createMaterialScene>>();
 const erase=()=>{for(const s of scenes.values())s.destroy();scenes.clear();};
 c.sync=reason=>{syncHeading(c);const o=c.options,items=o.items??[],next=JSON.stringify(items);
  if(key!==next){erase();body.innerHTML=items.map(item=>`<label class="ff-choice"><input type="radio" data-choice="${escape(item.value)}"><span class="rs-choice-surface" aria-hidden="true"></span>${item.icon?`<span class="ff-choice-icon" aria-hidden="true">${svg(item.icon)}</span>`:''}<span class="ff-choice-copy"><strong>${escape(item.label)}</strong><small>${escape(item.description)}</small></span>${item.badge?`<span class="ff-choice-badge">${escape(item.badge)}</span>`:''}<span class="ff-choice-check" aria-hidden="true"><i></i></span></label>`).join('');key=next;
   for(const card of body.querySelectorAll<HTMLElement>('.ff-choice'))scenes.set(card,createMaterialScene(q(card,'.rs-choice-surface'),config.variant,c.data===q<HTMLInputElement>(card,'input').dataset.choice?1:0));
  }
  body.querySelectorAll<HTMLInputElement>('input').forEach(input=>{input.name=o.name??group;input.value=input.dataset.choice!;input.checked=c.data===input.value;input.disabled=!!o.disabled||!!o.readOnly||!!items.find(i=>i.value===input.value)?.disabled;input.required=!!o.required;const card=input.closest<HTMLElement>('.ff-choice')!;const changed=card.dataset.selected!==String(input.checked);card.dataset.selected=String(input.checked);scenes.get(card)?.set(input.checked?1:0,reason==='initial'||reason==='reset');if(changed&&reason==='value')scenes.get(card)?.pulse();});
 };
 c.on(body,'change',e=>{const input=e.target;if(input instanceof HTMLInputElement&&input.checked)c.send(input.value);});
 c.on(body,'pointermove',e=>{const event=e as PointerEvent,card=(event.target as Element).closest<HTMLElement>('.ff-choice');if(!card||q<HTMLInputElement>(card,'input').matches(':disabled')||event.pointerType==='touch')return;const rect=card.getBoundingClientRect();card.style.setProperty('--rs-x',(100*(event.clientX-rect.left)/rect.width)+'%');scenes.get(card)?.pointer((event.clientX-rect.left)/rect.width);},{passive:true});
 c.cleanup(erase);c.sync('initial');return c;
}
export function renderCombobox(o:FoundationOptions):string {return heading(o)+`<div class="ff-combo-shell"><span class="ff-combo-icon" aria-hidden="true">${svg('search')}</span><input type="text" data-combo role="combobox" aria-autocomplete="list" aria-expanded="false" autocomplete="off" aria-label="${escape(o.label)}" placeholder="${escape(o.placeholder??'名前やキーワードを入力…')}"><button type="button" data-combo-toggle tabindex="-1" aria-label="候補を開く">${svg('down')}</button></div><div class="ff-chips" data-combo-chips></div><div class="ff-floating ff-combo-list" data-combo-panel><div class="rs-menu-edge" aria-hidden="true"></div><div data-results role="listbox"></div><div class="ff-menu-foot" data-result-count></div></div><div data-combo-form hidden></div><span class="ff-sr" data-combo-live role="status" aria-live="polite"></span>`;}
/** Editable input: composition, selection/caret, keyboard focus and undo are never animated. */
export function mountCombobox(root:HTMLElement,config:FoundationConfig,options:FoundationOptions={}):FoundationController {
 root.classList.add('sop-resonance');const c=createCore(root,config,options,choiceValue);if(!root.querySelector('[data-combo]'))root.innerHTML=renderCombobox(c.options);
 const input=q<HTMLInputElement>(root,'[data-combo]'),panel=q<HTMLElement>(root,'[data-combo-panel]'),results=q(root,'[data-results]'),shell=q(root,'.ff-combo-shell'),chips=q(root,'[data-combo-chips]');
 const uid=uniqueId('rs-combo');input.id=uid;results.id=uid+'-list';input.setAttribute('aria-controls',results.id);
 const overlay=resonanceOverlay(c,panel,root),scene=createMaterialScene(panel,config.variant,0),field=createMaterialScene(shell,config.variant,0);
 const lens=document.createElement('span');lens.className='rs-active-plane';lens.setAttribute('aria-hidden','true');panel.append(lens);
 let query='',active='',composing=false,editing=false,rowsKey='',chipsKey='',firstMove=true,entrance:Animation|null=null;
 const marker=presentationSpring(panel,{y:8,h:54,w:200,x:8,k:0},v=>{lens.style.transform=`translate(${v.x}px,${v.y}px) scaleY(${1+Math.max(0,v.k)*.045})`;lens.style.width=v.w+'px';lens.style.height=v.h+'px';});
 const filtered=()=>{const token=query.normalize('NFKC').toLocaleLowerCase();return(c.options.items??[]).filter(i=>(i.label+' '+(i.description??'')).normalize('NFKC').toLocaleLowerCase().includes(token));};
 const available=()=>c.options.loading||c.options.error?[]:filtered().filter(i=>!i.disabled);
 function movePlane(immediate=false){if(!overlay.open)return;const row=[...results.querySelectorAll<HTMLElement>('[data-option]')].find(r=>r.dataset.option===active),r=panel.getBoundingClientRect();lens.hidden=!row;if(row){const b=row.getBoundingClientRect();marker.to({x:b.left-r.left-panel.clientLeft,y:b.top-r.top-panel.clientTop+panel.scrollTop,w:b.width,h:b.height},immediate||firstMove);firstMove=false;}}
 function setActive(value:string,scroll=false){active=value;const rows=[...results.querySelectorAll<HTMLElement>('[data-option]')];let current:HTMLElement|undefined;for(const row of rows){const yes=row.dataset.option===active&&row.getAttribute('aria-disabled')!=='true';row.dataset.active=String(yes);if(yes)current=row;}
  if(current&&overlay.open){scene.set(.2+.8*(rows.indexOf(current)+1)/Math.max(1,rows.length));input.setAttribute('aria-activedescendant',current.id);if(scroll){const b=current.getBoundingClientRect(),p=panel.getBoundingClientRect();if(b.top<p.top+12)panel.scrollTop+=b.top-p.top-12;else if(b.bottom>p.bottom-32)panel.scrollTop+=b.bottom-p.bottom+32;}movePlane();}else{input.removeAttribute('aria-activedescendant');lens.hidden=true;}
 }
 function paintList(){const o=c.options,items=filtered(),values=asStrings(c.data),next=JSON.stringify([items,o.loading,o.error]);
  if(next!==rowsKey){let group='';results.innerHTML=o.loading?'<div class="ff-list-message" role="presentation">読み込み中…</div>':o.error?`<div class="ff-list-message" role="presentation">${escape(o.error)}</div>`:items.length?items.map(item=>{let head='';if(item.group&&item.group!==group){group=item.group;head=`<div class="rs-option-group" role="presentation">${escape(group)}</div>`;}return head+`<div id="${uid}-option-${(o.items??[]).indexOf(item)}" data-option="${escape(item.value)}" role="option" aria-selected="false" aria-disabled="${!!item.disabled}" class="ff-option">${item.icon?`<span class="ff-option-icon" aria-hidden="true">${svg(item.icon)}</span>`:''}<span class="rs-option-copy"><strong>${escape(item.label)}</strong><small>${escape(item.description)}</small></span>${item.badge?`<span class="ff-option-badge">${escape(item.badge)}</span>`:''}<span class="ff-option-check" aria-hidden="true">${svg('check')}</span></div>`;}).join(''):'<div class="ff-list-message" role="presentation">一致する候補がありません。</div>';rowsKey=next;}
  for(const row of results.querySelectorAll<HTMLElement>('[data-option]'))row.setAttribute('aria-selected',String(values.includes(row.dataset.option!)));
  results.setAttribute('aria-label',o.label??'候補');results.setAttribute('aria-multiselectable',String(!!o.multiple));q(panel,'[data-result-count]').textContent=o.loading?'LOADING':`${items.length} OPTIONS · ↑↓ / ENTER`;
  q(root,'[data-combo-live]').textContent=o.loading?'読み込み中':o.error??`${items.length}件の候補`;overlay.position();setActive(active);
 }
 function show(){if(c.dead||c.options.disabled||c.options.readOnly)return;const was=overlay.open;if(!was){active='';query='';editing=false;}paintList();overlay.show();input.setAttribute('aria-expanded','true');root.dataset.open='true';field.set(1);scene.set(1);if(!was){firstMove=true;entrance?.cancel();entrance=revealSurface(panel,config.variant,marker.reduced);}movePlane(true);}
 function hide(){if(c.dead)return;overlay.hide();input.setAttribute('aria-expanded','false');input.removeAttribute('aria-activedescendant');root.dataset.open='false';editing=false;query='';active='';lens.hidden=true;entrance?.cancel();scene.set(0,true);field.set(document.activeElement===input ? .55 : 0);c.sync('value');}
 function select(value:string){if(c.options.disabled||c.options.readOnly||c.options.loading||c.options.error||!(c.options.items??[]).some(i=>i.value===value&&!i.disabled))return;const previous=asStrings(c.data);editing=false;query='';c.send(c.options.multiple?previous.includes(value)?previous.filter(v=>v!==value):[...previous,value]:value);field.pulse();if(c.options.multiple){input.value='';paintList();input.focus();}else{hide();input.focus();}}
 c.sync=()=>{syncHeading(c);const o=c.options,values=asStrings(c.data);input.disabled=!!o.disabled;input.readOnly=!!o.readOnly;input.required=!!o.required&&!o.multiple;input.setAttribute('aria-required',String(!!o.required));input.setAttribute('aria-label',o.label??'選択');input.placeholder=o.placeholder??'名前やキーワードを入力…';q<HTMLButtonElement>(root,'[data-combo-toggle]').disabled=!!o.disabled||!!o.readOnly;
  if(!editing&&!composing)input.value=o.multiple?'':(o.items??[]).find(i=>i.value===values[0])?.label??'';
  if(o.disabled||o.readOnly){overlay.hide();input.setAttribute('aria-expanded','false');input.removeAttribute('aria-activedescendant');root.dataset.open='false';scene.set(0,true);field.set(0,true);}
  const chipState=JSON.stringify([o.multiple,values,o.items,o.disabled,o.readOnly]);if(chipState!==chipsKey){chips.innerHTML=o.multiple?values.map(v=>`<span class="ff-chip">${escape((o.items??[]).find(i=>i.value===v)?.label??v)}<button type="button" data-remove="${escape(v)}" aria-label="${escape((o.items??[]).find(i=>i.value===v)?.label??v)} を削除" ${o.disabled||o.readOnly?'disabled':''}>${svg('close')}</button></span>`).join(''):'';chipsKey=chipState;}
  q(root,'[data-combo-form]').innerHTML=o.name?values.map(v=>`<input type="hidden" name="${escape(o.name)}" value="${escape(v)}" ${o.disabled?'disabled':''}>`).join(''):'';input.setCustomValidity(o.required&&!values.length?'候補を選択してください。':'');paintList();
 };
 c.on(input,'input',()=>{editing=true;query=input.value;active='';if(!overlay.open&&!c.options.disabled&&!c.options.readOnly){overlay.show();input.setAttribute('aria-expanded','true');root.dataset.open='true';scene.set(1);entrance?.cancel();entrance=revealSurface(panel,config.variant,marker.reduced);}if(!composing){paintList();field.pulse();}});
 c.on(input,'compositionstart',()=>{composing=true;});c.on(input,'compositionend',()=>{composing=false;query=input.value;paintList();field.pulse();});
 c.on(input,'focus',()=>field.set(.55));c.on(input,'blur',()=>{if(!overlay.open)field.set(0);});
 c.on(input,'keydown',event=>{const e=event as KeyboardEvent;if(composing||e.isComposing||e.keyCode===229)return;
  if(e.key==='Escape'&&overlay.open){e.preventDefault();e.stopPropagation();hide();return;}if(e.key==='Tab'){if(overlay.open)hide();return;}
  if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();if(!overlay.open)show();const list=available();if(!list.length)return;const index=list.findIndex(i=>i.value===active),next=index<0?(e.key==='ArrowDown'?0:list.length-1):Math.max(0,Math.min(list.length-1,index+(e.key==='ArrowDown'?1:-1)));setActive(list[next].value,true);scene.pulse();}
  if(e.key==='Enter'&&overlay.open&&active){e.preventDefault();select(active);}
 });
 c.on(q(root,'[data-combo-toggle]'),'click',()=>{if(overlay.open)hide();else show();input.focus();});
 c.on(results,'pointermove',event=>{const row=(event.target as Element).closest<HTMLElement>('[data-option]');if(row?.getAttribute('aria-disabled')==='false'&&row.dataset.option!==active)setActive(row.dataset.option!);},{passive:true});
 c.on(results,'pointerdown',event=>{if((event.target as Element).closest('[data-option]'))event.preventDefault();});c.on(results,'click',event=>{const row=(event.target as Element).closest<HTMLElement>('[data-option]');if(row?.getAttribute('aria-disabled')==='false')select(row.dataset.option!);});
 c.on(chips,'pointerdown',e=>{if((e.target as Element).closest('[data-remove]'))e.preventDefault();});c.on(chips,'click',e=>{const b=(e.target as Element).closest<HTMLElement>('[data-remove]');if(b&&!c.options.disabled&&!c.options.readOnly){c.send(asStrings(c.data).filter(v=>v!==b.dataset.remove));input.focus();}});
 c.on(panel,'scroll',()=>movePlane(true),{passive:true});const size=typeof ResizeObserver==='undefined'?null:new ResizeObserver(()=>movePlane(true));size?.observe(results);
 c.on(document,'pointerdown',e=>{if(overlay.open&&!root.contains(e.target as Node))hide();},{capture:true});c.on(root,'focusout',e=>{if(root.contains((e as FocusEvent).relatedTarget as Node|null))return;queueMicrotask(()=>{if(!c.dead&&overlay.open&&!root.contains(document.activeElement))hide();});});
 c.cleanup(()=>{size?.disconnect();scene.destroy();field.destroy();marker.destroy();entrance?.cancel();lens.remove();input.removeAttribute('aria-activedescendant');input.setAttribute('aria-expanded','false');root.removeAttribute('data-open');});
 c.show=show;c.hide=hide;c.sync('initial');return c;
}
