from pathlib import Path
import json,hashlib
p=Path('docs/design-refinement-225/batches/B018');manifest=json.load(open(p/'review-input-6.json'));mismatch=[f for f,h in manifest['sourceHashes'].items() if hashlib.sha256(Path(f).read_bytes()).hexdigest()!=h];assert not mismatch
for name,n in [('measurements-6',20),('measurements-native-6',6),('measurements-wizards-6',14),('measurements-react-6',44),('measurements-settled-6',12),('measurements-settled-b-6',6)]:
 d=json.load(open(p/(name+'.json')));assert len(d)==n;assert not any(x.get('error')or any(not c['pass']for c in x.get('checks',[]))for x in d)
notes={562:'日付を結ぶ線が本文の外へ折れ、交互の札へ接続する製図の読み順が成立。文字・操作位置を動かさず、B569の一覧と構造を分離する。',563:'背の線から日付札の小穴へ輪を渡す接点が見える。本文の列を輪から離し、実日付・展開詳細も長文に対応する。',569:'連番・実日付・statusの読み順はBとして明確。ただし長い補足metaが折り返されず、通常/RTL/forcedの狭幅で切れる。',576:'少しずつ差し出す索引紙と現在工程の入力面が同じ紙色でつながる。7工程でも項目単位の幅を保ち、Bの単純なチェックリストと区別できる。',578:'綴じた外側の布と内側の入力紙が別の面になり、糸が紙端をまたぐ。7工程・長文でも布札を一文字列へ潰さず、入力・値・焦点は安定する。',581:'紙の入力面は独立したが、クリップは透明な単一の丸角輪郭を紙の上に載せた表現。Bのフォーム面に小飾りを足した段階に留まり、留める接点が弱い。',584:'工程を厚みのある独立した陶駒、入力を別の器として分け、Bの一面フォームと構造差が成立。7工程・狭幅は横向き駒の縦列へ替わり、文字と面の関係を保持する。',588:'広い次へボタンと短い工程表示は申し込み用Bとして読みやすいが、エラー文字・未到達名称と、7工程の極端に細い列が残る。',589:'工程チェックリストを縦に揃えるBの構成は成立。エラーと未到達名称の可読性、forcedで7列へ戻る長文工程を修正する。',590:'明朝の番号と下線入力による帳票向けBの用途差はあるが、エラー・未到達名称・7工程の細い列・長い入力ラベルの切れが残る。'}
def f(kind,d,r,e):return dict(kind=kind,description=d,recommendation=r,evidence=e)
finds={569:[f('long_content_clipping','長い.sg-event-metaが単一行のまま。root222pxでは通常右へ29.2px、RTL左へ31.2px、forced左へ49.2px超過しclip。650ms後も再現する。','metaを縮小/折返し可能にし、本文欄の内側で長い連続語を折り返す。forcedでも規則を維持。',['measurements-settled-6.json','evidence-6/clear-process-timeline-portable-settled-forced.png'])],581:[f('design_review_judgment','20×38pxの単一の輪郭は紙の上端をまたぐだけで、金具と紙の前後関係・把持箇所が示されない。機能不具合とは別のA造形の不足。','紙面を挟む金具と持ち手を別の面で表し、前後の重なりを見せる。入力文字や操作座標は保持する。',['evidence-6/review-581-sheet.jpg','evidence-6/review-588-sheet.jpg'])]}
for n,ratio in [(588,1.613),(589,1.620),(590,1.605)]:
 finds[n]=[f('contrast',f'async beforeNextで返したエラー文字#f1b8a5が淡色実背景上で{ratio:.3f}:1。通常幅/320px・gallery/portableで読み取り困難。','実背景に対応した濃い文字色と読みやすい寸法へ。forcedを含め実エラーで検証。',['contrast-summary-6.json','measurements-wizards-6.json']),f('future_step_legibility','未到達工程名がdisabledのopacityと共に薄くなり、R588 3.020:1/R589 2.757:1/R590 2.914:1。操作不可でも先の工程を知らせる文字は読める必要がある。disabled戻るボタンの薄さとは分けた情報設計上の評価。','native disabledは維持し、工程名/番号の表示は十分な濃さを保つ。',['contrast-summary-6.json']),f('many_steps_layout','320px・7工程で'+('forcedのみ'if n==589 else'通常とforced')+'横7列が維持され、工程名が日本語1文字/英字1〜2文字ずつに分断。R588通常の文字列幅12px・高さ739.1px、R590は15.7px・748.7px。R589forcedも約12.6px・462px。','4工程以上または狭いhostで番号＋工程名を横に置いた項目の縦列へ切り替える。forcedも同じ構造を適用。',['measurements-settled-b-6.json',f'evidence-6/review-{n}-sheet.jpg'])]
finds[590].append(f('long_field_label_clipping','長い入力ラベルがroot222pxで49.1px、gallery251pxで20.1px外へはみ出す。RTLは左へ同量。','label/spanの最小幅を解除し、入力面の幅で連続語を折り返す。',['measurements-settled-6.json','evidence-6/review-590-sheet.jpg']))
parts=[]
for x in json.load(open('docs/design-refinement-225/targets.json')):
 if x['batch']!='B018':continue
 n=x['number'];parts.append({'id':x['id'],'number':n,'verdict':'changes_required'if n in finds else'pass','note':notes[n],'findings':finds.get(n,[]),'evidence':[f'evidence-6/review-{n}-sheet.jpg','measurements-6.json','measurements-wizards-6.json'if x['category']=='wizards'else'measurements-native-6.json','measurements-react-6.json','contrast-summary-6.json'],'reviewed':{'round':6,'portable':True,'actualGallery':True,'hoverEntryExitReentry':True,'narrow320LongRTL':True,'forcedReduced':True,'native':True,'react4Formats':True,'ABVisualComparison':True}})
coverage={'primaryRows':20,'nativeTimelineChecks':42,'nativeWizardChecks':182,'reactPartsFormats':40,'reactChecks':136,'runtimeErrors':0,'sourceHashesMatched':100,'pendingRequiredMeasurements':[],'scope':'指定した状態・操作の検査。無欠陥保証ではない。Reactの7工程長文全組合せは未実施、同CSSのgallery/portableで検証。','settledContrastNote':'R569開閉直後の本文opacity0は遷移中の測定。650ms後に5.254:1以上と確認し、コントラスト不具合に含めていない。'}
(p/'review-6.json').write_text(json.dumps({'batch':'B018','round':6,'overall':'changes_required','parts':parts,'coverage':coverage},ensure_ascii=False,indent=2)+'\n');(p/'hash-verification-6.json').write_text(json.dumps({'matched':100,'mismatches':mismatch},indent=2))
lines=['# B018 round 6 独立検査','','5 pass / 5 changes_required。作者・共有ソースは変更していない。','','実gallery/portableで通常・hover出入り/再進入・320px/7工程長文/RTL/forced/reducedを確認。timelineの開閉・controlled・reset・更新、wizardの必須/email/textarea、非同期busy/拒否、Enter進行、戻ると入力DOM保持、完了、native form/reset/disabled、controlled、schema更新を検証。native224項目、React4形式×10件136項目は成功。作者100hash一致。','','| ID | 判定 | 根拠 |','|---|---|---|']
for x in parts:lines.append(f'| R{x["number"]} | {x["verdict"]} | {x["note"]} |')
lines+=['','Aの造形不足はR581。R569/R588/R589/R590は再現する表示不具合を含む。R588/589/590の未到達工程文字は、disabledコントロール一般の適合違反を断定する指摘ではなく、工程情報の読みやすさの要求。','','R569の一時的なopacity0は650ms後に解消しており、誤ってコントラスト不具合として扱わない。Reactの7工程長文全組合せは未実行。その他必須計測の未完なし。','','詳細は [review-6.json](review-6.json)。'];(p/'review-6.md').write_text('\n'.join(lines)+'\n');print('saved 5pass/5changes')
