from pathlib import Path
import json
p=Path('docs/design-refinement-225/batches/B004');parts=[x for x in json.load(open('docs/design-refinement-225/targets.json'))if x['batch']=='B004'];cs={x['number']:x for x in json.load(open(p/'contrast-summary-1.json'))if x['mode']=='portable'}
notes={152:'切歯状の索引と薄い紙面が明瞭。3項目/7項目・長文でも歯形と本文面がつながり、対象タブ保持も成立。',153:'吊り札と紐の接続、選択の赤茶が一貫。狭幅でも札と文字は移動せず安定するが、未選択の文字が薄い。',154:'上下・背のレールで青灰の紙面を支える構造が保たれる。縮小や長文で接続は壊れないが、非選択ラベルが薄い。',155:'屋根形の索引が独自の輪郭を作り、長文で高さが増えても本文と衝突しない。非選択の小文字が薄い。',156:'銅ピンがタブと紙をまとめる主題を保ち、長文・縮小で装飾が操作を覆わない。非選択ラベルが薄い。',157:'背の縫い目と紙の境界が自然で、狭幅でも本文の余白を保持。非選択の文字の可読性が不足。',158:'目盛りと独立キーの対応、明るい計器の造形が保たれる。長文で目盛りが分断されず操作も安定するが、非選択文字が薄い。',159:'しおりの切込みと緑の主題は明快で、縮小選択保持も正常。ただし選択/非選択ともラベルのコントラスト不足。',160:'本文下側の索引が構造差を作り、末尾縮小でも下側列だけが移動して対象を保持。非選択ラベルが薄い。',161:'斜めの背と大きな番号が維持され、長文ラベルは折り返して操作面内に収まる。非選択ラベルのコントラスト不足。'}
out=[]
for x in parts:
 n=x['number'];c=cs[n];fail=n!=152;findings=[]
 if fail:
  desc=f"定常・非選択の13pxラベルが {c['unselected']['color']} / 疑似要素背景 {c['unselected']['background']} で {c['unselected']['ratio']:.3f}:1。操作対象の通常文字として4.5:1に届かない。hoverでは濃くなるが、解除後は低い値に戻る。"
  if n==159:desc+=f" 選択済みも {c['selected']['color']} / {c['selected']['background']} で {c['selected']['ratio']:.3f}:1。"
  findings=[{'kind':'reproduced_contrast_defect','description':desc,'scope':'凍結portableと実galleryの双方。全状態は500ms待機して測定、遷移途中の低コントラストと区別。','recommendation':'素材の面・輪郭を保ち、非選択ラベル色を濃くする。R159は選択面を暗くするか選択文字を濃くして4.5:1以上を確保。hover/解除後と番号の継承色も確認する。','evidence':['contrast-1.json','contrast-summary-1.json',f"evidence-1/{x['id']}-portable-contrast-rest.png",f"evidence-1/{x['id']}-gallery-contrast-rest.png"]}]
 out.append({'id':x['id'],'number':n,'verdict':'changes_required'if fail else'pass','note':notes[n],'findings':findings,'evidence':['measurements-1.json','tabs-measurements-1.json','contrast-summary-1.json',f"evidence-1/tabs-portable-{1 if n<=156 else 2}-sheet.jpg",f"evidence-1/tabs-gallery-{1 if n<=156 else 2}-sheet.jpg"]})
r={'batch':'B004','round':1,'overall':'changes_required','parts':out,'coverage':{'interaction':'全10件×portable/actual gallery。通常、hover40ms/定常/退出60ms/再進入60ms/復帰、320px・長文・reduced/forcedを実測・撮影。page errorsなし。','resize':'20経路それぞれで1500→320/390/768px末尾選択（focusを外しselected fallbackを検査）、RTL末尾320、manualでEnd後フォーカス保持/Enter確定、7項目長文、transform:scale(.65)のホスト幅600→260px。対象の左右切れ最大0.000008px（丸め誤差）。','harness':'通常galleryの初回選択は既存実装。manual/RTL/7項目等の追加ケースは同じDOMを凍結initで再初期化する独立ハーネス。Reactラッパー自体は未実行。','visual':'通常4枚、特殊タブ4枚、定常contrast4枚のcontact sheetで全10件両経路を視認。最初のlong画像は選択直後の色遷移を含むためコントラスト確定根拠から除外。','contrast':'13pxの可視ラベルと、その直下の不透明疑似要素背景を定常500ms後に測定。選択/非選択/hover/解除/末尾選択の全10件両経路を記録。元から存在する可読性問題として報告し、共有リサイズ変更による回帰とは断定しない。','integrity':'開始・終了時のmanifest一致、共有selection-indicatorを含む。作者ファイル変更なし。','limits':'指定状態のChromium独立検査であり、全ブラウザ・全状態の無欠陥保証ではない。'},'evidence':['integrity-1.json']}
(p/'review-1.json').write_text(json.dumps(r,ensure_ascii=False,indent=2)+'\n');md='# B004 round 1 独立検査\n\nR152 pass、R153〜161 changes_required（9件）。\n\n共有リサイズ修正は10件すべて成立。LTR/RTL・manual・7項目・縮小ホストで対象の切れは丸め誤差以下。一方、定常ラベルの可読性不足を新規に確認した。造形の再設計は不要で、主な修正対象は非選択文字色、R159は選択時の配色も含む。\n\n|対象|選択|非選択|非選択hover|\n|---|---:|---:|---:|\n'
for n,c in cs.items():md+=f"|R{n}|{c['selected']['ratio']:.2f}|{c['unselected']['ratio']:.2f}|{c['hover']['ratio']:.2f}|\n"
md+='\n値はcontrast比。portable/galleryで一致。\n\n'+'\n'.join(f"- R{x['number']} {x['verdict']}: {x['note']}"for x in out)+'\n\n'+'\n\n'.join(r['coverage'].values())+'\n';(p/'review-1.md').write_text(md)
