import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {chromium} from 'playwright';
import {createServer} from 'vite';
const out=path.resolve('.test-output/badge-form');fs.mkdirSync(out,{recursive:true});
fs.writeFileSync(path.join(out,'index.html'),'<form><div id="host"></div><button type="reset">Reset</button></form><script type="module" src="./entry.ts"></script>');
fs.writeFileSync(path.join(out,'entry.ts'),`import {mountBadges} from '../../src/shared/foundation/navigation.ts';
window.items=[{value:'ready',label:'Ready'},{value:'draft',label:'Draft'},{value:'locked',label:'Locked',disabled:true}];
window.mount=(options={})=>{window.api?.destroy();const root=document.querySelector('#host');root.innerHTML='';window.api=mountBadges(root,{id:'badge-form',kind:'badges',variant:'essential',items:window.items,selectable:true,removable:true,name:'filters',defaultValue:['ready']},options)};window.mount();window.ready=true;`);
const server=await createServer({configFile:false,root:process.cwd(),optimizeDeps:{noDiscovery:true},server:{host:'127.0.0.1',port:0,hmr:false,watch:null}});await server.listen();
const browser=await chromium.launch({...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{}),headless:true});
try{
 const p=await browser.newPage();await p.goto(server.resolvedUrls!.local[0]+'.test-output/badge-form/index.html');await p.waitForFunction(()=>(window as any).ready);
 const data=()=>p.evaluate(()=>(window as any).api.getData());
 const form=(name='filters')=>p.locator('form').evaluate((e:HTMLFormElement,name)=>new FormData(e).getAll(name),name);
 const update=(options:Record<string,unknown>)=>p.evaluate(o=>(window as any).api.updateFoundation(o),options);
 const reset=()=>p.evaluate(()=>new Promise<void>(resolve=>{document.querySelector('form')!.reset();setTimeout(resolve,20)}));
 const choice=(value:string)=>p.locator(`[data-tag-select="${value}"]`);
 assert.deepEqual(await form(),['ready']);
 await choice('draft').evaluate(e=>{(window as any).savedInput=e;(window as any).savedLabel=e.closest('label')});await choice('draft').click();
 assert.deepEqual(await data(),['ready','draft']);assert.deepEqual(await form(),['ready','draft']);
 assert.equal(await choice('draft').evaluate(e=>e===(window as any).savedInput&&e.closest('label')===(window as any).savedLabel&&e===document.activeElement),true);
 assert.equal(await choice('draft').getAttribute('value'),'draft');assert.ok(await choice('locked').isDisabled());
 await update({name:'tags'});assert.deepEqual(await form(),[]);assert.deepEqual(await form('tags'),['ready','draft']);await update({name:'filters',value:['ready']});
 console.log('PASS tag names and values submit through native FormData while selection retains its checkbox, label and focus');
 await update({readOnly:true});assert.deepEqual(await form(),['ready']);await choice('draft').click();assert.deepEqual(await data(),['ready']);await choice('ready').focus();await p.keyboard.press('Space');assert.deepEqual(await form(),['ready']);
 assert.equal(await choice('ready').getAttribute('aria-readonly'),'true');await update({disabled:true});assert.deepEqual(await form(),[]);
 await update({disabled:false,readOnly:false,controlled:true,value:['ready']});await choice('draft').click();assert.deepEqual(await data(),['ready']);assert.deepEqual(await form(),['ready']);assert.equal(await choice('draft').isChecked(),false);
 await p.evaluate(()=>(window as any).api.updateFoundation({onDataChange:(value:unknown)=>(window as any).api.updateFoundation({value})}));await choice('draft').click();assert.deepEqual(await form(),['ready','draft']);
 console.log('PASS readonly preserves successful values, disabled omits them, and controlled changes cannot submit phantom selections');
 await p.evaluate(()=>(window as any).mount());await p.locator('[data-tag-remove="ready"]').click();assert.deepEqual(await form(),[]);assert.equal(await choice('ready').count(),0);await reset();assert.deepEqual(await form(),['ready']);assert.deepEqual(await data(),['ready']);
 await update({items:[{value:'draft',label:'Draft revised'},{value:'other',label:'Other'}],value:['draft']});await reset();assert.deepEqual(await data(),[]);assert.equal(await choice('ready').count(),0);
 await update({defaultValue:['other'],value:['draft']});await reset();assert.deepEqual(await form(),['other']);
 await update({selectable:false});assert.deepEqual(await form(),[]);await update({selectable:true});assert.deepEqual(await form(),['other']);
 await update({value:['draft']});await p.locator('form').evaluate(e=>e.addEventListener('reset',e=>e.preventDefault(),{once:true}));await reset();assert.deepEqual(await form(),['draft']);
 await p.evaluate(()=>{document.querySelector('form')!.reset();(window as any).api.destroy()});await p.waitForTimeout(30);assert.deepEqual(await data(),['draft']);
 console.log('PASS removal/reset, changed item schemas/defaults, display mode, canceled reset and destruction retain the native form contract');
}finally{await browser.close();await server.close()}
