import {galleryReady} from './gallery-ready.ts';
/** Real gallery + export inspector. Explicit offline test adapter is not a Vite build. */
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import{createRequire}from'node:module';import type{Browser}from'playwright';
import{ROOT,buildCatalog,FORMATS}from'../scripts/catalog.ts';import{offlineFiles}from'./offline-fixture.ts';import{getDelivery,buildPrompt,packageContents}from'../src/catalog/delivery.ts';import{requireLocalServerUrl}from'./vite-url.ts';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_PATH??'playwright') as typeof import('playwright');
const data=buildCatalog(),offline=process.env.SOP_TEST_MODE==='offline',out=path.join(ROOT,'.test-output/continuum-gallery');fs.mkdirSync(out,{recursive:true});const tests:string[]=[],errors:string[]=[];let browser:Browser|undefined,close:(()=>Promise<void>)|undefined;
async function run(name:string,fn:()=>Promise<void>){await fn();tests.push(name);console.log('PASS '+name);}
try{
 let url='';if(!offline){const{createServer}=await import('vite'),server=await createServer({root:ROOT,server:{host:'127.0.0.1',port:0}});await server.listen();url=requireLocalServerUrl(server,'CONTINUUM inspector');close=()=>server.close();}
 browser=await chromium.launch({headless:true,args:['--no-sandbox'],...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{})});const p=await browser.newPage({viewport:{width:1440,height:1080}});p.setDefaultTimeout(12000);p.on('pageerror',e=>errors.push(e.message));
 if(offline){const f=offlineFiles(data);await p.setContent(f.get('/index.html')!.replace(/<script[^>]*>[\s\S]*?<\/script>/g,'').replace(/<link[^>]*>/g,''));await p.addStyleTag({content:f.get('/test-styles.css')!});for(const vendor of ['prism','jszip'])await p.addScriptTag({content:fs.readFileSync(path.join(ROOT,'public/vendor/'+vendor+'.js'),'utf8')});await p.addScriptTag({content:f.get('/test-app.js')!});}else await p.goto(url);
 await run('gallery contains 787 total parts and the expected A/B category counts, retaining the 23 distinct original loaders',async()=>{
  for(const [cat,count,a]of [['progress',24,16],['uploads',20,13],['datepickers',20,13],['loaders',39,24]] as const){await p.locator(`[data-category="${cat}"]`).click();await galleryReady(p,true);assert.equal(await p.locator('[data-part]').count(),count);await p.locator('[data-design-filter="A"]').click();await galleryReady(p,true);assert.equal(await p.locator('[data-part]').count(),a);await p.locator('[data-design-filter="B"]').click();await galleryReady(p,true);assert.equal(await p.locator('[data-part]').count(),count-a);await p.locator('[data-design-filter="all"]').click();await galleryReady(p,true);}assert.equal(data.parts.length,787);
 });
 await run('all 58 portable/original source packages have resolvable runtime files and consistent integration instructions',async()=>{
  let bundles=0;for(const part of data.parts.filter(r=>r.tags.includes('CONTINUUM'))){for(const layout of ['portable','original'] as const)for(const format of FORMATS){const delivery=getDelivery(part,format,layout),files=packageContents(part,format,layout);assert.ok(delivery.files.some(f=>f.name===delivery.entry));assert.ok(delivery.runtimeFiles.every(f=>!f.name.includes('src/app/')));const prompt=files.find(f=>f.name==='PROMPT.md');assert.ok(prompt);assert.equal(prompt.code,buildPrompt(part,format,layout));assert.ok(files.some(f=>f.name==='INTEGRATION.json'));bundles++;}}
  assert.equal(bundles,464);console.log('Delivery combinations:',bundles);
 });
 await run('displayed code and prompts exactly match all formats/layouts for six representative A/B components',async()=>{
  let count=0;for(const id of ['tide-progress','folio-dropzone','prism-calendar','folding-cube-loader','arc-spinner-loader','line-sweep-loader']){const part=data.parts.find(p=>p.id===id)!;await p.locator(`[data-category="${part.category}"]`).click();await galleryReady(p,true);await p.locator(`[data-open="${id}"]`).click();await galleryReady(p,true);const d=p.locator('#part-details');for(const layout of ['portable','original'] as const){await d.locator('#export-layout').selectOption(layout);for(const format of FORMATS){await d.locator(`[data-format="${format}"]`).click();for(const file of getDelivery(part,format,layout).files){await d.locator(`[data-file="${file.name}"]`).evaluate(e=>(e as HTMLButtonElement).click());assert.deepEqual(await d.locator('.editor .line-code').allTextContents(),file.code.split('\n').map(line=>line||' '),file.name);count++;}await d.locator('[data-detail-tab="prompt"]').click();assert.equal(await d.locator('#prompt-text').inputValue(),buildPrompt(part,format,layout));await d.locator('[data-detail-tab="code"]').click();}}await d.locator('.close-detail').click();}console.log('Displayed source files:',count);
 });
 await run('progress inspector offers actual value jumps/range and unknown state, with correct reset',async()=>{
  await p.locator('[data-category="progress"]').click();await galleryReady(p,true);await p.locator('[data-open="tide-progress"]').click();await galleryReady(p,true);const d=p.locator('#part-details');await d.locator('[data-ct-jump="0"]').click();assert.equal(await d.locator('[data-progress]').evaluate((e:HTMLProgressElement)=>e.value),0);await d.locator('[data-ct-jump="100"]').click();assert.equal(await d.locator('[data-progress]').evaluate((e:HTMLProgressElement)=>e.value),100);await d.locator('[data-progress-state]').click();assert.equal(await d.locator('[data-progress]').getAttribute('value'),null);await d.locator('[data-foundation-reset]').click();assert.notEqual(await d.locator('[data-progress]').getAttribute('value'),null);assert.equal(await d.locator('[data-progress-state]').innerText(),'割合不明にする');await p.screenshot({path:path.join(out,'detail.png')});await d.locator('.close-detail').click();
 });
 await run('date inspector supports four modes, readOnly and reset without closing its parent dialog',async()=>{
  await p.locator('[data-category="datepickers"]').click();await galleryReady(p,true);await p.locator('[data-open="folio-calendar"]').click();await galleryReady(p,true);const d=p.locator('#part-details');for(const mode of ['range','datetime','time','date']){await d.locator('[data-ct-mode]').selectOption(mode);assert.equal(await d.locator('[data-date="0"]').getAttribute('type'),'text');if(mode==='range')assert.ok(await d.locator('[data-date="1"]').isVisible());await d.locator('[data-foundation-open]').click();assert.ok(await d.locator('[data-calendar]').isVisible());assert.equal(await d.locator('[data-time-picker]').isVisible(),mode==='time'||mode==='datetime');assert.equal(await d.locator('[data-calendar-date]').isVisible(),mode!=='time');await p.keyboard.press('Escape');assert.equal(await p.locator('#part-details[open]').count(),1);}
  await d.locator('[data-ct-readonly]').check();assert.ok(await d.locator('[data-calendar-toggle]').isDisabled());await d.locator('[data-foundation-reset]').click();assert.ok(!await d.locator('[data-ct-readonly]').isChecked());await d.locator('.close-detail').click();
 });
 await run('file selection in the inspector and loader pause use actual controllers, not canned animations',async()=>{
  await p.locator('[data-category="uploads"]').click();await galleryReady(p,true);await p.locator('[data-open="aurora-dropzone"]').click();await galleryReady(p,true);const d=p.locator('#part-details');await d.locator('[data-upload]').setInputFiles({name:'actual.txt',mimeType:'text/plain',buffer:Buffer.from('preview file')});assert.equal(await d.locator('.ct-file-row').count(),1);await d.locator('[data-ct-readonly]').check();assert.ok(await d.locator('[data-file-remove]').isDisabled());await d.locator('[data-foundation-reset]').click();assert.equal(await d.locator('.ct-file-row').count(),0);await d.locator('.close-detail').click();
  await p.locator('[data-category="loaders"]').click();await galleryReady(p,true);await p.locator('[data-open="iris-bloom-loader"]').click();await galleryReady(p,true);await d.locator('[data-demo-loader]').click();assert.equal(await d.locator('.sop-motion-loader').getAttribute('data-motion-running'),'false');await d.locator('[data-foundation-reset]').click();assert.equal(await d.locator('[data-demo-loader]').getAttribute('aria-pressed'),'false');await d.locator('.close-detail').click();
 });
 await run('320/390/768 inspector keeps new controls and source download reachable',async()=>{
  for(const width of [320,390,768]){await p.setViewportSize({width,height:1040});for(const id of ['mercury-progress','folio-dropzone','prism-calendar','arc-spinner-loader']){const part=data.parts.find(x=>x.id===id)!;await p.locator(`[data-category="${part.category}"]`).click();await galleryReady(p,true);await p.locator(`[data-open="${id}"]`).click();await galleryReady(p,true);const d=p.locator('#part-details');assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2));await d.locator('.copy-file').scrollIntoViewIfNeeded();assert.ok(await d.locator('.copy-file').isVisible());assert.ok(await d.locator('.download-file').isVisible());if(width===390&&id==='mercury-progress')await p.screenshot({path:path.join(out,'mobile-390.png')});await d.locator('.close-detail').click();}}
 });
 assert.deepEqual(errors,[]);console.log('CONTINUUM gallery '+tests.length+' checks passed');
}finally{fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({mode:offline?'real gallery / explicit offline compiled adapter, NOT Vite':'real Vite HTTP',passed:tests.length,tests,errors},null,2)+'\n');await browser?.close();await close?.();}
