import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createRequire} from 'node:module';
import type {Browser} from 'playwright';import {continuumFixture} from './continuum-fixture.ts';import {ROOT} from '../scripts/catalog.ts';import {requireLocalServerUrl} from './vite-url.ts';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_PATH??'playwright') as typeof import('playwright');
const f=continuumFixture(),changed=f.records.filter(p=>p.tags.includes('CONTINUUM')),offline=process.env.SOP_TEST_MODE==='offline';
const results:string[]=[],errors:string[]=[];let browser:Browser|undefined,close:(()=>Promise<void>)|undefined;
async function run(name:string,test:()=>Promise<void>){if(process.env.SOP_CONTINUUM_FILTER&&!new RegExp(process.env.SOP_CONTINUUM_FILTER).test(name))return;await test();results.push(name);console.log('PASS '+name);}
try{
 let url='';if(!offline){const vite=await import('vite'),server=await vite.createServer({root:ROOT,server:{host:'127.0.0.1',port:0}});await server.listen();url=requireLocalServerUrl(server,'CONTINUUM');close=()=>server.close();}
 browser=await chromium.launch({headless:true,args:['--no-sandbox'],...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{})});
 const p=await browser.newPage({viewport:{width:740,height:1000}});p.setDefaultTimeout(8000);p.on('pageerror',e=>errors.push(e.message));
 if(offline){await p.setContent(f.shell.replace(/<link[^>]*>/,''));await p.addStyleTag({content:f.styles});await p.addScriptTag({content:f.bundle()});}else await p.goto(new URL('.test-output/continuum/test.html',url).href);
 await p.waitForFunction(()=>typeof(window as any).mount==='function');
 const mount=async(ids:string|string[],options={})=>p.evaluate(({ids,options})=>(window as any).mount(ids,options),{ids:typeof ids==='string'?[ids]:ids,options});
 const update=async(options:Record<string,unknown>)=>p.evaluate(o=>(window as any).api.updateFoundation(o),options);
 const data=async()=>p.evaluate(()=>(window as any).api.getData());
 const actual=async()=>p.locator('[data-progress]').evaluate((e:HTMLProgressElement)=>({value:e.value,max:e.max,attr:e.getAttribute('value')}));
 await run('16 progress surfaces respond to real values while native percentages update synchronously',async()=>{
  for(const part of changed.filter(r=>r.category==='progress')){await mount(part.id,{value:0});const before=await p.locator('.ct-meter-scene').innerHTML();await p.evaluate(()=>(window as any).api.setData(75));assert.equal((await actual()).value,75,part.id);assert.match(await p.locator('[data-progress-reading]').innerText(),/75/);await p.waitForTimeout(55);assert.notEqual(await p.locator('.ct-meter-scene').innerHTML(),before,part.id);await p.evaluate(()=>(window as any).api.setData(100));assert.equal((await actual()).value,100);assert.equal(await p.locator('.sop-continuum').getAttribute('data-complete'),'true');}
  await p.waitForTimeout(1900);assert.equal(await p.evaluate(()=>(window as any).activeFrames.size),0);
 });
 await run('progress handles negative/decimal bounds, unknown values, updated labels and pause without false success',async()=>{
  await mount('tide-progress',{value:-5,min:-10,max:10,label:'転送量'});assert.deepEqual(await actual(),{value:5,max:20,attr:'5'});assert.match(await p.locator('[data-progress-reading]').innerText(),/25/);
  await update({min:0,max:1,value:.6,label:'変換'});assert.equal((await actual()).max,1);assert.match(await p.locator('[data-progress-reading]').innerText(),/60/);assert.equal(await p.locator('[data-progress]').getAttribute('aria-label'),'変換');
  await update({indeterminate:true});assert.equal((await actual()).attr,null);assert.equal(await p.locator('[data-progress-reading]').innerText(),'—');assert.equal(await p.locator('.sop-continuum').getAttribute('data-complete'),'false');
  await update({indeterminate:false,paused:true,value:1});assert.equal((await actual()).value,1);await p.waitForTimeout(50);assert.equal(await p.evaluate(()=>(window as any).activeFrames.size),0);assert.doesNotMatch(await p.locator('[data-ct-progress-state]').innerText(),/成功|送信完了/);
 });
 const txt=(name='notes.txt',size=8)=>({name,mimeType:'text/plain',buffer:Buffer.alloc(size,65)});
 await run('13 dropzones receive actual files, report selected not uploaded, keep native FormData and remove rows',async()=>{
  for(const part of changed.filter(r=>r.category==='uploads')){await mount(part.id,{name:'files',multiple:true,accept:'.txt',maxFiles:3});await p.locator('[data-upload]').setInputFiles([txt('日本語.txt'),txt('第二.txt')]);assert.equal(await p.locator('[data-file-remove]').count(),2,part.id);assert.match(await p.locator('[data-file-summary]').innerText(),/2/);assert.match(await p.locator('.ct-file-copy small').first().innerText(),/未送信/);assert.deepEqual(await p.evaluate(()=>new FormData(document.querySelector('form')!).getAll('files').map((x:any)=>x.name)),['日本語.txt','第二.txt']);await p.locator('[data-file-remove]').first().click();assert.equal(await p.locator('[data-file-remove]').count(),1);assert.deepEqual(await p.evaluate(()=>new FormData(document.querySelector('form')!).getAll('files').map((x:any)=>x.name)),['第二.txt']);}
 });
 await run('file validation rejects MIME/size/count and duplicate files without erasing a valid single selection',async()=>{
  await mount('folio-dropzone',{multiple:false,accept:'.txt',maxBytes:16});await p.locator('[data-upload]').setInputFiles(txt('keep.txt'));await p.locator('[data-upload]').setInputFiles({name:'bad.exe',mimeType:'application/octet-stream',buffer:Buffer.from('bad')});assert.equal(await p.locator('.ct-file-copy strong').innerText(),'keep.txt');assert.match(await p.locator('[data-upload-error]').innerText(),/形式/);
  await p.locator('[data-upload]').setInputFiles(txt('large.txt',20));assert.equal(await p.locator('.ct-file-copy strong').innerText(),'keep.txt');assert.match(await p.locator('[data-upload-error]').innerText(),/上限/);
  await update({multiple:true,maxFiles:2});await p.evaluate(()=>{const input=document.querySelector<HTMLInputElement>('[data-upload]')!;const same=input.files![0];const d=new DataTransfer();d.items.add(same);d.items.add(same);d.items.add(new File(['b'],'b.txt',{type:'text/plain'}));d.items.add(new File(['c'],'c.txt',{type:'text/plain'}));input.files=d.files;input.dispatchEvent(new Event('change',{bubbles:true}));});assert.equal(await p.locator('[data-file-remove]').count(),2);assert.match(await p.locator('[data-upload-error]').innerText(),/2ファイル/);
 });
 await run('uploads preserve rows on option updates, respect readonly/disabled, controlled refusal and native reset',async()=>{
  await mount('aurora-dropzone',{multiple:true,accept:'.txt',name:'asset',defaultValue:[]});await p.locator('[data-upload]').setInputFiles(txt());await p.locator('.ct-file-row').evaluate(e=>(e as HTMLElement).dataset.saved='yes');await update({label:'新しいラベル',placeholder:'資料を選択'});assert.equal(await p.locator('.ct-file-row').getAttribute('data-saved'),'yes');assert.equal(await p.locator('[data-intake-label]').innerText(),'資料を選択');
  await update({readOnly:true});assert.ok(await p.locator('[data-upload]').isDisabled());assert.ok(await p.locator('[data-file-remove]').isDisabled());await update({readOnly:false,disabled:true});assert.ok(await p.locator('[data-upload]').isDisabled());await update({disabled:false});await p.locator('#reset').click();await p.waitForTimeout(25);assert.equal(await p.locator('.ct-file-row').count(),0);
  await update({controlled:true,value:[]});await p.locator('[data-upload]').setInputFiles(txt());assert.equal(await p.locator('.ct-file-row').count(),0);assert.equal(await p.locator('[data-upload]').evaluate((e:HTMLInputElement)=>e.files!.length),0);
 });
 await run('drop handling opens the receiving surface, cannot bypass validation, and does not send requests',async()=>{
  await mount('copper-dropzone',{accept:'.txt',multiple:true});await p.locator('[data-drop]').dispatchEvent('dragenter');assert.equal(await p.locator('.sop-continuum').getAttribute('data-dragging'),'true');
  await p.evaluate(()=>{const transfer=new DataTransfer();transfer.items.add(new File(['local'],'drop.txt',{type:'text/plain'}));document.querySelector('[data-drop]')!.dispatchEvent(new DragEvent('drop',{bubbles:true,cancelable:true,dataTransfer:transfer}));});assert.equal(await p.locator('.ct-file-row').count(),1);assert.equal(await p.locator('.sop-continuum').getAttribute('data-dragging'),'false');assert.equal(await p.locator('.ct-file-copy strong').innerText(),'drop.txt');
 });
 await run('image object URLs are released on removal, reset and destruction',async()=>{
  await p.evaluate(()=>{const create=URL.createObjectURL.bind(URL),revoke=URL.revokeObjectURL.bind(URL);(window as any).objectURLs=new Set();URL.createObjectURL=b=>{const u=create(b);(window as any).objectURLs.add(u);return u;};URL.revokeObjectURL=u=>{(window as any).objectURLs.delete(u);revoke(u);};});
  const image={name:'pixel.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aUeEAAAAASUVORK5CYII=','base64')};
  for(const op of ['remove','reset','destroy']){await mount('prism-dropzone',{accept:'image/*',multiple:true,defaultValue:[]});await p.locator('[data-upload]').setInputFiles(image);assert.equal(await p.evaluate(()=>(window as any).objectURLs.size),1);if(op==='remove')await p.locator('[data-file-remove]').click();if(op==='reset')await p.locator('#reset').click();if(op==='destroy')await p.evaluate(()=>(window as any).unmount());await p.waitForTimeout(25);assert.equal(await p.evaluate(()=>(window as any).objectURLs.size),0,op);}
 });
 await run('13 calendar skins open actual grids, accept dates, and restore trigger focus',async()=>{
  for(const part of changed.filter(r=>r.category==='datepickers')){await mount(part.id,{mode:'date',value:'2026-09-07'});await p.locator('[data-calendar-toggle]').click();assert.ok(await p.locator('[data-calendar]').evaluate(e=>e.matches(':popover-open')),part.id);assert.equal(await p.locator('[role=row]').count(),6);assert.equal(await p.locator('[data-day]').count(),42);await p.locator('[data-day="2026-09-12"]').click();assert.equal(await data(),'2026-09-12');assert.equal(await p.locator('[data-date="0"]').inputValue(),'2026-09-12');assert.ok(await p.locator('[data-calendar]').isHidden());assert.ok(await p.locator('[data-calendar-toggle]').evaluate(e=>e===document.activeElement));}
 });
 await run('calendar keyboard/month motion and disabled dates preserve focus and real date constraints',async()=>{
  await mount('folio-calendar',{mode:'date',value:'2026-09-07',minDate:'2026-09-01',maxDate:'2026-10-20'});await p.evaluate(()=>(window as any).api.updateFoundation({isDateDisabled:(day:string)=>day==='2026-09-08'}));await p.locator('[data-calendar-toggle]').click();await p.keyboard.press('ArrowRight');assert.equal(await p.locator(':focus').getAttribute('data-day'),'2026-09-09');assert.ok(await p.locator('[data-day="2026-09-08"]').isDisabled());await p.keyboard.press('PageDown');assert.match(await p.locator('[data-month-title]').innerText(),/2026 \/ 10/);await p.keyboard.press('Enter');assert.equal(await data(),'2026-10-01');
  await p.locator('[data-calendar-toggle]').click();await p.locator('[data-month="-1"]').click();await p.waitForTimeout(25);assert.ok(await p.locator('.ct-calendar-sheet').evaluate(e=>e.getAnimations().length>0));await p.keyboard.press('Escape');assert.ok(await p.locator('[data-calendar]').isHidden());
 });
 await run('calendar ranges paint committed spans across rows and local months without UTC conversion',async()=>{
  await mount('prism-calendar',{mode:'range',value:[],defaultValue:[],name:'period'});await p.evaluate(()=>(window as any).api.setData(['2026-09-07']));await p.locator('[data-calendar-toggle]').click();await p.locator('[data-day="2026-09-18"]').click();assert.deepEqual(await data(),['2026-09-07','2026-09-18']);await p.locator('[data-calendar-toggle]').click();assert.ok(await p.locator('.ct-range-band').count()>=2);assert.equal(await p.locator('[data-ct-date-number]').innerText(),'07 — 18');assert.deepEqual(await p.evaluate(()=>[new FormData(document.querySelector('form')!).get('period[0]'),new FormData(document.querySelector('form')!).get('period[1]')]),['2026-09-07','2026-09-18']);
  await p.evaluate(()=>(window as any).api.setData(['2026-09-28','2026-10-04']));assert.deepEqual(await data(),['2026-09-28','2026-10-04']);await p.locator('[data-month="1"]').click();assert.ok(await p.locator('[data-day="2026-10-04"]').getAttribute('data-selected')==='true');
 });
 await run('authored datetime/time panels, empty state, reset, mode changes and readOnly remain functional',async()=>{
  await mount('ceramic-calendar',{mode:'datetime',value:'2026-09-07T15:30'});assert.equal(await p.locator('[data-date="0"]').getAttribute('type'),'text');await p.locator('[data-calendar-toggle]').click();assert.ok(await p.locator('[data-calendar-date]').isVisible());assert.ok(await p.locator('[data-time-picker]').isVisible());await p.locator('[data-day="2026-09-12"]').click();assert.equal(await data(),'2026-09-12T15:30');await p.locator('[data-time-hour="16"]').click();await p.locator('[data-time-minute="45"]').click();assert.equal(await data(),'2026-09-12T16:45');assert.ok(await p.locator('[data-calendar]').isHidden());
  await update({mode:'time',value:'15:30'});assert.ok(await p.locator('[data-calendar-toggle]').isVisible());assert.equal(await p.locator('[data-date="0"]').inputValue(),'15:30');await p.locator('[data-calendar-toggle]').click();assert.ok(await p.locator('[data-time-picker]').isVisible());assert.ok(await p.locator('[data-calendar-date]').isHidden());await p.locator('[data-time-hour="17"]').click();await p.locator('[data-time-minute="20"]').click();assert.equal(await data(),'17:20');
  await update({mode:'date',value:'2026-09-07',defaultValue:'2026-09-03'});await p.locator('[data-calendar-toggle]').click();await update({readOnly:true});assert.ok(await p.locator('[data-calendar]').isHidden());assert.ok(await p.locator('[data-calendar-toggle]').isDisabled());assert.ok(await p.locator('[data-date="0"]').evaluate((e:HTMLInputElement)=>e.readOnly));
  await update({readOnly:false});await p.locator('#reset').click();await p.waitForTimeout(25);assert.equal(await data(),'2026-09-03');await p.locator('[data-calendar-toggle]').click();await p.locator('[data-date-clear]').click();assert.equal(await data(),'');await p.locator('[data-calendar-toggle]').click();assert.equal(await p.locator('[data-ct-date-number]').innerText(),'—');
 });
 await run('nested dialog/top-layer calendar stays interactive; duplicated SVG definitions and values are independent',async()=>{
  await mount(['tide-progress','tide-progress'],{value:20});const ids=await p.locator('[id]').evaluateAll(es=>es.map(e=>e.id));assert.equal(ids.length,new Set(ids).size);await p.evaluate(()=>(window as any).apis[1].setData(80));assert.deepEqual(await p.locator('[data-progress]').evaluateAll(es=>es.map(e=>(e as HTMLProgressElement).value)),[20,80]);
  await mount('aurora-calendar',{mode:'date',value:'2026-09-07'});await p.locator('[data-sample]').evaluate(e=>{const d=document.createElement('dialog');d.style.cssText='background:#152329;padding:28px;width:480px';e.before(d);d.append(e);d.showModal();});await p.locator('[data-calendar-toggle]').click();await p.locator('[data-day="2026-09-11"]').click();assert.equal(await data(),'2026-09-11');await p.evaluate(()=>{(window as any).unmount();document.querySelector('dialog')?.remove();});
 });
 await run('16 new loaders animate as CSS scenes, pause including pseudo-elements and expose a readable status',async()=>{
  for(const part of changed.filter(r=>r.category==='loaders')){await mount(part.id);await p.waitForTimeout(75);assert.equal(await p.locator('.sop-motion-loader').getAttribute('data-motion-running'),'true');assert.ok(await p.locator('[role=status]').isVisible());assert.ok(await p.evaluate(()=>document.getAnimations().some(a=>a.playState==='running')),part.id);assert.equal(await p.evaluate(()=>(window as any).activeFrames.size),0);
   await update({paused:true,content:'接続を待っています'});await p.waitForTimeout(25);assert.equal(await p.evaluate(()=>document.getAnimations().filter(a=>a.playState==='running').length),0,part.id);assert.equal(await p.locator('[data-loader-label]').innerText(),'接続を待っています');await update({paused:false});assert.equal(await p.locator('.sop-motion-loader').getAttribute('data-motion-running'),'true');}
 });
 await run('B loaders fit small inline-sized stages and inherit colors on light as well as dark surfaces',async()=>{
  for(const part of changed.filter(r=>r.category==='loaders'&&r.designType==='B')){await mount(part.id);assert.ok((await p.locator('.ct-loader-stage').boundingBox())!.height<=60,part.id);await p.locator('.sop-motion-loader').evaluate((e:HTMLElement)=>{e.style.color='rgb(20, 30, 40)';e.style.background='white';});assert.equal(await p.locator('[data-loader-label]').evaluate(e=>getComputedStyle(e).color),'rgb(20, 30, 40)');const box=await p.locator('.ct-loader-body').boundingBox();assert.ok(box&&box.width<=140&&box.height<=40,part.id);}
 });
 await run('visibility pauses CSS loaders outside viewport, resuming when they re-enter without timers',async()=>{
  await mount('liquid-merge-loader');await p.waitForTimeout(90);assert.equal(await p.locator('.sop-motion-loader').getAttribute('data-motion-running'),'true');await p.locator('[data-sample]').evaluate((e:HTMLElement)=>e.style.marginTop='3000px');await p.waitForFunction(()=>document.querySelector('.sop-motion-loader')?.getAttribute('data-motion-running')==='false');assert.equal(await p.evaluate(()=>document.getAnimations().filter(a=>a.playState==='running').length),0);await p.locator('[data-sample]').evaluate((e:HTMLElement)=>e.style.marginTop='0px');await p.waitForFunction(()=>document.querySelector('.sop-motion-loader')?.getAttribute('data-motion-running')==='true');
 });
 await run('all 58 changed and new layouts fit 320/390/768 and long Japanese text without page overflow',async()=>{
  await p.emulateMedia({reducedMotion:'reduce'});for(const width of [320,390,768]){await p.setViewportSize({width,height:1000});for(const part of changed){await mount(part.id,{label:'狭い画面でも利用できる長い日本語の見出しです',description:'用途に合わせて説明文を差し替えできます。',...(part.category==='datepickers'?{mode:'date'}:{})});if(part.category==='datepickers')await p.evaluate(()=>(window as any).api.show());assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2),part.id+':'+width);if(part.category==='datepickers'){const b=await p.locator('[data-calendar]').boundingBox();assert.ok(b&&b.x>=0&&b.x+b.width<=width+1&&b.y>=0&&b.y+b.height<=1001,part.id+'calendar:'+width);}}}
  await p.setViewportSize({width:740,height:1000});await p.emulateMedia({reducedMotion:'no-preference'});
 });
 await run('reduced motion is static yet usable, forced colors retain native progress/file/date controls',async()=>{
  await p.emulateMedia({reducedMotion:'reduce'});for(const part of changed){await mount(part.id);if(part.category==='progress')await p.evaluate(()=>(window as any).api.setData(83));if(part.category==='uploads')await p.locator('[data-upload]').focus();if(part.category==='datepickers')await p.evaluate(()=>(window as any).api.show());await p.waitForTimeout(15);assert.equal(await p.evaluate(()=>(window as any).activeFrames.size),0,part.id);assert.equal(await p.evaluate(()=>document.getAnimations().filter(a=>a.playState==='running').length),0,part.id);}
  await p.emulateMedia({reducedMotion:'reduce',forcedColors:'active'});await mount('nixie-progress',{value:50});assert.ok(await p.locator('[data-progress]').isVisible());assert.ok(await p.locator('.ct-meter-scene').isHidden());await mount('folio-calendar',{value:'2026-09-07'});await p.locator('[data-calendar-toggle]').click();await p.locator('[data-day="2026-09-08"]').click();assert.equal(await data(),'2026-09-08');await mount('tide-dropzone',{accept:'.txt'});await p.locator('[data-upload]').setInputFiles(txt());assert.equal(await p.locator('.ct-file-row').count(),1);await p.emulateMedia({reducedMotion:'no-preference',forcedColors:'none'});
 });
 await run('teardown removes all event-driven frames, animations, objects and top-layer panels',async()=>{
  for(const part of changed){await mount(part.id);if(part.category==='progress')await p.evaluate(()=>(window as any).api.setData(90));if(part.category==='uploads')await p.locator('[data-upload]').focus();if(part.category==='datepickers')await p.evaluate(()=>(window as any).api.show());await p.evaluate(()=>(window as any).unmount());await p.waitForTimeout(15);assert.equal(await p.evaluate(()=>(window as any).activeFrames.size),0,part.id);assert.equal(await p.locator(':popover-open').count(),0);assert.equal(await p.evaluate(()=>document.getAnimations().filter(a=>a.playState==='running').length),0,part.id);}
 });
 await run('styles are instance-scoped and match when all 887 component skins are present',async()=>{
  await p.emulateMedia({reducedMotion:'reduce'});const shot=async()=>{const snapshots:Record<string,unknown>={};for(const part of changed){await p.mouse.move(0,0);await mount(part.id);if(part.category==='datepickers')await p.evaluate(()=>(window as any).api.show());await p.mouse.move(0,0);snapshots[part.id]=await p.locator('.sop-continuum,.sop-motion-loader,.ct-progress-stage,.ff-reading,.ct-intake,.ct-intake-copy strong,.ff-calendar,.ff-calendar-grid button,.ct-loader-stage,.ct-loader-status').evaluateAll(es=>es.map(e=>{const c=getComputedStyle(e);return Object.fromEntries(['color','background','padding','font-size','border','width','height','transform','position'].map(k=>[k,c.getPropertyValue(k)]));}));}return snapshots;};
  const before=await shot(),seen=new Set<string>();const css=(file:string):string=>{if(seen.has(file))return '';seen.add(file);return fs.readFileSync(path.join(ROOT,file),'utf8').replace(/@import\s+["']([^"']+)["']\s*;/g,(_,ref:string)=>css(path.posix.normalize(path.posix.join(path.posix.dirname(file),ref))));};const registry=JSON.parse(fs.readFileSync(path.join(ROOT,'src/catalog/registry.json'),'utf8')) as string[];await p.addStyleTag({content:registry.map(base=>css(base+'/styles.css')).join('\n')});assert.deepEqual(await shot(),before);await p.emulateMedia({reducedMotion:'no-preference'});
 });
 await run('last frame captures representative real progress/upload/calendar/new loader views',async()=>{
  await mount(['tide-progress','orbital-loom-loader'],{value:64});await p.waitForTimeout(500);await p.screenshot({path:path.join(f.out,'progress-loader.png'),fullPage:true});await mount('folio-dropzone');await p.locator('[data-upload]').focus();await p.waitForTimeout(550);await p.screenshot({path:path.join(f.out,'upload.png')});await mount('prism-calendar',{value:['2026-09-07','2026-09-18'],mode:'range'});await p.locator('[data-calendar-toggle]').click();await p.waitForTimeout(550);await p.screenshot({path:path.join(f.out,'calendar.png')});await p.setViewportSize({width:390,height:844});await p.screenshot({path:path.join(f.out,'mobile-390.png')});
 });
 assert.deepEqual(errors,[]);console.log(`CONTINUUM ${results.length} browser checks passed (${offline?'explicit offline adapter, NOT Vite':'Vite HTTP'}).`);
}catch(error){console.error(error);throw error;}finally{fs.writeFileSync(path.join(f.out,'browser-results.json'),JSON.stringify({mode:offline?'real Chromium / explicit offline compiled fixture; not Vite':'real Vite HTTP',passed:results.length,tests:results,errors},null,2)+'\n');await browser?.close();await close?.();}
