"use strict";
require('./register-ts.cjs');
const test = require('node:test');
const assert = require('node:assert/strict');
const {Spring, clamp, isDrag, dragValue, orbitPosition} = require('../src/shared/motion.ts');
const {validateArchivePath, prepareArchive} = require('../src/shared/archive.js');
test('clamp respects bounds',()=>{assert.equal(clamp(-2),0);assert.equal(clamp(4),1);assert.equal(clamp(.4),.4);});
test('spring converges to the requested state',()=>{for(const target of [1,0,1]){const s=new Spring(1-target);s.setTarget(target);for(let i=0;i<1200;i++)s.advance(1/60);assert.equal(s.value,target);assert.equal(s.velocity,0);assert.ok(s.settled);}});
test('spring ignores invalid elapsed time',()=>{const s=new Spring(0);s.setTarget(1);for(const dt of [0,-1,NaN,Infinity]){s.advance(dt);assert.equal(s.value,0);}});
test('snap cancels spring velocity',()=>{const s=new Spring();s.setTarget(1);s.advance(.02);s.snap(.2);assert.equal(s.value,.2);assert.equal(s.velocity,0);});
test('horizontal drag does not consume vertical scrolling',()=>{assert.ok(isDrag(20,1));assert.ok(!isDrag(1,20));assert.ok(!isDrag(3,0));});
test('drag value is scaled and clamped',()=>{assert.equal(dragValue(0,50,100),.5);assert.equal(dragValue(0,50,100,.5),1);assert.equal(dragValue(1,100,100),1);assert.equal(dragValue(0,-100,100),0);});
test('orbital endpoints match artwork',()=>{assert.equal(orbitPosition(0).x,44);assert.equal(orbitPosition(1).x,236);assert.ok(Math.abs(orbitPosition(1).y-73)<1e-10);});
test('ordinary source paths are accepted',()=>{for(const p of ['init.js','src/ChromeToggle.tsx','assets/styles.css'])assert.equal(validateArchivePath(p),p);});
test('unsafe paths and Windows device names are rejected',()=>{for(const p of ['../x','/x','a\\x','a//x','CON.js','aux.txt','x/NUL','file.','x:bad','a\u0000b'])assert.throws(()=>validateArchivePath(p));});
test('source archives keep filenames and code',()=>{const e=prepareArchive([{name:'app.js',code:'const 日本語 = 1;\n'}],'source');assert.deepEqual(e[0],{name:'app.js',code:'const 日本語 = 1;\n'});assert.ok(e.some(f=>f.name==='WINDOWS-README.txt'));});
test('text archives change only filenames, with a restoration map',()=>{const e=prepareArchive([{name:'app.js',code:'const x = 1;'}],'text');assert.equal(e[0].name,'app.js.txt');assert.equal(e[0].code,'const x = 1;');assert.ok(JSON.parse(e.find(f=>f.name==='FILE-MAP.json.txt').code).files.some(f=>f.original==='app.js'));});
test('case-insensitive duplicate names are rejected',()=>assert.throws(()=>prepareArchive([{name:'a.js',code:''},{name:'A.js',code:''}],'source')));
test('generated filenames cannot replace source files',()=>assert.throws(()=>prepareArchive([{name:'FILE-MAP.json',code:''}],'text')));
test('archive modes are explicit',()=>assert.throws(()=>prepareArchive([],'unknown')));
