/** New collections: real Vite by default; explicit offline transport never claims HTTP/Vite success. */
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {createRequire} from 'node:module';
import type {Page,Browser} from 'playwright';
import {ROOT,buildCatalog} from '../scripts/catalog.ts';
import {offlineFiles,testBundle} from './offline-fixture.ts';
import {getDelivery} from '../src/catalog/delivery.ts';
import {requireLocalServerUrl} from './vite-url.ts';
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.PLAYWRIGHT_PATH??'playwright') as typeof import('playwright');
const offline=process.env.SOP_TEST_MODE==='offline',data=buildCatalog();
const parts=data.parts.filter(p=>p.category==='dropdowns'||p.category==='accordions');
const dropdowns=parts.filter(p=>p.category==='dropdowns'),accordions=parts.filter(p=>p.category==='accordions');
const out=path.join(ROOT,'.test-output/disclosures');fs.mkdirSync(out,{recursive:true});
const passed:string[]=[],errors:string[]=[];let browser:Browser|undefined,closeServer:(()=>Promise<void>)|undefined,url='';
async function run(name:string,fn:()=>Promise<void>){await fn();passed.push(name);console.log('PASS '+name);}
let page:Page;
try{
 if(!offline){const {createServer}=await import('vite');const server=await createServer({root:ROOT,server:{port:0,host:'127.0.0.1'}});closeServer=()=>server.close();await server.listen();url=requireLocalServerUrl(server,'Vite disclosure test server');}
 browser=await chromium.launch({headless:true,args:['--no-sandbox'],...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{})});
 const context=await browser.newContext({viewport:{width:1440,height:1000},hasTouch:true});
 const track=()=>{const set=new Set<number>(),request=requestAnimationFrame.bind(window),cancel=cancelAnimationFrame.bind(window);Object.assign(window,{pendingDisclosureRAF:set});window.requestAnimationFrame=fn=>{const id=request(t=>{set.delete(id);fn(t);});set.add(id);return id;};window.cancelAnimationFrame=id=>{set.delete(id);cancel(id);};};
 const listen=(p:Page)=>p.on('pageerror',e=>errors.push(e.message));
 page=await context.newPage();listen(page);
 if(offline){const files=offlineFiles();await page.setContent(files.get('/index.html')!.replace(/<script[^>]*>[\s\S]*?<\/script>/g,'').replace(/<link[^>]*>/g,''));await page.addStyleTag({content:files.get('/test-styles.css')!});for(const name of ['prism','jszip'])await page.addScriptTag({content:fs.readFileSync(path.join(ROOT,'public/vendor/'+name+'.js'),'utf8')});await page.addScriptTag({content:files.get('/test-app.js')!});}else await page.goto(url);
 await run('24 dropdowns: actual options, End/Enter commit, Escape cancellation, no accidental detail dialog',async()=>{
  await page.locator('[data-category="dropdowns"]').click();assert.equal(await page.locator('[data-part]').count(),24);
  for(const p of dropdowns){const root=page.locator(`[data-part="${p.id}"] .sop-select`),button=root.locator('.sop-select-trigger');await button.click();assert.equal(await button.getAttribute('aria-expanded'),'true');await page.keyboard.press('End');const last=await root.locator('[role="option"]').last().getAttribute('data-value');await page.keyboard.press('Enter');assert.equal(await root.getAttribute('data-value'),last);assert.equal(await button.getAttribute('aria-expanded'),'false');await button.click();await page.keyboard.press('Home');await page.keyboard.press('Escape');assert.equal(await root.getAttribute('data-value'),last);assert.equal(await page.locator('dialog[open]').count(),0);}
 });
 await run('Dropdown top layer in the detail modal; first Escape closes choices, next closes detail',async()=>{
  await page.locator('[data-open="aurora-select"]').click();const modal=page.locator('dialog[open]').first(),button=modal.locator('.sop-select-trigger');await button.click();await page.waitForTimeout(300);const panel=modal.locator('.sop-select-popup');assert.equal(await panel.evaluate(e=>e.matches(':popover-open')),true);const box=(await panel.boundingBox())!;assert.ok(box.x>=0&&box.y>=0&&box.x+box.width<=1440&&box.y+box.height<=1001);await page.screenshot({path:path.join(out,'dropdown-detail.png')});await page.keyboard.press('Escape');assert.equal(await button.getAttribute('aria-expanded'),'false');assert.equal(await page.locator('dialog[open]').count(),1);await page.keyboard.press('Escape');assert.equal(await page.locator('dialog[open]').count(),0);
 });
 await run('24 accordions: real height transitions, single expand, native buttons and keyboard focus',async()=>{
  await page.locator('[data-category="accordions"]').click();
  for(const p of accordions){const root=page.locator(`[data-part="${p.id}"] .sop-accordion`);const triggers=root.locator('.sop-accordion-trigger');await triggers.nth(1).click();assert.equal(await triggers.nth(1).getAttribute('aria-expanded'),'true');assert.equal(await triggers.first().getAttribute('aria-expanded'),'false');assert.equal(await root.locator('.sop-accordion-panel').first().evaluate(e=>(e as HTMLElement).inert),true);await triggers.nth(1).focus();await page.keyboard.press('End');assert.equal(await triggers.last().evaluate(e=>e===document.activeElement),true);await page.keyboard.press('Enter');assert.equal(await triggers.last().getAttribute('aria-expanded'),'true');assert.equal(await page.locator('dialog[open]').count(),0);}
 });
 await run('Accordion designed interiors remain interactive; multiple expand controls work',async()=>{
  const settings=page.locator('[data-part="settings-accordion"] .sop-accordion');await settings.locator('.sop-accordion-trigger').first().click();const check=settings.locator('.sop-accordion-content input').first();const before=await check.isChecked();await check.click();assert.notEqual(await check.isChecked(),before);assert.equal(await page.locator('dialog[open]').count(),0);
  await page.locator('[data-open="folio-accordion"]').click();const modal=page.locator('dialog[open]').first();await modal.locator('[data-inspect-multiple]').check();await modal.locator('.sop-accordion-trigger').nth(1).click();assert.equal(await modal.locator('.sop-accordion-trigger[aria-expanded="true"]').count(),2);await modal.locator('[data-inspect-collapse]').click();assert.equal(await modal.locator('.sop-accordion-trigger[aria-expanded="true"]').count(),0);await page.keyboard.press('Escape');
 });
 await run('Both new categories at 320 / 390 / 768px: no page overflow, viewport-contained popup and detail controls',async()=>{
  for(const width of [320,390,768]){await page.setViewportSize({width,height:900});for(const category of ['dropdowns','accordions']){await page.locator(`[data-category="${category}"]`).click();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));for(const p of parts.filter(p=>p.category===category)){const root=page.locator(`[data-part="${p.id}"] ${category==='dropdowns'?'.sop-select':'.sop-accordion'}`),b=(await root.boundingBox())!;assert.ok(b.x>=-1&&b.x+b.width<=width+1,p.id+width);}}
   await page.locator('[data-category="dropdowns"]').click();const b=page.locator('[data-part="aurora-select"] .sop-select-trigger');await b.click();await page.waitForTimeout(250);const box=(await page.locator('[data-part="aurora-select"] .sop-select-popup').boundingBox())!;assert.ok(box.x>=0&&box.x+box.width<=width+1&&box.y>=0&&box.y+box.height<=901);if(width===390)await page.screenshot({path:path.join(out,'mobile-390.png')});await page.keyboard.press('Escape');}
  await page.setViewportSize({width:1440,height:1000});
 });
 // Isolated controllers: no gallery styles or globals, unrelated existing application controls remain intact.
 const isolated=await context.newPage();listen(isolated);await isolated.setContent('<main id="test"></main><button id="outside">Next control</button>');await isolated.addStyleTag({content:data.styles});await isolated.evaluate(track);
 const extras=new Map([['.test-output/disclosure-controllers.ts',"import{createSelectController}from'../src/shared/select-controller';import{createAccordionController}from'../src/shared/accordion-controller';Object.assign(window,{DisclosureControllers:{createSelectController,createAccordionController}});"]]);
 await isolated.addScriptTag({content:testBundle('.test-output/disclosure-controllers.ts',extras)});
 const controllerSetup=async(kind:'select'|'accordion',markup:string,options:Record<string,unknown>={})=>{
  await isolated.evaluate(({kind,markup,options})=>{const w=window as any;w.instance?.destroy();document.querySelector('#test')!.innerHTML=`<form id="form">${markup}<button type="reset" id="reset">Reset</button></form>`;const root=document.querySelector('#form')!.firstElementChild as HTMLElement;w.lastRequested=null;w.instance=w.DisclosureControllers[kind==='select'?'createSelectController':'createAccordionController'](root,{...options,onValueChange:(v:string)=>w.lastRequested=v,onExpandedChange:(v:string[])=>w.lastRequested=v});},{kind,markup,options});
 };
 await run('Native select: typeahead, form submission/reset, disabled choice, disabled field and external focus',async()=>{
  const p=dropdowns[0];await controllerSetup('select',p.markup);
  await isolated.locator('.sop-select-input').evaluate(e=>(e as HTMLInputElement).name='atmosphere');
  const button=isolated.locator('.sop-select-trigger');await button.click();await isolated.keyboard.press('v');await isolated.keyboard.press('Enter');assert.equal(await isolated.locator('[aria-selected="true"]').getAttribute('data-value'),'violet');
  assert.equal(await isolated.evaluate(()=>new FormData(document.querySelector('form')!).get('atmosphere')),'violet');await isolated.locator('#reset').click();assert.equal(await isolated.locator('.sop-select').getAttribute('data-value'),'arctic');
  await isolated.locator('[role="option"]').nth(1).evaluate(e=>e.setAttribute('aria-disabled','true'));await button.click();await isolated.keyboard.press('ArrowDown');await isolated.keyboard.press('Enter');assert.equal(await isolated.locator('.sop-select').getAttribute('data-value'),'solar');
  await button.click();await isolated.locator('#outside').focus();assert.equal(await button.getAttribute('aria-expanded'),'false');await button.evaluate(e=>(e as HTMLButtonElement).disabled=true);await isolated.waitForTimeout(0);assert.equal(await isolated.evaluate(()=>new FormData(document.querySelector('form')!).has('atmosphere')),false);
 });
 await run('Controlled native select refuses commits until setValue; empty choices stay safe',async()=>{
  await controllerSetup('select',dropdowns[0].markup,{controlled:true});await isolated.locator('.sop-select-trigger').click();await isolated.keyboard.press('End');await isolated.keyboard.press('Enter');assert.equal(await isolated.locator('.sop-select').getAttribute('data-value'),'arctic');assert.equal(await isolated.evaluate(()=>(window as any).lastRequested),'lunar');await isolated.evaluate(()=>{(window as any).instance.setValue('solar');});assert.equal(await isolated.locator('.sop-select').getAttribute('data-value'),'solar');await isolated.evaluate(()=>{document.querySelectorAll('[role=option]').forEach(e=>e.remove());(window as any).instance.refresh();});await isolated.locator('.sop-select-trigger').click();assert.equal(await isolated.locator('.sop-select-trigger').getAttribute('aria-expanded'),'false');
 });
 await run('Accordion controlled refusal, dynamic content height, focus recovery and required-open policy',async()=>{
  await controllerSetup('accordion',accordions[0].markup,{controlled:true});await isolated.locator('.sop-accordion-trigger').nth(1).click();assert.equal(await isolated.locator('.sop-accordion-trigger').nth(1).getAttribute('aria-expanded'),'false');assert.deepEqual(await isolated.evaluate(()=>(window as any).lastRequested),['section-2']);
  await controllerSetup('accordion',accordions[0].markup,{collapsible:false});await isolated.locator('.sop-accordion-trigger').first().focus();await isolated.keyboard.press('Enter');assert.equal(await isolated.locator('.sop-accordion-trigger').first().getAttribute('aria-expanded'),'true');await isolated.locator('.sop-accordion-content').first().evaluate(e=>{const b=document.createElement('button');b.textContent='Inside';e.append(b);b.focus();});await isolated.evaluate(()=>(window as any).instance.setExpanded(['section-2']));assert.equal(await isolated.locator('.sop-accordion-trigger').first().evaluate(e=>e===document.activeElement),true);await isolated.locator('.sop-accordion-content').nth(1).evaluate(e=>{const d=document.createElement('div');d.style.height='800px';e.append(d);});await isolated.waitForTimeout(450);assert.ok((await isolated.locator('.sop-accordion-panel').nth(1).boundingBox())!.height>800);
 });
 await run('Nested accordions keep independent state and unique ids; cleanup leaves no RAF',async()=>{
  await controllerSetup('accordion',accordions[0].markup,{multiple:true});await isolated.locator('.sop-accordion-content').first().evaluate((e,markup)=>e.insertAdjacentHTML('beforeend',markup),accordions[1].markup);await isolated.evaluate(()=>{const w=window as any;w.nested=w.DisclosureControllers.createAccordionController(document.querySelector('.sop-accordion .sop-accordion'));});const inner=isolated.locator('.sop-accordion .sop-accordion');await inner.locator('.sop-accordion-trigger').nth(1).click();assert.equal(await isolated.locator('#form>.sop-accordion>.sop-accordion-item').first().getAttribute('data-open'),'true');const ids=await isolated.locator('[id]').evaluateAll(es=>es.map(e=>e.id));assert.equal(ids.length,new Set(ids).size);await isolated.evaluate(()=>{const w=window as any;w.nested.destroy();w.instance.destroy();document.querySelector('#test')!.replaceChildren();});await isolated.waitForTimeout(50);assert.equal(await isolated.evaluate(()=>(window as any).pendingDisclosureRAF.size),0);
 });
 await isolated.close();
 await run('Reduced-motion: menus and accordion panels use no animated transition',async()=>{await page.emulateMedia({reducedMotion:'reduce'});await page.locator('[data-category="accordions"]').click();const b=page.locator('[data-part="folio-accordion"] .sop-accordion-trigger').nth(1);await b.click();assert.equal(await b.evaluate(e=>getComputedStyle(e).transitionDuration),'0s');await page.emulateMedia({reducedMotion:'no-preference'});});
 // Real React verification: no substitute implementation. Offline requires an actual runtime supplied explicitly.
 if(!offline||process.env.SOP_REACT_BROWSER_BUNDLE){
  for(const format of ['tsx','jsx']as const)for(const layout of ['portable','original']as const){
   const extras=new Map<string,string>(),prefix=`.test-output/disclosures/react-${format}-${layout}`;
   const imports=parts.map((p,i)=>{const d=getDelivery(p,format,layout);for(const f of d.files){const name=`${prefix}/${p.id}/${f.name}`;extras.set(name,f.code);fs.mkdirSync(path.dirname(path.join(ROOT,name)),{recursive:true});fs.writeFileSync(path.join(ROOT,name),f.code);}return `import Part${i} from './${p.id}/${d.entry}';`;}).join('\n');
   const source=`import React,{useState}from'react';import{createRoot}from'react-dom/client';${imports}\nconst parts=[${parts.map((p,i)=>`{id:${JSON.stringify(p.id)},select:${p.category==='dropdowns'},C:Part${i}}`).join(',')}];
function Item({part,declined=false}){const [value,setValue]=useState('a'),[expanded,setExpanded]=useState(['a']),[updated,update]=useState(false);const C=part.C;return <section data-react-part={part.id} data-declined={declined}><button onClick={()=>update(!updated)} className="update">Update content</button>{part.select?<C label="Destination" name="choice" items={[{value:'a',label:updated?'Alpha changed':'Alpha',description:'Description A'},{value:'b',label:'Beta',description:'Description B'}]} value={value} onValueChange={declined?()=>{}:setValue}/>:<C items={[{value:'a',title:'First section',content:<label><input type="checkbox"/>Independent setting</label>},{value:'b',title:updated?'Changed':'Second section',content:<div style={{height:updated?500:60}}>Detailed content</div>}]} expanded={expanded} onExpandedChange={declined?()=>{}:setExpanded}/>}</section>}
function App(){const[show,setShow]=useState(true);return <><button id="mount" onClick={()=>setShow(!show)}>Mount</button>{show&&parts.map(p=><Item key={p.id} part={p}/>)}{show&&<Item part={parts[0]} declined/>}</>};createRoot(document.getElementById('root')).render(<React.StrictMode><App/></React.StrictMode>);`;
   const entry=prefix+'/main.jsx';extras.set(entry,source);fs.writeFileSync(path.join(ROOT,entry),source);const html='<html><head><meta charset="utf-8"></head><body style="background:#14181a;color:#ddd"><div id="root"></div><script type="module" src="./main.jsx"></script></body></html>';fs.writeFileSync(path.join(ROOT,prefix,'index.html'),html);
   const reactPage=await context.newPage();listen(reactPage);await reactPage.addInitScript(track);
   if(offline){await reactPage.setContent(html.replace(/<script[\s\S]*?<\/script>/,''));await reactPage.evaluate(track);await reactPage.addStyleTag({content:data.styles+'section[data-react-part]{max-width:430px;padding:24px;margin:24px}'});const runtime=fs.readFileSync(process.env.SOP_REACT_BROWSER_BUNDLE!,'utf8');await reactPage.evaluate(async text=>{const u=URL.createObjectURL(new Blob([text],{type:'text/javascript'}));const m=await import(u);Object.assign(window,{ActualReact:m.r,ActualReactDOM:m.e});URL.revokeObjectURL(u);},runtime);await reactPage.addScriptTag({content:testBundle(entry,extras,'const React=window.ActualReact,ReactDOMClient=window.ActualReactDOM;')});}
   else{await reactPage.goto(new URL('/'+prefix+'/index.html',url).href);}
   await run(`Actual React ${format}/${layout}: 48 exports, controlled state, item updates, refusal and mount cleanup`,async()=>{
    await reactPage.locator('[data-react-part]').first().waitFor();assert.equal(await reactPage.locator('[data-react-part]').count(),49);
    for(const p of parts){const root=reactPage.locator(`[data-react-part="${p.id}"][data-declined="false"]`);if(p.category==='dropdowns'){const b=root.locator('.sop-select-trigger');await b.click();await reactPage.keyboard.press('End');await reactPage.keyboard.press('Enter');await reactPage.waitForFunction(id=>document.querySelector(`[data-react-part="${id}"][data-declined="false"] .sop-select`)?.getAttribute('data-value')==='b',p.id);await root.locator('.update').click();assert.ok((await root.locator('[role="option"]').first().innerText()).includes('Alpha changed'));}else{const b=root.locator('.sop-accordion-trigger').nth(1);await b.click();assert.equal(await b.getAttribute('aria-expanded'),'true');await root.locator('.update').click();assert.ok((await b.innerText()).includes('Changed'));}}
    const refused=reactPage.locator('[data-declined="true"]');await refused.locator('.sop-select-trigger').click();await reactPage.keyboard.press('End');await reactPage.keyboard.press('Enter');assert.equal(await refused.locator('.sop-select').getAttribute('data-value'),'a');
    const ids=await reactPage.locator('[id]').evaluateAll(es=>es.map(e=>e.id));assert.equal(ids.length,new Set(ids).size);
    for(let i=0;i<3;i++){await reactPage.locator('#mount').click();assert.equal(await reactPage.locator('[data-react-part]').count(),0);await reactPage.waitForTimeout(50);assert.equal(await reactPage.evaluate(()=>(window as any).pendingDisclosureRAF.size),0);await reactPage.locator('#mount').click();assert.equal(await reactPage.locator('[data-react-part]').count(),49);}
   });await reactPage.close();
  }
 }else console.log('React runtime checks NOT RUN: no actual React browser runtime supplied in offline mode.');
 assert.deepEqual(errors,[]);
}finally{fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({transport:offline?'explicit synthetic browser document (NOT Vite HTTP)':'real Vite HTTP for gallery/React',react:offline?(process.env.SOP_REACT_BROWSER_BUNDLE?'actual installed runtime supplied':'not executed'):'installed React',passed,errors},null,2));await browser?.close();await closeServer?.();}
console.log(`Disclosure checks: ${passed.length} passed.`);
