import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {chromium} from 'playwright';import {createServer} from 'vite';import {buildCatalog,ROOT} from '../scripts/catalog.ts';import {getDelivery} from '../src/catalog/delivery.ts';import {currentParts} from './gallery-counts.ts';
const specs=currentParts().filter(p=>p.tags.includes('EXPANSION-50'));const categories=[...new Set(specs.map(p=>p.category))];const chosen=process.env.SOP_EXPANSION_CATEGORIES?.split(',');
const server=await createServer({root:ROOT,configFile:false,optimizeDeps:{entries:[],noDiscovery:true},server:{host:'127.0.0.1',port:0,hmr:false,watch:{ignored:['**/.test-output/**','**/docs/**']}}});await server.listen();const browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{})});const errors:string[]=[];
try{for(const category of categories.filter(c=>!chosen||chosen.includes(c))){const parts=buildCatalog(ROOT,specs.filter(p=>p.category===category).map(p=>p.id),{appearance:false}).parts;
 for(const layout of ['portable','original'] as const){const directory=path.join(ROOT,`.test-output/expansion-50-native/${category}/${layout}`);fs.mkdirSync(directory,{recursive:true});
 const imports=parts.map((p,i)=>{const d=getDelivery(p,'js',layout);for(const f of d.files){const target=path.join(directory,p.id,f.name);fs.mkdirSync(path.dirname(target),{recursive:true});fs.writeFileSync(target,f.code);}return `import {init as init${i}} from './${p.id}/${d.entry}';\nimport './${p.id}/${d.stylesheet}';`;}).join('\n');
 fs.writeFileSync(path.join(directory,'entry.js'),imports+`\nconst entries=[${parts.map((p,i)=>`{id:${JSON.stringify(p.id)},markup:${JSON.stringify(p.markup)},init:init${i}}`).join(',')}];window.controllers=[];for(const p of entries){const host=document.createElement('section');host.dataset.part=p.id;host.innerHTML=p.markup;document.querySelector('#root').append(host);window.controllers.push(p.init(host.firstElementChild));}window.teardown=()=>{for(const c of window.controllers)c?.destroy?.();document.querySelector('#root').replaceChildren()};window.ready=true;`);
 fs.writeFileSync(path.join(directory,'index.html'),'<html><head><meta charset="utf-8"><link rel="icon" href="data:,"><style>body{margin:0;padding:12px;background:#242b36;color:#eee}section{width:100%;max-width:340px;margin:15px 0;padding:10px;box-sizing:border-box}</style></head><body><div id="root"></div><script type="module" src="./entry.js"></script></body></html>');
 const page=await browser.newPage({viewport:{width:390,height:844},reducedMotion:'reduce'});page.on('pageerror',e=>errors.push(e.message));await page.goto(server.resolvedUrls!.local[0]+path.relative(ROOT,path.join(directory,'index.html')).replaceAll('\\','/'),{timeout:120000});await page.waitForFunction(()=>(window as any).ready,undefined,{timeout:120000});
 for(const p of parts){const host=page.locator(`[data-part="${p.id}"]`);assert.ok(await host.locator(`.sop-${p.id}`).count(),p.id+' native root');if(['ornaments','loaders'].includes(category))assert.equal(await host.locator('.x-composition i').count(),6,p.id+' native artwork');if(category==='toggles'){const sw=host.locator('[role=switch]');const before=await sw.getAttribute('aria-checked');await sw.click();assert.notEqual(await sw.getAttribute('aria-checked'),before);}if(category==='tabs'){await host.locator('[role=tab]').last().click();assert.equal(await host.locator('[role=tab]').last().getAttribute('aria-selected'),'true');}}
 if(category==='commands')for(let index=0;index<parts.length;index++){
  const id=parts[index].id,root=page.locator(`[data-part="${id}"]`),input=root.locator('.wb-command-input'),call=(name:string,arg?:unknown)=>page.evaluate(({index,name,arg})=>(window as any).controllers[index][name](arg),{index,name,arg});const items=[{id:'a',label:'First',group:'Actual group'},{id:'off',label:'Disabled',group:'Actual group',disabled:true},{id:'b',label:'Last'}];await call('updateWorkbench',{items});await call('openWorkbench');assert.equal(await root.locator('[role=group]').count(),1);await input.press('ArrowDown');assert.equal(await input.evaluate(e=>document.getElementById(e.getAttribute('aria-activedescendant')!)?.dataset.command),'b',id+' exported disabled skip');await call('updateWorkbench',{items:[items[0],items[2],items[1]],label:'Updated command'});assert.equal(await input.evaluate(e=>document.getElementById(e.getAttribute('aria-activedescendant')!)?.dataset.command),'b');await input.fill('native');await input.press('End');await page.keyboard.insertText(' edited');const original=await input.elementHandle();await call('updateWorkbench',{placeholder:'Changed hint'});assert.equal(await input.evaluate((e,old)=>e===old,original),true);await input.press('Control+z');assert.equal(await input.inputValue(),'native');await input.fill('');await call('updateWorkbench',{items:[{id:'parent',label:'Parent',children:[{id:'nested',label:'Nested',children:[{id:'leaf',label:'Leaf'}]}]}]});await root.locator('[data-command=parent]').click();await root.locator('[data-command=nested]').click();await root.locator('[data-command-level="0"]').click();assert.deepEqual((await call('getWorkbench') as any).path,['parent']);assert.equal(await input.evaluate(e=>e===document.activeElement),true);await page.keyboard.press('Escape');assert.equal((await call('getWorkbench') as any).open,false);
 }
 if(category==='navigation')for(let index=0;index<parts.length;index++){
 const id=parts[index].id,root=page.locator(`[data-part="${id}"] .sop-wb`).first(),items=[{id:'a',label:'First',href:'#a'},{id:'parent',label:'Parent',children:[{id:'child',label:'Child',href:'#child'}]},{id:'off',label:'Disabled',disabled:true,children:[{id:'blocked',label:'Blocked',href:'#blocked'}]}],update=async(patch:unknown)=>{await page.evaluate(({index,patch})=>(window as any).controllers[index].updateWorkbench(patch),{index,patch});},state=()=>page.evaluate(index=>(window as any).controllers[index].getWorkbench(),index);await update({items,layout:'sidebar',brand:'Live brand',brandHref:'#brand',label:'Live navigation'});const link=root.locator('.wb-nav-desktop [data-nav=a]');await link.focus();await update({items:items.map(i=>i.id==='a'?{...i,label:'Updated first'}:i)});assert.equal(await link.evaluate(e=>e===document.activeElement),true);assert.equal(await root.locator('.wb-nav-brand strong').textContent(),'Live brand');assert.equal(await root.locator('.wb-nav-brand>a').getAttribute('href'),'#brand');assert.equal(await root.locator('.wb-navigation-frame').getAttribute('aria-label'),'Live navigation');await root.locator('[data-nav-group=parent]').press('ArrowDown');await root.locator('.wb-nav-flyout [data-nav=child]').focus();await update({items:items.map(i=>i.id==='parent'?{...i,children:[{id:'child',label:'New child',href:'#new-child'}]}:i)});assert.equal((await state()).group,'parent');assert.equal(await root.locator('.wb-nav-flyout [data-nav=child]').evaluate(e=>e===document.activeElement),true);await page.keyboard.press('Escape');await update({layout:'mobile'});await root.locator('.wb-nav-mobile-open').click();const off=root.locator('dialog [data-nav-mobile-group=off]');assert.equal(await off.locator('summary').getAttribute('aria-disabled'),'true');await off.locator('summary').dispatchEvent('click');assert.equal(await off.evaluate(e=>(e as HTMLDetailsElement).open),false);assert.equal(await off.locator('[data-nav=blocked]').getAttribute('href'),null);const actual=root.locator('dialog [data-nav-mobile-group=parent]');await actual.locator('summary').click();await actual.locator('[data-nav=child]').focus();await update({items:items.map(i=>i.id==='parent'?{...i,children:[{id:'child',label:'Mobile child',href:'#mobile-child'}]}:i)});assert.equal(await actual.evaluate(e=>(e as HTMLDetailsElement).open),true);assert.equal(await actual.locator('[data-nav=child]').evaluate(e=>e===document.activeElement),true);await page.keyboard.press('Escape');await page.waitForFunction(index=>(window as any).controllers[index].getWorkbench().open===false,index);
 }
 if(category==='tables')for(let index=0;index<parts.length;index++){
  const id=parts[index].id,root=page.locator(`[data-part="${id}"]`),call=(name:string,arg?:unknown)=>page.evaluate(({index,name,arg})=>(window as any).controllers[index][name](arg),{index,name,arg}),state=()=>call('getWorkbench'),input=root.locator('input[type=search]');await root.locator('[data-sort=size]').click();assert.equal((await state()).sort.direction,'ascending');await input.fill('Design');assert.equal((await state()).total,1);await input.fill('');const fixedSelection=["archive-ledger-table", "inspection-grid-table", "folded-register-table", "stone-record-table", "letterpress-data-table", "index-drawer-table", "rail-dataset-table", "stitched-register-table", "open-sheet-table", "folio-register-table", "caption-register-table", "blueprint-register-table", "ribbon-register-table", "ceramic-register-table", "receipt-register-table"].includes(id),geometry=()=>root.evaluate(e=>{const base=e.getBoundingClientRect();return [...e.querySelectorAll('tbody tr[data-row] input,tbody tr[data-row] .wb-cell-text,.wb-table-search input')].map(n=>{const a=n.getBoundingClientRect();return[a.x-base.x,a.y-base.y,a.width,a.height,getComputedStyle(n).font]})}),beforeSelection=await geometry();await root.locator('[data-row-check]').first().check();assert.equal((await state()).selected.length,1);if(fixedSelection)assert.deepEqual(await geometry(),beforeSelection,id+' native selected glyph/hit stable');await root.locator('[data-table-clear]').click();assert.deepEqual((await state()).selected,[]);if(fixedSelection)assert.deepEqual(await geometry(),beforeSelection,id+' native clear glyph/hit stable');await root.locator('[data-table-page=next]').click();assert.equal((await state()).page,2);await root.locator('[data-sort=name]').focus();await call('updateWorkbench',{label:'Live table'});assert.equal(await root.locator('[data-sort=name]').evaluate(e=>e===document.activeElement),true);assert.equal(await root.locator('h3').textContent(),'Live table');await call('updateWorkbench',{loading:true});assert.equal(await root.locator('table').getAttribute('aria-busy'),'true');await call('updateWorkbench',{loading:false,error:'Actual error'});assert.match((await root.locator('tbody').textContent())??'',/Actual error/);await call('updateWorkbench',{error:'',disabled:true});assert.equal(await input.isDisabled(),true);await call('updateWorkbench',{disabled:false,rows:[]});assert.match((await root.locator('tbody').textContent())??'',/該当するデータ/);
 }
 if(category==='contextmenus')for(let index=0;index<parts.length;index++){
  const id=parts[index].id,root=page.locator(`[data-part="${id}"]`),action=(key:string)=>root.locator(`[data-menu-action="${key}"]`),call=(name:string,arg?:unknown)=>page.evaluate(({index,name,arg})=>(window as any).controllers[index][name](arg),{index,name,arg});await call('updateWorkbench',{items:[{id:'toggle',label:'Check',kind:'checkbox'},{id:'off',label:'Disabled',disabled:true},{id:'parent',label:'Parent',children:[{id:'child',label:'Child'}]}],checked:{toggle:false}});await call('openWorkbench');await action('toggle').focus();await call('updateWorkbench',{label:'Updated actions',targetLabel:'Updated file',targetDescription:'Updated description'});assert.equal(await action('toggle').evaluate(e=>e===document.activeElement),true,id+' native owned focus');assert.equal(await root.locator('[role=menu]').getAttribute('aria-label'),'Updated actions');assert.equal(await root.locator('.wb-context-target-copy strong').textContent(),'Updated file');assert.equal(await root.locator('.wb-context-target-copy small').textContent(),'Updated description');await action('toggle').click();assert.equal(await action('toggle').getAttribute('aria-checked'),'false');await action('off').focus();await action('off').press('Enter');assert.equal((await call('getWorkbench')).lastAction,null);await action('parent').click();await call('updateWorkbench',{items:[{id:'parent',label:'New parent',children:[{id:'child',label:'New child'}]}]});assert.deepEqual((await call('getWorkbench')).path,['parent']);assert.equal(await action('child').locator('strong').textContent(),'New child');await page.keyboard.press('ArrowLeft');assert.equal(await action('parent').evaluate(e=>e===document.activeElement),true);await root.locator('.sop-wb').evaluate(e=>e.setAttribute('dir','rtl'));await page.keyboard.press('ArrowLeft');assert.deepEqual((await call('getWorkbench')).path,['parent']);await page.keyboard.press('ArrowRight');assert.deepEqual((await call('getWorkbench')).path,[]);await action('parent').click();await call('updateWorkbench',{items:[]});assert.equal(await root.locator('[role=menu]').evaluate(e=>e===document.activeElement),true);await page.keyboard.press('Escape');assert.equal((await call('getWorkbench')).open,false);await call('openWorkbench');assert.equal(await root.locator('[role=menu]').evaluate(e=>e===document.activeElement),true);await page.keyboard.press('Escape');
 }
 if(['ornaments','loaders'].includes(category)){
  await page.emulateMedia({reducedMotion:'no-preference'});
  for(let i=0;i<parts.length;i++){
   const root=page.locator(`[data-part="${parts[i].id}"]`).locator(`.sop-${parts[i].id}`);await root.scrollIntoViewIfNeeded();
   await page.waitForFunction(id=>{const root=document.querySelector(`[data-part="${id}"]`)!;return root.getAnimations({subtree:true}).some(a=>a.playState==='running');},parts[i].id);
   await page.evaluate(i=>(window as any).controllers[i].setPaused(true),i);
   assert.ok(await root.evaluate(e=>e.getAnimations({subtree:true}).every(a=>a.playState==='paused')),parts[i].id+' pauses actual animation');
   await page.evaluate(i=>(window as any).controllers[i].setPaused(false),i);
  }
  await page.emulateMedia({reducedMotion:'reduce'});
  for(const p of parts)assert.equal(await page.locator(`[data-part="${p.id}"] .x-composition`).evaluate(e=>e.getAnimations({subtree:true}).length),0,p.id+' reduced motion');
 }
 for(const width of [320,390,768]){await page.setViewportSize({width,height:844});await page.evaluate(()=>new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve()))));assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),category+' native '+layout+' fits '+width);}
 await page.evaluate(()=>(window as any).teardown());assert.equal(await page.locator('[data-part]').count(),0);await page.close();console.log('PASS '+category+' '+parts.length+' native JavaScript '+layout+' real imports, narrow widths, cleanup');}
}assert.deepEqual(errors,[]);}finally{await browser.close();await server.close();}
