import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {chromium} from 'playwright';import {createServer} from 'vite';
import {buildCatalog,ROOT} from '../scripts/catalog.ts';import {getDelivery} from '../src/catalog/delivery.ts';import {currentParts} from './gallery-counts.ts';import {lightSelectedContrast} from './light-selected-contrast.ts';
const specs=currentParts().filter(p=>p.tags.includes('EXPANSION-50'));const categories=[...new Set(specs.map(p=>p.category))];const chosen=process.env.SOP_EXPANSION_CATEGORIES?.split(',');
const browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{})});const errors:string[]=[];
const server=await createServer({root:ROOT,configFile:false,cacheDir:path.join(ROOT,'.test-output/expansion-50-react/vite-cache'),optimizeDeps:{entries:[],noDiscovery:true,include:['react','react-dom','react-dom/client','react/jsx-dev-runtime']},server:{host:'127.0.0.1',port:0,hmr:false,watch:null}});await server.listen();
try{
 for(const category of categories.filter(c=>!chosen||chosen.includes(c))){
  const parts=buildCatalog(ROOT,specs.filter(p=>p.category===category).map(p=>p.id),{appearance:false}).parts;
  for(const [format,layout] of [['tsx','portable'],['jsx','original'],['tsx','original'],['jsx','portable']] as const){
   const directory=path.join(ROOT,`.test-output/expansion-50-react/${category}/${format}-${layout}`);fs.mkdirSync(directory,{recursive:true});
   const imports=parts.map((part,i)=>{const d=getDelivery(part,format,layout);for(const f of d.files){const target=path.join(directory,part.id,f.name);fs.mkdirSync(path.dirname(target),{recursive:true});fs.writeFileSync(target,f.code);}return `import C${i} from './${part.id}/${d.entry}';`;}).join('\n');
   fs.writeFileSync(path.join(directory,'entry.jsx'),`import React,{useState} from 'react';import{createRoot}from'react-dom/client';${imports}\nconst entries=[${parts.map((p,i)=>`{id:${JSON.stringify(p.id)},C:C${i}}`).join(',')}];window.calls=[];window.searchFixtures={};window.commandFixtures={};function SearchFixture({id,C}){const[query,setQuery]=useState(''),[label,setLabel]=useState('Search'),[accept,setAccept]=useState(true);window.searchFixtures[id]={setLabel,setAccept};return <C query={query} label={label} onQueryChange={q=>{window.calls.push(q);if(accept)setQuery(q)}}/>}function CommandFixture({id,C}){const[options,setOptions]=useState({items:[{id:'a',label:'First',group:'Actual group'},{id:'off',label:'Disabled',group:'Actual group',disabled:true},{id:'b',label:'Last'}]});window.commandFixtures[id]={update:patch=>setOptions(o=>({...o,...patch}))};return <C {...options}/>}window.contextFixtures={};window.contextApis={};function ContextFixture({id,C}){const[options,setOptions]=useState({items:[{id:'toggle',label:'Check',kind:'checkbox'},{id:'off',label:'Disabled',disabled:true},{id:'parent',label:'Parent',children:[{id:'child',label:'Child'}]}],checked:{toggle:false}});window.contextFixtures[id]={update:patch=>setOptions(o=>({...o,...patch}))};return <C {...options} apiRef={api=>window.contextApis[id]=api} onCheckedChange={(key,value)=>window.calls.push({key,value})}/>}window.navigationFixtures={};window.navigationApis={};function NavigationFixture({id,C}){const[options,setOptions]=useState({layout:'sidebar',active:'a',items:[{id:'a',label:'First',href:'#a'},{id:'parent',label:'Parent',children:[{id:'child',label:'Child',href:'#child'}]},{id:'off',label:'Disabled',disabled:true,children:[{id:'blocked',label:'Blocked',href:'#blocked'}]}]});window.navigationFixtures[id]={update:patch=>setOptions(o=>({...o,...patch}))};return <C {...options} apiRef={api=>window.navigationApis[id]=api} onNavigate={()=>false} onActiveChange={key=>window.calls.push(key)}/>}const root=createRoot(document.querySelector('#root'));window.teardown=()=>root.unmount();root.render(<React.StrictMode>{entries.map(({id,C})=><section key={id} data-part={id}>${category==='searchbars'?'<SearchFixture id={id} C={C}/>':category==='commands'?'<CommandFixture id={id} C={C}/>':category==='contextmenus'?'<ContextFixture id={id} C={C}/>':category==='navigation'?'<NavigationFixture id={id} C={C}/>':'<C/>'}</section>)}</React.StrictMode>);`);
   fs.writeFileSync(path.join(directory,'index.html'),'<html><head><meta charset="utf-8"><link rel="icon" href="data:,"><style>body{background:#222831;color:#eee;padding:12px;margin:0;font:14px Arial}#root>section{display:block;width:min(100%,340px);padding:10px;margin:15px 0;box-sizing:border-box}</style></head><body><div id="root"></div><script type="module" src="./entry.jsx"></script></body></html>');
   const page=await browser.newPage({viewport:{width:390,height:844},reducedMotion:'reduce'});page.on('pageerror',e=>{errors.push(e.message);console.error(e.message)});
   await page.goto(server.resolvedUrls!.local[0]+path.relative(ROOT,path.join(directory,'index.html')).replaceAll('\\','/'),{timeout:120000});await page.waitForFunction(n=>document.querySelectorAll('[data-part]').length===n,parts.length,{timeout:120000});
   for(const p of parts){const host=page.locator(`[data-part="${p.id}"]`),root=host.locator(`.sop-${p.id}`).first();assert.ok(await root.count(),p.id+' React root');assert.ok((await root.innerHTML()).length>30,p.id+' rendered');
    if(['loaders','ornaments'].includes(category))assert.equal(await root.locator('.x-composition i').count(),6,p.id+' authored artwork');
    if(category==='toggles'){const sw=root;const before=await sw.getAttribute('aria-checked');await sw.click();assert.notEqual(await sw.getAttribute('aria-checked'),before);}
    if(category==='checkboxes'){await root.locator('input').check();assert.ok(await root.locator('input').isChecked());}
    if(category==='searchbars'){
     const input=root.locator('.wb-search-input');await input.fill('native');await input.press('End');await page.keyboard.insertText(' edited');const original=await input.elementHandle();await page.evaluate(id=>(window as any).searchFixtures[id].setLabel('Updated search'),p.id);await page.waitForTimeout(30);assert.equal(await input.evaluate((e,old)=>e===old,original),true,p.id+' connected controlled editor');assert.equal(await input.inputValue(),'native edited');await input.press('Control+z');await page.waitForTimeout(30);assert.equal(await input.inputValue(),'native',p.id+' accepted controlled native undo');await page.evaluate(id=>(window as any).searchFixtures[id].setAccept(false),p.id);await page.waitForTimeout(20);await input.fill('declined');await page.waitForTimeout(30);assert.equal(await input.inputValue(),'native',p.id+' controlled decline');
    }
    if(category==='commands'){
     const input=root.locator('.wb-command-input'),update=async(patch:unknown)=>{await page.evaluate(({id,patch})=>(window as any).commandFixtures[id].update(patch),{id:p.id,patch});await page.waitForTimeout(30);};await root.locator('.wb-command-launch').click();assert.equal(await root.locator('[role=group]').count(),1);await input.press('ArrowDown');assert.equal(await input.evaluate(e=>document.getElementById(e.getAttribute('aria-activedescendant')!)?.dataset.command),'b');await update({items:[{id:'a',label:'First'},{id:'b',label:'Last'},{id:'off',label:'Disabled',disabled:true}],label:'Updated command'});assert.equal(await input.evaluate(e=>document.getElementById(e.getAttribute('aria-activedescendant')!)?.dataset.command),'b');await input.fill('native');await input.press('End');await page.keyboard.insertText(' edited');const original=await input.elementHandle();await update({placeholder:'Changed hint'});assert.equal(await input.evaluate((e,old)=>e===old,original),true);await input.press('Control+z');assert.equal(await input.inputValue(),'native');await input.fill('');await update({items:[{id:'parent',label:'Parent',children:[{id:'nested',label:'Nested',children:[{id:'leaf',label:'Leaf'}]}]}]});await root.locator('[data-command=parent]').click();await root.locator('[data-command=nested]').click();await root.locator('[data-command-level="0"]').click();assert.equal(await root.locator('[data-command=nested]').count(),1);assert.equal(await input.evaluate(e=>e===document.activeElement),true);await page.keyboard.press('Escape');assert.equal(await root.locator('dialog[open]').count(),0);
    }
    if(category==='navigation'){
     const update=async(patch:unknown)=>{await page.evaluate(({id,patch})=>(window as any).navigationFixtures[id].update(patch),{id:p.id,patch});await page.waitForTimeout(30);},state=()=>page.evaluate(id=>(window as any).navigationApis[id].getState(),p.id),items=[{id:'a',label:'Updated first',href:'#a'},{id:'parent',label:'Parent',children:[{id:'child',label:'Child',href:'#child'}]},{id:'off',label:'Disabled',disabled:true,children:[{id:'blocked',label:'Blocked',href:'#blocked'}]}];const link=root.locator('.wb-nav-desktop [data-nav=a]');await link.focus();await update({items,brand:'Live brand',brandHref:'#brand',label:'Live navigation'});assert.equal(await link.evaluate(e=>e===document.activeElement),true);assert.equal(await root.locator('.wb-nav-brand strong').textContent(),'Live brand');assert.equal(await root.locator('.wb-nav-brand>a').getAttribute('href'),'#brand');assert.equal(await root.locator('.wb-navigation-frame').getAttribute('aria-label'),'Live navigation');await root.locator('[data-nav-group=parent]').press('ArrowDown');await root.locator('.wb-nav-flyout [data-nav=child]').click();assert.equal((await state()).active,'a');await update({active:'child'});assert.equal(await root.locator('[data-nav-group=parent]').getAttribute('data-current'),'');await root.locator('[data-nav-group=parent]').press('ArrowDown');await root.locator('.wb-nav-flyout [data-nav=child]').focus();await update({items:items.map(i=>i.id==='parent'?{...i,children:[{id:'child',label:'New child',href:'#new-child'}]}:i)});assert.equal((await state()).group,'parent');assert.equal(await root.locator('.wb-nav-flyout [data-nav=child]').evaluate(e=>e===document.activeElement),true);await page.keyboard.press('Escape');await update({layout:'mobile'});await root.locator('.wb-nav-mobile-open').click();const off=root.locator('dialog [data-nav-mobile-group=off]');await off.locator('summary').dispatchEvent('click');assert.equal(await off.evaluate(e=>(e as HTMLDetailsElement).open),false);assert.equal(await off.locator('[data-nav=blocked]').getAttribute('href'),null);const actual=root.locator('dialog [data-nav-mobile-group=parent]');await actual.locator('summary').click();await actual.locator('[data-nav=child]').focus();await update({items:items.map(i=>i.id==='parent'?{...i,children:[{id:'child',label:'Mobile child',href:'#mobile-child'}]}:i)});assert.equal(await actual.evaluate(e=>(e as HTMLDetailsElement).open),true);assert.equal(await actual.locator('[data-nav=child]').evaluate(e=>e===document.activeElement),true);await page.keyboard.press('Escape');await page.waitForFunction(id=>(window as any).navigationApis[id].getState().open===false,p.id);
    }
    if(category==='contextmenus'){
     const action=(key:string)=>root.locator(`[data-menu-action="${key}"]`),update=async(patch:unknown)=>{await page.evaluate(({id,patch})=>(window as any).contextFixtures[id].update(patch),{id:p.id,patch});await page.waitForTimeout(30);},state=()=>page.evaluate(id=>(window as any).contextApis[id].getState(),p.id);await root.locator('.wb-context-open').click();await action('toggle').focus();await update({label:'Updated actions',targetLabel:'Updated file',targetDescription:'Updated description'});assert.equal(await action('toggle').evaluate(e=>e===document.activeElement),true,p.id+' React owned focus');assert.equal(await root.locator('[role=menu]').getAttribute('aria-label'),'Updated actions');assert.equal(await root.locator('.wb-context-target-copy strong').textContent(),'Updated file');assert.equal(await root.locator('.wb-context-target-copy small').textContent(),'Updated description');await action('toggle').click();assert.equal(await action('toggle').getAttribute('aria-checked'),'false');await update({checked:{toggle:true}});assert.equal(await action('toggle').getAttribute('aria-checked'),'true');await action('off').focus();await action('off').press('Enter');assert.equal((await state()).lastAction,null);await action('parent').click();await update({items:[{id:'parent',label:'New parent',children:[{id:'child',label:'New child'}]}]});assert.deepEqual((await state()).path,['parent']);assert.equal(await action('child').locator('strong').textContent(),'New child');await page.keyboard.press('ArrowLeft');assert.equal(await action('parent').evaluate(e=>e===document.activeElement),true);await root.evaluate(e=>e.setAttribute('dir','rtl'));await page.keyboard.press('ArrowLeft');assert.deepEqual((await state()).path,['parent']);await page.keyboard.press('ArrowRight');assert.deepEqual((await state()).path,[]);await action('parent').click();await update({items:[]});assert.equal(await root.locator('[role=menu]').evaluate(e=>e===document.activeElement),true);await page.keyboard.press('Escape');assert.equal((await state()).open,false);
    }
    if(category==='textboxes'){await root.locator('input:not([type=hidden]),textarea').first().fill('長い日本語の入力を保持します');}
    if(category==='ratings'){await root.locator('input[type=radio]').nth(3).check();assert.match(await root.locator('output').innerText(),/4 \/ 5/);}
    if(category==='sliders'){await root.locator('input[type=range]').first().fill('73');assert.match(await root.locator('[data-reading]').innerText(),/73/);}
   }
   const contrast=await lightSelectedContrast(page,parts.filter(p=>!['tabs','segments'].includes(p.category)).map(p=>p.id));assert.deepEqual(contrast.failures,[]);
   for(const width of [320,390,768]){await page.setViewportSize({width,height:844});const measure=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth}));assert.ok(measure.scroll<=width+1,category+' '+format+' '+layout+' fits '+width+': '+JSON.stringify(measure));}
   await page.evaluate(()=>(window as any).teardown());assert.equal(await page.locator('[data-part]').count(),0);await page.close();console.log('PASS '+category+' '+parts.length+' React '+format+' '+layout+' strict cleanup, narrow widths, contrast');
  }
 }
 assert.deepEqual(errors,[]);
}finally{await browser.close();await server.close();}
