/** Browser fixture uses authored sources. It is not a Vite replacement in the release. */
import fs from 'node:fs';import path from 'node:path';
import {ROOT} from '../scripts/catalog.ts';import {testBundle} from './offline-fixture.ts';
export function liquidGlassFixture(){
 const read=(p:string)=>fs.readFileSync(path.join(ROOT,p),'utf8');
 const bases=(JSON.parse(read('src/catalog/registry.json')) as string[]).filter(b=>b.split('/').at(-1)?.startsWith('lg-'));
 const records=bases.map(base=>({...JSON.parse(read(base+'/meta.json')),base,markup:read(base+'/markup.html')}));
 const seen=new Set<string>();function css(file:string):string{if(seen.has(file))return '';seen.add(file);return read(file).replace(/@import\s+["']([^"']+)["']\s*;/g,(_,ref:string)=>css(path.posix.normalize(path.posix.join(path.posix.dirname(file),ref))));}
 const styles=bases.map(b=>css(b+'/styles.css')).join('\n')+'\n'+read('src/app/liquid-glass-preview.css');
 const source=records.map((p,i)=>`import {init as init${i}} from '/${p.base}/vanilla/init.ts';`).join('\n')+`\nimport {glassScene} from '/src/app/liquid-glass-preview.ts';
 const records=${JSON.stringify(records)},mounts=[${records.map((_,i)=>'init'+i).join(',')}];
 window.glassRecords=records;window.glassApis=[];window.glassScenes=[];
 window.unmount=()=>{window.glassApis.forEach(c=>c.destroy());window.glassApis=[];window.glassScenes.forEach(c=>c());window.glassScenes=[];document.querySelector('#host').replaceChildren();};
 window.mount=(ids=records.map(p=>p.id),options={})=>{window.unmount();for(const id of ids){const i=records.findIndex(p=>p.id===id),p=records[i];const section=document.createElement('section');section.className='study';section.dataset.sample=id;
 const label=document.createElement('header');label.className='study-label';label.innerHTML='<span>'+p.name+'</span><small>'+p.designType+' / '+p.category.toUpperCase()+'</small>';
 const host=document.createElement('div');host.className='specimen';host.innerHTML=p.markup;section.append(label,host);document.getElementById('host').append(section);
 const root=host.firstElementChild;window.glassScenes.push(glassScene(host,root));window.glassApis.push(mounts[i](root,options));}
 window.api=window.glassApis[0];};window.mount();
 document.querySelector('#material').addEventListener('change',e=>window.glassApis.forEach(c=>c.updateGlass({material:e.target.value})));
 document.querySelector('#scene').addEventListener('change',e=>{document.querySelectorAll('.lg-demo-host').forEach(el=>el.dataset.lgScene=e.target.value);window.glassApis.forEach(c=>c.updateGlass({appearance:e.target.value==='paper'?'light':'dark'}));});
 document.querySelector('#drift').addEventListener('change',e=>document.querySelectorAll('.lg-demo-host').forEach(el=>el.dataset.lgDrift=String(e.target.checked)));
 document.querySelector('#optics').addEventListener('change',e=>window.glassApis.forEach(c=>c.updateGlass({optics:e.target.checked?'refractive':'standard'})));
 `;
 const frame=`*{box-sizing:border-box}html{color-scheme:dark}body{background:#10171d;color:#edf5f6;margin:0;font:14px system-ui,-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif}.masthead{max-width:1152px;margin:auto;padding:34px 32px 25px;border-bottom:1px solid #3e526244;display:flex;justify-content:space-between;font:10px Consolas,monospace;letter-spacing:2px;color:#afc9d6}.hero{max-width:1152px;margin:auto;padding:40px 32px 25px;display:flex;justify-content:space-between;align-items:end;gap:25px}.hero h1{font:400 57px/1.06 Georgia,serif;letter-spacing:-2px;margin:0}.hero p{font:12px/1.9 system-ui;color:#a9bdc8;max-width:290px;margin:0}.bar{max-width:1088px;margin:6px auto 20px;display:flex;gap:18px;flex-wrap:wrap;align-items:center;font-size:11px}.bar label{display:flex;gap:8px;align-items:center}.bar select{border:1px solid #455e6d;background:#172630;color:#d8e9ef;border-radius:8px;padding:7px 10px}.bar input{accent-color:#b4dbea}#host{max-width:1152px;padding:0 32px 42px;margin:auto;display:grid;grid-template-columns:1fr 1fr;gap:28px 24px}.study{min-width:0}.study-label{display:flex;justify-content:space-between;align-items:center;padding:12px 2px 14px;font-size:14px}.study-label small{font:9px Consolas,monospace;letter-spacing:1px;color:#9eb8c5}.specimen{min-height:238px;padding:38px 30px;display:flex;align-items:center;justify-content:center}.specimen:has(.lg-tabs){min-height:280px}.lg-tabs{max-width:420px}body[data-single=true] .masthead,body[data-single=true] .hero,body[data-single=true] .bar{display:none}body[data-single=true] #host{display:block;max-width:560px;padding:20px;}body[data-single=true] .specimen{min-height:330px}body[data-single=true] .study-label{padding-bottom:20px}#outside{position:fixed;bottom:10px;right:10px;background:#203140;color:#dfeef3;border:1px solid #405766;padding:9px;border-radius:7px}body[data-capture=true] #outside{display:none}@media(max-width:600px){.hero{display:block;padding:28px 18px}.hero h1{font-size:42px}.hero p{margin-top:16px}.masthead{padding:22px 18px;font-size:9px}#host{grid-template-columns:1fr;padding:0 15px 25px;gap:18px}.bar{padding:0 18px}.specimen{padding:24px 15px}}`;
 const shell=`<!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Liquid Glass — STATE OF PLAY</title><link rel="stylesheet" href="./styles.css"></head><body><div class="masthead"><span>STATE OF PLAY / MATERIAL STUDIES</span><span>VOL. 01 — LIQUID GLASS</span></div><div class="hero"><h1>A different<br><i>kind of light.</i></h1><p>透ける、反射する、かたちを変える。<br>触れた光が、次の操作へつながる。<br>8 pieces · 4 interactions</p></div><div class="bar"><label>素材<select id="material"><option value="clear">Clear</option><option value="regular">Regular</option><option value="solid">Solid</option></select></label><label>背景<select id="scene"><option value="coast">海と砂</option><option value="paper">明るい紙面</option><option value="ink">暗い面</option><option value="grid">格子</option></select></label><label><input type="checkbox" id="drift">背景を動かす</label><label><input type="checkbox" id="optics">実験：屈折</label></div><main id="host"></main><button type="button" id="outside">外側</button><script src="./fixture.js" defer></script></body></html>`;
 const out=path.join(ROOT,'.test-output/liquid-glass');fs.mkdirSync(out,{recursive:true});const entry='.test-output/liquid-glass/fixture.ts';
 fs.writeFileSync(path.join(ROOT,entry),source);fs.writeFileSync(path.join(out,'styles.css'),styles+'\n'+frame);fs.writeFileSync(path.join(out,'index.html'),shell);
 fs.writeFileSync(path.join(out,'fixture.js'),testBundle(entry,new Map([[entry,source]])));
 return {records,out};
}
