import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import ts from 'typescript';
import {ROOT,buildCatalog,FORMATS} from '../scripts/catalog.ts';
import {getDelivery,buildPrompt,packageContents} from '../src/catalog/delivery.ts';
import {dependencies,sourceReferences,isLocalReference,resolveLocal} from '../scripts/source-tools.ts';
import {DEFAULT_GLASS,normalizeGlass,lensVector} from '../src/shared/liquid-glass/core.ts';
const read=(p:string)=>fs.readFileSync(path.join(ROOT,p),'utf8'),exists=(p:string)=>fs.existsSync(path.join(ROOT,p));
const bases=(JSON.parse(read('src/catalog/registry.json')) as string[]).filter(p=>p.split('/').at(-1)!.startsWith('lg-'));
const records=bases.map(base=>({...JSON.parse(read(base+'/meta.json')),base}));
test('Liquid Glass first release has eight additions, two intentions in each of four existing categories',()=>{assert.equal(records.length,8);for(const c of ['toggles','buttons','tabs','dropdowns']){const group=records.filter(r=>r.category===c);assert.equal(group.length,2);assert.deepEqual(group.map(r=>r.designType).sort(),['A','B']);}assert.ok(records.every(r=>r.tags.includes('GLASS LAB')));});
test('material settings are normalized and independent of A/B labels',()=>{assert.deepEqual(normalizeGlass({}),DEFAULT_GLASS);const clear=normalizeGlass({material:'clear',appearance:'light'});assert.equal(clear.optics,'standard');assert.deepEqual(normalizeGlass({paused:true},clear),{...clear,paused:true});assert.equal(normalizeGlass({material:'invalid' as never},clear).material,'clear');});
test('lens map has a stable center and bounded continuous edge displacement',()=>{assert.deepEqual(lensVector(90,28,180,56,28,14),[0,0]);assert.deepEqual(lensVector(-10,0,180,56,28,14),[0,0]);for(let y=0;y<=56;y+=2)for(let x=0;x<=180;x+=2){const v=lensVector(x,y,180,56,28,14);assert.ok(v.every(n=>Number.isFinite(n)&&Math.abs(n)<=.43));}assert.ok(Math.abs(lensVector(90,4,180,56,28,14)[1])>.1);});
test('every new runtime and example closes over actual source files, not gallery code',()=>{for(const r of records)for(const entry of ['vanilla/init.ts','vanilla/index.html',`react/${r.componentName}.tsx`,'react/Example.tsx']){for(const f of dependencies(r.base+'/'+entry,read,exists))assert.ok(!f.startsWith('src/app/')&&!f.startsWith('src/catalog/'),r.id+' -> '+f);}});
test('all new React/TS wrappers and shared effects transpile without syntax errors',()=>{const checked=new Set<string>();for(const r of records)for(const entry of ['vanilla/init.ts',`react/${r.componentName}.tsx`,'react/Example.tsx'])for(const f of dependencies(r.base+'/'+entry,read,exists))if(/\.tsx?$/.test(f))checked.add(f);for(const f of checked){const d=ts.transpileModule(read(f),{fileName:f,reportDiagnostics:true,compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext,jsx:ts.JsxEmit.Preserve}}).diagnostics??[];assert.deepEqual(d.filter(v=>v.category===ts.DiagnosticCategory.Error),[],f);}});
test('no unsolicited network, DOM snapshotting or idle render loop in the material',()=>{const s=read('src/shared/liquid-glass/core.ts');assert.doesNotMatch(s,/fetch\(|setInterval\(|html2canvas/);assert.match(s,/!dead&&!frame&&visible&&!document.hidden/);assert.match(s,/optics==='refractive'/);assert.match(s,/removeLenses/);assert.match(s,/abort\.abort/);});
test('motion, transparency, unsupported-backdrop and forced-colors fallbacks are authored',()=>{const s=read('src/shared/liquid-glass/material.css');for(const token of ['prefers-reduced-motion','prefers-reduced-transparency','prefers-contrast','forced-colors','@supports not','data-lg-material="solid"'])assert.ok(s.includes(token),token);assert.doesNotMatch(s,/:root\s*\{|\bbody\s*\{/);});
test('original ornament init templates no longer contain unexpanded braces',()=>{for(const base of JSON.parse(read('src/catalog/registry.json')) as string[])if(base.startsWith('src/parts/ornaments/'))assert.doesNotMatch(read(base+'/vanilla/init.ts'),/\{\{|\}\}/,base);});
test('all glass delivery formats and layouts retain exact code, relative paths and project-aware prompts',()=>{
 const catalog=buildCatalog();for(const p of catalog.parts.filter(x=>x.tags.includes('GLASS LAB')))for(const format of FORMATS)for(const layout of ['original','portable']as const){
  const d=getDelivery(p,format,layout),names=new Set(d.files.map(f=>f.name));assert.ok(d.files.some(f=>f.name===d.entry));
  for(const file of d.files)for(const ref of sourceReferences(file.code,file.name).filter(isLocalReference))assert.ok(names.has(resolveLocal(file.name,ref.request,n=>names.has(n))));
  assert.ok(d.files.some(f=>f.name.endsWith('material.css')));assert.ok(d.files.some(f=>f.name.endsWith(format==='js'||format==='jsx'?'core.js':'core.ts')));
  const prompt=buildPrompt(p,format,layout,true);assert.match(prompt,/Liquid Glass|ガラス/);assert.match(prompt,/プロジェクト/);assert.ok(prompt.includes(d.entry));assert.match(prompt,/屈折/);
 }
});
