import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';
import {createRequire} from 'node:module';import type {Browser} from 'playwright';
import {ROOT} from '../scripts/catalog.ts';import {liquidGlassFixture} from './liquid-glass-fixture.ts';import {requireLocalServerUrl} from './vite-url.ts';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_PATH??'playwright') as typeof import('playwright');
const offline=process.env.SOP_TEST_MODE==='offline',f=liquidGlassFixture(),passed:string[]=[],errors:string[]=[];
let browser:Browser|undefined,closeServer:(()=>Promise<void>)|undefined;
const run=async(name:string,fn:()=>Promise<void>)=>{await fn();passed.push(name);console.log('PASS '+name);};
try{
 let url='';if(!offline){const {createServer}=await import('vite');const s=await createServer({root:ROOT,server:{host:'127.0.0.1',port:0}});await s.listen();url=requireLocalServerUrl(s,'Liquid Glass');closeServer=()=>s.close();}
 browser=await chromium.launch({headless:true,args:['--no-sandbox'],...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{})});
 const p=await browser.newPage({viewport:{width:980,height:900}});p.setDefaultTimeout(30000);p.on('pageerror',e=>errors.push(e.message));
 if(offline){const html=fs.readFileSync(path.join(f.out,'index.html'),'utf8').replace('<link rel="stylesheet" href="./styles.css">','').replace('<script src="./fixture.js" defer></script>','');await p.setContent(html);await p.addStyleTag({content:fs.readFileSync(path.join(f.out,'styles.css'),'utf8')});await p.addScriptTag({content:fs.readFileSync(path.join(f.out,'fixture.js'),'utf8')});}else {await p.goto(new URL('.test-output/liquid-glass/index.html',url).href,{waitUntil:'commit',timeout:180000});await p.waitForFunction(()=>Boolean((window as any).api),undefined,{timeout:180000});}
 await p.evaluate(()=>{document.body.dataset.single='true';document.body.dataset.capture='true';});
 const mount=async(id:string|string[],options:Record<string,unknown>={})=>{await p.evaluate(([ids,o])=>(window as any).mount(ids,o),[typeof id==='string'?[id]:id,options]);await p.waitForTimeout(60);};
 await run('8 new parts mount with real DOM and stable APIs',async()=>{for(const r of f.records){await mount(r.id);assert.equal(await p.locator('.lg-root').count(),1);assert.equal(await p.evaluate(()=>(window as any).api.getGlass().optics),'standard');}assert.deepEqual(errors,[]);});
 await run('Toggle native click, keyboard, drag and controlled decline',async()=>{for(const id of ['lg-lens-toggle','lg-mist-toggle']){await mount(id);const root=p.locator('.lg-toggle');await root.click();assert.equal(await root.getAttribute('aria-checked'),'true');await root.press('ArrowLeft');assert.equal(await root.getAttribute('aria-checked'),'false');const b=(await root.boundingBox())!;await p.mouse.move(b.x+20,b.y+b.height/2);await p.mouse.down();await p.mouse.move(b.x+b.width-12,b.y+b.height/2,{steps:10});await p.mouse.up();assert.equal(await root.getAttribute('aria-checked'),'true');await root.evaluate((e:HTMLButtonElement)=>e.disabled=true);await root.click({force:true});assert.equal(await root.getAttribute('aria-checked'),'true');}
 await p.evaluate(()=>{(window as any).calls=0;(window as any).mount(['lg-lens-toggle'],{checked:false,controlled:true,onCheckedChange:()=>{(window as any).calls++;}});});await p.locator('.lg-toggle').click();assert.equal(await p.locator('.lg-toggle').getAttribute('aria-checked'),'false');assert.equal(await p.evaluate(()=>(window as any).calls),1);});
 await run('Button pressure does not move label; busy and disabled block activation',async()=>{await mount('lg-pressure-button');const label=p.locator('.sop-action-label');const before=(await label.boundingBox())!;await p.locator('.lg-button').hover();await p.mouse.down();await p.waitForTimeout(140);const after=(await label.boundingBox())!;assert.ok(Math.abs(before.x-after.x)<.1&&Math.abs(before.y-after.y)<.1);await p.mouse.up();
 await p.evaluate(()=>{(window as any).clicks=0;document.querySelector('.lg-button')!.addEventListener('click',()=>{(window as any).clicks++;});(window as any).api.setLoading(true);});await p.locator('.lg-button').click({force:true});assert.equal(await p.evaluate(()=>(window as any).clicks),0);await p.evaluate(()=>(window as any).api.setLoading(false));await p.locator('.lg-button').press('Space');assert.equal(await p.evaluate(()=>(window as any).clicks),1);});
 await run('Tabs retain panel inputs and manual keyboard activation',async()=>{await mount('lg-flow-tabs');await p.locator('[data-choice-value="notes"]').click();await p.locator('input[aria-label="メモ"]').fill('日本語の入力を保持');await p.locator('[data-choice-value="overview"]').click();await p.locator('[data-choice-value="notes"]').click();assert.equal(await p.locator('input[aria-label="メモ"]').inputValue(),'日本語の入力を保持');await mount('lg-index-tabs',{activation:'manual'});await p.locator('.sop-choice-item').first().focus();await p.keyboard.press('ArrowRight');assert.equal(await p.evaluate(()=>(window as any).api.getValue()),'overview');await p.keyboard.press('Enter');assert.equal(await p.evaluate(()=>(window as any).api.getValue()),'details');});
 await run('Tabs indicator measures 2, 5 and 7 variable-width choices, including vertical mode',async()=>{for(const n of [2,5,7]){await mount('lg-flow-tabs');await p.evaluate(n=>{const root=document.querySelector('.lg-tabs')!,list=root.querySelector('.sop-choice-list')!,panels=root.querySelector('.sop-choice-panels')!;list.querySelectorAll('button').forEach(b=>b.remove());panels.replaceChildren();for(let i=0;i<n;i++){const b=document.createElement('button');b.className='sop-choice-item';b.dataset.choiceValue='x'+i;b.textContent=i%2?'少し長い日本語':'項目'+i;list.append(b);const panel=document.createElement('section');panel.className='sop-choice-panel';panel.dataset.panelValue='x'+i;panel.textContent='内容'+i;panels.append(panel);}(window as any).api.refresh();(window as any).api.setValue('x'+(n-1));},n);await p.waitForTimeout(600);const measurements=await p.evaluate(()=>{const root=document.querySelector('.lg-tabs')!,item=root.querySelector<HTMLElement>('[data-selected="true"]')!,marker=root.querySelector<HTMLElement>('.sop-choice-marker')!;return[item.offsetWidth,parseFloat(marker.style.getPropertyValue('--sop-choice-w'))];});assert.equal(measurements[0],measurements[1]);await p.evaluate(()=>(window as any).api.setOrientation('vertical'));assert.equal(await p.locator('.lg-tabs').getAttribute('data-orientation'),'vertical');}});
 await run('Dropdown keyboard highlight, Escape cancellation and actual selection',async()=>{await mount('lg-bloom-select');const button=p.locator('.sop-select-trigger');await button.click();await button.press('End');assert.equal(await p.evaluate(()=>(window as any).api.getValue()),'updated');await button.press('Escape');assert.equal(await p.evaluate(()=>(window as any).api.getValue()),'updated');await button.click();await button.press('End');await button.press('Enter');assert.equal(await p.evaluate(()=>(window as any).api.getValue()),'size');assert.equal(await p.locator('.sop-select-input').inputValue(),'size');assert.equal(await p.locator('.sop-select-popup').isVisible(),false);});
 await run('Dropdown background tracks hover without moving option labels',async()=>{await mount('lg-bloom-select');await p.locator('.sop-select-trigger').click();await p.waitForTimeout(350);const option=p.locator('[role="option"]').nth(2),copy=option.locator('b');const before=(await copy.boundingBox())!;await option.hover();await p.waitForTimeout(450);const after=(await copy.boundingBox())!;assert.ok(Math.abs(before.x-after.x)<.1&&Math.abs(before.y-after.y)<.1);assert.equal(await option.getAttribute('data-active'),'true');const delta=await p.evaluate(()=>{const opt=document.querySelector<HTMLElement>('[data-active="true"]')!,lens=document.querySelector<HTMLElement>('.lg-active-lens')!;return Math.abs(opt.getBoundingClientRect().top-lens.getBoundingClientRect().top);});assert.ok(delta<2);});
 await run('Dropdown supports disabled options, form reset and controlled value',async()=>{
 await p.evaluate(()=>{const form=document.createElement('form');form.id='test-form';const host=document.querySelector('#host')!;host.before(form);form.append(host);});
 await mount('lg-clarity-select');await p.locator('.sop-select-trigger').click();await p.locator('[role="option"]').nth(1).click();
 assert.equal(await p.evaluate(()=>(window as any).api.getValue()),'name');
 await p.locator('#test-form').evaluate((e:HTMLFormElement)=>e.reset());await p.waitForTimeout(30);
 assert.equal(await p.evaluate(()=>(window as any).api.getValue()),'updated');
 await p.evaluate(()=>{const form=document.querySelector('#test-form')!;form.before(document.querySelector('#host')!);form.remove();});
 await mount('lg-clarity-select',{controlled:true,value:'updated'});await p.locator('.sop-select-trigger').click();await p.locator('[role="option"]').nth(1).click();
 assert.equal(await p.evaluate(()=>(window as any).api.getValue()),'updated');
 await p.evaluate(()=>{document.querySelectorAll('[role="option"]').forEach(e=>e.setAttribute('aria-disabled','true'));(window as any).api.refresh();(window as any).api.setOpen(true);});
 assert.equal(await p.evaluate(()=>(window as any).api.getOpen()),false);
 });
 await run('Popup is above an existing dialog and stays in a narrow viewport',async()=>{await p.setViewportSize({width:390,height:700});await mount('lg-bloom-select');await p.evaluate(()=>{const dialog=document.createElement('dialog');dialog.id='test-dialog';dialog.style.cssText='width:340px;max-height:600px;padding:18px;background:#1c303c;color:white';const host=document.querySelector('#host')!;host.before(dialog);dialog.append(host);dialog.showModal();});await p.locator('.sop-select-trigger').click();await p.waitForTimeout(400);assert.equal(await p.locator('.sop-select-popup').evaluate(e=>e.matches(':popover-open')),true);const r=(await p.locator('.sop-select-popup').boundingBox())!;assert.ok(r.x>=0&&r.x+r.width<=390);await p.keyboard.press('Escape');assert.equal(await p.locator('#test-dialog').evaluate((e:HTMLDialogElement)=>e.open),true);await p.evaluate(()=>{const d=document.querySelector<HTMLDialogElement>('#test-dialog')!;d.close();d.before(document.querySelector('#host')!);d.remove();});});
 await run('Material and appearance changes preserve committed values and content',async()=>{await mount('lg-lens-toggle');await p.locator('.lg-toggle').click();for(const material of ['clear','regular','solid'])for(const appearance of ['light','dark','auto']){await p.evaluate(o=>(window as any).api.updateGlass(o),{material,appearance});assert.equal(await p.locator('.lg-toggle').getAttribute('aria-checked'),'true');}await mount('lg-flow-tabs');await p.locator('[data-choice-value="notes"]').click();await p.locator('input[aria-label="メモ"]').fill('残す');await p.evaluate(()=>(window as any).api.updateGlass({material:'solid',appearance:'light'}));assert.equal(await p.locator('input[aria-label="メモ"]').inputValue(),'残す');assert.equal(await p.locator('.sop-choice-marker').evaluate(e=>getComputedStyle(e).getPropertyValue('--lg-opacity').trim()),'1');});
 await run('Light/dark/grid scenes and long labels fit 320, 390 and 768 widths',async()=>{for(const width of [320,390,768]){await p.setViewportSize({width,height:820});for(const r of f.records){await mount(r.id);for(const scene of ['paper','ink','grid']){await p.evaluate(scene=>{document.querySelector<HTMLElement>('.lg-demo-host')!.dataset.lgScene=scene;(window as any).api.updateGlass({appearance:scene==='paper'?'light':'dark'});},scene);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),r.id+' '+width+' '+scene);}if(r.category==='buttons'){await p.locator('.sop-action-label').evaluate(e=>e.textContent='とても長い日本語でも文字を読めるようにする');assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));}}}});
 await run('Standard mode has no SVG resource and optional refraction cleans up completely',async()=>{await mount('lg-pressure-button');assert.equal(await p.locator('[data-lg-resource]').count(),0);await p.evaluate(()=>(window as any).api.updateGlass({optics:'refractive'}));assert.ok(await p.locator('[data-lg-resource]').count()>0);await p.evaluate(()=>(window as any).api.updateGlass({optics:'standard'}));assert.equal(await p.locator('[data-lg-resource]').count(),0);for(let i=0;i<3;i++){await mount('lg-lens-toggle',{optics:'refractive'});await p.evaluate(()=>(window as any).unmount());assert.equal(await p.locator('[data-lg-resource]').count(),0);}});
 await run('Multiple copies retain independent values and unique SVG/listbox identities',async()=>{await mount(['lg-bloom-select','lg-bloom-select','lg-lens-toggle','lg-lens-toggle'],{optics:'refractive'});const ids=await p.locator('[id]').evaluateAll(elements=>elements.map(e=>e.id));assert.equal(new Set(ids).size,ids.length);await p.locator('.lg-toggle').first().click();assert.equal(await p.locator('.lg-toggle').last().getAttribute('aria-checked'),'false');});
 await run('Reduced motion and forced colors preserve control semantics',async()=>{await p.emulateMedia({reducedMotion:'reduce'});await mount('lg-lens-toggle');await p.locator('.lg-toggle').click();assert.equal(await p.locator('.lg-toggle').getAttribute('aria-checked'),'true');assert.equal(await p.locator('.lg-knob').evaluate(e=>getComputedStyle(e).transitionDuration),'0s');await p.emulateMedia({forcedColors:'active'});await mount('lg-bloom-select',{optics:'refractive'});await p.locator('.sop-select-trigger').click();assert.equal(await p.locator('.sop-select-popup').evaluate(e=>getComputedStyle(e).backdropFilter),'none');assert.equal(await p.locator('[data-lg-resource]').count(),0);await p.emulateMedia({reducedMotion:'no-preference',forcedColors:'none'});});
 await run('Pausing stops optical motion without changing input values',async()=>{await mount('lg-lens-toggle');await p.evaluate(()=>(window as any).api.setPaused(true));await p.locator('.lg-toggle').click();assert.equal(await p.locator('.lg-toggle').getAttribute('aria-checked'),'true');assert.equal(await p.locator('.lg-knob').evaluate(e=>getComputedStyle(e).transitionDuration),'0s');await p.evaluate(()=>(window as any).api.setPaused(false));assert.equal(await p.locator('.lg-toggle').getAttribute('data-lg-paused'),'false');});
 await run('No page errors after repeated switching and destruction',async()=>{for(let i=0;i<4;i++){await mount(f.records.map(r=>r.id));await p.evaluate(()=>(window as any).unmount());}await p.waitForTimeout(600);assert.equal(await p.locator('[data-lg-resource]').count(),0);assert.deepEqual(errors,[]);});
 console.log(`Liquid Glass browser: ${passed.length} passed.`);
}finally{fs.writeFileSync(path.join(f.out,'browser-results.json'),JSON.stringify({mode:offline?'Actual Chromium, authorized local source document (not Vite HTTP)':'Vite HTTP',passed:passed.length,tests:passed,errors},null,2));await browser?.close();await closeServer?.();}
