import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {chromium} from 'playwright';import {createServer} from 'vite';
const ids=['track-stop-pages','ledger-page-tabs','coin-stack-pages','shuttle-key-pages'],dir=path.resolve('.test-output/pagination-strip');fs.mkdirSync(dir,{recursive:true});
fs.writeFileSync(path.join(dir,'index.html'),'<style>body{margin:20px;min-height:2000px}#host{width:560px;margin-top:400px}</style><div id="host"></div><script type="module" src="./entry.ts"></script>');
fs.writeFileSync(path.join(dir,'entry.ts'),ids.map((id,i)=>`import {init as i${i}} from '../../src/parts/pagination/${id}/vanilla/init.ts';import '../../src/parts/pagination/${id}/styles.css';`).join('\n')+`const inits=[${ids.map((_,i)=>'i'+i)}];window.mount=(i,dir)=>{window.api?.destroy();const h=document.querySelector('#host');h.style.width='560px';h.style.transform='none';h.dir=dir;h.innerHTML='<div class="sop-foundation sop-'+${JSON.stringify(ids)}[i]+'"></div>';window.api=inits[i](h.firstElementChild,{defaultValue:999,totalPages:1000})};window.ready=true;`);
const server=await createServer({configFile:false,root:process.cwd(),optimizeDeps:{noDiscovery:true},server:{host:'127.0.0.1',port:0,hmr:false,watch:null}});await server.listen();const browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{})});
try{const page=await browser.newPage({viewport:{width:1100,height:900}});await page.goto(server.resolvedUrls!.local[0]+'.test-output/pagination-strip/index.html');await page.waitForFunction(()=>(window as any).ready);
 const visible=()=>page.waitForFunction(()=>{const strip=document.querySelector<HTMLElement>('.ff-page-window')!,current=strip.querySelector<HTMLElement>('[aria-current=page]')!;const a=strip.getBoundingClientRect(),b=current.getBoundingClientRect();return b.left>=a.left-1&&b.right<=a.right+1});
 for(let i=0;i<ids.length;i++)for(const dir of ['ltr','rtl']){await page.evaluate(({i,dir})=>(window as any).mount(i,dir),{i,dir});await page.evaluate(()=>{document.querySelector<HTMLElement>('#host')!.style.width='235px';window.scrollTo(0,170)});await visible();assert.equal(await page.evaluate(()=>scrollY),170);assert.equal(await page.evaluate(()=>(window as any).api.getData()),999);
  await page.evaluate(()=>(window as any).api.setData(2));await visible();assert.equal(await page.locator('[aria-current=page]').textContent(),'02');
  await page.evaluate(()=>{document.querySelector<HTMLElement>('#host')!.style.transform='scale(.75)';(window as any).api.setData(999)});await visible();assert.equal(await page.evaluate(()=>scrollY),170);
  await page.locator('.ff-page-window [aria-current=page]').focus();await page.keyboard.press('Tab');const focus=await page.evaluate(()=>{const e=document.activeElement as HTMLElement,s=e.parentElement!;const a=s.getBoundingClientRect(),b=e.getBoundingClientRect();return{left:b.left-a.left,right:a.right-b.right,inStrip:s.classList.contains('ff-page-window')}});assert.ok(focus.inStrip&&focus.left>=-1&&focus.right>=-1);
  await page.evaluate(()=>(window as any).api.destroy());console.log('PASS selected/focused page stays visible in one strip without page scroll',ids[i],dir);}
}finally{await browser.close();await server.close()}
