import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createRequire} from 'node:module';
import type {Browser} from 'playwright';import {resonanceFixture} from './resonance-fixture.ts';import {ROOT} from '../scripts/catalog.ts';import {requireLocalServerUrl} from './vite-url.ts';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_PATH??'playwright') as typeof import('playwright');
const fixture=resonanceFixture(),revised=fixture.records.filter(p=>p.tags.includes('RESONANCE')),offline=process.env.SOP_TEST_MODE==='offline';const tests:string[]=[],errors:string[]=[];let browser:Browser|undefined,close:(()=>Promise<void>)|undefined;
async function run(name:string,fn:()=>Promise<void>){if(process.env.SOP_RESONANCE_FILTER&&!new RegExp(process.env.SOP_RESONANCE_FILTER).test(name))return;await fn();tests.push(name);console.log('PASS '+name);}
try {
 let url='';if(!offline){const {createServer}=await import('vite'),s=await createServer({root:ROOT,server:{host:'127.0.0.1',port:0}});await s.listen();url=requireLocalServerUrl(s,'RESONANCE');close=()=>s.close();}
 browser=await chromium.launch({headless:true,args:['--no-sandbox'],...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{})});const p=await browser.newPage({viewport:{width:740,height:1000}});p.setDefaultTimeout(7000);p.on('pageerror',e=>errors.push(e.message));
 if(offline){await p.setContent(fixture.shell.replace(/<link[^>]*>/,''));await p.addStyleTag({content:fixture.styles});await p.addScriptTag({content:fixture.bundle()});}else await p.goto(new URL('.test-output/resonance/test.html',url).href);
 await p.waitForFunction(()=>typeof(window as any).mount==='function');
 const mount=async(id:string|string[],options={})=>p.evaluate(({ids,options})=>(window as any).mount(ids,options),{ids:typeof id==='string'?[id]:id,options});const val=()=>p.evaluate(()=>(window as any).api.getData());
 await run('16 radio materials commit native checked state immediately; each scene deforms and settles',async()=>{
  for(const part of revised.filter(p=>p.category==='radios')){await mount(part.id);const cards=p.locator('.ff-choice');const before=await cards.first().locator('.rs-scene').innerHTML();await cards.first().click();assert.equal(await cards.first().getAttribute('data-selected'),'true',part.id);assert.ok(await cards.first().locator('input').isChecked());await p.waitForTimeout(75);assert.notEqual(await cards.first().locator('.rs-scene').innerHTML(),before,part.id);assert.equal(await cards.count(),3);}
  await p.waitForTimeout(1300);assert.equal(await p.evaluate(()=>(window as any).activeFrames.size),0);
 });
 await run('radio keyboard, name, form reset, readonly and controlled-declined values stay native',async()=>{
  const items=[{value:'a',label:'Alpha'},{value:'b',label:'Beta',disabled:true},{value:'c',label:'Gamma'}];await mount('folio-choice',{items,defaultValue:'a',name:'quality',required:true});await p.locator('input[value=a]').focus();await p.keyboard.press('ArrowRight');assert.equal(await val(),'c');assert.equal(await p.evaluate(()=>new FormData(document.querySelector('form')!).get('quality')),'c');await p.locator('#reset').click();await p.waitForTimeout(25);assert.equal(await val(),'a');
  await p.evaluate(()=>(window as any).api.updateFoundation({controlled:true,value:'a'}));await p.locator('.ff-choice').last().click();assert.equal(await val(),'a');assert.ok(await p.locator('input[value=a]').isChecked());await p.evaluate(()=>(window as any).api.updateFoundation({readOnly:true}));assert.ok(await p.locator('input[value=a]').isDisabled());
 });
 await run('radio dynamic 2/4/7 items and repeated copies remain isolated without duplicate identifiers',async()=>{
  for(const count of [2,4,7]){await mount(['prism-choice','prism-choice'],{items:Array.from({length:count},(_,i)=>({value:'v'+i,label:i===2?'長い日本語でも内容を変えられます':'Option '+i})),defaultValue:'v0'});await p.locator('[data-sample]').first().locator('.ff-choice').last().click();const values=await p.evaluate(()=>(window as any).apis.map((a:any)=>a.getData()));assert.deepEqual(values,['v'+(count-1),'v0']);const ids=await p.locator('[id]').evaluateAll(es=>es.map(e=>e.id));assert.equal(ids.length,new Set(ids).size);}
 });
 await run('16 editable combo materials open real options, track hover and commit without moving focus',async()=>{
  for(const part of revised.filter(p=>p.category==='comboboxes')){await mount(part.id,{multiple:false,defaultValue:''});await p.locator('[data-combo-toggle]').click();await p.locator('[data-option]').nth(1).hover();assert.equal(await p.locator('[data-option]').nth(1).getAttribute('data-active'),'true');assert.ok(await p.locator('[data-combo]').evaluate(e=>e===document.activeElement));await p.keyboard.press('Enter');assert.equal(await val(),'folio');assert.equal(await p.locator('[data-combo]').getAttribute('aria-expanded'),'false');assert.equal(await p.locator('[data-combo]').inputValue(),'Folio');}
 });
 await run('combo filtering, empty/loading/error/group states, multiple chips and form payloads work',async()=>{
  const items=[{value:'a',label:'Alpha',group:'One'},{value:'b',label:'Beta',group:'One',disabled:true},{value:'c',label:'Gamma',group:'Two'}];await mount('aurora-finder',{items,name:'pick',defaultValue:'',multiple:true});const input=p.locator('[data-combo]');await input.fill('al');assert.equal(await p.locator('[data-option]').count(),1);await input.press('ArrowDown');await input.press('Enter');assert.deepEqual(await val(),['a']);await input.fill('gam');await input.press('ArrowDown');await input.press('Enter');assert.deepEqual(await val(),['a','c']);assert.deepEqual(await p.evaluate(()=>new FormData(document.querySelector('form')!).getAll('pick')),['a','c']);await p.locator('[data-remove=a]').click();assert.deepEqual(await val(),['c']);
  await input.fill('');await p.evaluate(()=>(window as any).api.show());assert.equal(await p.locator('.rs-option-group').count(),2);await p.evaluate(()=>(window as any).api.updateFoundation({loading:true}));assert.equal(await p.locator('[data-option]').count(),0);assert.match(await p.locator('[data-results]').innerText(),/読み込み/);await input.press('ArrowDown');await input.press('Enter');assert.deepEqual(await val(),['c']);await p.evaluate(()=>(window as any).api.updateFoundation({loading:false,error:'通信を確認'}));assert.match(await p.locator('[data-results]').innerText(),/通信/);await p.evaluate(()=>(window as any).api.updateFoundation({error:''}));await input.fill('not-found');assert.match(await p.locator('[data-results]').innerText(),/ありません/);
 });
 await run('combo IME preedit Enter does not choose; rerender does not replace input or its caret',async()=>{
  await mount('prism-finder',{multiple:false,items:[{value:'a',label:'Alpha'},{value:'j',label:'日本語'}],defaultValue:''});const input=p.locator('[data-combo]');await input.fill('a');await input.press('ArrowDown');await input.evaluate(e=>{(window as any).savedInput=e;e.dispatchEvent(new CompositionEvent('compositionstart',{data:'に'}));e.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',isComposing:true,bubbles:true}));});assert.equal(await val(),'');await input.evaluate((e:HTMLInputElement)=>{e.value='日本';e.setSelectionRange(1,1);e.dispatchEvent(new CompositionEvent('compositionend',{data:'日本',bubbles:true}));});assert.equal(await p.locator('[data-option]').count(),1);await p.evaluate(()=>(window as any).api.updateFoundation({label:'更新したラベル'}));assert.ok(await input.evaluate(e=>e===(window as any).savedInput));assert.equal(await input.evaluate((e:HTMLInputElement)=>e.selectionStart),1);await input.press('ArrowDown');await input.press('Enter');assert.equal(await val(),'j');
 });
 await run('combo active background matches actual row bounds after scrolling, resize and quick reversals',async()=>{
  await mount('mercury-finder',{items:Array.from({length:14},(_,i)=>({value:'v'+i,label:i%2?'長い日本語の候補です '+i:'Option '+i,description:'補足説明は任意です。'}))});await p.locator('[data-combo-toggle]').click();const input=p.locator('[data-combo]');for(let i=0;i<12;i++)await input.press('ArrowDown');await p.waitForTimeout(1000);const delta=await p.locator('[data-combo-panel]').evaluate(e=>{const a=e.querySelector('.ff-option[data-active=true]')!.getBoundingClientRect(),b=e.querySelector('.rs-active-plane')!.getBoundingClientRect();return Math.max(Math.abs(a.top-b.top),Math.abs(a.left-b.left),Math.abs(a.height-b.height),Math.abs(a.width-b.width));});assert.ok(delta<2,String(delta));const active=await input.getAttribute('aria-activedescendant');assert.ok(active&&await p.locator('#'+active).isVisible());await input.press('Escape');assert.ok(await p.locator('[data-combo-panel]').isHidden());
 });
 await run('controlled combobox can decline updates and disabled state does not open a menu',async()=>{
  await mount('folio-finder',{multiple:false,value:'aurora',controlled:true});await p.locator('[data-combo-toggle]').click();await p.locator('[data-option=folio]').click();assert.equal(await val(),'aurora');assert.equal(await p.locator('[data-combo]').inputValue(),'Aurora');await p.evaluate(()=>(window as any).api.updateFoundation({disabled:true}));await p.evaluate(()=>(window as any).api.show());assert.ok(await p.locator('[data-combo-panel]').isHidden());
 });
 await run('all 16 notices have actual live content, distinct arrivals and an actionable dismiss',async()=>{
  const entrances=new Set<string>();
  for(const part of revised.filter(p=>p.category==='toasts')){await mount(part.id);await p.evaluate(()=>(window as any).api.notify({title:'変更を受け取りました',description:'あなたのアプリから渡した内容です。',tone:'success',duration:0,actionLabel:'確認する'}));assert.equal(await p.locator('.ff-notice[role=status]').count(),1);assert.equal(await p.locator('.ff-notice .ff-notice-copy strong').textContent(),'変更を受け取りました');assert.equal(await p.locator('.ff-notice .rs-notice-art').count(),1);assert.equal(await p.locator('.ff-notice .rs-scene').count(),0);const motion=await p.locator('.ff-notice').evaluate(el=>el.getAnimations().map(animation=>JSON.stringify((animation.effect as KeyframeEffect).getKeyframes())).join('|'));assert.ok(motion,part.id);entrances.add(motion);await p.waitForTimeout(50);await p.locator('[data-notice-close]').click();assert.equal(await p.locator('.ff-notice[role]').count(),0);await p.waitForTimeout(220);assert.equal(await p.locator('.ff-notice').count(),0);}
  assert.equal(entrances.size,16);
 });
 await run('toast duration pauses on hover and focus, then resumes with one timer and one action',async()=>{
  await mount('nixie-notice');await p.mouse.move(10,10);await p.evaluate(()=>{(window as any).actionCount=0;(window as any).api.notify({title:'Auto',duration:650,actionLabel:'Action',onAction:()=>{(window as any).actionCount++;}});});await p.waitForTimeout(180);await p.locator('.ff-notice').hover();await p.waitForTimeout(800);assert.equal(await p.locator('.ff-notice:not([data-closing])').count(),1);await p.locator('[data-notice-action]').focus();await p.mouse.move(5,5);await p.waitForTimeout(600);assert.equal(await p.locator('.ff-notice:not([data-closing])').count(),1);await p.locator('[data-notice-action]').click();assert.equal(await p.evaluate(()=>(window as any).actionCount),1);await p.waitForTimeout(220);assert.equal(await p.locator('.ff-notice').count(),0);
  await p.mouse.move(5,5);await p.evaluate(()=>(window as any).api.notify({title:'Resume',duration:500}));await p.waitForTimeout(120);await p.locator('.ff-notice').hover();await p.waitForTimeout(550);await p.mouse.move(5,5);await p.waitForTimeout(620);assert.equal(await p.locator('.ff-notice').count(),0);
 });
 await run('toast zero-duration, maximum stack and API pause/resume preserve real lifetime',async()=>{
  await mount('ceramic-notice',{maxNotices:2});await p.evaluate(()=>{for(let i=0;i<4;i++)(window as any).api.notify({title:'Notice '+i,duration:0});});assert.equal(await p.locator('.ff-notice').count(),2);await p.waitForTimeout(200);assert.equal(await p.locator('.ff-notice').count(),2);await p.evaluate(()=>(window as any).api.dismiss());await p.waitForTimeout(220);assert.equal(await p.locator('.ff-notice').count(),0);
  await p.evaluate(()=>{(window as any).api.setPaused(true);(window as any).api.notify({title:'Paused',duration:220});});await p.waitForTimeout(400);assert.equal(await p.locator('.ff-notice').count(),1);await p.evaluate(()=>(window as any).api.setPaused(false));await p.waitForTimeout(450);assert.equal(await p.locator('.ff-notice').count(),0);
 });
 await run('all 16 hints distinguish a non-focusable tooltip from an interactive dialog',async()=>{
  for(const part of revised.filter(p=>p.category==='hints')){await mount(part.id,{interactive:false});const trigger=p.locator('[data-hint-trigger]');await trigger.focus();assert.equal(await p.locator('[data-hint-panel]').getAttribute('role'),'tooltip');assert.ok(await trigger.evaluate(e=>e===document.activeElement));assert.ok(await trigger.getAttribute('aria-describedby'));assert.equal(await p.locator('[data-hint-panel] input:visible').count(),0);await p.keyboard.press('Escape');assert.ok(await p.locator('[data-hint-panel]').isHidden());assert.equal(await trigger.getAttribute('aria-expanded'),null);}
 });
 await run('16 A hints use distinct information artwork and reveal motion',async()=>{
  const motions=new Set<string>();
  for(const part of revised.filter(part=>part.category==='hints')){
   await mount(part.id,{interactive:true});
   await p.evaluate(()=>(window as any).api.show());
   const panel=p.locator('[data-hint-panel]'),art=panel.locator(':scope > .rs-hint-art');
   assert.ok(await panel.isVisible(),part.id);
   if(['aperture','prism'].includes(part.foundation?.variant??'')){
    assert.equal(await panel.locator(':scope > .rs-scene').count(),1,part.id);
    assert.equal(await art.count(),0,part.id);
   }else{
    assert.equal(await art.count(),1,part.id);
    assert.equal(await panel.locator(':scope > .rs-scene').count(),0,part.id);
    const frame=await art.evaluate(element=>(element.getAnimations()[0]?.effect as KeyframeEffect|null)?.getKeyframes()[0]);
    assert.ok(frame,part.id+' has entrance motion');
    motions.add(JSON.stringify(frame));
   }
   await p.keyboard.press('Escape');
  }
  assert.ok(motions.size>=12,'distinct hint motions: '+motions.size);
 });
await run('hint hover crossing and Escape preserve trigger focus; popover updates retain child state',async()=>{
  await mount('aurora-popover',{interactive:false});const trigger=p.locator('[data-hint-trigger]'),panel=p.locator('[data-hint-panel]');await p.locator('#outside').focus();await trigger.hover();await panel.hover();await p.waitForTimeout(240);assert.ok(await panel.isVisible());await p.mouse.move(1,1);await p.waitForTimeout(250);assert.ok(await panel.isHidden());
  await p.evaluate(()=>(window as any).api.updateFoundation({interactive:true}));await trigger.click();assert.equal(await panel.getAttribute('role'),'dialog');assert.equal(await trigger.getAttribute('aria-expanded'),'true');await panel.locator('input').check();await p.evaluate(()=>(window as any).api.updateFoundation({content:'内容だけ変更します。'}));assert.ok(await panel.locator('input').isChecked());await panel.locator('[data-hint-action]').focus();await p.keyboard.press('Escape');assert.ok(await panel.isHidden());assert.ok(await trigger.evaluate(e=>e===document.activeElement));await trigger.click();assert.ok(await panel.locator('input').isChecked());await p.evaluate(()=>(window as any).api.updateFoundation({interactive:false}));assert.equal(await panel.getAttribute('role'),'tooltip');assert.equal(await panel.locator('input:visible').count(),0);assert.equal(await trigger.getAttribute('aria-expanded'),null);
 });
 await run('overlays appear above the gallery dialog without moving or duplicating actual content',async()=>{
  await mount('velvet-popover',{interactive:true});await p.locator('[data-sample]').evaluate(e=>{const d=document.createElement('dialog');d.style.cssText='width:440px;max-height:90vh;background:#111;padding:30px';e.before(d);d.append(e);d.showModal();});await p.locator('[data-hint-trigger]').click();assert.ok(await p.locator('[data-hint-panel]').evaluate(e=>e.matches(':popover-open')));await p.locator('[data-hint-panel] input').check();assert.ok(await p.locator('[data-hint-panel] input').isChecked());await p.evaluate(()=>{(window as any).unmount();document.querySelector('dialog')?.remove();});
 });
 await run('all 64 A parts fit 320/390/768 with long Japanese text and no page overflow',async()=>{
  for(const width of [320,390,768]){await p.setViewportSize({width,height:960});for(const part of revised){await mount(part.id,{label:'幅の狭い画面でも使える長い日本語のラベル',description:'説明は自由に差し替えられます。'});if(part.category==='comboboxes'||part.category==='hints')await p.evaluate(()=>(window as any).api.show());if(part.category==='toasts')await p.evaluate(()=>(window as any).api.notify({title:'長い日本語の通知メッセージを使います',description:'内容を普通のアプリへ差し替えても収まることを確認します。',duration:0}));assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2),part.id+':page '+width);const floating=p.locator('.ff-floating:not([hidden]),.ff-toast-stack:not([hidden])');for(let i=0;i<await floating.count();i++){const b=await floating.nth(i).boundingBox();assert.ok(b&&b.x>=-1&&b.x+b.width<=width+1,part.id+':panel '+width);assert.ok(b&&b.y>=-1&&b.y+b.height<=961,part.id+':height '+width);}}}
 });
 await run('reduced motion settles immediately; forced colors retain native focus, selection and text',async()=>{
  await p.setViewportSize({width:740,height:1000});await p.emulateMedia({reducedMotion:'reduce'});for(const part of revised){await mount(part.id);if(part.category==='radios')await p.locator('.ff-choice').last().click();else if(part.category==='toasts')await p.evaluate(()=>(window as any).api.notify({title:'Static',duration:0}));else await p.evaluate(()=>(window as any).api.show());await p.waitForTimeout(20);assert.equal(await p.evaluate(()=>(window as any).activeFrames.size),0,part.id);assert.equal(await p.evaluate(()=>document.getAnimations().filter(a=>a.playState==='running').length),0,part.id);}
  await p.emulateMedia({reducedMotion:'reduce',forcedColors:'active'});await mount('prism-choice');assert.ok(await p.locator('.rs-scene').first().isHidden());await p.locator('.ff-choice').last().click();assert.ok(await p.locator('.ff-choice input').last().isChecked());await mount('nixie-finder');await p.locator('[data-combo-toggle]').click();await p.locator('[data-combo]').press('ArrowDown');assert.equal(await p.locator('[data-option][data-active=true]').count(),1);await p.emulateMedia({reducedMotion:'no-preference',forcedColors:'none'});
 });
 await run('idle/teardown clear every presentation RAF, timer effect and top-layer panel',async()=>{
  for(const part of revised){await mount(part.id);if(part.category==='radios')await p.locator('.ff-choice').last().click();else if(part.category==='toasts')await p.evaluate(()=>(window as any).api.notify({title:'Dispose',duration:200}));else await p.evaluate(()=>(window as any).api.show());await p.evaluate(()=>(window as any).unmount());await p.waitForTimeout(15);assert.equal(await p.evaluate(()=>(window as any).activeFrames.size),0,part.id);assert.equal(await p.locator(':popover-open').count(),0,part.id);}
  await mount('tide-finder');await p.evaluate(()=>(window as any).api.show());await p.waitForTimeout(1600);assert.equal(await p.evaluate(()=>(window as any).activeFrames.size),0);await p.evaluate(()=>(window as any).unmount());await p.waitForTimeout(250);assert.equal(await p.evaluate(()=>document.getAnimations().filter(a=>a.playState==='running').length),0);
 });

 await run('64 material layouts stay identical when every other component stylesheet is loaded',async()=>{
  await p.emulateMedia({reducedMotion:'reduce'});await p.setViewportSize({width:740,height:1000});
  const snapshots=async()=>{await p.mouse.move(0,0);const out:Record<string,unknown>={};for(const part of revised){await mount(part.id,{multiple:false});if(part.category==='toasts')await p.evaluate(()=>(window as any).api.notify({title:'Same title',description:'same description',duration:0}));else if(part.category!=='radios')await p.evaluate(()=>(window as any).api.show());
   out[part.id]=await p.evaluate(()=>[...document.querySelectorAll('.sop-resonance,.ff-choice,.ff-combo-shell,.ff-option,.ff-notice,.ff-hint-panel,.ff-hint-panel>p,.ff-hint-heading,.rs-hint-actions,.ff-hint-facts,.ff-hint-checkbox,.rs-hint-actions > .ff-action')].map(e=>{const c=getComputedStyle(e);return Object.fromEntries(['background','color','border','border-radius','box-shadow','font-size','font-family','padding','margin','display','position','transform','clip-path','width','height'].map(k=>[k,c.getPropertyValue(k)]));}));}return out;};
  const before=await snapshots(),seen=new Set<string>();const readCSS=(relative:string):string=>{if(seen.has(relative))return '';seen.add(relative);return fs.readFileSync(path.join(ROOT,relative),'utf8').replace(/@import\s+["']([^"']+)["']\s*;/g,(_match,imported:string)=>readCSS(path.posix.normalize(path.posix.join(path.posix.dirname(relative),imported))));};
  const registry=JSON.parse(fs.readFileSync(path.join(ROOT,'src/catalog/registry.json'),'utf8')) as string[];await p.addStyleTag({content:registry.map(base=>readCSS(base+'/styles.css')).join('\n')});assert.deepEqual(await snapshots(),before);await p.evaluate(()=>(window as any).unmount());await p.emulateMedia({reducedMotion:'no-preference'});
 });
 assert.deepEqual(errors,[]);console.log('RESONANCE: '+tests.length+' passed');
} finally {fs.writeFileSync(path.join(fixture.out,'browser-results.json'),JSON.stringify({mode:offline?'explicit offline compiled fixture / real Chromium, NOT Vite':'real Vite HTTP',passed:tests.length,tests,errors},null,2)+'\n');await browser?.close();await close?.();}
