import {galleryReady} from './gallery-ready.ts';
/** Actual gallery/export integration. Offline mode is explicit and never reported as a Vite build. */
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import type {Browser} from 'playwright';
import {ROOT,buildCatalog,FORMATS} from '../scripts/catalog.ts';import {offlineFiles} from './offline-fixture.ts';import {getDelivery,buildPrompt} from '../src/catalog/delivery.ts';import {requireLocalServerUrl} from './vite-url.ts';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_PATH??'playwright') as typeof import('playwright'),data=buildCatalog(),offline=process.env.SOP_TEST_MODE==='offline',out=path.join(ROOT,'.test-output/resonance-gallery');fs.mkdirSync(out,{recursive:true});const tests:string[]=[],errors:string[]=[];let browser:Browser|undefined,close:(()=>Promise<void>)|undefined;
async function run(name:string,fn:()=>Promise<void>){await fn();tests.push(name);console.log('PASS '+name);}
try{
 let url='';if(!offline){const{createServer}=await import('vite'),s=await createServer({root:ROOT,server:{host:'127.0.0.1',port:0}});await s.listen();url=requireLocalServerUrl(s,'RESONANCE gallery');close=()=>s.close();}
 browser=await chromium.launch({headless:true,args:['--no-sandbox'],...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{})});const p=await browser.newPage({viewport:{width:1440,height:1000}});p.setDefaultTimeout(9000);p.on('pageerror',e=>errors.push(e.message));
 if(offline){const f=offlineFiles(data);await p.setContent(f.get('/index.html')!.replace(/<script[^>]*>[\s\S]*?<\/script>/g,'').replace(/<link[^>]*>/g,''));await p.addStyleTag({content:f.get('/test-styles.css')!});for(const v of ['prism','jszip'])await p.addScriptTag({content:fs.readFileSync(path.join(ROOT,'public/vendor/'+v+'.js'),'utf8')});await p.addScriptTag({content:f.get('/test-app.js')!});}else await p.goto(url);
 await run('gallery counts 16 revised A / 8 unchanged B per category and representative materials operate',async()=>{
  for(const category of ['radios','comboboxes','toasts','hints']){await p.locator(`[data-category="${category}"]`).click();await galleryReady(p,true);assert.equal(await p.locator('[data-part]').count(),24);await p.locator('[data-design-filter="A"]').click();await galleryReady(p,true);assert.equal(await p.locator('[data-part]').count(),16);for(const part of data.parts.filter(part=>part.category===category&&part.designType==='A'&&['aurora','folio','prism'].includes(part.foundation?.variant??''))){const card=p.locator(`[data-part="${part.id}"]`);assert.equal(await card.locator('.sop-resonance').count(),1);if(category==='radios'){await card.locator('.ff-choice').last().click();assert.equal(await card.locator('.ff-choice').last().getAttribute('data-selected'),'true');}else if(category==='comboboxes'){await card.locator('[data-combo-toggle]').click();await card.locator('[data-combo]').press('ArrowDown');assert.equal(await card.locator('[data-option][data-active=true]').count(),1);await p.keyboard.press('Escape');}else if(category==='toasts'){await card.locator('[data-notify]').click();assert.equal(await card.locator('.ff-notice[role=status]').count(),1);await card.locator('[data-notice-close]').click();await p.waitForTimeout(200);}else{await card.locator('[data-hint-trigger]').click();assert.ok(await card.locator('[data-hint-panel]').isVisible());await p.keyboard.press('Escape');}assert.equal(await p.locator('#part-details[open]').count(),0);}await p.locator('[data-design-filter="B"]').click();await galleryReady(p,true);assert.equal(await p.locator('[data-part]').count(),8);assert.equal(await p.locator('.sop-resonance').count(),0);await p.locator('[data-design-filter="all"]').click();await galleryReady(p,true);}
 });
 await run('inspector source and prompts exactly match actual exports for all formats and both layouts',async()=>{
  let files=0;for(const id of ['aurora-choice','prism-finder','folio-notice','velvet-popover']){const part=data.parts.find(p=>p.id===id)!;await p.locator(`[data-category="${part.category}"]`).click();await galleryReady(p,true);await p.locator(`[data-open="${id}"]`).click();await galleryReady(p,true);const d=p.locator('#part-details');for(const layout of ['portable','original'] as const){await d.locator('#export-layout').selectOption(layout);for(const format of FORMATS){await d.locator(`[data-format="${format}"]`).click();const delivery=getDelivery(part,format,layout);for(const f of delivery.files){await d.locator(`[data-file="${f.name}"]`).evaluate(e=>(e as HTMLButtonElement).click());assert.deepEqual(await d.locator('.editor .line-code').allTextContents(),f.code.split('\n').map(line=>line||' '),`${id}/${layout}/${format}/${f.name}`);files++;}await d.locator('[data-detail-tab="prompt"]').click();assert.equal(await d.locator('#prompt-text').inputValue(),buildPrompt(part,format,layout));await d.locator('[data-detail-tab="code"]').click();}}await d.locator('.close-detail').click();}console.log('Source files compared:',files);
 });
 await run('combobox and hints open above the real inspector; Escape leaves the inspector open',async()=>{
  for(const id of ['aurora-finder','velvet-popover']){const part=data.parts.find(p=>p.id===id)!;await p.locator(`[data-category="${part.category}"]`).click();await galleryReady(p,true);await p.locator(`[data-open="${id}"]`).click();await galleryReady(p,true);const d=p.locator('#part-details');await d.locator('[data-foundation-open]').click();const panel=d.locator(id.endsWith('finder')?'[data-combo-panel]':'[data-hint-panel]');assert.ok(await panel.isVisible());assert.ok(await panel.evaluate(e=>e.matches(':popover-open')));if(id.endsWith('finder')){await d.locator('[data-combo]').focus();await p.keyboard.press('ArrowDown');}else{await panel.locator('input').check();}await p.keyboard.press('Escape');assert.ok(await panel.isHidden());assert.equal(await p.locator('#part-details[open]').count(),1);await p.screenshot({path:path.join(out,'detail.png')});await d.locator('.close-detail').click();}
 });
 await run('320 / 390 / 768 inspector views retain editable controls, file downloads and code visibility',async()=>{
  for(const width of [320,390,768]){await p.setViewportSize({width,height:1040});for(const id of ['aurora-choice','prism-finder','folio-notice','velvet-popover']){const part=data.parts.find(p=>p.id===id)!;await p.locator(`[data-category="${part.category}"]`).click();await galleryReady(p,true);await p.locator(`[data-open="${id}"]`).click();await galleryReady(p,true);const d=p.locator('#part-details');assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2));await d.locator('.copy-file').scrollIntoViewIfNeeded();assert.ok(await d.locator('.copy-file').isVisible());assert.ok(await d.locator('.download-file').count());if(width===390&&id==='prism-finder')await p.screenshot({path:path.join(out,'mobile-390.png')});await d.locator('.close-detail').click();}}
 });
 assert.deepEqual(errors,[]);console.log('RESONANCE gallery: '+tests.length+' checks passed');
}finally{fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({mode:offline?'real gallery through explicit offline document, NOT Vite':'real Vite HTTP',passed:tests.length,tests,errors},null,2)+'\n');await browser?.close();await close?.();}
