import {galleryReady} from './gallery-ready.ts';
/** Inspector and exports use real generated sources; offline mode is explicitly not Vite. */
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import{createRequire}from'node:module';import type{Browser}from'playwright';
import{ROOT,buildCatalog,FORMATS}from'../scripts/catalog.ts';import{offlineFiles}from'./offline-fixture.ts';import{getDelivery,buildPrompt,packageContents}from'../src/catalog/delivery.ts';import{requireLocalServerUrl}from'./vite-url.ts';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_PATH??'playwright') as typeof import('playwright');
console.log('Build catalog for SEQUENCE inspector');const data=buildCatalog(),offline=process.env.SOP_TEST_MODE==='offline',out=path.join(ROOT,'.test-output/sequence-gallery');fs.mkdirSync(out,{recursive:true});const tests:string[]=[],errors:string[]=[];let browser:Browser|undefined,close:(()=>Promise<void>)|undefined;
async function run(name:string,fn:()=>Promise<void>){await fn();tests.push(name);console.log('PASS '+name);}
try{
 let url='';if(!offline){const{createServer}=await import('vite'),server=await createServer({root:ROOT,server:{host:'127.0.0.1',port:0}});await server.listen();url=requireLocalServerUrl(server,'SEQUENCE inspector');close=()=>server.close();}
 browser=await chromium.launch({headless:true,args:['--no-sandbox'],...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{})});const p=await browser.newPage({viewport:{width:1440,height:1080}});p.setDefaultTimeout(25000);p.on('pageerror',e=>errors.push(e.message));
 if(offline){console.log('Compile actual gallery fixture');const f=offlineFiles(data);await p.setContent(f.get('/index.html')!.replace(/<script[^>]*>[\s\S]*?<\/script>/g,'').replace(/<link[^>]*>/g,''));await p.addStyleTag({content:f.get('/test-styles.css')!});for(const vendor of ['prism','jszip'])await p.addScriptTag({content:fs.readFileSync(path.join(ROOT,'public/vendor/'+vendor+'.js'),'utf8')});await p.addScriptTag({content:f.get('/test-app.js')!});}else await p.goto(url);
 await run('catalog still has 817 parts; category filters preserve 10/6 paginations and 16/8 tags',async()=>{
  for(const[cat,count,a]of[['pagination',16,10],['badges',24,16]] as const){await p.locator(`[data-category="${cat}"]`).click();await galleryReady(p,true);assert.equal(await p.locator('[data-part]').count(),count);await p.locator('[data-design-filter="A"]').click();await galleryReady(p,true);assert.equal(await p.locator('[data-part]').count(),a);await p.locator('[data-design-filter="B"]').click();await galleryReady(p,true);assert.equal(await p.locator('[data-part]').count(),count-a);await p.locator('[data-design-filter="all"]').click();await galleryReady(p,true);}assert.equal(data.parts.length,817);
 });
 await run('all 26 parts include controller, art, usage, prompt and valid integration paths in all eight deliveries',async()=>{
  let bundles=0;for(const part of data.parts.filter(r=>r.tags.includes('SEQUENCE')))for(const layout of['portable','original']as const)for(const format of FORMATS){const delivery=getDelivery(part,format,layout),files=packageContents(part,format,layout);assert.ok(delivery.files.some(f=>f.name===delivery.entry));assert.ok(delivery.runtimeFiles.every(f=>!f.name.includes('src/app/')));assert.ok(files.some(f=>f.name.endsWith('/sequence/skin.ts')||f.name.endsWith('/sequence/skin.js')));assert.equal(files.find(f=>f.name==='PROMPT.md')?.code,buildPrompt(part,format,layout));assert.ok(files.some(f=>f.name==='INTEGRATION.json'));bundles++;}assert.equal(bundles,208);console.log('Deliveries checked:',bundles);
 });
 await run('inspector code matches every exported file for four representative materials in all formats and layouts',async()=>{
  let count=0;for(const id of['folio-pages','mercury-pages','prism-tags','ceramic-tags']){const part=data.parts.find(r=>r.id===id)!;await p.locator(`[data-category="${part.category}"]`).click();await galleryReady(p,true);await p.locator(`[data-open="${id}"]`).click();await galleryReady(p,true);const d=p.locator('#part-details');for(const layout of['portable','original']as const){await d.locator('#export-layout').selectOption(layout);for(const format of FORMATS){await d.locator(`[data-format="${format}"]`).evaluate(e=>(e as HTMLButtonElement).click());for(const file of getDelivery(part,format,layout).files){await d.locator(`[data-file="${file.name}"]`).evaluate(e=>(e as HTMLButtonElement).click());assert.deepEqual(await d.locator('.editor .line-code').allTextContents(),file.code.split('\n').map(l=>l||' '),file.name);count++;}await d.locator('[data-detail-tab="prompt"]').evaluate(e=>(e as HTMLButtonElement).click());assert.equal(await d.locator('#prompt-text').inputValue(),buildPrompt(part,format,layout));await d.locator('[data-detail-tab="code"]').evaluate(e=>(e as HTMLButtonElement).click());}}await d.locator('.close-detail').evaluate(e=>(e as HTMLButtonElement).click());}console.log('Displayed source files checked:',count);
 });
 await run('pagination inspector changes total/pages and resets without faking data loads',async()=>{
  await p.locator('[data-category="pagination"]').click();await galleryReady(p,true);await p.locator('[data-open="folio-pages"]').click();await galleryReady(p,true);const d=p.locator('#part-details');await d.locator('[data-sq-demo-pages]').selectOption('100');await d.locator('[data-sq-demo-jump="last"]').click();assert.equal(await d.locator('[aria-current="page"]').getAttribute('data-page'),'100');await d.locator('[data-sq-demo-pages]').selectOption('1');assert.equal(await d.locator('[aria-current="page"]').getAttribute('data-page'),'1');await d.locator('[data-foundation-reset]').click();assert.equal(await d.locator('[data-sq-demo-pages]').inputValue(),'12');assert.equal(await d.locator('[aria-current="page"]').getAttribute('data-page'),'4');await p.screenshot({path:path.join(out,'pagination-detail.png')});await d.locator('.close-detail').evaluate(e=>(e as HTMLButtonElement).click());
 });
 await run('tag inspector supports display/select/delete/both, restores removed items and holds value when switching code format',async()=>{
  await p.locator('[data-category="badges"]').click();await galleryReady(p,true);await p.locator('[data-open="aurora-tags"]').click();await galleryReady(p,true);const d=p.locator('#part-details');await d.locator('[data-sq-demo-mode]').selectOption('both');const input=d.locator('[data-tag-select]').first(),key=await input.getAttribute('data-tag-select');await input.check();await d.locator('[data-format="jsx"]').click();assert.ok(await d.locator(`[data-tag-select="${key}"]`).isChecked());const before=await d.locator('[data-tag-key]').count();await d.locator('[data-tag-remove]').first().click();assert.equal(await d.locator('[data-tag-key]').count(),before-1);await d.locator('[data-foundation-reset]').click();assert.equal(await d.locator('[data-tag-key]').count(),before);await d.locator('[data-sq-demo-mode]').selectOption('display');assert.equal(await d.locator('.sq-chip input,.sq-chip button').count(),0);await d.locator('[data-sq-demo-long]').click();assert.equal(await d.locator('[data-tag-key]').count(),3);await d.locator('[data-sq-demo-restore]').click();assert.equal(await d.locator('[data-tag-key]').count(),before);await p.screenshot({path:path.join(out,'tags-detail.png')});await d.locator('.close-detail').evaluate(e=>(e as HTMLButtonElement).click());
 });
 await run('320/390/768 inspectors keep preview controls and copy/file-save accessible',async()=>{
  for(const width of[320,390,768]){await p.setViewportSize({width,height:1040});for(const id of['mercury-pages','folio-tags']){const part=data.parts.find(x=>x.id===id)!;await p.locator(`[data-category="${part.category}"]`).click();await galleryReady(p,true);await p.locator(`[data-open="${id}"]`).click();await galleryReady(p,true);const d=p.locator('#part-details');assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2),id+width);await d.locator('.copy-file').scrollIntoViewIfNeeded();assert.ok(await d.locator('.copy-file').isVisible());assert.ok(await d.locator('.download-file').isVisible());if(width===390&&id==='mercury-pages')await p.screenshot({path:path.join(out,'mobile-390.png')});await d.locator('.close-detail').evaluate(e=>(e as HTMLButtonElement).click());}}
 });
 assert.deepEqual(errors,[]);console.log('SEQUENCE gallery '+tests.length+' checks passed');
}finally{fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({mode:offline?'real gallery / explicit offline compiled adapter, NOT Vite':'real Vite HTTP',passed:tests.length,tests,errors},null,2)+'\n');await browser?.close();await close?.();}
