import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createRequire} from 'node:module';
import type {Browser,Page} from 'playwright';import {signatureFixture} from './signature-fixture.ts';import {ROOT} from '../scripts/catalog.ts';import {requireLocalServerUrl} from './vite-url.ts';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_PATH??'playwright') as typeof import('playwright');
const offline=process.env.SOP_TEST_MODE==='offline',fixture=signatureFixture(),passed:string[]=[],errors:string[]=[];
let browser:Browser|undefined,closeServer:(()=>Promise<void>)|undefined;
async function run(name:string,fn:()=>Promise<void>){await fn();passed.push(name);console.log('PASS '+name);}
try{
 let url='';if(!offline){const {createServer}=await import('vite');const s=await createServer({root:ROOT,server:{host:'127.0.0.1',port:0}});await s.listen();url=requireLocalServerUrl(s,'Signature');closeServer=()=>s.close();}
 browser=await chromium.launch({headless:true,args:['--no-sandbox'],...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{})});
 const p=await browser.newPage({viewport:{width:620,height:1000}});p.setDefaultTimeout(6000);p.on('pageerror',e=>errors.push(e.message));
 if(offline){await p.setContent(fixture.shell.replace('<link rel="stylesheet" href="./styles.css">',''));await p.addStyleTag({content:fixture.styles});await p.addScriptTag({content:fixture.bundle()});}else await p.goto(new URL('.test-output/signature/test.html',url).href,{waitUntil:'domcontentloaded',timeout:120000});
 async function mount(id:string|string[],options:Record<string,unknown>={}){await p.evaluate(([ids,opt])=>(window as any).mount(ids,opt),[typeof id==='string'?[id]:id,options]);await p.waitForTimeout(35);}
 const state=()=>p.evaluate(()=>(window as any).api.getState());
 await run('All 96 actual native components mount and expose independent state',async()=>{for(const item of fixture.records){await mount(item.id);assert.equal(await p.locator('#host>.sample-nonexistent').count(),0);assert.equal(await p.locator('#host .sop-sig').count(),1,item.id);assert.ok(await state(),item.id);}});
 await run('Avatar selection, passive display, disabled and controlled decline',async()=>{await mount('orbital-portrait');await p.locator('[data-user=rin]').click();assert.equal((await state()).value,'rin');await p.evaluate(()=>(window as any).api.update({value:'sora'}));await p.locator('[data-user=nao]').click();assert.equal((await state()).value,'sora');await p.evaluate(()=>(window as any).api.reset());assert.equal((await state()).value,'sora');await p.evaluate(()=>(window as any).api.update({interactive:false}));assert.equal(await p.locator('#host button[data-user]').count(),0);await p.evaluate(()=>(window as any).api.update({interactive:true,disabled:true}));assert.ok(await p.locator('[data-user=sora]').isDisabled());});
 await run('Avatar custom data is literal text and image failures leave the portrait fallback',async()=>{await mount('iris-portrait',{users:[{id:'a',name:'<b>日本語</b>',initials:'日',src:'/missing-avatar.png'},{id:'b',name:'Long name'}],value:'a'});assert.equal(await p.locator('.sg-person-name').first().textContent(),'<b>日本語</b>');await p.locator('img').evaluate((e:HTMLImageElement)=>e.dispatchEvent(new Event('error')));assert.ok(await p.locator('img').isHidden());assert.ok(await p.locator('.sg-initials').first().isVisible());});
 await run('Ratings preview without committing; native radio selection, clear and form reset',async()=>{await mount('blossom-rating');await p.locator('[data-rank="5"]').hover();assert.equal((await state()).value,3);assert.equal((await state()).preview,5);await p.locator('[data-rank="5"]').click();assert.equal((await state()).value,5);await p.locator('.sg-rating-clear').click();assert.equal((await state()).value,0);await p.locator('#reset').click();assert.equal((await state()).value,3);});
 await run('Rating dynamic maximum, keyboard, controlled value and read-only protect state',async()=>{await mount('simple-star-rating',{max:7,value:2,readOnly:true});await p.locator('[data-rank="7"]').click({force:true});assert.equal((await state()).value,2);await p.evaluate(()=>(window as any).api.update({value:undefined,readOnly:false,max:10}));await p.locator('input[type=radio]').nth(1).focus();await p.keyboard.press('End');assert.equal((await state()).value,10);await p.keyboard.press('Home');assert.equal((await state()).value,1);await p.keyboard.press('ArrowRight');assert.equal((await state()).value,2);});
 await run('Color HEX accepts shorthand, rejects invalid values and preserves edit drafts',async()=>{await mount('prism-laboratory',{name:'accent'});const hex=p.locator('[data-hex]');await hex.fill('#f80');await hex.press('Enter');assert.equal((await state()).value,'#FF8800');await hex.fill('invalid');await hex.press('Enter');assert.equal((await state()).value,'#FF8800');assert.equal((await state()).valid,false);await hex.press('Escape');await hex.fill('#a');await p.evaluate(()=>(window as any).api.update({label:'Updated'}));assert.equal(await hex.inputValue(),'#a');await hex.fill('#123456');await hex.press('Enter');assert.equal(await p.evaluate(()=>new FormData(document.querySelector('form')!).get('accent')),'#123456');});
 await run('Color SV drag, hue keyboard and palette all update one value; reset and readonly',async()=>{await mount('chromatic-orbit');const area=p.locator('.sg-color-sv'),box=(await area.boundingBox())!;await p.mouse.click(box.x+box.width*.8,box.y+box.height*.35);const before=(await state()).value;await p.locator('[data-channel=h]').focus();await p.keyboard.press('ArrowRight');assert.notEqual((await state()).value,before);const swatch=await p.locator('[data-swatch]').nth(2).getAttribute('data-swatch');await p.locator('[data-swatch]').nth(2).click();assert.equal((await state()).value,swatch);await p.locator('#reset').click();assert.equal((await state()).value,'#A5BCE0');await p.evaluate(()=>(window as any).api.update({readOnly:true}));assert.ok(await p.locator('[data-channel=h]').isDisabled());assert.ok(await p.locator('[data-hex]').getAttribute('readonly')!==null);});
 await run('Skeleton shows real retained content without declaring completion or losing input',async()=>{await mount('folding-skeleton');await p.locator('[data-sg-slot]').evaluate(e=>{const input=document.createElement('input');input.setAttribute('aria-label','読み込み後の入力');e.append(input);});assert.equal(await p.locator('.sop-sig').getAttribute('aria-busy'),'true');await p.evaluate(()=>(window as any).api.update({loading:false}));const input=p.locator('[data-sg-slot] input');assert.ok(await input.isVisible());await input.fill('保持した入力');await p.evaluate(()=>(window as any).api.update({loading:true}));assert.ok(await input.isHidden());await p.evaluate(()=>(window as any).api.update({loading:false}));assert.equal(await input.inputValue(),'保持した入力');await p.evaluate(()=>(window as any).api.update({loading:true,rows:8,paused:true}));assert.equal(await p.locator('.sg-sk-lines>i').count(),8);assert.equal(await p.locator('.sop-sig').evaluate(e=>(e as HTMLElement).style.getPropertyValue('--sg-play')),'paused');});
 await run('Timeline keeps dates/status fixed and supports keyboard, custom data, controlled expansion',async()=>{await mount('document-timeline');const summary=p.locator('summary').first();await summary.focus();await p.keyboard.press('Enter');assert.ok((await state()).expanded.includes('idea'));assert.equal(await p.locator('[data-event=release]').getAttribute('data-status'),'pending');await p.evaluate(()=>(window as any).api.update({expanded:['review']}));await summary.click();assert.deepEqual((await state()).expanded,['review']);await p.evaluate(()=>(window as any).api.reset());assert.deepEqual((await state()).expanded,['review']);await p.evaluate(()=>(window as any).api.update({items:[{id:'new',title:'新しい項目',description:'<strong>text</strong>'}],expanded:[]}));assert.equal(await p.locator('summary').count(),1);assert.equal((await state()).count,1);});
 await run('Wizard validates required fields, preserves text going back and completes without network',async()=>{await mount('folio-wizard');await p.locator('[data-wizard-next]').click();assert.equal((await state()).index,0);await p.locator('input[data-field]').fill('Studio');await p.locator('[data-wizard-next]').click();assert.equal((await state()).index,1);await p.locator('textarea').fill('Content saved in memory');await p.locator('[data-wizard-prev]').click();assert.equal(await p.locator('input[data-field]').inputValue(),'Studio');await p.locator('[data-wizard-next]').click();assert.equal(await p.locator('textarea').inputValue(),'Content saved in memory');await p.locator('[data-wizard-next]').click();await p.locator('[data-wizard-next]').click();assert.equal((await state()).complete,true);await p.locator('#reset').click();assert.equal((await state()).complete,false);assert.equal((await state()).index,0);});
 await run('Wizard async guard blocks duplicates, permits rejection and ignores stale results',async()=>{await mount('assembly-wizard');await p.locator('input[data-field]').fill('Example');await p.evaluate(()=>(window as any).api.update({beforeNext:()=>new Promise(resolve=>(window as any).finish=resolve)}));await p.locator('[data-wizard-next]').click();assert.equal((await state()).busy,true);assert.ok(await p.locator('[data-wizard-next]').isDisabled());await p.evaluate(()=>(window as any).finish('再確認してください'));await p.waitForTimeout(10);assert.equal((await state()).index,0);assert.match(await p.locator('[data-wizard-error]').textContent()??'',/再確認/);await p.locator('[data-wizard-next]').click();await p.evaluate(()=>{(window as any).api.update({current:'review'});(window as any).finish(true);});await p.waitForTimeout(10);assert.equal((await state()).current,'review');assert.equal((await state()).busy,false);});
 await run('Wizard arbitrary step counts, forward navigation policy and retained fields on structural updates',async()=>{await mount('expedition-wizard');await p.locator('input[data-field]').fill('Retained');await p.evaluate(()=>{const initial=JSON.parse(document.querySelector<HTMLElement>('.sop-sig')!.dataset.sgConfig!);(window as any).api.update({steps:[...initial.steps,{id:'extra',title:'追加の工程'},{id:'last',title:'終了'}],allowJump:true});});assert.equal((await state()).count,5);assert.equal(await p.locator('input[data-field]').inputValue(),'Retained');await p.locator('[data-step-target=last]').click();assert.equal((await state()).index,4);await p.evaluate(()=>(window as any).api.update({steps:[]}));assert.equal((await state()).count,0);assert.ok(await p.locator('[data-wizard-next]').isDisabled());});
 await run('Six components of the same kind have independent native identifiers and state',async()=>{for(const id of ['circle-profile','nova-rating','classic-color','text-skeleton','basic-timeline','essential-wizard']){await mount(Array.from({length:3},()=>id));const ids=await p.locator('[id]').evaluateAll(nodes=>nodes.map(n=>n.id));assert.equal(ids.length,new Set(ids).size,id);if(id==='nova-rating'){await p.locator('[data-sample]').first().locator('[data-rank="5"]').click();assert.equal(await p.evaluate(()=>(window as any).apis[0].getState().value),5);assert.equal(await p.evaluate(()=>(window as any).apis[1].getState().value),3);}}});
 await run('All 96 components fit 320 / 390 / 768 px and 10 ratings/long Japanese labels',async()=>{for(const width of [320,390,768]){await p.setViewportSize({width,height:1000});for(const item of fixture.records){await mount(item.id);const overflow=await p.evaluate(()=>document.documentElement.scrollWidth-innerWidth);assert.ok(overflow<=1,`${width} ${item.id}: ${overflow}`);}}await mount('nova-rating',{max:10,label:'非常に長い日本語のラベルを表示する評価インターフェース'});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await p.setViewportSize({width:620,height:1000});});
 await run('Motion reduction stops decorative loops and retains usable controls',async()=>{await p.emulateMedia({reducedMotion:'reduce'});await mount('orbital-portrait');await p.locator('[data-user=rin]').click();assert.equal((await state()).value,'rin');await mount('scanner-skeleton');assert.equal(await p.locator('.sop-sig').getAttribute('data-sg-reduced'),'true');assert.equal(await p.locator('.sop-sig').evaluate(e=>e.getAnimations({subtree:true}).filter(a=>a.playState==='running').length),0);await p.emulateMedia({reducedMotion:'no-preference'});});
 await run('Unmount cancels animations, observers and pending wizard callbacks',async()=>{await mount('shimmer-skeleton');await p.evaluate(()=>(window as any).unmount());assert.equal(await p.locator('.sop-sig').count(),0);await mount('essential-wizard');await p.locator('input[data-field]').fill('Late');await p.evaluate(()=>(window as any).api.update({beforeNext:()=>new Promise(resolve=>(window as any).late=resolve),onStepChange:()=>{(window as any).unexpected=true}}));await p.locator('[data-wizard-next]').click();await p.evaluate(()=>{(window as any).unmount();(window as any).late(true);});await p.waitForTimeout(10);assert.equal(await p.evaluate(()=>!!(window as any).unexpected),false);});
 await mount(['orbital-portrait','blossom-rating','chromatic-orbit']);await p.screenshot({path:path.join(fixture.out,'components.png'),fullPage:true});assert.deepEqual(errors,[]);
 console.log(`Signature browser checks: ${passed.length} passed (${offline?'explicit offline source adapter':'Vite HTTP'}).`);
}finally{fs.writeFileSync(path.join(fixture.out,'browser-results.json'),JSON.stringify({mode:offline?'Chromium offline author-source adapter, NOT Vite':'Vite HTTP',passed:passed.length,tests:passed,errors},null,2));await browser?.close();await closeServer?.();}
