import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';
import {createRequire} from 'node:module';import type {Browser} from 'playwright';
import {transformFixture} from './transform-fixture.ts';import {ROOT} from '../scripts/catalog.ts';import {requireLocalServerUrl} from './vite-url.ts';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_PATH??'playwright') as typeof import('playwright');
const f=transformFixture(),offline=process.env.SOP_TEST_MODE==='offline',revised=f.records.filter(p=>p.tags.includes('TRANSFORM'));
const selections=revised.filter(p=>['tabs','segments'].includes(p.category)),sliders=revised.filter(p=>p.category==='sliders'),popups=revised.filter(p=>p.category==='popups');
const tests:string[]=[],errors:string[]=[];let browser:Browser|undefined,close:(()=>Promise<void>)|undefined;
async function run(name:string,fn:()=>Promise<void>){if(process.env.SOP_TRANSFORM_FILTER&&!new RegExp(process.env.SOP_TRANSFORM_FILTER).test(name))return;await fn();tests.push(name);console.log('PASS '+name);}
try {
 let url='';if(!offline){const{createServer}=await import('vite');const s=await createServer({root:ROOT,server:{host:'127.0.0.1',port:0}});await s.listen();url=requireLocalServerUrl(s,'TRANSFORM fixture');close=()=>s.close();}
 browser=await chromium.launch({headless:true,args:['--no-sandbox'],...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{})});
 const p=await browser.newPage({viewport:{width:740,height:1000}});p.on('pageerror',e=>errors.push(e.message));p.setDefaultTimeout(5000);p.setDefaultNavigationTimeout(30000);await p.emulateMedia({reducedMotion:'no-preference'});
 if(offline){await p.setContent(f.shell.replace('<link rel="stylesheet" href="./styles.css">',''));await p.addStyleTag({content:f.styles});await p.addScriptTag({content:f.bundle()});}else await p.goto(new URL('.test-output/transform/test.html',url).href);
 await p.waitForFunction(()=>typeof (window as any).mount==='function');
 const mount=async(id:string|string[],options={})=>p.evaluate(({ids,options})=>(window as any).mount(ids,options),{ids:typeof id==='string'?[id]:id,options});
 const marker=async()=>p.locator('.sop-choice').first().evaluate(e=>{const r=e as HTMLElement,t=r.querySelector(':scope > .sop-choice-list > [data-selected="true"]') as HTMLElement;return{x:parseFloat(r.style.getPropertyValue('--tr-x')),y:parseFloat(r.style.getPropertyValue('--tr-y')),w:parseFloat(r.style.getPropertyValue('--tr-w')),h:parseFloat(r.style.getPropertyValue('--tr-h')),tx:t.offsetLeft,ty:t.offsetTop,tw:t.offsetWidth,th:t.offsetHeight};});
 const aligned=async()=>{await p.waitForTimeout(1000);const m=await marker();for(const k of ['x','y','w','h'] as const)assert.ok(Math.abs(m[k]-m[('t'+k) as 'tx'|'ty'|'tw'|'th'])<1,JSON.stringify(m));};
 await run('32 selection designs commit immediately and move a visible, measured material plate',async()=>{
  for(const part of selections){await mount(part.id);const buttons=p.locator('.sop-choice-item');await buttons.last().click();assert.equal(await buttons.last().getAttribute('data-selected'),'true');assert.ok(await p.locator('.sop-choice-marker').isVisible(),part.id);await p.waitForTimeout(80);assert.ok(await p.locator('.sop-choice').evaluate(e=>parseFloat((e as HTMLElement).style.getPropertyValue('--tr-energy')))>0,part.id);await aligned();}
 });
 await run('horizontal Prism and Orbital segments do not show a decorative vertical scrollbar',async()=>{
  for(const id of ['prism-segments','orbital-segments']){
   await mount(id);const list=p.locator('.sop-choice-list');
   for(const index of [0,2]){
    await list.locator('.sop-choice-item').nth(index).click();await p.waitForTimeout(700);
    const state=await list.evaluate(el=>{const node=el as HTMLElement,css=getComputedStyle(node);return{overflowY:css.overflowY,gutter:node.offsetWidth-node.clientWidth-parseFloat(css.borderLeftWidth)-parseFloat(css.borderRightWidth)};});
    assert.equal(state.overflowY,'hidden',id);assert.ok(state.gutter<=1,`${id}: ${JSON.stringify(state)}`);
    assert.equal(await list.locator('.sop-choice-item').nth(index).getAttribute('data-selected'),'true');
   }
   const originalHeight=await list.evaluate(el=>el.clientHeight);
   await list.evaluate(el=>{const original=el.querySelector('.sop-choice-item')!;for(let i=0;i<4;i++){const copy=original.cloneNode(true) as HTMLElement;copy.dataset.choiceValue='extra-'+i;copy.dataset.selected='false';copy.querySelectorAll('[id]').forEach(node=>node.removeAttribute('id'));const input=copy.querySelector('input')!;input.value='extra-'+i;input.checked=false;copy.querySelector('.sop-choice-label')!.textContent='追加候補 '+i;el.append(copy);}});
   await p.evaluate(()=>(window as any).api.refresh());
   const wrapped=await list.evaluate(el=>({height:el.clientHeight,bottom:el.getBoundingClientRect().bottom,last:el.querySelector('.sop-choice-item:last-child')!.getBoundingClientRect().bottom}));
   assert.ok(wrapped.height>originalHeight&&wrapped.last<=wrapped.bottom+1,`${id}: ${JSON.stringify(wrapped)}`);
   await p.evaluate(()=>(window as any).api.setOrientation('vertical'));
   assert.equal(await list.evaluate(el=>getComputedStyle(el).overflowY),'visible',id+' vertical mode');
  }
 });
 await run('two, four and seven uneven options, wrapping, vertical and RTL use actual element bounds',async()=>{
  for(const id of ['aurora-tabs','prism-segments'])for(const count of [2,4,7]){await mount(id);await p.locator('.sop-choice').evaluate((e,count)=>{const w=window as any,list=e.querySelector(':scope > .sop-choice-list')!,items=[...list.querySelectorAll(':scope > .sop-choice-item')],panels=e.querySelector(':scope > .sop-choice-panels'),tmpl=items[0],pt=panels?.firstElementChild;for(const item of items)item.remove();panels?.replaceChildren();for(let i=0;i<count;i++){const t=tmpl.cloneNode(true) as HTMLElement;t.dataset.choiceValue='item-'+i;t.dataset.selected='false';t.querySelectorAll('[id]').forEach(n=>n.removeAttribute('id'));t.removeAttribute('id');t.querySelector('.sop-choice-label')!.textContent=i%2?'長い項目の名前 '+i:'Item '+i;const input=t.querySelector('input');if(input){input.value='item-'+i;input.checked=false;}list.append(t);if(panels&&pt){const panel=pt.cloneNode(true) as HTMLElement;panel.removeAttribute('id');panel.dataset.panelValue='item-'+i;panels.append(panel);}}w.api.refresh();},count);await p.locator('.sop-choice-item').last().click();await aligned();await p.evaluate(()=>(window as any).api.setOrientation('vertical'));await aligned();await p.locator('.sop-choice').evaluate(e=>e.setAttribute('dir','rtl'));await p.evaluate(()=>(window as any).api.setOrientation('horizontal'));await aligned();}
 });
 await run('tabs manual activation, disabled options and editable panel values remain native',async()=>{
  await mount('folio-tabs',{activation:'manual'});const items=p.locator('.sop-choice-item'),firstValue=await items.first().getAttribute('data-choice-value');await p.evaluate(v=>(window as any).api.setValue(v),firstValue);await items.first().focus();await p.keyboard.press('End');assert.equal(await items.first().getAttribute('aria-selected'),'true');await p.keyboard.press('Enter');assert.equal(await items.last().getAttribute('aria-selected'),'true');
  await p.locator('.sop-choice-panel').last().evaluate(e=>{const input=document.createElement('input');input.id='kept-memo';input.value='保存される入力';e.append(input);});await items.first().click();await items.last().click();assert.equal(await p.locator('#kept-memo').inputValue(),'保存される入力');await p.evaluate(()=>(window as any).api.setDisabled(true));await items.first().dispatchEvent('click');assert.equal(await items.last().getAttribute('aria-selected'),'true');
 });
 await run('controlled selection rejects mutations and preserves the committed material target',async()=>{
  for(const id of ['aurora-tabs','prism-segments']){await mount(id,{controlled:true,value:'choice-1'});await p.locator('.sop-choice-item').last().click();assert.equal(await p.evaluate(()=>(window as any).api.getValue()),'choice-1');await aligned();}
 });
 await run('native radios keep separate form payloads and reset each segment instance',async()=>{
  await mount(['mercury-segments','ceramic-segments']);const roots=p.locator('.sop-segments');const init=await p.evaluate(()=>(window as any).apis.map((c:any)=>c.getValue()));for(let i=0;i<2;i++)await roots.nth(i).locator('.sop-choice-item').last().click();const selected=await p.locator('.sop-segments input:checked').count();assert.equal(selected,2);await p.locator('#reset').click();await p.waitForTimeout(30);assert.deepEqual(await p.evaluate(()=>(window as any).apis.map((c:any)=>c.getValue())),init);
 });
 await run('selection markers settle after fast reversal, resize and nested different skins',async()=>{
  await mount('kinetic-tabs');await p.evaluate(async()=>{const c=(window as any).api;for(let i=0;i<8;i++){c.setValue(i%2?'choice-1':'choice-3');await new Promise(r=>setTimeout(r,20));}c.setValue('choice-2');});await aligned();
  await p.locator('.sop-choice-panel:not([hidden])').evaluate(e=>{const w=window as any,r=w.records.find((r:any)=>r.id==='capillary-segments'),div=document.createElement('div');div.innerHTML=r.markup;e.append(div);w.initAt(r.id,div.firstElementChild);});await p.locator('.sop-capillary-segments .sop-choice-item').last().click();assert.equal(await p.locator('.sop-kinetic-tabs').getAttribute('data-value'),'choice-2');await p.setViewportSize({width:450,height:1000});await aligned();await p.setViewportSize({width:740,height:1000});
 });
 await run('nested selection skins retain their own computed material instead of ancestor styles',async()=>{
  await mount('capillary-segments');const snapshot=await p.locator('.sop-transit-plate').evaluate(e=>{const s=getComputedStyle(e),b=getComputedStyle(e,'::before');return[s.backgroundImage,s.borderRadius,s.boxShadow,b.backgroundImage];});
  await mount('kinetic-tabs');await p.locator('.sop-choice-panel:not([hidden])').evaluate(e=>{const w=window as any,r=w.records.find((r:any)=>r.id==='capillary-segments'),box=document.createElement('div');box.innerHTML=r.markup;e.append(box);w.initAt(r.id,box.firstElementChild);});
  const nested=await p.locator('.sop-capillary-segments .sop-transit-plate').evaluate(e=>{const s=getComputedStyle(e),b=getComputedStyle(e,'::before');return[s.backgroundImage,s.borderRadius,s.boxShadow,b.backgroundImage];});assert.deepEqual(nested,snapshot);
 });
 await run('all 16 slider materials use native range inputs and change geometry when dragged',async()=>{
  for(const part of sliders){await mount(part.id,{range:false,min:0,max:100,step:1,value:20});const field=p.locator('input[type=range]').first(),before=await p.locator('.sop-drive-art').innerHTML();await field.focus();await p.keyboard.press('End');assert.equal(await field.inputValue(),'100');assert.match(await p.locator('[data-reading]').innerText(),/100/);await p.waitForTimeout(70);assert.notEqual(await p.locator('.sop-drive-art').innerHTML(),before,part.id);assert.ok(await p.locator('.sop-drive-art').evaluate(e=>e.clientWidth>200),part.id);}
 });
 await run('dual range thumbs share one scale, clamp crossing, and follow rail pointer capture',async()=>{
  await mount('tide-range',{range:true,min:0,max:100,step:1,value:[20,80]});const fields=p.locator('input[type=range]');for(let i=0;i<2;i++){assert.equal(await fields.nth(i).getAttribute('min'),'0');assert.equal(await fields.nth(i).getAttribute('max'),'100');}await fields.first().focus();await p.keyboard.press('End');assert.deepEqual(await p.evaluate(()=>(window as any).api.getData()),[80,80]);await fields.last().focus();await p.keyboard.press('Home');assert.deepEqual(await p.evaluate(()=>(window as any).api.getData()),[80,80]);
  await p.evaluate(()=>(window as any).api.setData([20,80]));const rect=(await p.locator('.ff-slider').boundingBox())!;await p.mouse.move(rect.x+rect.width*.3,rect.y+rect.height*.25);await p.mouse.down();await p.mouse.move(rect.x+rect.width*.43,rect.y+rect.height*.25,{steps:10});await p.mouse.up();const values=await p.evaluate(()=>(window as any).api.getData());assert.ok(values[0]>30&&values[0]<55,JSON.stringify(values));assert.equal(values[1],80);
 });
 await run('slider configuration, negative decimals, readonly, form reset and controlled values stay in sync',async()=>{
  await mount('mercury-range',{range:false,min:-2,max:2,step:.25,value:.5,unit:'V',name:'level',defaultValue:0});await p.locator('input[type=range]').first().focus();await p.keyboard.press('ArrowRight');assert.equal(await p.evaluate(()=>(window as any).api.getData()),.75);assert.equal(await p.evaluate(()=>new FormData(document.querySelector('form')!).get('level')),'0.75');await p.evaluate(()=>(window as any).api.updateFoundation({min:-10,max:10,step:.5,unit:'dB',value:2}));assert.equal(await p.locator('[data-min]').textContent(),'-10dB');assert.equal(await p.locator('[data-max]').textContent(),'10dB');assert.match(await p.locator('[data-reading]').textContent()??'',/2dB/);await p.evaluate(()=>(window as any).api.updateFoundation({readOnly:true}));assert.ok(await p.locator('input[type=range]').first().isDisabled());await p.locator('input[type=range]').first().evaluate((e:HTMLInputElement)=>{e.value='9';e.dispatchEvent(new Event('input',{bubbles:true}));});assert.equal(await p.evaluate(()=>(window as any).api.getData()),2);await p.evaluate(()=>(window as any).api.updateFoundation({readOnly:false}));await p.locator('#reset').click();assert.equal(await p.locator('input[type=range]').first().inputValue(),'0');
  await mount('nixie-range',{controlled:true,range:false,value:30});await p.locator('input[type=range]').first().focus();await p.keyboard.press('End');assert.equal(await p.locator('input[type=range]').first().inputValue(),'30');
 });
 await run('RTL sliders mirror both the exact fill and the decorative geometry',async()=>{
  await mount('prism-range',{range:true,value:[20,70]});await p.locator('.sop-drive-range').evaluate(e=>e.setAttribute('dir','rtl'));await p.evaluate(()=>(window as any).api.updateFoundation({value:[20,70]}));const result=await p.locator('.sop-drive-range').evaluate(e=>({start:parseFloat((e as HTMLElement).style.getPropertyValue('--ff-start')),end:parseFloat((e as HTMLElement).style.getPropertyValue('--ff-end')),transform:getComputedStyle(e.querySelector('.sop-drive-art')!).transform}));assert.ok(Math.abs(result.start-30)<.01&&Math.abs(result.end-80)<.01);assert.match(result.transform,/-1/);
 });
 await run('all 16 popup entrances use the real dialog, animate then settle, and return focus',async()=>{
  for(const part of popups){await mount(part.id);await p.locator('.sop-popup-trigger').click();assert.ok(await p.locator('dialog').evaluate((e:HTMLDialogElement)=>e.open));assert.ok(await p.locator('dialog').evaluate(e=>e.getAnimations({subtree:true}).length)>0,part.id);await p.waitForTimeout(1050);assert.ok(await p.locator('dialog').evaluate(e=>{const t=getComputedStyle(e).transform;return t==='none'||new DOMMatrixReadOnly(t).isIdentity;}),part.id);await p.keyboard.press('Escape');await p.locator('dialog').waitFor({state:'hidden',timeout:2500});assert.ok(await p.locator('.sop-popup-trigger').evaluate(e=>e===document.activeElement),part.id+' focus return');}
 });
 await run('popup input and focus survive reopen; native content is not cloned',async()=>{
  await mount('folio-window');await p.locator('.sop-popup-trigger').click();const dialog=p.locator('dialog');await dialog.evaluate(e=>{const input=document.createElement('input');input.id='popup-memo';input.value='Write';e.querySelector('.sop-popup-body')!.append(input);});await p.waitForTimeout(900);await p.locator('#popup-memo').fill('この内容を保持');for(let i=0;i<20;i++){await p.keyboard.press(i%2?'Shift+Tab':'Tab');assert.ok(await dialog.evaluate(e=>e.contains(document.activeElement)));}await p.keyboard.press('Escape');await p.waitForTimeout(220);await p.locator('.sop-popup-trigger').click();await p.waitForTimeout(900);assert.equal(await p.locator('#popup-memo').inputValue(),'この内容を保持');assert.equal(await p.locator('#popup-memo').count(),1);
 });
 await run('popup close policies, rapid reversal and stacked modals preserve top-layer locking',async()=>{
  await mount('titanium-dialog',{closeOnEscape:false,closeOnBackdrop:false});await p.locator('.sop-popup-trigger').click();await p.keyboard.press('Escape');assert.ok(await p.locator('dialog').evaluate((e:HTMLDialogElement)=>e.open));await p.evaluate(()=>(window as any).api.setOpen(false));await p.waitForTimeout(60);await p.evaluate(()=>(window as any).api.setOpen(true));await p.waitForTimeout(250);assert.ok(await p.locator('dialog').evaluate((e:HTMLDialogElement)=>e.open));
  await mount(['aurora-window','opal-window']);await p.locator('.sop-popup-trigger').first().click();await p.evaluate(()=>(window as any).apis[1].setOpen(true));assert.equal(await p.locator('dialog[open]').count(),2);await p.keyboard.press('Escape');await p.waitForTimeout(220);assert.equal(await p.locator('dialog[open]').count(),1);assert.equal(await p.evaluate(()=>document.documentElement.style.overflow),'hidden');await p.evaluate(()=>(window as any).apis[0].setOpen(false));await p.waitForTimeout(220);assert.equal(await p.evaluate(()=>document.documentElement.style.overflow),'');
 });
 await run('all 64 revised designs fit 320 / 390 / 768 and long Japanese labels',async()=>{
  for(const width of [320,390,768]){await p.setViewportSize({width,height:1040});for(const part of revised){await mount(part.id);if(part.category==='popups'){await p.locator('.sop-popup-trigger').click();await p.waitForTimeout(80);assert.ok(await p.locator('dialog').evaluate(e=>e.scrollWidth<=e.clientWidth+2),part.id+':dialog '+width);}else if(part.category==='sliders'){await p.locator('[data-ff-label]').evaluate(e=>e.textContent='幅の狭い設定画面でも使える長い日本語ラベル');}else{await p.locator('.sop-choice-label').first().evaluate(e=>e.textContent='長い日本語の項目名を使用します');}assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2),part.id+': '+width);}}
 });
 await run('reduced motion goes to final states and forced colors keeps native controls legible',async()=>{
  await p.setViewportSize({width:740,height:1000});await p.emulateMedia({reducedMotion:'reduce'});for(const part of revised){await mount(part.id);if(part.category==='popups')await p.locator('.sop-popup-trigger').click();else if(part.category==='sliders')await p.evaluate(()=>(window as any).api.setData(40));else await p.locator('.sop-choice-item').last().click();await p.waitForTimeout(50);assert.equal(await p.evaluate(()=>(window as any).activeFrames.size),0,part.id);assert.equal(await p.evaluate(()=>document.getAnimations().filter(a=>a.playState==='running').length),0,part.id);}
  await p.emulateMedia({forcedColors:'active',reducedMotion:'reduce'});await mount('aurora-tabs');assert.ok(await p.locator('.sop-transit-plate').isHidden());await p.locator('.sop-choice-item').last().click();await mount('tide-range',{range:false});assert.ok(await p.locator('.sop-drive-art').isHidden());await p.locator('input[type=range]').first().focus();await p.keyboard.press('End');assert.equal(await p.locator('input[type=range]').first().inputValue(),'100');await p.emulateMedia({forcedColors:'none',reducedMotion:'no-preference'});
 });
 await run('idle and teardown leave no presentation RAF, duplicate IDs or global locks',async()=>{
  for(const id of ['aurora-tabs','ceramic-segments','tide-range','aurora-window']){await mount([id,id]);if(id.endsWith('range'))await p.evaluate(()=>(window as any).apis.forEach((a:any)=>a.setData([30,65])));else if(!id.endsWith('window'))await p.locator('.sop-choice-item').last().click();else await p.locator('.sop-popup-trigger').first().click();await p.waitForTimeout(1600);assert.equal(await p.evaluate(()=>(window as any).activeFrames.size),0,id);const ids=await p.locator('[id]').evaluateAll(es=>es.map(e=>e.id));assert.equal(ids.length,new Set(ids).size,id);await p.evaluate(()=>(window as any).unmount());await p.waitForTimeout(30);assert.equal(await p.evaluate(()=>(window as any).activeFrames.size),0);assert.equal(await p.evaluate(()=>document.documentElement.style.overflow),'');}
 });
 assert.deepEqual(errors,[]);console.log('TRANSFORM checks: '+tests.length+' passed');
} finally {fs.writeFileSync(path.join(f.out,'browser-results.json'),JSON.stringify({mode:offline?'explicit offline fixture / real Chromium, not Vite':'real Vite HTTP',passed:tests.length,tests,errors},null,2)+'\n');await browser?.close();await close?.();}
