import {galleryReady} from './gallery-ready.ts';
/** The real catalogue and inspector, with explicit offline transport only when requested. */
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createRequire}from'node:module';import type{Browser}from'playwright';
import {ROOT,buildCatalog,FORMATS}from'../scripts/catalog.ts';import{offlineFiles}from'./offline-fixture.ts';import{getDelivery,buildPrompt}from'../src/catalog/delivery.ts';import{requireLocalServerUrl}from'./vite-url.ts';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_PATH??'playwright') as typeof import('playwright');const data=buildCatalog(),offline=process.env.SOP_TEST_MODE==='offline',out=path.join(ROOT,'.test-output/transform-gallery');fs.mkdirSync(out,{recursive:true});const results:string[]=[],errors:string[]=[];let browser:Browser|undefined,close:(()=>Promise<void>)|undefined;
async function run(name:string,fn:()=>Promise<void>){await fn();results.push(name);console.log('PASS '+name);}
try{
 let url='';if(!offline){const{createServer}=await import('vite'),s=await createServer({root:ROOT,server:{host:'127.0.0.1',port:0}});await s.listen();url=requireLocalServerUrl(s,'TRANSFORM gallery');close=()=>s.close();}
 browser=await chromium.launch({headless:true,args:['--no-sandbox'],...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{})});const p=await browser.newPage({viewport:{width:1440,height:1000}});p.setDefaultTimeout(8000);p.on('pageerror',e=>errors.push(e.message));
 if(offline){const f=offlineFiles(data);await p.setContent(f.get('/index.html')!.replace(/<script[^>]*>[\s\S]*?<\/script>/g,'').replace(/<link[^>]*>/g,''));await p.addStyleTag({content:f.get('/test-styles.css')!});for(const v of ['prism','jszip'])await p.addScriptTag({content:fs.readFileSync(path.join(ROOT,'public/vendor/'+v+'.js'),'utf8')});await p.addScriptTag({content:f.get('/test-app.js')!});}else await p.goto(url);
 await run('four categories retain 24 items, A16 / B8, and revised parts operate in the gallery',async()=>{
  for(const category of ['tabs','segments','popups','sliders']){await p.locator(`[data-category="${category}"]`).click();await galleryReady(p,true);assert.equal(await p.locator('[data-part]').count(),24);await p.locator('[data-design-filter="A"]').click();await galleryReady(p,true);assert.equal(await p.locator('[data-part]').count(),16);for(const part of data.parts.filter(part=>part.category===category&&part.designType==='A')){const card=p.locator(`[data-part="${part.id}"]`);if(category==='tabs'||category==='segments'){await card.locator('.sop-choice-item').last().click();assert.equal(await card.locator('.sop-choice-item').last().getAttribute('data-selected'),'true');}else if(category==='sliders'){await card.locator('input[type=range]').first().focus();await p.keyboard.press('ArrowRight');}else{await card.locator('.sop-popup-trigger').click();assert.ok(await card.locator('dialog').isVisible());await p.keyboard.press('Escape');await p.waitForTimeout(230);}assert.equal(await p.locator('#part-details[open]').count(),0);}await p.locator('[data-design-filter="B"]').click();await galleryReady(p,true);assert.equal(await p.locator('[data-part]').count(),8);await p.locator('[data-design-filter="all"]').click();await galleryReady(p,true);}
 });
 await run('actual displayed source files and prompts match both exported layouts / all formats',async()=>{
  let checked=0;for(const id of ['aurora-tabs','mercury-segments','folio-window','tide-range']){const part=data.parts.find(p=>p.id===id)!;await p.locator(`[data-category="${part.category}"]`).click();await galleryReady(p,true);await p.locator(`[data-open="${id}"]`).click();await galleryReady(p,true);const d=p.locator('#part-details');for(const layout of ['portable','original'] as const){await d.locator('#export-layout').selectOption(layout);for(const format of FORMATS){await d.locator(`[data-format="${format}"]`).click();const delivery=getDelivery(part,format,layout);for(const f of delivery.files){await d.locator(`[data-file="${f.name}"]`).evaluate(e=>(e as HTMLButtonElement).click());assert.deepEqual(await d.locator('.editor .line-code').allTextContents(),f.code.split('\n').map(line=>line||' '),`${id}/${layout}/${format}/${f.name}`);checked++;}await d.locator('[data-detail-tab="prompt"]').click();assert.equal(await d.locator('#prompt-text').inputValue(),buildPrompt(part,format,layout));await d.locator('[data-detail-tab="code"]').click();}}await d.locator('.close-detail').click();}console.log('Source files compared:',checked);
 });
 await run('selection inspector dynamic option counts retain transformed markers and keyboard state',async()=>{
  await p.locator('[data-category="tabs"]').click();await galleryReady(p,true);await p.locator('[data-open="aurora-tabs"]').click();await galleryReady(p,true);const d=p.locator('#part-details');for(const n of [2,4,7,3]){await d.locator(`[data-selection-count="${n}"]`).click();assert.equal(await d.locator('.sop-choice-item').count(),n);await d.locator('.sop-choice-item').last().click();assert.equal(await d.locator('[data-selection-kind]').getAttribute('data-value'),`choice-${n}`);assert.ok(await d.locator('.sop-choice-marker').isVisible());}await p.screenshot({path:path.join(out,'detail.png')});await d.locator('.close-detail').click();
 });
 await run('popup opens above the inspector, closes only itself and restores inspector focus',async()=>{
  await p.locator('[data-category="popups"]').click();await galleryReady(p,true);await p.locator('[data-open="folio-window"]').click();await galleryReady(p,true);const d=p.locator('#part-details');await d.locator('.sop-popup-trigger').click();assert.equal(await p.locator('dialog[open]').count(),2);await p.keyboard.press('Escape');await p.waitForTimeout(230);assert.equal(await p.locator('dialog[open]').count(),1);assert.ok(await d.locator('.sop-popup-trigger').evaluate(e=>e===document.activeElement));await d.locator('.close-detail').click();
 });
 await run('320 / 390 / 768 inspector views keep the code editor and real controls reachable',async()=>{
  for(const width of [320,390,768]){await p.setViewportSize({width,height:1040});for(const id of ['aurora-tabs','mercury-segments','folio-window','tide-range']){const part=data.parts.find(p=>p.id===id)!;await p.locator(`[data-category="${part.category}"]`).click();await galleryReady(p,true);await p.locator(`[data-open="${id}"]`).click();await galleryReady(p,true);const d=p.locator('#part-details');assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2));assert.ok(await d.locator('.download-file').count());await d.locator('.copy-file').scrollIntoViewIfNeeded();assert.ok(await d.locator('.copy-file').isVisible());if(width===390&&id==='aurora-tabs')await p.screenshot({path:path.join(out,'mobile-390.png')});await d.locator('.close-detail').click();}}
 });
 assert.deepEqual(errors,[]);console.log('TRANSFORM gallery: '+results.length+' checks passed');
}finally{fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({mode:offline?'real gallery through explicit offline document, not Vite':'real Vite HTTP',passed:results.length,tests:results,errors},null,2)+'\n');await browser?.close();await close?.();}
