/** Rebuilt v4.10 components on real Chromium; the fixture is not a Vite production build. */
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import{createRequire}from'node:module';
import {wayfinderFixture} from './wayfinder-fixture.ts';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_PATH??'playwright') as typeof import('playwright');
const f=wayfinderFixture(),targets=f.records.filter(p=>p.tags.includes('WAYFINDER'));
const results:string[]=[],errors:string[]=[];
const browser=await chromium.launch({headless:true,args:['--no-sandbox'],...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{})});
const p=await browser.newPage({viewport:{width:760,height:1040}});p.setDefaultTimeout(6000);p.on('pageerror',e=>errors.push(e.message));
async function run(name:string,fn:()=>Promise<void>){await fn();results.push(name);console.log('PASS '+name);}
const mount=async(id:string,options={})=>p.evaluate(({id,options})=>(window as any).mount([id],options),{id,options});
const update=async(options:Record<string,unknown>)=>p.evaluate(o=>(window as any).api.updateFoundation(o),options);
const data=()=>p.evaluate(()=>(window as any).api.getData());
const items=[{value:'workspace',label:'Workspace',href:'#workspace'},{value:'library',label:'Library',href:'#library'},{value:'design',label:'Design',href:'#design'},{value:'details',label:'Details'}];
try{
 await p.setContent(f.shell.replace(/<link[^>]*>/g,''));await p.addStyleTag({content:f.styles});await p.addScriptTag({content:f.bundle()});
 await run('all 23 targets mount independent native controls without page errors',async()=>{for(const t of targets){await mount(t.id);assert.equal(await p.locator('[data-foundation-mounted=true]').count(),1);if(t.category==='numbers')assert.equal(await p.locator('[data-number]').count(),1);else assert.equal(await p.locator('[aria-current=page]').count(),1);}});
 await run('ten breadcrumb designs keep URLs, content and active-route motion distinct',async()=>{for(const t of targets.filter(t=>t.category==='breadcrumbs')){await p.mouse.move(0,0);await mount(t.id,{items});await p.waitForTimeout(70);assert.equal(await p.locator('a[href="#library"]').innerText(),'Library');const before=await p.locator('.wf-route circle').getAttribute('cx');await p.locator('a[href="#workspace"]').hover();await p.waitForTimeout(60);assert.notEqual(await p.locator('.wf-route circle').getAttribute('cx'),before);assert.equal(await p.locator('[aria-current=page]').innerText(),'Details');}});
 await run('collapsed ancestors open in a real overlay, Escape returns focus, and links are not replaced',async()=>{await mount('blueprint-trail',{items:[...items.slice(0,3),{value:'extra',label:'Assets',href:'#assets'},{value:'last',label:'Last'}]});const more=p.locator('[data-crumb-more]');await more.click();assert.ok(await p.locator('.wf-crumb-menu a[href="#library"]').isVisible());await p.keyboard.press('Escape');assert.ok(await p.locator('.wf-crumb-menu').isHidden());assert.ok(await more.evaluate(e=>e===document.activeElement));await more.click();await update({label:'Updated trail'});assert.ok(await p.locator('.wf-crumb-menu').isHidden());await p.waitForFunction(()=>document.activeElement?.hasAttribute('data-crumb-more'));});
 await run('ordinary native anchor click is not intercepted and disabled items cannot navigate',async()=>{await mount('folio-trail',{items});await p.locator('a[href="#library"]').click();assert.ok(p.url().endsWith('#library'));await mount('folio-trail',{items,disabled:true});assert.equal(await p.locator('.wf-trail a[href]').count(),0);});
 await run('all thirteen number layouts adjust immediate committed values, bounds and scale',async()=>{for(const t of targets.filter(t=>t.category==='numbers')){await mount(t.id,{defaultValue:3,min:0,max:24,step:1,unit:'kg'});await p.locator('[data-adjust="1"]').click();assert.equal(await data(),4);assert.equal(await p.locator('[data-number]').inputValue(),'4');assert.equal(await p.locator('[data-unit]').innerText(),'kg');await update({min:-10,max:10,step:.25,unit:'m'});assert.equal(await p.locator('[data-wf-min]').innerText(),'-10');assert.equal(await p.locator('[data-wf-max]').innerText(),'10');assert.equal(await p.locator('[data-unit]').innerText(),'m');}});
 await run('native direct editing supports decimals, empty input, invalid draft, arrows, and form reset',async()=>{await mount('blueprint-stepper',{defaultValue:2,min:-10,max:10,step:.25,name:'amount'});const input=p.locator('[data-number]');await input.fill('3.25');await input.press('Enter');assert.equal(await data(),3.25);await input.press('ArrowUp');assert.equal(await data(),3.5);await input.fill('');await p.locator('#outside').click();assert.equal(await data(),null);await input.fill('oops');await input.press('Enter');assert.equal(await input.getAttribute('aria-invalid'),'true');await input.press('Escape');assert.equal(await input.inputValue(),'');await p.locator('#reset').click();await p.waitForTimeout(30);assert.equal(await input.inputValue(),'2');assert.equal(await p.locator('form').evaluate((e:HTMLFormElement)=>new FormData(e).get('amount')),'2');});
 await run('controlled values can be declined; readonly and disabled prevent change',async()=>{await mount('mercury-stepper',{value:5,controlled:true});await p.locator('[data-adjust="1"]').click();assert.equal(await data(),5);assert.equal(await p.locator('[data-number]').inputValue(),'5');await update({readOnly:true});assert.ok(await p.locator('[data-adjust="1"]').isDisabled());assert.ok(await p.locator('[data-number]').evaluate((e:HTMLInputElement)=>e.readOnly));await update({readOnly:false,disabled:true});assert.ok(await p.locator('[data-number]').isDisabled());});
 await run('IME composition and uncommitted native draft survive unrelated options updates',async()=>{await mount('tide-stepper');const input=p.locator('[data-number]');await input.focus();await input.fill('-');await update({unit:'kg'});assert.equal(await input.inputValue(),'-');await input.evaluate(e=>e.dispatchEvent(new CompositionEvent('compositionstart',{bubbles:true})));await input.press('Enter');assert.equal(await input.inputValue(),'-');await input.evaluate(e=>e.dispatchEvent(new CompositionEvent('compositionend',{bubbles:true,data:'1'})));await input.fill('4');await input.press('Enter');assert.equal(await data(),4);});
 await run('23 components fit 320/390/768px and long Japanese text without page overflow',async()=>{for(const width of [320,390,768]){await p.setViewportSize({width,height:1040});for(const t of targets){await mount(t.id,{label:'長い日本語の項目名も実際の画面で確認します',items:items.map((x,i)=>({...x,label:'資料の階層と表示内容を整理する長いラベル'+i})),unit:'単位'});await p.waitForTimeout(25);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2),t.id+' '+width);}}await p.setViewportSize({width:760,height:1040});});
 await run('reduced motion, forced colors and teardown leave accessible content without animation residue',async()=>{await p.emulateMedia({reducedMotion:'reduce'});for(const t of targets){await mount(t.id,{items});if(t.category==='numbers')await p.locator('[data-adjust="1"]').click();else await p.locator('.wf-trail a').first().hover();await p.waitForTimeout(50);assert.equal(await p.evaluate(()=>(window as any).activeFrames.size),0);await p.evaluate(()=>(window as any).unmount());assert.equal(await p.evaluate(()=>document.getAnimations().filter(a=>a.playState==='running').length),0);}await p.emulateMedia({reducedMotion:'reduce',forcedColors:'active'});await mount('prism-stepper');assert.ok(await p.locator('[data-number]').isVisible());await mount('folio-trail',{items});assert.ok(await p.locator('[aria-current=page]').isVisible());await p.emulateMedia({reducedMotion:'no-preference',forcedColors:'none'});});
 await run('plain B controls remain mounted on the old controller and style',async()=>{for(const t of f.records.filter(t=>t.designType==='B')){await mount(t.id);assert.equal(await p.locator('.sop-wayfinder').count(),0);assert.equal(await p.locator('[data-foundation-mounted=true]').count(),1);}});
 assert.deepEqual(errors,[]);
 // Screenshot of the rebuilt source; do not re-use pictures of the lost build as evidence.
 await p.evaluate(()=>document.body.dataset.capture='true');
 fs.mkdirSync(path.join(f.out,'captures'),{recursive:true});
 for(const t of targets){await mount(t.id,{items,value:t.category==='numbers'?8:null});await p.waitForTimeout(120);await p.locator('section[data-sample]').screenshot({path:path.join(f.out,'captures',t.id+'.png')});}
 console.log(`${results.length} checks passed (real Chromium, compiled fixture, not Vite).`);
}finally{fs.writeFileSync(path.join(f.out,'results.json'),JSON.stringify({passed:results.length,results,errors,mode:'real Chromium / compiled source fixture; not Vite'},null,2));await browser.close();}
