import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createRequire} from 'node:module';
import type {Browser,Page} from 'playwright';import {workbenchFixture} from './workbench-fixture.ts';import {ROOT} from '../scripts/catalog.ts';import {requireLocalServerUrl} from './vite-url.ts';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_PATH??'playwright') as typeof import('playwright');
const offline=process.env.SOP_TEST_MODE==='offline',f=workbenchFixture(),passed:string[]=[],errors:string[]=[];
let browser:Browser|undefined,closeServer:(()=>Promise<void>)|undefined;
async function run(name:string,fn:()=>Promise<void>){await fn();passed.push(name);console.log('PASS '+name);}
try{
 let url='';if(!offline){const {createServer}=await import('vite');const s=await createServer({root:ROOT,configFile:false,server:{host:'127.0.0.1',port:0,hmr:false,watch:null}});await s.listen();url=requireLocalServerUrl(s,'Workbench');closeServer=()=>s.close();}
 browser=await chromium.launch({headless:true,args:['--no-sandbox'],...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{})});
 const p=await browser.newPage({viewport:{width:720,height:950}});p.setDefaultTimeout(5000);p.on('pageerror',e=>errors.push(e.message));
 if(offline){await p.setContent(f.shell.replace('<link rel="stylesheet" href="./styles.css">',''));await p.addStyleTag({content:f.styles});await p.addScriptTag({content:f.bundle()});}else await p.goto(new URL('.test-output/workbench/test.html',url).href,{waitUntil:'domcontentloaded',timeout:120000});
 const mount=async(id:string|string[],options:Record<string,unknown>={})=>{await p.evaluate(([ids,o])=>(window as any).mount(ids,o),[typeof id==='string'?[id]:id,options]);await p.waitForTimeout(20);};
 const state=()=>p.evaluate(()=>(window as any).api.getState());
 await run('88 actual skins mount independently with public API and without page errors',async()=>{for(const r of f.records){await mount(r.id);assert.equal(await p.locator('#host .sop-wb').count(),1,r.id);assert.ok(await state());}});
 await run('Search query, filter, keyboard, submit, clear and native form reset',async()=>{await mount('parallax-search',{name:'query'});const input=p.locator('.wb-search-input');await input.fill('design');assert.equal((await state()).results,1);await input.press('ArrowDown');assert.ok(await input.getAttribute('aria-activedescendant'));await input.press('Enter');assert.equal((await state()).open,false);await input.fill('');await p.locator('[data-filter=settings]').click();assert.equal((await state()).results,2);await input.fill('workspace');assert.equal((await state()).results,1);await p.locator('.wb-search-clear').click();assert.equal(await input.inputValue(),'');await input.fill('sample');assert.equal(await p.evaluate(()=>new FormData(document.querySelector('form')!).get('query')),'sample');await p.locator('#reset').click();assert.equal((await state()).query,'');});
 await run('Search async aborts older requests and ignores stale success and failure',async()=>{await mount('lagoon-search',{debounceMs:0});await p.evaluate(()=>{(window as any).jobs=[];(window as any).api.update({search:(q:string,_f:string,signal:AbortSignal)=>new Promise((resolve,reject)=>(window as any).jobs.push({q,signal,resolve,reject}))});});const input=p.locator('.wb-search-input');await input.fill('first');await p.waitForFunction(()=>(window as any).jobs.some((x:any)=>x.q==='first'));await input.fill('second');await p.waitForFunction(()=>(window as any).jobs.some((x:any)=>x.q==='second'));assert.equal(await p.evaluate(()=>(window as any).jobs.find((j:any)=>j.q==='first').signal.aborted),true);await p.evaluate(()=>{(window as any).jobs.find((j:any)=>j.q==='second').resolve([{id:'second',label:'second'}]);});await p.waitForTimeout(30);await p.evaluate(()=>(window as any).jobs.find((j:any)=>j.q==='first').resolve([{id:'first',label:'first'}]));assert.equal(await p.locator('[data-result]').getAttribute('data-result'),'second');});
 await run('Search composition does not execute, unsafe URLs do not navigate, custom content stays literal',async()=>{await mount('essential-searchbar',{items:[{id:'literal',label:'<b>日本語</b>',href:'javascript:alert(1)'},{id:'off',label:'無効',disabled:true}],filters:[]});const input=p.locator('.wb-search-input');await input.focus();assert.equal(await p.locator('[data-result=literal]').evaluate(e=>e.tagName),'BUTTON');assert.equal(await p.locator('[data-result=literal] strong').innerText(),'<b>日本語</b>');await p.evaluate(()=>{(window as any).submitted=0;(window as any).api.update({onSubmit:()=>{(window as any).submitted++}});document.querySelector('input')!.dispatchEvent(new CompositionEvent('compositionstart',{bubbles:true}));});await input.press('Enter');assert.equal(await p.evaluate(()=>(window as any).submitted),0);await input.dispatchEvent('compositionend');await p.evaluate(()=>(window as any).api.update({query:'fixed'}));await input.fill('declined');assert.equal((await state()).query,'fixed');});
 await run('Search schema updates preserve native editing, owned focus and semantic keyboard selection',async()=>{
  const items=[{id:'a',label:'Design',group:'docs'},{id:'off',label:'Disabled',group:'docs',disabled:true},{id:'b',label:'Workspace',group:'settings'}],filters=[{id:'all',label:'All'},{id:'docs',label:'Documents'},{id:'settings',label:'Settings'}];
  await mount('essential-searchbar',{items,filters,defaultFilter:'all',name:'nativeQuery'});const input=p.locator('.wb-search-input'),docs=p.locator('[data-filter=docs]');
  await docs.focus();await p.evaluate(filters=>(window as any).api.update({filters:filters.map(f=>({...f,label:f.label+' updated'}))}),filters);assert.equal(await docs.evaluate(e=>e===document.activeElement),true);
  await input.focus();await p.locator('[data-result=a]').focus();await p.evaluate(()=>(window as any).api.update({label:'New label'}));assert.equal(await p.locator('[data-result=a]').evaluate(e=>e===document.activeElement),true);
  await input.focus();await input.press('ArrowDown');await p.evaluate(items=>(window as any).api.update({items:[items[2],items[1],items[0]]}),items);assert.equal(await input.evaluate(e=>document.getElementById(e.getAttribute('aria-activedescendant')!)?.dataset.result),'a');
  const original=await input.elementHandle();await input.fill('native');await input.press('End');await p.keyboard.insertText(' edited');await input.evaluate(e=>(e as HTMLInputElement).setSelectionRange(2,5));await p.evaluate(()=>(window as any).api.update({placeholder:'New hint'}));assert.equal(await input.evaluate((e,old)=>e===old,original),true);assert.deepEqual(await input.evaluate(e=>[(e as HTMLInputElement).selectionStart,(e as HTMLInputElement).selectionEnd]),[2,5]);await input.press('Control+z');assert.equal(await input.inputValue(),'native');assert.equal(await p.evaluate(()=>new FormData(document.querySelector('form')!).get('nativeQuery')),'native');
  await input.fill('');await docs.click();await p.evaluate(filters=>(window as any).api.update({filters:[filters[0],filters[2]]}),filters);assert.equal((await state()).filter,'all');assert.equal(await p.locator('[data-filter=all]').evaluate(e=>e===document.activeElement),true);
  await p.locator('#outside').focus();await p.evaluate(items=>(window as any).api.update({items}),items);assert.equal(await p.locator('#outside').evaluate(e=>e===document.activeElement),true);
  await p.setViewportSize({width:320,height:950});await input.focus();await input.press('ArrowDown');await input.press('Enter');const announcement=await p.locator('.wb-search-status').evaluate(e=>{const r=e.getBoundingClientRect(),root=e.closest('.sop-wb')!;return {position:getComputedStyle(e).position,width:r.width,height:r.height,overflow:root.scrollWidth-root.clientWidth,text:e.textContent};});assert.equal(announcement.position,'absolute');assert.ok(announcement.width<=1&&announcement.height<=1);assert.ok(announcement.overflow<=1);assert.ok(announcement.text);await p.setViewportSize({width:720,height:950});
 });
 await run('Search IME Enter preserves the native form and destroyed APIs retain their last state',async()=>{
  await mount('essential-searchbar',{name:'q'});await p.evaluate(()=>{(window as any).nativeSubmits=0;(window as any).searchSubmits=0;document.querySelector('form')!.addEventListener('submit',e=>{e.preventDefault();(window as any).nativeSubmits++},{once:true});(window as any).api.update({onSubmit:()=>(window as any).searchSubmits++});});
  const input=p.locator('.wb-search-input');await input.focus();await input.dispatchEvent('compositionstart');await input.fill('未確定');await input.press('Enter');assert.equal(await p.evaluate(()=>(window as any).nativeSubmits),0);assert.equal(await p.evaluate(()=>(window as any).searchSubmits),0);await input.dispatchEvent('compositionend');assert.equal((await state()).query,'未確定');
  await p.evaluate(()=>(window as any).api.destroy());const dead=await state();await p.evaluate(()=>{(window as any).api.reset();(window as any).api.update({query:'changed'});(window as any).api.close();(window as any).api.open();});assert.deepEqual(await state(),dead);
 });
 await run('Command palette drill-down, query, keyboard execute, Escape and focus return',async()=>{await mount('aperture-command');const launch=p.locator('.wb-command-launch');await launch.click();await p.locator('[data-command=view]').click();assert.deepEqual((await state()).path,['view']);await p.locator('.wb-command-input').press('Backspace');assert.deepEqual((await state()).path,[]);await p.locator('.wb-command-input').fill('新しい');await p.locator('.wb-command-input').press('Enter');assert.equal((await state()).open,false);assert.equal((await state()).lastCommand,'create');assert.equal(await launch.evaluate(e=>e===document.activeElement),true);await launch.click();await p.keyboard.press('Escape');assert.equal((await state()).open,false);assert.equal(await p.evaluate(()=>document.documentElement.style.overflow),'');});
 await run('Command async execution blocks duplicates, surfaces failures and cancels stale work',async()=>{await mount('deck-command');await p.evaluate(()=>{(window as any).calls=0;(window as any).api.update({onExecute:(_i:any,signal:AbortSignal)=>new Promise((resolve,reject)=>{(window as any).calls++;(window as any).execution={resolve,reject,signal};})});(window as any).api.open();});await p.locator('[data-command=create]').click();assert.equal((await state()).busy,true);assert.equal(await p.locator('.wb-command-input').getAttribute('readonly'),'');await p.locator('.wb-command-input').press('Enter');assert.equal(await p.evaluate(()=>(window as any).calls),1);await p.evaluate(()=>(window as any).execution.reject(Error('接続できません')));await p.waitForTimeout(30);assert.match((await state()).error,/接続/);await p.locator('[data-command=create]').click();await p.keyboard.press('Escape');assert.ok(await p.evaluate(()=>(window as any).execution.signal.aborted));await p.evaluate(()=>(window as any).execution.resolve());assert.equal((await state()).open,false);});
 await run('Ctrl+K is opt-in globally; multiple palettes dispatch only one, controlled open may decline',async()=>{await mount(['essential-command','light-command']);await p.locator('#outside').focus();await p.keyboard.press('Control+k');assert.equal(await p.locator('dialog[open]').count(),0);await p.evaluate(()=>(window as any).apis[1].update({hotkey:true}));await p.keyboard.press('Control+k');assert.equal(await p.locator('dialog[open]').count(),1);await p.keyboard.press('Escape');await mount('compact-command',{open:false});await p.locator('.wb-command-launch').click();assert.equal((await state()).open,false);});
 await run('Command schema updates preserve semantic selection, live labels, native editing and compatible drill paths',async()=>{
  const items=[{id:'a',label:'First'},{id:'off',label:'Disabled',disabled:true},{id:'b',label:'Last'}];await mount('essential-command',{items});await p.locator('.wb-command-launch').click();const input=p.locator('.wb-command-input'),active=()=>input.evaluate(e=>document.getElementById(e.getAttribute('aria-activedescendant')!)?.dataset.command);await input.press('ArrowDown');assert.equal(await active(),'b');await input.press('ArrowUp');assert.equal(await active(),'a');await input.press('Control+End');assert.equal(await active(),'b');await p.evaluate(items=>(window as any).api.update({items:[items[0],items[2],items[1]],label:'Updated command',triggerLabel:'Updated trigger'}),items);assert.equal(await active(),'b');assert.equal(await p.locator('.wb-launch-copy strong').textContent(),'Updated command');assert.equal(await p.locator('.wb-command-top .wb-eyebrow').textContent(),'Updated command');assert.equal(await p.locator('.wb-command-launch span').textContent(),'Updated trigger');
  await input.fill('native');await input.press('End');await p.keyboard.insertText(' edited');const original=await input.elementHandle();await input.evaluate(e=>(e as HTMLInputElement).setSelectionRange(2,5));await p.evaluate(()=>(window as any).api.update({placeholder:'Updated hint'}));assert.equal(await input.evaluate((e,old)=>e===old,original),true);assert.deepEqual(await input.evaluate(e=>[(e as HTMLInputElement).selectionStart,(e as HTMLInputElement).selectionEnd]),[2,5]);assert.equal(await input.evaluate(e=>e===document.activeElement),true);await input.press('Control+z');assert.equal(await input.inputValue(),'native');await input.fill('');
  await p.evaluate(()=>(window as any).api.update({items:[{id:'parent',label:'Group',children:[{id:'child',label:'Child'}]}]}));await p.locator('[data-command=parent]').click();await p.evaluate(()=>(window as any).api.update({items:[{id:'parent',label:'Updated group',children:[{id:'child',label:'Updated child'}]}]}));assert.deepEqual((await state()).path,['parent']);assert.equal(await p.locator('[data-command=child] strong').textContent(),'Updated child');await p.evaluate(()=>(window as any).api.update({items:[{id:'parent',label:'Updated group',children:[{id:'nested',label:'Nested',children:[{id:'leaf',label:'Leaf'}]}]}]}));await p.locator('[data-command=nested]').click();assert.deepEqual((await state()).path,['parent','nested']);await p.locator('[data-command-level="0"]').click();assert.deepEqual((await state()).path,['parent']);assert.equal(await input.evaluate(e=>e===document.activeElement),true);assert.equal(await p.locator('[data-command=nested]').count(),1);await p.evaluate(()=>(window as any).api.update({items:[{id:'parent',label:'Empty group',children:[]}]}));assert.deepEqual((await state()).path,[]);await p.evaluate(()=>(window as any).api.update({items:[{id:'a',label:'First',group:'Create'},{id:'b',label:'Last',group:'Navigate'}]}));assert.equal(await p.getByRole('group',{name:'Create',exact:true}).getByRole('option').count(),1);assert.equal(await p.getByRole('group',{name:'Navigate',exact:true}).getByRole('option').count(),1);
 });
 await run('Command all-disabled navigation cannot execute and destroyed APIs are inert',async()=>{
  await mount('essential-command',{items:[{id:'off',label:'Disabled',disabled:true}]});await p.evaluate(()=>{(window as any).calls=0;(window as any).api.update({onExecute:()=>(window as any).calls++});});await p.locator('.wb-command-launch').click();const input=p.locator('.wb-command-input');for(const key of ['ArrowDown','ArrowUp','Control+Home','Control+End','Enter'])await input.press(key);assert.equal(await input.getAttribute('aria-activedescendant'),null);assert.equal(await p.evaluate(()=>(window as any).calls),0);await input.fill('native');await p.evaluate(()=>(window as any).api.destroy());const dead=await state();await p.evaluate(()=>{(window as any).api.reset();(window as any).api.open();(window as any).api.close();(window as any).api.update({items:[]});});assert.deepEqual(await state(),dead);assert.equal(await p.evaluate(()=>document.documentElement.style.overflow),'');
 });
 await run('Command groups label real options and ancestor buttons return to their actual level',async()=>{
  await mount('essential-command',{items:[{id:'a',label:'First',group:'Actual group A'},{id:'b',label:'Second',group:'Actual group A'},{id:'c',label:'Third',group:'Actual group B'},{id:'plain',label:'Ungrouped'}]});await p.locator('.wb-command-launch').click();assert.equal(await p.locator('[role=group]').count(),2);assert.equal(await p.locator('[role=group]').first().locator('[role=option]').count(),2);assert.equal(await p.locator('[role=option]').count(),4);assert.equal(await p.locator('[data-command-level]').count(),0);
  await p.evaluate(()=>(window as any).api.update({items:[{id:'parent',label:'Parent',children:[{id:'nested',label:'Nested',children:[{id:'leaf',label:'Leaf'}]}]}]}));await p.locator('[data-command=parent]').click();await p.locator('[data-command=nested]').click();assert.deepEqual((await state()).path,['parent','nested']);assert.equal(await p.locator('[data-command-level]').count(),2);assert.equal(await p.locator('[data-command-level="1"]').getAttribute('aria-current'),'location');await p.locator('[data-command-level="0"]').click();assert.deepEqual((await state()).path,['parent']);assert.equal(await p.locator('[data-command=nested]').count(),1);assert.equal(await p.locator('.wb-command-input').evaluate(e=>e===document.activeElement),true);await p.locator('[data-command-back]').click();assert.deepEqual((await state()).path,[]);assert.equal(await p.locator('[data-command-level]').count(),0);
 });
 await run('Context menu is scoped; keyboard and explicit trigger; submenu and checkbox actions',async()=>{await mount('hinge-context');const target=p.locator('.wb-context-target');await target.click({button:'right'});assert.equal((await state()).open,true);await p.locator('[data-menu-action=move]').click();assert.ok((await state()).path.length);await p.keyboard.press('ArrowLeft');assert.equal((await state()).path.length,0);await p.locator('[data-menu-action=pin]').click();assert.equal((await state()).checked.pin,false);await p.keyboard.press('Escape');assert.equal((await state()).open,false);await target.focus();await p.keyboard.press('Shift+F10');assert.equal((await state()).open,true);await p.locator('#outside').click();assert.equal((await state()).open,false);assert.equal(await p.locator('#outside').evaluate(e=>e.dispatchEvent(new MouseEvent('contextmenu',{bubbles:true,cancelable:true}))),true);await p.evaluate(()=>(window as any).api.update({targetElement:document.getElementById('outside')}));await p.locator('#outside').click({button:'right'});assert.equal((await state()).open,true);await p.keyboard.press('Escape');await p.evaluate(()=>(window as any).api.update({targetElement:null}));assert.equal(await p.locator('#outside').evaluate(e=>e.dispatchEvent(new MouseEvent('contextmenu',{bubbles:true,cancelable:true}))),true);assert.ok(await p.locator('.wb-context-target').isVisible());});
 await run('Context updates preserve owned focus, live target labels and compatible submenu paths in RTL',async()=>{
  const items=[{id:'a',label:'First'},{id:'toggle',label:'Check',kind:'checkbox'},{id:'parent',label:'Parent',children:[{id:'child',label:'Child'}]}];await mount('hinge-context',{items});await p.locator('.wb-context-open').click();await p.locator('[data-menu-action=toggle]').focus();await p.evaluate(()=>(window as any).api.update({label:'Updated actions',targetLabel:'Updated file',targetDescription:'Updated description'}));assert.equal(await p.locator('[data-menu-action=toggle]').evaluate(e=>e===document.activeElement),true);assert.equal(await p.locator('[role=menu]').getAttribute('aria-label'),'Updated actions');assert.equal(await p.locator('.wb-context-target-copy strong').textContent(),'Updated file');assert.equal(await p.locator('.wb-context-target-copy small').textContent(),'Updated description');assert.equal(await p.locator('.wb-context-target').getAttribute('aria-label'),'Updated file');await p.locator('#outside').focus();await p.evaluate(()=>(window as any).api.update({label:'Outside update'}));assert.equal(await p.locator('#outside').evaluate(e=>e===document.activeElement),true);await p.locator('[data-menu-action=parent]').click();await p.evaluate(()=>(window as any).api.update({items:[{id:'parent',label:'New parent',children:[{id:'child',label:'New child'}]}]}));assert.deepEqual((await state()).path,['parent']);assert.equal(await p.locator('[data-menu-action=child] strong').textContent(),'New child');assert.equal(await p.locator('[role=menu]').getAttribute('aria-label'),'New parent');await p.keyboard.press('ArrowLeft');assert.equal(await p.locator('[data-menu-action=parent]').evaluate(e=>e===document.activeElement),true);await p.locator('.sop-wb').evaluate(e=>e.setAttribute('dir','rtl'));await p.keyboard.press('ArrowLeft');assert.deepEqual((await state()).path,['parent']);await p.keyboard.press('ArrowRight');assert.deepEqual((await state()).path,[]);
 });
 await run('Empty Context menus retain Escape focus and destroyed APIs preserve checked state without callbacks',async()=>{
  await mount('ticket-context',{items:[{id:'toggle',label:'Check',kind:'checkbox'},{id:'off',label:'Disabled',disabled:true}]});await p.locator('.wb-context-open').click();await p.locator('[data-menu-action=toggle]').click();assert.equal((await state()).checked.toggle,true);await p.evaluate(()=>(window as any).api.update({items:[]}));assert.equal(await p.locator('[role=menu]').evaluate(e=>e===document.activeElement),true);await p.keyboard.press('Escape');assert.equal((await state()).open,false);assert.equal(await p.locator('.wb-context-open').evaluate(e=>e===document.activeElement),true);await p.locator('.wb-context-open').click();assert.equal(await p.locator('[role=menu]').evaluate(e=>e===document.activeElement),true);await p.keyboard.press('Escape');await p.evaluate(()=>{(window as any).deadCalls=0;(window as any).api.update({onOpenChange:()=>{(window as any).deadCalls++;}});(window as any).api.destroy();});const dead=await state(),calls=await p.evaluate(()=>(window as any).deadCalls);await p.evaluate(()=>{const a=(window as any).api;a.reset();a.open();a.close();a.update({items:[]});});assert.deepEqual(await state(),dead);assert.equal(await p.evaluate(()=>(window as any).deadCalls),calls);
 });
 await run('Changing reduced motion cancels an active decorative Context pulse and retains native controls',async()=>{
  await p.emulateMedia({reducedMotion:'no-preference'});await mount('hinge-context');await p.locator('.wb-context-open').click();assert.ok(await p.locator('.sop-wb').evaluate(e=>e.querySelector('.wb-art')!.getAnimations().some(a=>a.playState==='running')));await p.emulateMedia({reducedMotion:'reduce'});await p.waitForFunction(()=>document.querySelector('.sop-wb')?.getAttribute('data-wb-reduced')==='true');assert.equal(await p.locator('.sop-wb').evaluate(e=>[...e.querySelectorAll('.wb-art')].flatMap(e=>e.getAnimations()).filter(a=>a.playState==='running').length),0);assert.equal((await state()).open,true);await p.keyboard.press('Escape');assert.equal((await state()).open,false);await p.emulateMedia({reducedMotion:'no-preference'});
 });
 await run('Context ignores queued scroll at the same anchor but closes when the anchor moves',async()=>{
  await mount('hinge-context');const oldHeight=await p.evaluate(()=>{const old=document.body.style.minHeight;document.body.style.minHeight='2400px';window.scrollTo(0,0);return old;});
  await p.locator('.wb-context-open').click();assert.equal((await state()).open,true);
  await p.evaluate(()=>document.dispatchEvent(new Event('scroll')));assert.equal((await state()).open,true);
  await p.locator('[data-menu-action=open]').click();assert.equal((await state()).lastAction,'open');
  await p.locator('.wb-context-open').click();await p.evaluate(()=>window.scrollTo(0,240));
  await p.waitForFunction(()=>(window as any).api.getState().open===false);
  await p.evaluate(old=>{document.body.style.minHeight=old;window.scrollTo(0,0);},oldHeight);
 });
 await run('Context disabled actions and controlled check state do not trigger side effects',async()=>{await mount('ticket-context',{checked:{pin:true}});await p.evaluate(()=>{(window as any).actions=[];(window as any).api.update({onAction:(item:any)=>(window as any).actions.push(item.id)});(window as any).api.open();});await p.locator('[data-menu-action=share]').click({force:true});assert.deepEqual(await p.evaluate(()=>(window as any).actions),[]);await p.locator('[data-menu-action=pin]').click();assert.equal((await state()).checked.pin,true);await p.keyboard.press('Home');assert.equal(await p.locator('[data-menu-action=open]').evaluate(e=>e===document.activeElement),true);await p.keyboard.press('End');assert.equal(await p.locator('[data-menu-action=share]').evaluate(e=>e===document.activeElement),true);});
 await run('Context semantic groups preserve original flat step positions and real subjects',async()=>{await mount('thin-step-context',{targetLabel:'Actual file',items:[{id:'a',label:'First',group:'One'},{id:'b',label:'Second',group:'One'},{id:'c',label:'Third',group:'Two'},{id:'parent',label:'Actual parent',children:[{id:'child',label:'Child'}]}]});await p.evaluate(()=>(window as any).api.open());assert.equal(await p.locator('[role=group]').count(),2);assert.deepEqual(await p.locator('[role=group]').evaluateAll(es=>es.map(e=>e.getAttribute('aria-label'))),['One','Two']);for(const [id,index,margin]of [['a',2,7],['b',3,14],['c',5,0],['parent',6,0]] as const){assert.equal(await p.locator(`[data-menu-action=${id}]`).getAttribute('data-menu-flat-index'),String(index));assert.equal(await p.locator(`[data-menu-action=${id}]`).evaluate(e=>getComputedStyle(e).marginLeft),margin+'px');}assert.equal(await p.locator('.wb-context-subject').textContent(),'Actual file');await p.locator('[data-menu-action=parent]').click();assert.equal(await p.locator('.wb-context-subject').textContent(),'Actual parent');assert.equal(await p.locator('[role=group]').count(),0);});
 await run('Navigation has real hrefs, preserves modified clicks and supports SPA callbacks',async()=>{await mount('paper-index-nav');await p.evaluate(()=>{(window as any).navigations=[];(window as any).api.update({onNavigate:(item:any)=>{(window as any).navigations.push(item.id);return false;}});});const project=p.locator('.wb-nav-desktop [data-nav=projects]');assert.equal(await project.getAttribute('href'),'#destination');await project.click();assert.equal((await state()).active,'projects');assert.deepEqual(await p.evaluate(()=>(window as any).navigations),['projects']);assert.equal(await project.evaluate(e=>e.dispatchEvent(new MouseEvent('click',{ctrlKey:true,bubbles:true,cancelable:true}))),true);await p.evaluate(()=>(window as any).api.update({active:'overview'}));await project.click();assert.equal((await state()).active,'overview');for(const other of p.context().pages())if(other!==p)await other.close();await p.bringToFront();});
 await run('Navigation groups and mobile modal preserve semantics, focus and current location',async()=>{await mount('ribbon-header');await p.locator('[data-nav-group=more]').click();assert.equal((await state()).group,'more');assert.ok(await p.locator('.wb-nav-flyout').isVisible());await p.keyboard.press('Escape');assert.equal((await state()).group,null);await p.evaluate(()=>(window as any).api.update({layout:'mobile'}));await p.locator('.wb-nav-mobile-open').click();assert.equal((await state()).open,true);assert.equal(await p.locator('dialog nav').count(),1);for(let i=0;i<12;i++)await p.keyboard.press('Tab');assert.equal(await p.locator('dialog').evaluate(e=>e.contains(document.activeElement)),true);await p.keyboard.press('Escape');assert.equal((await state()).open,false);});
 await run('Current navigation reading follows only a real selected row and survives schema, mode and focus changes',async()=>{const items=[{id:'a',label:'First',href:'#a'},{id:'parent',label:'Parent',children:[{id:'child',label:'Child',href:'#child'}]}];await mount('ledger-index-navigation',{layout:'sidebar',currentPresentation:'inline',items,defaultActive:'a'});await p.evaluate(()=>(window as any).api.update({onNavigate:()=>false}));const foot=p.locator('.wb-nav-foot'),link=p.locator('.wb-nav-desktop [data-nav=a]');assert.equal(await foot.evaluate(e=>e.parentElement?.querySelector('[data-nav]')?.getAttribute('data-nav')),'a');await link.focus();await p.evaluate(items=>(window as any).api.update({items:items.map(i=>i.id==='a'?{...i,label:'New first'}:i)}),items);assert.equal(await link.evaluate(e=>e===document.activeElement),true);assert.equal(await p.locator('.wb-nav-location').textContent(),'New first');await p.evaluate(()=>(window as any).api.update({active:'child'}));assert.equal(await foot.evaluate(e=>e.parentElement?.querySelector('[data-nav-group]')?.getAttribute('data-nav-group')),'parent');assert.equal(await p.locator('.wb-nav-location').textContent(),'Child');await p.evaluate(()=>(window as any).api.update({active:'absent'}));assert.equal(await foot.isVisible(),false);assert.equal(await p.locator('[data-nav-current-row]').count(),0);await p.evaluate(()=>(window as any).api.update({currentPresentation:'footer'}));assert.equal(await foot.evaluate(e=>e.parentElement?.className),'wb-navigation-frame');await p.evaluate(()=>(window as any).api.update({currentPresentation:'inline',items:[]}));assert.equal(await foot.isVisible(),false);});
 await run('Real mobile current reading is derived from selection and preserves owned reading focus across item updates',async()=>{for(const id of ['ledger-index-navigation','caption-rail-navigation','ribbon-top-navigation']){const items=[{id:'a',label:'First',href:'#a'},{id:'b',label:'Second',href:'#b'}];await mount(id,{layout:'mobile',items,defaultActive:'a'});await p.locator('.wb-nav-mobile-open').click();const reading=p.locator('dialog .wb-nav-mobile-reading');assert.equal(await p.locator('dialog .wb-nav-mobile-location').textContent(),'First');await reading.focus();await p.evaluate(items=>(window as any).api.update({items:items.map(i=>i.id==='a'?{...i,label:'Updated first'}:i)}),items);assert.equal(await p.locator('dialog .wb-nav-mobile-location').textContent(),'Updated first');assert.equal(await reading.evaluate(e=>e===document.activeElement),true,id+' current reading owned focus');await p.evaluate(()=>(window as any).api.update({active:'b'}));assert.equal(await p.locator('dialog .wb-nav-mobile-location').textContent(),'Second');await p.evaluate(()=>(window as any).api.update({active:'absent'}));assert.equal(await reading.isVisible(),false);assert.equal(await p.locator('.wb-nav-mobile-close').evaluate(e=>e===document.activeElement),true,id+' hidden reading stays in modal');await p.keyboard.press('Escape');await p.evaluate(()=>(window as any).api.update({layout:'sidebar',active:'a'}));const desktop=p.locator('.wb-nav-foot');await desktop.focus();await p.evaluate(items=>(window as any).api.update({items:items.map(i=>({...i,label:i.label+' desktop'}))}),items);assert.equal(await desktop.evaluate(e=>e===document.activeElement),true,id+' desktop reading owns focus after rebuild');}await mount('arc-dock',{layout:'mobile'});await p.locator('.wb-nav-mobile-open').click();assert.equal(await p.locator('dialog .wb-nav-mobile-reading').count(),0);await p.keyboard.press('Escape');});
 await run('Inline navigation uses one real controlled group in flow, preserves page-scroll reading and rebuilds owned children',async()=>{const items=[{id:'parent',label:'Actual parent',children:[{id:'child',label:'Actual child',href:'#child'}]}];await mount('folded-index-navigation',{layout:'sidebar',groupPresentation:'inline',items});const trigger=p.locator('[data-nav-group=parent]');await trigger.press('ArrowDown');assert.equal((await state()).group,'parent');assert.equal(await p.locator('.wb-nav-flyout').evaluate(e=>e.parentElement?.tagName),'LI');assert.equal(await p.locator('.wb-nav-flyout').getAttribute('popover'),null);assert.equal(await p.locator('.wb-nav-flyout').getAttribute('role'),'group');assert.equal(await p.locator('.wb-nav-flyout').getAttribute('aria-labelledby'),await trigger.getAttribute('id'));await p.evaluate(()=>document.dispatchEvent(new Event('scroll')));assert.equal((await state()).group,'parent');await p.locator('.wb-nav-flyout [data-nav=child]').focus();await p.evaluate(items=>(window as any).api.update({items:items.map(i=>({...i,children:[{id:'child',label:'New child',href:'#new-child'}]}))}),items);assert.equal((await state()).group,'parent');assert.equal(await p.locator('.wb-nav-flyout [data-nav=child]').evaluate(e=>e===document.activeElement),true);assert.equal(await p.locator('.wb-nav-flyout [data-nav=child]').getAttribute('href'),'#new-child');await p.keyboard.press('Escape');assert.equal((await state()).group,null);assert.equal(await p.locator('.wb-nav-flyout').isVisible(),false);assert.equal(await trigger.evaluate(e=>e===document.activeElement),true);});
 await run('Navigation ignores queued scroll while its actual group anchor stays fixed',async()=>{await mount('paper-index-nav',{layout:'sidebar'});const trigger=p.locator('[data-nav-group]').first();await trigger.scrollIntoViewIfNeeded();await p.waitForTimeout(30);await trigger.press('ArrowDown');assert.equal((await state()).group,'more');await p.evaluate(()=>document.dispatchEvent(new Event('scroll')));assert.equal((await state()).group,'more');assert.equal(await p.locator('.wb-nav-flyout [data-nav]').first().evaluate(e=>e===document.activeElement),true);await p.keyboard.press('Escape');});
 await run('All popover navigation groups expose the selected child and close on page scroll',async()=>{
  await p.evaluate(()=>{document.body.style.minHeight='2500px';});
  let tested=0;
  for(const part of f.records.filter(r=>r.category==='navigation')){
   await mount(part.id,{layout:'sidebar',groupPresentation:'popover'});
   await p.evaluate(()=>window.scrollTo(0,0));
   const trigger=p.locator('.wb-nav-desktop [data-nav-group]').first();
   if(!await trigger.isVisible())continue;
   tested++;
   await trigger.click();
   const leaf=p.locator('.wb-nav-flyout [data-nav]:not([aria-disabled="true"])').first();
   const id=await leaf.getAttribute('data-nav'),label=(await leaf.locator('strong').innerText()).trim();
   await leaf.click();
   assert.equal((await state()).active,id,part.id);
   assert.equal((await p.locator('.wb-nav-location').innerText()).trim(),label,part.id);
   assert.equal(await trigger.getAttribute('data-current'),'',part.id);
   assert.ok((await trigger.getAttribute('aria-label'))?.includes(label),part.id);
   await trigger.click();
   assert.equal((await state()).group,await trigger.getAttribute('data-nav-group'),part.id);
   if(part.id==='axis-rail-nav'){
    await p.locator('.wb-nav-flyout').evaluate(el=>{(el as HTMLElement).style.maxHeight='70px';el.scrollTop=30;});
    await p.waitForTimeout(30);
    assert.ok((await state()).group,part.id+' internal list scroll');
   }
   await p.evaluate(()=>window.scrollTo(0,320));
   await p.waitForFunction(()=>(window as any).api.getState().group===null);
   assert.equal(await p.locator('.wb-nav-flyout').isVisible(),false,part.id);
  }
  assert.ok(tested>=15,`Tested ${tested} visible navigation groups`);
  await mount('axis-rail-nav',{layout:'sidebar'});
  const keyboardTrigger=p.locator('.wb-nav-desktop [data-nav-group]').first();
  await keyboardTrigger.focus();await p.keyboard.press('ArrowDown');
  assert.equal((await state()).group,'more');
  const keyboardLeaf=p.locator('.wb-nav-flyout [data-nav]').first();
  assert.ok(await keyboardLeaf.evaluate(element=>element===document.activeElement));
  await keyboardLeaf.press('Enter');
  assert.equal((await state()).active,await keyboardLeaf.getAttribute('data-nav'));
  await p.evaluate(()=>{document.body.style.minHeight='';window.scrollTo(0,0);});
 });
await run('Navigation schema updates retain owned destination and live brand labels, with compatible flyouts',async()=>{const items=[{id:'a',label:'First',href:'#a'},{id:'parent',label:'Actual parent',children:[{id:'child',label:'Child',href:'#child'}]}];await mount('paper-index-nav',{layout:'sidebar',items});const link=p.locator('.wb-nav-desktop [data-nav=a]');await link.focus();await p.evaluate(items=>(window as any).api.update({items,brand:'Updated brand',brandHref:'#brand',label:'Updated navigation'}),items);assert.equal(await link.evaluate(e=>e===document.activeElement),true);assert.equal(await p.locator('.wb-nav-brand strong').textContent(),'Updated brand');assert.equal(await p.locator('.wb-nav-brand>a').getAttribute('href'),'#brand');assert.equal(await p.locator('.wb-navigation-frame').getAttribute('aria-label'),'Updated navigation');await p.locator('[data-nav-group=parent]').press('ArrowDown');await p.locator('.wb-nav-flyout [data-nav=child]').focus();await p.evaluate(items=>(window as any).api.update({items:items.map(i=>i.id==='parent'?{...i,children:[{id:'child',label:'Updated child',href:'#new-child'}]}:i)}),items);assert.equal((await state()).group,'parent');assert.equal(await p.locator('.wb-nav-flyout [data-nav=child]').evaluate(e=>e===document.activeElement),true);assert.equal(await p.locator('.wb-nav-flyout [data-nav=child]').getAttribute('href'),'#new-child');await p.keyboard.press('Escape');assert.equal(await p.locator('[data-nav-group=parent]').evaluate(e=>e===document.activeElement),true);await p.locator('#reset').focus();await p.evaluate(items=>(window as any).api.update({items}),items);assert.equal(await p.locator('#reset').evaluate(e=>e===document.activeElement),true);});
await run('Navigation mobile groups inherit disabled state and retain actual open details and owned links',async()=>{const items=[{id:'parent',label:'Parent',children:[{id:'child',label:'Child',href:'#child'}]},{id:'off',label:'Disabled group',disabled:true,children:[{id:'blocked',label:'Blocked',href:'#blocked'}]}];await mount('paper-index-nav',{layout:'mobile',items});await p.locator('.wb-nav-mobile-open').click();const blocked=p.locator('dialog [data-nav-mobile-group=off]');assert.equal(await blocked.locator('summary').getAttribute('aria-disabled'),'true');await blocked.locator('summary').dispatchEvent('click');assert.equal(await blocked.evaluate(e=>(e as HTMLDetailsElement).open),false);assert.equal(await blocked.locator('[data-nav=blocked]').getAttribute('href'),null);const actual=p.locator('dialog [data-nav-mobile-group=parent]');await actual.locator('summary').click();await actual.locator('[data-nav=child]').focus();await p.evaluate(items=>(window as any).api.update({items:items.map(i=>i.id==='parent'?{...i,children:[{id:'child',label:'New child',href:'#new-child'}]}:i)}),items);assert.equal(await actual.evaluate(e=>(e as HTMLDetailsElement).open),true);assert.equal(await actual.locator('[data-nav=child]').evaluate(e=>e===document.activeElement),true);assert.equal(await actual.locator('[data-nav=child]').getAttribute('href'),'#new-child');await p.keyboard.press('Escape');await p.waitForFunction(()=>(window as any).api.getState().open===false);});
await run('Navigation destroyed modal APIs cannot lock scroll, mutate state or call callbacks',async()=>{await mount('paper-index-nav',{layout:'mobile'});await p.evaluate(()=>{(window as any).deadCalls=[];(window as any).api.update({onOpenChange:(open:boolean)=>(window as any).deadCalls.push(open)});(window as any).api.open();(window as any).api.destroy();});assert.equal(await p.evaluate(()=>document.documentElement.style.overflow),'');const before=await state(),calls=await p.evaluate(()=>(window as any).deadCalls);await p.evaluate(()=>{(window as any).api.open();(window as any).api.reset();(window as any).api.close();(window as any).api.update({items:[]});});assert.deepEqual(await state(),before);assert.deepEqual(await p.evaluate(()=>(window as any).deadCalls),calls);assert.equal(await p.locator('dialog[open]').count(),0);assert.equal(await p.evaluate(()=>document.documentElement.style.overflow),'');});
await run('Data table numeric three-state sorting, paging and query do not mutate source rows',async()=>{await mount('ledger-table');await p.locator('[data-sort=size]').click();assert.deepEqual((await state()).sort,{key:'size',direction:'ascending'});let text=await p.locator('tbody [data-column=size]').allTextContents();assert.equal(Number(text[0]),32);await p.locator('[data-sort=size]').click();text=await p.locator('tbody [data-column=size]').allTextContents();assert.equal(Number(text[0]),256);await p.locator('[data-sort=size]').click();assert.equal((await state()).sort,null);await p.locator('[data-table-page=next]').click();assert.equal((await state()).page,2);await p.locator('.wb-table-search input').fill('design');assert.equal((await state()).total,1);assert.equal((await state()).page,1);});
 await run('Row selection is keyed by identity, select-all affects current page only and row actions are callbacks',async()=>{await mount('control-room-table');const first=await p.locator('[data-row-check]').first().getAttribute('data-row-check');await p.locator('[data-row-check]').first().check();await p.locator('[data-sort=size]').click();assert.ok((await state()).selected.includes(first));await p.locator('[data-table-all]').check();assert.ok((await state()).selected.length>=4);await p.locator('[data-table-page=next]').click();const before=(await state()).selected.length;await p.locator('[data-table-all]').check();assert.ok((await state()).selected.length>before);await p.evaluate(()=>{(window as any).rowAction=null;(window as any).api.update({onRowAction:(a:any,r:any)=>(window as any).rowAction={a:a.id,id:r.id}})});await p.locator('[data-action]').first().click();assert.ok(await p.evaluate(()=>(window as any).rowAction.id));await p.locator('[data-table-clear]').click();assert.deepEqual((await state()).selected,[]);});
 await run('Table manual/server mode returns requests without re-sorting or slicing the supplied page',async()=>{await mount('essential-table',{manual:true,rowCount:80,page:3,pageSize:10,sort:null});await p.evaluate(()=>{(window as any).requested={};(window as any).api.update({onPageChange:(page:number)=>(window as any).requested.page=page,onSortChange:(sort:any)=>(window as any).requested.sort=sort});});await p.locator('[data-table-page=next]').click();assert.equal((await state()).page,3);assert.equal(await p.evaluate(()=>(window as any).requested.page),4);await p.locator('[data-sort=size]').click();assert.equal((await state()).sort,null);assert.equal(await p.evaluate(()=>(window as any).requested.sort.key),'size');assert.equal(await p.locator('tbody [data-row]').count(),8);});
 await run('Column resizing supports keyboard and pointer; sticky columns remain aligned',async()=>{await mount('optical-matrix');const grip=p.locator('[data-resize=name]');await grip.focus();const initial=Number(await grip.getAttribute('aria-valuenow'));await p.keyboard.press('ArrowRight');assert.equal(Number(await grip.getAttribute('aria-valuenow')),initial+12);await p.keyboard.press('Home');assert.equal(Number(await grip.getAttribute('aria-valuenow')),88);const r=(await grip.boundingBox())!;await p.mouse.move(r.x+r.width/2,r.y+r.height/2);await p.mouse.down();await p.mouse.move(r.x+85,r.y+4);await p.mouse.up();assert.ok(Number(await grip.getAttribute('aria-valuenow'))>100);assert.equal(await p.locator('tbody [data-first-column]').first().evaluate(e=>getComputedStyle(e).position),'sticky');});
 await run('All skins keep page width at 320/390/768; native table overflows only inside its scroll area',async()=>{for(const width of [320,390,768]){await p.setViewportSize({width,height:950});for(const r of f.records){await mount(r.id);const overflow=await p.evaluate(()=>document.documentElement.scrollWidth-window.innerWidth);assert.ok(overflow<=1,`${r.id} at ${width}: ${overflow}px`);}}});
 for(const other of p.context().pages())if(other!==p)await other.close();await p.bringToFront();
 await run('Popovers and modal frames stay within a small viewport; Escape closes only the active layer',async()=>{await p.setViewportSize({width:390,height:750});for(const r of f.records.filter(x=>['commands','contextmenus'].includes(x.category))){await mount(r.id);await p.evaluate(()=>(window as any).api.open());const selector=r.category==='commands'?'dialog[open]':'.wb-context-panel';await p.waitForTimeout(700);const box=(await p.locator(selector).boundingBox())!;assert.ok(box.x>=-1&&box.x+box.width<=391,r.id+' '+JSON.stringify(box));assert.ok(box.y>=-1&&box.y+box.height<=751,r.id+' '+JSON.stringify(box));await p.keyboard.press('Escape');assert.equal((await state()).open,false);}});
 await run('Reduced motion keeps input and actions working; unmount aborts work and releases modal locks',async()=>{await p.emulateMedia({reducedMotion:'reduce'});await mount('aperture-command');await p.evaluate(()=>(window as any).api.open());assert.equal(await p.locator('.sop-wb').getAttribute('data-wb-reduced'),'true');await p.evaluate(()=>(window as any).unmount());assert.equal(await p.evaluate(()=>document.documentElement.style.overflow),'');await mount('parallax-search');await p.locator('input').fill('design');assert.equal((await state()).results,1);await p.evaluate(()=>(window as any).unmount());assert.equal(await p.locator('#host *').count(),0);await p.emulateMedia({reducedMotion:'no-preference'});assert.deepEqual(errors,[]);});
 console.log(`Workbench browser checks: ${passed.length} passed.`);
}finally{fs.writeFileSync(path.join(f.out,'browser-results.json'),JSON.stringify({mode:offline?'actual Chromium / offline source fixture; Vite not executed':'Vite HTTP',passed:passed.length,tests:passed,errors},null,2));await browser?.close();await closeServer?.();}
