import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createRequire} from 'node:module';
import type {Browser,Page} from 'playwright';import {workbenchFixture} from './workbench-fixture.ts';import {ROOT} from '../scripts/catalog.ts';import {requireLocalServerUrl} from './vite-url.ts';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_PATH??'playwright') as typeof import('playwright');
const offline=process.env.SOP_TEST_MODE==='offline',f=workbenchFixture(),passed:string[]=[],errors:string[]=[];
let browser:Browser|undefined,closeServer:(()=>Promise<void>)|undefined;
async function run(name:string,fn:()=>Promise<void>){await fn();passed.push(name);console.log('PASS '+name);}
try{
 let url='';if(!offline){const {createServer}=await import('vite');const s=await createServer({root:ROOT,server:{host:'127.0.0.1',port:0}});await s.listen();url=requireLocalServerUrl(s,'Workbench');closeServer=()=>s.close();}
 browser=await chromium.launch({headless:true,args:['--no-sandbox'],...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{})});
 const p=await browser.newPage({viewport:{width:720,height:950}});p.setDefaultTimeout(5000);p.on('pageerror',e=>errors.push(e.message));
 if(offline){await p.setContent(f.shell.replace('<link rel="stylesheet" href="./styles.css">',''));await p.addStyleTag({content:f.styles});await p.addScriptTag({content:f.bundle()});}else await p.goto(new URL('.test-output/workbench/test.html',url).href,{waitUntil:'domcontentloaded',timeout:120000});
 const mount=async(id:string|string[],options:Record<string,unknown>={})=>{await p.evaluate(([ids,o])=>(window as any).mount(ids,o),[typeof id==='string'?[id]:id,options]);await p.waitForTimeout(20);};
 const state=()=>p.evaluate(()=>(window as any).api.getState());
 await run('88 actual skins mount independently with public API and without page errors',async()=>{for(const r of f.records){await mount(r.id);assert.equal(await p.locator('#host .sop-wb').count(),1,r.id);assert.ok(await state());}});
 await run('Search query, filter, keyboard, submit, clear and native form reset',async()=>{await mount('parallax-search',{name:'query'});const input=p.locator('.wb-search-input');await input.fill('design');assert.equal((await state()).results,1);await input.press('ArrowDown');assert.ok(await input.getAttribute('aria-activedescendant'));await input.press('Enter');assert.equal((await state()).open,false);await input.fill('');await p.locator('[data-filter=settings]').click();assert.equal((await state()).results,2);await input.fill('workspace');assert.equal((await state()).results,1);await p.locator('.wb-search-clear').click();assert.equal(await input.inputValue(),'');await input.fill('sample');assert.equal(await p.evaluate(()=>new FormData(document.querySelector('form')!).get('query')),'sample');await p.locator('#reset').click();assert.equal((await state()).query,'');});
 await run('Search async aborts older requests and ignores stale success and failure',async()=>{await mount('lagoon-search',{debounceMs:0});await p.evaluate(()=>{(window as any).jobs=[];(window as any).api.update({search:(q:string,_f:string,signal:AbortSignal)=>new Promise((resolve,reject)=>(window as any).jobs.push({q,signal,resolve,reject}))});});const input=p.locator('.wb-search-input');await input.fill('first');await p.waitForFunction(()=>(window as any).jobs.some((x:any)=>x.q==='first'));await input.fill('second');await p.waitForFunction(()=>(window as any).jobs.some((x:any)=>x.q==='second'));assert.equal(await p.evaluate(()=>(window as any).jobs.find((j:any)=>j.q==='first').signal.aborted),true);await p.evaluate(()=>{(window as any).jobs.find((j:any)=>j.q==='second').resolve([{id:'second',label:'second'}]);});await p.waitForTimeout(30);await p.evaluate(()=>(window as any).jobs.find((j:any)=>j.q==='first').resolve([{id:'first',label:'first'}]));assert.equal(await p.locator('[data-result]').getAttribute('data-result'),'second');});
 await run('Search composition does not execute, unsafe URLs do not navigate, custom content stays literal',async()=>{await mount('essential-searchbar',{items:[{id:'literal',label:'<b>日本語</b>',href:'javascript:alert(1)'},{id:'off',label:'無効',disabled:true}],filters:[]});const input=p.locator('.wb-search-input');await input.focus();assert.equal(await p.locator('[data-result=literal]').evaluate(e=>e.tagName),'BUTTON');assert.equal(await p.locator('[data-result=literal] strong').innerText(),'<b>日本語</b>');await p.evaluate(()=>{(window as any).submitted=0;(window as any).api.update({onSubmit:()=>{(window as any).submitted++}});document.querySelector('input')!.dispatchEvent(new CompositionEvent('compositionstart',{bubbles:true}));});await input.press('Enter');assert.equal(await p.evaluate(()=>(window as any).submitted),0);await input.dispatchEvent('compositionend');await p.evaluate(()=>(window as any).api.update({query:'fixed'}));await input.fill('declined');assert.equal((await state()).query,'fixed');});
 await run('Command palette drill-down, query, keyboard execute, Escape and focus return',async()=>{await mount('aperture-command');const launch=p.locator('.wb-command-launch');await launch.click();await p.locator('[data-command=view]').click();assert.deepEqual((await state()).path,['view']);await p.locator('.wb-command-input').press('Backspace');assert.deepEqual((await state()).path,[]);await p.locator('.wb-command-input').fill('新しい');await p.locator('.wb-command-input').press('Enter');assert.equal((await state()).open,false);assert.equal((await state()).lastCommand,'create');assert.equal(await launch.evaluate(e=>e===document.activeElement),true);await launch.click();await p.keyboard.press('Escape');assert.equal((await state()).open,false);assert.equal(await p.evaluate(()=>document.documentElement.style.overflow),'');});
 await run('Command async execution blocks duplicates, surfaces failures and cancels stale work',async()=>{await mount('deck-command');await p.evaluate(()=>{(window as any).calls=0;(window as any).api.update({onExecute:(_i:any,signal:AbortSignal)=>new Promise((resolve,reject)=>{(window as any).calls++;(window as any).execution={resolve,reject,signal};})});(window as any).api.open();});await p.locator('[data-command=create]').click();assert.equal((await state()).busy,true);assert.equal(await p.locator('.wb-command-input').getAttribute('readonly'),'');await p.locator('.wb-command-input').press('Enter');assert.equal(await p.evaluate(()=>(window as any).calls),1);await p.evaluate(()=>(window as any).execution.reject(Error('接続できません')));await p.waitForTimeout(30);assert.match((await state()).error,/接続/);await p.locator('[data-command=create]').click();await p.keyboard.press('Escape');assert.ok(await p.evaluate(()=>(window as any).execution.signal.aborted));await p.evaluate(()=>(window as any).execution.resolve());assert.equal((await state()).open,false);});
 await run('Ctrl+K is opt-in globally; multiple palettes dispatch only one, controlled open may decline',async()=>{await mount(['essential-command','light-command']);await p.locator('#outside').focus();await p.keyboard.press('Control+k');assert.equal(await p.locator('dialog[open]').count(),0);await p.evaluate(()=>(window as any).apis[1].update({hotkey:true}));await p.keyboard.press('Control+k');assert.equal(await p.locator('dialog[open]').count(),1);await p.keyboard.press('Escape');await mount('compact-command',{open:false});await p.locator('.wb-command-launch').click();assert.equal((await state()).open,false);});
 await run('Context menu is scoped; keyboard and explicit trigger; submenu and checkbox actions',async()=>{await mount('hinge-context');const target=p.locator('.wb-context-target');await target.click({button:'right'});assert.equal((await state()).open,true);await p.locator('[data-menu-action=move]').click();assert.ok((await state()).path.length);await p.keyboard.press('ArrowLeft');assert.equal((await state()).path.length,0);await p.locator('[data-menu-action=pin]').click();assert.equal((await state()).checked.pin,false);await p.keyboard.press('Escape');assert.equal((await state()).open,false);await target.focus();await p.keyboard.press('Shift+F10');assert.equal((await state()).open,true);await p.locator('#outside').click();assert.equal((await state()).open,false);assert.equal(await p.locator('#outside').evaluate(e=>e.dispatchEvent(new MouseEvent('contextmenu',{bubbles:true,cancelable:true}))),true);await p.evaluate(()=>(window as any).api.update({targetElement:document.getElementById('outside')}));await p.locator('#outside').click({button:'right'});assert.equal((await state()).open,true);await p.keyboard.press('Escape');await p.evaluate(()=>(window as any).api.update({targetElement:null}));assert.equal(await p.locator('#outside').evaluate(e=>e.dispatchEvent(new MouseEvent('contextmenu',{bubbles:true,cancelable:true}))),true);assert.ok(await p.locator('.wb-context-target').isVisible());});
 await run('Context disabled actions and controlled check state do not trigger side effects',async()=>{await mount('ticket-context',{checked:{pin:true}});await p.evaluate(()=>{(window as any).actions=[];(window as any).api.update({onAction:(item:any)=>(window as any).actions.push(item.id)});(window as any).api.open();});await p.locator('[data-menu-action=share]').click({force:true});assert.deepEqual(await p.evaluate(()=>(window as any).actions),[]);await p.locator('[data-menu-action=pin]').click();assert.equal((await state()).checked.pin,true);await p.keyboard.press('Home');assert.equal(await p.locator('[data-menu-action=open]').evaluate(e=>e===document.activeElement),true);await p.keyboard.press('End');assert.equal(await p.locator('[data-menu-action=share]').evaluate(e=>e===document.activeElement),true);});
 await run('Navigation has real hrefs, preserves modified clicks and supports SPA callbacks',async()=>{await mount('paper-index-nav');await p.evaluate(()=>{(window as any).navigations=[];(window as any).api.update({onNavigate:(item:any)=>{(window as any).navigations.push(item.id);return false;}});});const project=p.locator('.wb-nav-desktop [data-nav=projects]');assert.equal(await project.getAttribute('href'),'#destination');await project.click();assert.equal((await state()).active,'projects');assert.deepEqual(await p.evaluate(()=>(window as any).navigations),['projects']);assert.equal(await project.evaluate(e=>e.dispatchEvent(new MouseEvent('click',{ctrlKey:true,bubbles:true,cancelable:true}))),true);await p.evaluate(()=>(window as any).api.update({active:'overview'}));await project.click();assert.equal((await state()).active,'overview');for(const other of p.context().pages())if(other!==p)await other.close();await p.bringToFront();});
 await run('Navigation groups and mobile modal preserve semantics, focus and current location',async()=>{await mount('ribbon-header');await p.locator('[data-nav-group=more]').click();assert.equal((await state()).group,'more');assert.ok(await p.locator('.wb-nav-flyout').isVisible());await p.keyboard.press('Escape');assert.equal((await state()).group,null);await p.evaluate(()=>(window as any).api.update({layout:'mobile'}));await p.locator('.wb-nav-mobile-open').click();assert.equal((await state()).open,true);assert.equal(await p.locator('dialog nav').count(),1);for(let i=0;i<12;i++)await p.keyboard.press('Tab');assert.equal(await p.locator('dialog').evaluate(e=>e.contains(document.activeElement)),true);await p.keyboard.press('Escape');assert.equal((await state()).open,false);});
 await run('Data table numeric three-state sorting, paging and query do not mutate source rows',async()=>{await mount('ledger-table');await p.locator('[data-sort=size]').click();assert.deepEqual((await state()).sort,{key:'size',direction:'ascending'});let text=await p.locator('tbody [data-column=size]').allTextContents();assert.equal(Number(text[0]),32);await p.locator('[data-sort=size]').click();text=await p.locator('tbody [data-column=size]').allTextContents();assert.equal(Number(text[0]),256);await p.locator('[data-sort=size]').click();assert.equal((await state()).sort,null);await p.locator('[data-table-page=next]').click();assert.equal((await state()).page,2);await p.locator('.wb-table-search input').fill('design');assert.equal((await state()).total,1);assert.equal((await state()).page,1);});
 await run('Row selection is keyed by identity, select-all affects current page only and row actions are callbacks',async()=>{await mount('control-room-table');const first=await p.locator('[data-row-check]').first().getAttribute('data-row-check');await p.locator('[data-row-check]').first().check();await p.locator('[data-sort=size]').click();assert.ok((await state()).selected.includes(first));await p.locator('[data-table-all]').check();assert.ok((await state()).selected.length>=4);await p.locator('[data-table-page=next]').click();const before=(await state()).selected.length;await p.locator('[data-table-all]').check();assert.ok((await state()).selected.length>before);await p.evaluate(()=>{(window as any).rowAction=null;(window as any).api.update({onRowAction:(a:any,r:any)=>(window as any).rowAction={a:a.id,id:r.id}})});await p.locator('[data-action]').first().click();assert.ok(await p.evaluate(()=>(window as any).rowAction.id));await p.locator('[data-table-clear]').click();assert.deepEqual((await state()).selected,[]);});
 await run('Table manual/server mode returns requests without re-sorting or slicing the supplied page',async()=>{await mount('essential-table',{manual:true,rowCount:80,page:3,pageSize:10,sort:null});await p.evaluate(()=>{(window as any).requested={};(window as any).api.update({onPageChange:(page:number)=>(window as any).requested.page=page,onSortChange:(sort:any)=>(window as any).requested.sort=sort});});await p.locator('[data-table-page=next]').click();assert.equal((await state()).page,3);assert.equal(await p.evaluate(()=>(window as any).requested.page),4);await p.locator('[data-sort=size]').click();assert.equal((await state()).sort,null);assert.equal(await p.evaluate(()=>(window as any).requested.sort.key),'size');assert.equal(await p.locator('tbody [data-row]').count(),8);});
 await run('Column resizing supports keyboard and pointer; sticky columns remain aligned',async()=>{await mount('optical-matrix');const grip=p.locator('[data-resize=name]');await grip.focus();const initial=Number(await grip.getAttribute('aria-valuenow'));await p.keyboard.press('ArrowRight');assert.equal(Number(await grip.getAttribute('aria-valuenow')),initial+12);await p.keyboard.press('Home');assert.equal(Number(await grip.getAttribute('aria-valuenow')),88);const r=(await grip.boundingBox())!;await p.mouse.move(r.x+r.width/2,r.y+r.height/2);await p.mouse.down();await p.mouse.move(r.x+85,r.y+4);await p.mouse.up();assert.ok(Number(await grip.getAttribute('aria-valuenow'))>100);assert.equal(await p.locator('tbody [data-first-column]').first().evaluate(e=>getComputedStyle(e).position),'sticky');});
 await run('All skins keep page width at 320/390/768; native table overflows only inside its scroll area',async()=>{for(const width of [320,390,768]){await p.setViewportSize({width,height:950});for(const r of f.records){await mount(r.id);const overflow=await p.evaluate(()=>document.documentElement.scrollWidth-window.innerWidth);assert.ok(overflow<=1,`${r.id} at ${width}: ${overflow}px`);}}});
 for(const other of p.context().pages())if(other!==p)await other.close();await p.bringToFront();
 await run('Popovers and modal frames stay within a small viewport; Escape closes only the active layer',async()=>{await p.setViewportSize({width:390,height:750});for(const r of f.records.filter(x=>['commands','contextmenus'].includes(x.category))){await mount(r.id);await p.evaluate(()=>(window as any).api.open());const selector=r.category==='commands'?'dialog[open]':'.wb-context-panel';await p.waitForTimeout(700);const box=(await p.locator(selector).boundingBox())!;assert.ok(box.x>=-1&&box.x+box.width<=391,r.id+' '+JSON.stringify(box));assert.ok(box.y>=-1&&box.y+box.height<=751,r.id+' '+JSON.stringify(box));await p.keyboard.press('Escape');assert.equal((await state()).open,false);}});
 await run('Reduced motion keeps input and actions working; unmount aborts work and releases modal locks',async()=>{await p.emulateMedia({reducedMotion:'reduce'});await mount('aperture-command');await p.evaluate(()=>(window as any).api.open());assert.equal(await p.locator('.sop-wb').getAttribute('data-wb-reduced'),'true');await p.evaluate(()=>(window as any).unmount());assert.equal(await p.evaluate(()=>document.documentElement.style.overflow),'');await mount('parallax-search');await p.locator('input').fill('design');assert.equal((await state()).results,1);await p.evaluate(()=>(window as any).unmount());assert.equal(await p.locator('#host *').count(),0);await p.emulateMedia({reducedMotion:'no-preference'});assert.deepEqual(errors,[]);});
 console.log(`Workbench browser checks: ${passed.length} passed.`);
}finally{fs.writeFileSync(path.join(f.out,'browser-results.json'),JSON.stringify({mode:offline?'actual Chromium / offline source fixture; Vite not executed':'Vite HTTP',passed:passed.length,tests:passed,errors},null,2));await browser?.close();await closeServer?.();}
