import{parse as parseCSS}from'postcss';
import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import{buildCatalog,ROOT}from'../../../scripts/catalog.ts';import{getDelivery}from'../../../src/catalog/delivery.ts';
const batch=process.argv[2],round=process.argv[3]??'1',work=path.join(ROOT,'docs/design-refinement-225'),dir=path.join(work,'batches',batch),targets=JSON.parse(fs.readFileSync(work+'/targets.json','utf8')).filter((r:any)=>r.batch===batch),snap=path.join(dir,'snapshot','round-'+round);if(fs.existsSync(snap))throw new Error('Immutable snapshot already exists: '+snap);const hashes:Record<string,string>={};
const parts=buildCatalog(ROOT,targets.map((r:any)=>r.id),{appearance:false}).parts;let imports='';
for(const r of targets)parseCSS(fs.readFileSync(path.join(ROOT,'src/parts',r.category,r.id,'styles.css'),'utf8'),{from:r.id+'/styles.css'});fs.mkdirSync(snap,{recursive:true});
for(const[r,a]of targets.map((r:any)=>[r,parts.find(p=>p.id===r.id)] as const)){const base=path.join(ROOT,'src/parts',r.category,r.id);fs.cpSync(base,path.join(snap,'source',r.id),{recursive:true});const walk=(p:string)=>{for(const f of fs.readdirSync(p,{withFileTypes:true})){const q=path.join(p,f.name);if(f.isDirectory())walk(q);else hashes[path.relative(ROOT,q)]=crypto.createHash('sha256').update(fs.readFileSync(q)).digest('hex')}};walk(base);const d=getDelivery(a!,'js','portable');for(const f of d.files){const q=path.join(snap,'exports',a!.id,f.name);fs.mkdirSync(path.dirname(q),{recursive:true});fs.writeFileSync(q,f.code)}const i=parts.indexOf(a!);imports+=`import{init as i${i}}from'./exports/${a!.id}/${d.entry}';import'./exports/${a!.id}/${d.stylesheet}';\n`}
fs.writeFileSync(snap+'/entry.js',imports+`window.apis={};for(const a of [${parts.map((a,i)=>`{id:${JSON.stringify(a.id)},markup:${JSON.stringify(a.markup)},init:i${i}}`).join(',')}]){const h=document.querySelector('[data-part="'+a.id+'"] .art');h.innerHTML=a.markup;window.apis[a.id]=a.init(h.firstElementChild)}window.ready=true;`);
fs.writeFileSync(snap+'/index.html','<!doctype html><html lang="ja"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="icon" href="data:,"><style>*{box-sizing:border-box}body{margin:0;padding:24px;background:#eef0f1;color:#263343;font:14px system-ui}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,350px),1fr));gap:24px}section[data-part]{min-width:0;border:1px solid #c9d0d7;background:white}h2{margin:0;padding:12px;font-size:15px}.art{min-height:210px;padding:24px;display:flex;align-items:center;justify-content:center;background:#181d23;color:#eee}.art>*{max-width:100%}</style><div class="grid">'+targets.map((r:any)=>`<section data-part="${r.id}"><h2>R${String(r.number).padStart(3,'0')} ${r.name}</h2><div class="art"></div></section>`).join('')+'</div><script type="module" src="./entry.js"></script>');
const manifest={batch,round,created:new Date().toISOString(),ids:targets.map((r:any)=>r.id),sourceHashes:hashes};fs.writeFileSync(snap+'/manifest.json',JSON.stringify(manifest,null,2));fs.writeFileSync(dir+'/review-input-'+round+'.json',JSON.stringify(manifest,null,2));const state=JSON.parse(fs.readFileSync(dir+'/status.json','utf8'));state.state='reviewing';state.sourceHashes=hashes;state.reviewRounds.push({round:Number(round),snapshot:path.relative(ROOT,snap),state:'pending'});fs.writeFileSync(dir+'/status.json',JSON.stringify(state,null,2)+'\n');console.log(JSON.stringify({batch,round,parts:targets.length,snapshot:snap}));
