import json,hashlib
from pathlib import Path
p=Path(__file__).parent;root=p.parents[3];inp=json.load(open(p/'review-input-3.json'));checks={f:hashlib.sha256((root/f).read_bytes()).hexdigest()==h for f,h in inp['sourceHashes'].items()};data=json.load(open(p/'measurements-3.json'))
notes={430:'親パスから明朝の章見出しへつなぐ配置は読書用途に合う。省略メニュー内の長い階層名が収まらない。',436:'ピルから穴付きの矩形札へ進んだが、輪が穴を通る前後関係はまだ弱い。共有nativeフォーム契約も修正が必要。',437:'ラベルと凹んだ数値窓を別面へ分け、計器札としての意味が読み取れる。造形を維持して共有nativeフォームを修正したい。',439:'コの字金具の幅を抑え、札との重なりと読み面の余白が釣り合った。共有nativeフォームの修正が必要。',442:'十字の主張が細い基準線へ抑えられ、切欠きと文字位置の関係が明快。共有nativeフォームの修正が必要。',443:'読み面を平らに保ち、背後へ折り返す短い末端が接続するため旧単なる矩形札と区別できる。共有nativeフォームの修正が必要。',445:'近接画像で紙肌と活字、下端の厚み、選択時の浅い押込みが読める。造形の方向は成立。共有nativeフォームの修正が必要。',450:'本文に添える索引語という B の用途差はあるが、件数可読性と長いラベルの収まり、共有nativeフォームが未完成。',458:'短い布帯の中央に数値、左右へキーを保ち、320pxでも極端に細長い腰にならない。実入力/キー/フォーム/resetも通過。',459:'上下の顎と左右キーは320pxでも連続し、数量操作の形を保つ。galleryに限るhover背景衝突が残る。'}
finds={}
def add(n,k,d,rec,ev):finds.setdefault(n,[]).append(dict(kind=k,description=d,recommendation=rec,evidence=ev))
for n in [436,437,439,442,443,445,450]:
 add(n,'native_form','init({name:"tags",selectable:true,removable:true,defaultValue:["ready"]})でdesignをSpace選択するとAPIは["ready","design"]だが、checkboxのnameは空、valueは全て"on"、FormDataは空。portable/gallery全14例一致。readOnlyではchecked inputをdisabledにするため送信対象から除外される。選択のたびに旧input.isConnected=falseとなる置換も確認。','nameとitem.valueをnative checkboxへ反映し、readOnlyは操作を止めつつ選択値を送信できる契約にする。安定キーでnative要素を保持する実装を推奨。削除→resetで既定readyが戻る既存成功も維持する。',['measurements-badges-native-3.json','measurements-badges-3.json'])
add(436,'design_judgment','通常・hover・選択の近接画像では輪の全周が札の手前に現れ、穴がどこで輪を受けるかが判然としない。穴付き札へ進んだものの、縁に楕円を添えた印象が残る。これは操作不具合ではなく A の物理接点の読み取りに関する判断。','穴と輪の交差位置を揃え、輪の一部を紙の背面へ隠し、穴から手前へ出る接点を見せる。紙面・文字の余白と小型タグの比率を保つ。',['evidence-3/loop-label-tags-portable-rest.png','evidence-3/badges-portable-native-1-sheet.jpg'])
add(430,'overflow','省略メニューで空白なし階層名 LongUnbrokenProjectIdentifier1234567890 を2回連結すると折り返されず、panel clientWidth238 / scrollWidth447。portable/gallery、LTR/RTL/forcedで末尾が欠ける。','メニューとリンクを縮小可能にしoverflow-wrap:anywhereなどで文字を面内へ折り返す。',['evidence-3/breadcrumbs-portable-menus-1-sheet.jpg','evidence-3/breadcrumbs-gallery-menus-1-sheet.jpg','measurements-breadcrumbs-long-3.json'])
add(450,'contrast','件数8/4は11pxのrgb(117,98,70)にopacity .7がかかり、実背景合成で通常3.047:1、選択面では2.755:1。portable/gallery一致。','件数は有効な情報として4.5:1以上へ。opacityを外し必要なら専用色で穏やかな強弱を保つ。',['contrast-summary-3.json','evidence-3/badges-portable-native-2-sheet.jpg'])
add(450,'overflow','LongUnbrokenProjectIdentifier1234567890がタグ内で折り返されない。portable root222pxでは文字が左右約53/37px、RTLは37/53pxはみ出す。gallery235pxでも左右約46/31px。削除付きでも横溢れが残りforced画像でもタグ末尾が欠ける。','タグ/ラベルをmin-width:0,max-width:100%で制限し、長い語を折り返し、件数と削除を面内に残す。',['measurements-3.json','measurements-badges-3.json','evidence-3/badges-portable-native-2-sheet.jpg','evidence-3/badges-gallery-native-2-sheet.jpg'])
add(459,'gallery_hover_contrast','actual galleryで＋hover完了後、24px白記号に対し背景がcolor(srgb .832353 .866863 .880196)へ変わり比率1.378:1。解除でrgb(99,133,147)へ戻り3.957:1。portableはhoverでも3.957:1。後続number CSS内の広域 .sop-foundation .ff-stepper > button:hover:not(:disabled) がbackground color-mixを適用している。','この部品のhover面を十分な優先度で固定/調整するか、共通hoverが個別の素材面を上書きしないよう範囲を修正する。galleryとportable双方の往復で確認。',['measurements-hover-r459-3.json','contrast-summary-3.json','evidence-3/open-jaw-number-gallery-hover.png'])
parts=[]
for row in data:
 if row['mode']!='portable':continue
 n=row['number'];cat=row['category'];group=2 if n in [443,445,450] else 1;ev=[f'evidence-3/{cat}-{mode}-{tag}-{group}-sheet.jpg' for mode in ['portable','gallery'] for tag in ['base','menus' if cat=='breadcrumbs' else 'native']]
 parts.append(dict(id=row['id'],number=n,verdict='changes_required' if n in finds else 'pass',note=notes[n],findings=finds.get(n,[]),evidence=ev,reviewed=['round3 immutable portable + actual gallery CSS frozen fixture','rest/hover entry exit reentry returned','320 / long label / RTL / forced / reduced',{'badges':'native Space selection / remove / FormData / readonly / disabled / display mode / reset / node identity','numbers':'native name/FormData / increment / ArrowUp / typed commit / invalid / Escape / Home End / reset new bounds / readonly disabled / long unit','breadcrumbs':'expanded menu / hover link / long name / Enter navigation / Escape focus return / disabled'}[cat]]))
r=dict(batch='B013',round=3,overall='changes_required',parts=parts,coverage={'parts':10,'pass':1,'changes_required':9,'sourceHashesMatchAtFinalization':all(checks.values()),'changedAfterCapture':[f for f,v in checks.items() if not v],'viewedSheets':sorted(str(f.relative_to(p)) for f in (p/'evidence-3').glob('*-sheet.jpg')),'dependencyNote':'7タグはsrc/shared/foundation/navigation.tsのmountBadgesを実際に使用。sequence/badges.tsのreset修正とは別経路。shared変更後はB011/B012のfreezeと依存確認が必要。','scope':'特定条件の実操作・実画像検査。造形判断と再現不具合を区別。無欠陥保証ではない。'},evidence=['measurements-3.json','measurements-badges-3.json','measurements-badges-native-3.json','measurements-numbers-3.json','measurements-breadcrumbs-long-3.json','measurements-hover-r459-3.json','contrast-summary-3.json'])
(p/'review-3.json').write_text(json.dumps(r,ensure_ascii=False,indent=2)+'\n')
lines=['# B013 round3 独立検査','', '**changes_required — 1件 pass（R458）/ 9件差戻し。**','', '全10件を凍結portableと実galleryで実操作。16比較画像と候補の近接画像を視認した。作者変更は行っていない。タグ7件はSEQUENCEではなく共有navigation.tsの既存mountBadgesを使用する。','']
for q in parts:
 lines += [f"## R{q['number']:03} {q['id']} — {q['verdict']}",'',q['note'],'']
 for f in q['findings']:lines += [f"- **{f['kind']}**: {f['description']} 改善案: {f['recommendation']}"]
 lines += ['', '証拠: '+', '.join(f'[{Path(e).name}]({e})' for e in q['evidence']),'']
lines+=['## 検査条件','', '通常/hover往復、320px、長文、RTL、forced/reducedを全件確認。タグはnative選択・削除・FormData・readonly/disabled・表示モード・resetを検査。数量は3→4→5、12.5入力→13、無効文字のnative検証、Escape、Home/End、reset3とbounds変更後4を確認。パンくずはリンクとEscape復帰を検査。フォームfixtureはEnter送信でページ遷移しないようsubmitの既定動作のみ抑止。','', 'R459の通常記号は24pxで3.957:1を満たすが、gallery hover1.378:1は不足。配布全形態での再現とは断定していない。R436の物理接点は造形判断として分離した。共有navigation変更後はB011/B012の依存ハッシュ更新と対象外関数不変・実操作の再確認が必要。','', '特定条件の検査であり、全状態の無欠陥保証ではない。']
(p/'review-3.md').write_text('\n'.join(lines)+'\n');print('saved 1 pass / 9 changes_required; hashes',all(checks.values()))
