import json
from pathlib import Path
p=Path(__file__).parent
parts=[x for x in json.loads(Path('docs/design-refinement-225/targets.json').read_text()) if x['batch']=='B015']
notes={490:'縦長肖像と明朝氏名・上下罫で著者一覧の用途は明快。氏名/イニシャルはhover往復で固定。ただしforced選択氏名が消失する。',491:'丸い封印の厚みと濃い確定輪郭で一列の尺度を読める。角張ったR496との差も成立。',492:'連続する厚い台に検査札が差さる構造は成立。forced時だけ旧座標が残り星が枠と交差する。',493:'一本の桁から接続する折り札が五段階を連続させ、狭幅でも吊り構造を保持。',494:'半楕円の開口と二脚が石のアーチとして読め、三角旗状の誤読を解消。',496:'上下の位置決め切欠きと角面・青灰色で、金色の封印R491との同形を回避。',497:'細い柱と一本のレールが信号の五段階を結び、塗り/確定縁が実値と対応。',498:'横布と留め帯、上下の縫い目の構造は成立。ただし選択星と布のコントラスト不足。',499:'小さいC形留具と前の星札の接点は明快。ただしforcedの星縮小と通常星の低コントラストが残る。',500:'駒形の肩・下面の厚みが一列の評価札として成立。ただし選択星と駒面のコントラスト不足。'}
findings={490:[{'kind':'forced_colors_visibility','description':'forced-colorsで選択行はHighlight、氏名は白いtext backplate上で白文字となり消失。初期Sora/選択Rin、portable/gallery、React4形式で再現。','recommendation':'選択行と子の文字/背景/forced-color-adjustを一貫させ、氏名を明示的なHighlightText/Highlight面に保つ。','evidence':['evidence-2/warm-author-profile-portable-forced-default.png','evidence-2/warm-author-profile-gallery-forced-selected-rin.png','measurements-focused-forced-2.json']},{'kind':'design_readability','description':'root222pxでは外22px+stage20pxの二重余白で氏名列72px。長い日本語氏名は134px高、英語連続名は161px高へ細分化。操作不能/overflowではなくBの可読性改善案。','recommendation':'肖像を保持してstage内余白を整理し、氏名へ横幅を戻す。','evidence':['evidence-2/avatars-portable-base-1-sheet.jpg','measurements-2.json']}],492:[{'kind':'forced_colors_geometry','description':'root222pxでforced札幅22.80pxに対し星SVG14.55pxが札左端より2.59px外へ出て、星と縁が交差。通常は幅20.16pxで中央。旧left:calc(50% - 14px)が縮んだ星に残る。','recommendation':'forcedも星の幅に対応した中央配置へ変更。','evidence':['evidence-2/inspection-score-rating-portable-focused-forced.png','measurements-focused-ratings-2.json']}],499:[{'kind':'forced_colors_geometry','description':'forcedだけ旧左22px insetが残る。root222pxで札幅10.80px、星SVG6.16px（通常19.83px）。gallery251pxでも星10.20pxとなり、値記号の形が読みにくい。','recommendation':'装飾を除いたforced面のinsetを再設定し、星の可読寸法を確保。','evidence':['evidence-2/open-bracket-rating-portable-focused-forced.png','measurements-focused-ratings-2.json']}]}
colors={498:('#86608c','#c9aace',2.490),499:('#9b5b2e','#d9b48d',2.765),500:('#996b25','#d5b36c',2.340)}
for n,(fg,bg,ratio) in colors.items():findings.setdefault(n,[]).append({'kind':'nontext_contrast','description':f'評価値を示す選択星{fg}と実面{bg}が{ratio:.3f}:1で3:1未満。portable/gallery両方でcomputedとスクリーンショットの実ピクセルを照合。','recommendation':'素材の面を保持し、選択星を濃くして少なくとも3:1を確保。','evidence':['contrast-stars-2.json','measurements-star-pixels-2.json',f"evidence-2/{next(x['id'] for x in parts if x['number']==n)}-portable-focused-normal.png"]})
rows=[]
for x in parts:
 n=x['number'];rows.append({'id':x['id'],'number':n,'verdict':'changes_required' if n in findings else 'pass','note':notes[n],'findings':findings.get(n,[]),'evidence':[f"evidence-2/{x['id']}-portable-rest.png",f"evidence-2/{x['id']}-gallery-narrow.png",f"evidence-2/{x['id']}-react-forced.png",'measurements-2.json','measurements-react-2.json','measurements-avatars-2.json' if n==490 else 'measurements-ratings-2.json'],'reviewed':{'portable':True,'actualGallery':True,'hoverEntryExitReentry':True,'narrow320':True,'longLabelRTL':True,'forcedReduced':True,'native':True,'reactFormats':['tsx-portable','jsx-original','tsx-original','jsx-portable']}})
coverage={'source':'round-2 immutable snapshot; browser開始/終了時source100hash一致、修正release前に終了記録','hash':'hash-verification-2.json','counts':{'parts':10,'pass':5,'changes_required':5,'primaryModeCases':20,'nativeRatingsModeCases':18,'nativeAvatarModeCases':2,'reactPlacements':40},'visualSheets':[str(f.relative_to(p)) for f in sorted((p/'evidence-2').glob('*sheet.jpg'))],'visualScope':'全10件を通常/hover/320/RTL/forced、native選択/clear/10段階/RTL末尾、React実配布の画像で視認。入口40ms/退出60ms/再進入60msは計測も参照。全状態/環境の無欠陥保証ではない。','nativeRatings':'値3のpreview5→退出復帰、選択4/矢印5/Home1/End5/clear0/reset3、readonly値/送信維持、disabled送信除外、requiredclear非表示、controlled2維持、max10末尾Space/矢印/LTR/RTL、max2clamp、forced4/0が18ケースで一致。React4形式も5/clear0/controlled2/10を確認。','avatar':'Space→Rin/Enter→Nao/resetSora、controlledSora、disabled、表示専用、長名/RTL、React選択を確認。8文字initialsはストレス入力として記録、通常2文字の評価と区別。','motion':'全20primaryケースreduced時animations空。通常hover往復で文字/操作位置の新たな移動なし。','contrast':'通常テキスト最小4.806:1。星は実面合成/ピクセル照合、R498/499/500のみ3:1未満。','fixture':'portable frozen initとgallery実CSSを併用。nativegalleryは実root cloneをformへ入れfrozen initで初期化。Reactは実export4形式をViteで実行。'}
out={'batch':'B015','round':2,'overall':'changes_required','parts':rows,'coverage':coverage};(p/'review-2.json').write_text(json.dumps(out,ensure_ascii=False,indent=2)+'\n')
md='# B015 round 2 独立検査\n\n5 pass / 5 changes_required。source100ファイルは全計測後・作者release前にも一致。\n\n'
for r in rows:
 md+=f"- R{r['number']} {r['id']}: **{r['verdict']}** — {r['note']}\n"
 for f in r['findings']:md+=f"  - {f['kind']}: {f['description']} 改善: {f['recommendation']}\n"
md+='\n通常・hover入口/解除/再進入、320px・長文・RTL、forced/reduced、native値/フォーム/keyboard/reset/controlled、React4配布形式を検査。全件実画像を視認。詳しい条件と証拠は review-2.json。通常テキスト最小4.806:1。ratingのpreviewは未確定値で、outputは確定値のままという契約を区別した。\n\nR490の狭幅余白はデザイン可読性の指摘であり操作不能とは判定していない。Aの素材構造は全9件で成立し、今回の差戻しは再現する表示の残存問題。特定条件での検査であり無欠陥保証ではない。\n'
(p/'review-2.md').write_text(md)
print('saved',len(rows))
