from pathlib import Path
import json,hashlib,shutil
p=Path('docs/design-refinement-225/batches/B017');manifest=json.load(open(p/'review-input-4.json'));mismatch=[f for f,h in manifest['sourceHashes'].items() if hashlib.sha256(Path(f).read_bytes()).hexdigest()!=h];assert not mismatch
shutil.copyfile('docs/design-refinement-225/batches/B018/captures/main/clear-process-timeline-normal.png',p/'evidence-4/comparison-B569-normal.png')
primary=json.load(open(p/'measurements-4.json'));native=json.load(open(p/'measurements-native-4.json'));colors=json.load(open(p/'measurements-colors-4.json'));react=json.load(open(p/'measurements-react-4.json'));assert len(primary)==20 and len(native)==14 and len(colors)==6 and len(react)==44
assert not any(x.get('error') or any(not c['pass'] for c in x.get('checks',[])) for x in native+colors+react+primary)
notes={523:'短い二股リボンを独立した色見本として並べ、上端の留め・折り線・外に出したコードで積層帯から構造を分離。Bのコード付き候補行/RGB編集面とも用途と造形の違いが明確。',528:'名前を読みながら似たテーマ色を選べる候補行はBとして成立。44pxの軸操作・12pxの値は改善したが、エラー説明の可読性とforced長文見出し時の現在色見本を修正する。',530:'大きなSV面とRGB編集、額縁付き候補の組みで制作向けBの用途を示す。エラーの淡い文字と、長文見出しによる現在色見本の縮みが残る。',536:'白い写真縁と台紙の余白、左の注記罫が一枚の写真記録としてつながる。待機から実内容へ同じ組版を保持し、B550の著者先行カードとは順序・写真の扱いを分離。',539:'図版と注記を二列にしたが、全体は外周細枠の平面カード。狭幅では一般的な図版上段カードになり、Aとしての開放格子の構造が弱い。',541:'小図版＋右見出し→本文→下部項目はB548と同じ読み順。番号・横罫・明朝・紙色を加えた差が中心で、Aの再設計として構造差が不足。',548:'小図版を見出し横に置く低いプレビューはBの用途として成立するが、長い見出しと著者名が狭幅で切れる。',550:'著者・見出しを先に読む記事型BとしてR548と情報順序を分離したが、長い見出し・著者名が切れる。',556:'余白へ引き出す実日付と、注記から本文へ続く折れた罫が記録帳の構造として成立。展開後の本文・実日付・statusも保持する。',557:'連番・時刻・見出し・status・展開本文を縦へ置く青いログ面。B569との比較で情報の配置と開閉構造がほぼ同じで、主な差は色/書体/罫に留まる。'}
def finding(kind,description,recommendation,evidence):return dict(kind=kind,description=description,recommendation=recommendation,evidence=evidence)
finds={528:[finding('contrast','不正HEXの説明#ffd1c5が実背景#f6edf4上で1.208:1。実gallery/portable双方で読み取り困難。','エラー説明を実背景に対して4.5:1以上の文字色にし、通常/狭幅/forcedを確認する。',['contrast-summary-4.json','evidence-4/soft-theme-color-gallery-color-error.png']),finding('long_label_swatch_collapse','長文見出し＋320px＋forcedで現在色見本の幅がportable11.06px/gallery12.66pxへ縮む（通常60px）。','forcedにも見本の最小幅とflex-shrink:0を適用し、見出し側を折り返す。',['measurements-focused-colors-4.json'])],530:[finding('contrast','不正HEXの説明#ffd1c5が実背景#f6efdf上で1.208:1。実gallery/portable双方で再現。','実背景に合う濃いエラー文字と十分な文字寸法へ。',['contrast-summary-4.json','evidence-4/warm-studio-color-gallery-color-error.png']),finding('long_label_swatch_collapse','320pxの長い見出しで現在色見本が29pxからportable8.02px/gallery9.05pxへ縮む。forcedも11.06/12.66px。','現在色の最小幅を保持し、見出しを残り幅で折り返す。',['measurements-focused-colors-4.json','evidence-4/warm-studio-color-portable-focused-long.png'])],539:[finding('design_review_judgment','外周枠の二列カードが中心で、Open Gridの開いた構造が実画像から十分に読めない。機能不具合とは別のA造形の評価。','外周の箱を解き、図版・注記・本文の間を実際に背景へ開き、開放辺/交差する格子で関係を作る。',['evidence-4/review-539-sheet.jpg'])],541:[finding('design_review_judgment','B548と小図版付き見出し・本文・下部項目の骨格を共有し、番号と罫以外のA構造差が不足。','図版付きカードを離れ、実件数を示す索引と独立レコードを構成要素にして読み込み前後を対応させる。',['evidence-4/review-541-sheet.jpg','evidence-4/review-548-sheet.jpg'])],548:[finding('long_content_clipping','320pxの長い見出し/著者名がrootからはみ出してclipされる。見出し超過portable132.3px/gallery103.3px、RTLでは左側同量。forcedもportable48.3px/gallery19.3px超過。','profile内の文字列へmin-width:0と折返しを適用し、狭幅では必要に応じ図版との並びを変える。forcedでも保持する。',['measurements-4.json','evidence-4/review-548-sheet.jpg'])],550:[finding('long_content_clipping','長い見出しがroot222pxで41.8px、gallery251pxで12.8pxはみ出して切れる。RTLは左側へ、forcedも38.8/9.8pxの超過。','著者/見出し列を縮小可能にして長い語を折り返す。画像や本文だけの折返しでは解消しない。',['measurements-4.json','evidence-4/review-550-sheet.jpg'])],557:[finding('design_review_judgment','太い筐体は除去されたが、B569の連番・時刻・見出し・status・展開本文とほぼ同じ配置。Aとしてログの別の構造を示す改善が不足。','時刻専用レーン、連続するログ記録と展開領域の接続など、ログを読む目的に対応した骨格へ再構成する。',['evidence-4/review-557-sheet.jpg','evidence-4/comparison-B569-normal.png'])]}
parts=[]
for x in json.load(open('docs/design-refinement-225/targets.json')):
 if x['batch']!='B017':continue
 n=x['number'];parts.append({'id':x['id'],'number':n,'verdict':'changes_required' if n in finds else 'pass','note':notes[n],'findings':finds.get(n,[]),'evidence':[f'evidence-4/review-{n}-sheet.jpg','measurements-4.json','measurements-react-4.json','contrast-summary-4.json','measurements-colors-4.json' if x['category']=='colors' else 'measurements-native-4.json'],'reviewed':{'round':4,'portable':True,'actualGallery':True,'hoverEntryExitReentry':True,'narrow320LongRTL':True,'forcedReduced':True,'native':True,'react4Formats':True,'ABVisualComparison':True}})
coverage={'primaryRows':20,'nativeRows':14,'nativeChecks':sum(len(x['checks'])for x in native),'colorsRows':6,'reactPartsFormats':40,'reactChecks':sum(len(x.get('checks',[]))for x in react),'runtimeErrors':0,'sourceHashesMatched':100,'pendingRequiredMeasurements':[],'limitations':['Chromiumの指定状態に対する検査であり無欠陥保証ではない。','Reactの長文全組合せは再実行していない。長文の不具合は同作者CSSの実gallery/portableで実測した。','初期のcolor長文写真に並行撮影名衝突があったためcolors-primary-4とcolors-4の-color-接頭辞で再撮影。判定には再撮影とfocused-colorsの証拠を用いた。']}
(p/'hash-verification-4.json').write_text(json.dumps({'sourceHashesMatched':100,'mismatches':mismatch,'snapshotInternalHashes':{str(f.relative_to(p/'snapshot/round-4')):hashlib.sha256(f.read_bytes()).hexdigest()for f in (p/'snapshot/round-4').rglob('*')if f.is_file() and '/internal/'in str(f)}},indent=2))
out={'batch':'B017','round':4,'overall':'changes_required','parts':parts,'coverage':coverage};(p/'review-4.json').write_text(json.dumps(out,ensure_ascii=False,indent=2)+'\n')
lines=['# B017 round 4 独立検査','', '3 pass / 7 changes_required。作者・共有ソースは変更していない。','', '実gallery/portableの通常・hover入口/解除/再進入・320px・長文・RTL・forced/reduced、色入力のHEX/実値/form/reset/controlled、skeletonのslot保持/焦点復帰/rows/破棄、timelineのEnter/Space/disabled/controlled/reset/項目更新を確認。React 4形式×10件も実操作を確認し、runtimeエラー無し。作者100hashは凍結版に一致。','', '| ID | 判定 | 根拠 |','|---|---|---|']
for x in parts:lines.append(f'| R{x["number"]} | {x["verdict"]} | {x["note"]} |')
lines+=['','確定した再現不具合: R528/R530のエラー文字1.208:1、現在色見本の長文時縮小、R548/R550の見出し・著者名clip。Aの造形判断: R539/R541/R557。造形判断はブラウザ故障とは区別する。','','未完の必須計測はない。React長文全組合せは未実行で、同CSSのgallery/portableで確認した。初期colors画像名の衝突は接頭辞を分けて再撮影した。','', '個別数値・改善案・根拠は [review-4.json](review-4.json)。']
(p/'review-4.md').write_text('\n'.join(lines)+'\n');print('saved 3 pass /7 changes_required',coverage)
