from pathlib import Path
import json,hashlib
p=Path(__file__).parent;m=json.load(open(p/'review-input-11.json'));bad=[f for f,h in m['sourceHashes'].items()if hashlib.sha256(Path(f).read_bytes()).hexdigest()!=h];assert not bad;(p/'hash-verification-final-11.json').write_text(json.dumps({'authorHashesMatched':100,'sharedHashesMatched':1,'mismatches':bad},indent=2)+'\n')
allrows=[]
for name,count in [('tables',14),('navigation',4),('loader',2),('react-navigation',12),('react-tables-loader',36)]:
 d=json.load(open(p/f'measurements-{name}-11.json'));assert len(d)==count;allrows+=d
assert not any(r.get('error')or r.get('errors')or any(not c['pass']for c in r.get('checks',[]))for r in allrows)
r=json.load(open(p/'review-9.json'));r.update(round=11,overall='changes_required')
notes={669:'強制配色の6項目幅は改善。通常dockはcolumnへ160px basisが高さとして作用し、巨大な縦空白が残る。',670:'連番と項目の24px間隔、dock折返し、badge12pxを確認。6項目/長文/RTL/forcedを維持。',673:'折面の構造を維持。長いstatusはセル内、ソート記号/進捗文字のコントラストを改善。',679:'独立した見出し・検索・記録紙を保持。長いstatusはセル内、ソート記号が明瞭。',683:'通しリボンと支持帯の構造を維持。長いstatusとソート/進捗の可読性を改善。',684:'通常の一体陶トレーは成立。forcedで旧操作列の巨大な太枠が復活するため境界寸法を修正。',688:'進行状況を読むBとして、12pxの補助文字/状態/総数を整理。長い見出しとstatusの切れを解消。',689:'比較しやすい格子のBとして、12px補助文字と長文折返しを維持。',690:'資料一覧向けの書体と見出し構成を維持。12px補助文字、長い見出し/status折返しを確認。',696:'固定基部と六つの筒の伸縮をforcedでも維持。周期・停止・reduced・長文・Reactを確認。'}
for x in r['parts']:
 n=x['number'];x.update(verdict='pass',findings=[],note=notes[n],evidence=['measurements-navigation-11.json'if n<673 else'measurements-loader-11.json'if n==696 else'measurements-tables-11.json',f'evidence-11/sheet-{x["id"]}.jpg']);x['reviewed']['round']=11
 if n==669:x.update(verdict='changes_required',findings=[{'kind':'dock_column_basis_height_regression','description':'通常配色dockの旧flex-direction:columnに、新しいli flex-basis:160pxが高さとして作用。6項目が各160px高となり、約40pxの内容間に過大な縦空白。1100/320双方。forcedはrowで各40px。横幅最小値のみの検査では発見できない。','recommendation':'dockリストをrowへ明示して幅基準の折返しにするか、columnを保つならbasis:autoにして行の高さを内容へ戻す。','evidence':['measurements-dock-height-forced-11.json','evidence-11/layouts-sheet-clear-line-navigation.jpg','evidence-11/dock-height-1100-normal.png']}])
 if n==684:x.update(verdict='changes_required',findings=[{'kind':'forced_obsolete_action_column_geometry','description':'新操作列の規則がforced-colors:noneに限られ、forcedで旧16px/40pxの左右枠・最終行24px底枠/72px丸角が復活。巨大な黒い取手が操作列を囲み、通常の一体トレーから意図しない過大境界へ変わる。fresh portable、gallery、RTLで確認。機能失敗ではなく表示構造の不整合。','recommendation':'操作列の新width/min-width112px、padding12px、border-inline0/radius0と見出し/終行境界の規則をforcedにも適用。色はsystem色のまま。','evidence':['measurements-ceramic-forced-11.json','evidence-11/ceramic-register-table-portable-forced.png','evidence-11/ceramic-register-table-gallery-forced.png','evidence-11/fresh-sheet-ceramic-register-table.jpg']}])
r['coverage']={'authorHashesMatched':100,'sharedHashesMatched':1,'nativeChecks':290,'reactChecks':196,'reactPlacements':40,'tableFreshConditions':56,'navigationLayouts':64,'numberSpacingConditions':4,'dockHeightConditions':4,'imagesViewed':['10 primary sheets','7 fresh table sheets /28 states','2 navigation layouts sheets /16 states','30 gallery images /3 sheets','28 React images /3 sheets','R684 forced close','R696 forced close'],'pendingRequiredMeasurements':[],'limitations':['旧10件の指摘は解消。今回はR669の軸方向とbasisの組合せ、R684の旧forced境界を追加検出。','コントラストは実背景の合成を計測。全9文字を持つパーツの対象rest/hover/selected/error等で最小4.611以上。disabledは別扱い。','横スクロールによる列の部分表示は不具合とせず、セル内のbadge領域と外側見出しを検査した。','React長文の全組合せは未実行。同作者CSSをgallery/portableで実査。','特定状態の検査であり無欠陥保証ではない。']}
(p/'review-11.json').write_text(json.dumps(r,ensure_ascii=False,indent=2)+'\n');lines=['# B022 round 11 独立再検査','','8 pass / 2 changes_required。前回の長文/コントラスト/loader forced指摘は解消。R669の通常dock行高とR684のforced旧操作列境界を修正。','','| ID | 判定・根拠 |','|---|---|']+[f'| R{x["number"]} | {x["verdict"]}: {x["note"]} |'for x in r['parts']]+['','gallery/portable native290 checks、React4形式196 checks成功。fresh長文表56条件とnav64配置、全10の画像を実査。作者100＋共有1 hash一致、作者未変更。詳細は[review-11.json](review-11.json)。'];(p/'review-11.md').write_text('\n'.join(lines)+'\n');print('8pass2changes saved')
