from pathlib import Path
import json
p=Path(__file__).parent;hashes=json.load(open(p/'hash-verification-final-9.json'));assert not hashes['mismatches']
files=['measurements-navigation-9.json','measurements-tables-9.json','measurements-loader-9.json','measurements-react-navigation-9.json','measurements-react-tables-loader-9.json'];data=[json.load(open(p/f))for f in files];assert [len(a)for a in data]==[4,14,2,12,36];assert not any(r.get('error')or r.get('errors')or any(not c['pass']for c in r.get('checks',[]))for a in data for r in a)
targets=[r for r in json.load(open('docs/design-refinement-225/targets.json'))if r['batch']=='B022'];finds={r['number']:[]for r in targets}
def f(kind,description,recommendation,evidence):return dict(kind=kind,description=description,recommendation=recommendation,evidence=evidence)
for n in [669,670]:finds[n].append(f('dock_many_item_readability','6項目＋長名のdock、320px forcedで日本語1文字/英字1〜2文字の縦列となり、行先が読みにくい。R670は通常配色のdockでも同様。枠内収まりとは別の項目最小幅不足。','dockの項目幅を保持して折返し/狭幅1列へ。6項目・長文・LTR/RTL・forcedで確認。',['measurements-layouts-9.json',f'evidence-9/layouts-{next(r["id"]for r in targets if r["number"]==n)}.jpg']))
finds[670].append(f('adjacent_number_label_spacing','標準横並びで前項目の名称Range右端と次項目左端が同座標（portable概要右691/次項目左691、gallery678.5/678.5）。次の連番02が名称に接して「概要02」の連続文字列に見える。幾何的な文字重なりとは区別。','項目間または番号列外側に余白を確保し、現在地の薄い面にも名称と番号が安定して収まるようにする。',['measurements-numbers-9.json','evidence-9/warm-editorial-navigation-gallery-ltr-numbers.png']))
bleed={673:243.48,679:201.61,683:243.48,684:243.48,688:147.95,689:139.95,690:217.61};ratios={673:2.974,679:2.817,683:2.438,684:2.516,688:2.151,689:2.069,690:2.032}
for n in bleed:
 id=next(r['id']for r in targets if r['number']==n)
 finds[n].append(f('long_badge_overlaps_adjacent_cells',f'未操作fresh fixtureの長い状態名がnowrapで自セルから{bleed[n]}px横へ突出する（320px通常LTR）。td overflow:visibleのため容量/進捗など隣列へ重なり、横スクロール後も状態文字と数値が混ざる。主gallery/portableとfresh通常/forced・LTR/RTLでも追跡。','状態札のmax-width/min-widthとwhite-space/overflow-wrapを設定し、セル内で読める折返しにする。列の情報を重ねない。',['measurements-table-layout-9.json','measurements-tables-9.json',f'evidence-9/fresh-{id}.jpg']))
 finds[n].append(f('sort_indicator_contrast',f'操作可能な未ソート列を示す↕印が実背景合成{ratios[n]}:1。非テキストの状態/操作記号として3:1未満。B3はopacity0.5が残る。disabledではない。','並べ替え印を実面に対して3:1以上へ。列名文字の4.5:1判定とは区別する。',['contrast-summary-9.json']))
for n,ratio in [(673,4.275),(683,4.318)]:finds[n].append(f('selected_progress_text_contrast',f'選択行の進捗100%は12pxで{ratio}:1。gallery/portableの定常選択面で4.5:1未満。','選択面に対して進捗数値の色を濃くする。',['contrast-summary-9.json','measurements-tables-9.json']))
for n,x in [(688,166.69),(689,112.84),(690,242)]:finds[n].append(f('long_heading_clipping',f'320px fresh fixtureで長い見出しがroot端を{x}px越えて切れる。通常・forcedとLTR/RTLを追跡。表の横スクロールとは別の見出し領域。','見出しのflex min-widthを解放し長語を折返す。長い題名でも表外枠に収める。',['measurements-table-layout-9.json',f'evidence-9/sheet-{next(r["id"]for r in targets if r["number"]==n)}.jpg']))
finds[696].append(f('forced_shape_reverts_to_old_design','通常の基部付き六段筒がforcedでは旧六重矩形へ戻り、同じ伸縮機構として認識できない。新幾何がforced-colors:none内にあるため旧位置/寸法/アニメ規則が復活。gallery/portable/Reactで実画像確認。状態通知やpaused/reducedの機能故障とは区別した造形整合性の指摘。','筒の位置・寸法・共通位相・基部を配色条件から独立させ、forcedでは色と境界だけをシステム色へ。',['evidence-9/sheet-telescopic-stroke-loader.jpg','evidence-9/telescopic-stroke-loader-react-forced.png','src/parts/loaders/telescopic-stroke-loader/styles.css']))
notes={669:'簡潔な側線と密度の高い一覧は実用的。forced dock多項目の可読幅を修正。',670:'章番号と本文で読む用途差は成立。横並びの隣番号との余白、dock多項目を修正。',673:'折面が見出し/検索帯/記録面を連結し、Bの平面表から構造的に分離。長状態札とソート印/選択進捗色を修正。',679:'見出し・操作面・記録紙の独立と開いた外縁が成立。長状態札とソート印を修正。',683:'通したリボンと保持帯、選択時の折返し札が実際の面を支持。長状態札とソート印/選択進捗色を修正。',684:'陶の釉薬縁、側面の持ち手穴、凹面の操作帯が一体の器を作る。長状態札とソート印を修正。',688:'状態と進捗を追う広い行が実用的。長状態札・長題名・ソート印を修正。',689:'列境界と密度の高い照合用途が明快。長状態札・長題名・ソート印を修正。',690:'書名活字と管理札を読む用途差が成立。長状態札・長題名・ソート印を修正。',696:'通常の筒は各位相で基部との接続を保ち、0/3600msが一致。forcedだけ旧矩形へ戻る点を修正。'}
parts=[]
for r in targets:
 n=r['number'];parts.append(dict(id=r['id'],number=n,verdict='changes_required',note=notes[n],findings=finds[n],evidence=[f'evidence-9/sheet-{r["id"]}.jpg','measurements-navigation-9.json'if n<673 else'measurements-loader-9.json'if n==696 else'measurements-tables-9.json'],reviewed={'round':9,'actualGallery':True,'portable':True,'hoverEntryExitReentry':True,'narrow320LongRTL':True,'forcedReduced':True,'native':True,'react4Formats':True,'ABVisualComparison':True}))
coverage={'authorHashesMatched':100,'sharedHashesMatched':1,'hashVerificationBeforeAuthorRelease':True,'primaryRows':20,'nativeChecks':sum(len(r.get('checks',[]))for a in data[:3]for r in a),'reactPartsFormats':40,'reactChecks':sum(len(r.get('checks',[]))for a in data[3:]for r in a),'navLayoutConditions':64,'freshTableConditions':56,'loaderTimelinePhases':[0,900,1800,2700,3600],'imagesViewed':['2 navigation primary sheets /24 states','2 navigation layout sheets /16 states','7 table portable sheets /42 states','7 table gallery sheets /28 states','loader sheet /12 states','3 React sheets /20 states','fresh folded/warm table sheets /8 states','folded forced full image'],'pendingRequiredMeasurements':[],'limitations':['作者ソース参照計測と最終hash保存後にparentへrelease。以後の画像判定は凍結済み証拠のみ。','R670は番号と名称の余白0による可読性指摘で、文字の幾何的重なりとは断定しない。','R696はforced造形の整合性判断で、状態通知の機能故障とは区別。','表の長いセル値は独立した列へ侵入する点を不具合とした。必要な横スクロール自体は不具合ではない。','初回controlled checkbox fixtureはcheck()がchecked維持を待ち続けるためclick()へ修正して全14行再実行。','React長文/全layout組合せは未実行。同作者CSSをgallery/portableで実査。','特定状態のChromium検査であり無欠陥保証ではない。']}
(p/'review-9.json').write_text(json.dumps(dict(batch='B022',round=9,overall='changes_required',parts=parts,coverage=coverage),ensure_ascii=False,indent=2)+'\n');lines=['# B022 round 9 独立検査','','0 pass / 10 changes_required。通常のA構造は成立しているが、各件に残存する表示/可読性の問題を修正する。検査担当は作者未変更。','','| ID | 判定・根拠 |','|---|---|']+[f'| R{x["number"]} | changes_required: {x["note"]} |'for x in parts];lines+=['','表7件の長い状態札が139.95〜243.48pxセル外へ侵入し隣列に重なる。B表3件の長題名も枠外へ切れる。並べ替え印は7件で3:1未満、R673/R683の選択進捗文字は4.5:1未満。navigationのdock多項目とR670の隣番号余白、R696のforced旧造形復活も記録した。','','操作試験はnative '+str(coverage['nativeChecks'])+' checks、React '+str(coverage['reactChecks'])+' checks成功。これは表示上の問題の合格を意味しない。作者100+共有1 hashをrelease直前に照合。必須未完なし。詳細・改善案・証拠は[review-9.json](review-9.json)。'];(p/'review-9.md').write_text('\n'.join(lines)+'\n');print('B022r9 saved',coverage['nativeChecks'],coverage['reactChecks'])
