from pathlib import Path
import json
base=Path('docs/design-refinement-225/batches');p=base/'B016';old=json.loads((p/'review-4.json').read_text());summary=json.loads((p/'start-summary-5.json').read_text());assert not summary['sourceMismatches'];assert all(not r['firstFullyVisible'] and r['diagnosticStartVisible']for r in summary['rows'])
def finding(id,rnd):return {'kind':'overflow_start_inaccessible','description':'max10・320pxで共有rating.cssのjustify-content:centerがgridにも残り、列が両側へあふれる。scrollLeftが先頭端でも1番が可視範囲外/欠け、Homeで値1へ変更しても星/確定位置が見えずポインター到達できない。LTR/RTL・実gallery/portableで再現。','recommendation':'作者のgrid列をjustify-content:startで開始辺へ揃え、先頭/末尾の実ポインター到達性と選択可視性を両方向で検証する。','evidence':[f'measurements-start-{rnd}.json',f'start-summary-{rnd}.json',f'evidence-{rnd}/{id}-portable-start-ltr-first.png',f'evidence-{rnd}/{id}-portable-start-rtl-first.png']}
notes={504:'r4の端の星と縁の重なり、およびmax10の陶面途切れは解消。末尾選択星の背景は平面#dbe7ceへ統一し3.393:1。ただし共通の中央寄せによる先頭到達不能を新規検出。',517:'光学盤とSVの構造・390/320pxの収まりを保持。forcedで3軌道と白境界付き黒thumbが復帰し、色相/彩度/明度・HEX・実ポインターの同期も成立。',520:'試し刷りの紙面・RGB組版行を保持。forcedで3軌道の全幅が描画され、つまみと数値を読める。HEX/エラー/解除/reset/readonly/disabled/controlledも成立。',522:'横長色面と測定レーンの構造を保持。forcedで3軌道の全幅とthumbが可視。通常/狭幅/RTL/keyboard/HEXの値同期も成立。'}
rows=[]
for r in old['parts']:
 n=r['number'];rating=n<517;r['verdict']='changes_required' if rating else 'pass';r['findings']=[finding(r['id'],5)]if rating else [];r['note']=notes.get(n,r['note']+' 造形・通常操作の評価はr4同一作者で継承するが、max10先頭到達不能を新規検出。');r['reviewed']['round']=5;r['reviewed']['focusedStartLTRRTL']=rating;r['reviewed']['fullRecheck']=n in notes
 if n in notes:r['evidence']=[s.replace('evidence-4','evidence-5').replace('-4.json','-5.json')for s in r['evidence']]
 r['evidence']+=['hash-verification-5.json','start-summary-5.json'if rating else 'measurements-focused-colors-5.json'];rows.append(r)
coverage={'source':'snapshot/round-5 / review-input-5.json;全計測終了・作者release前の100sourcehash一致','authorChanges':'r4から504/517/520/522の4CSSのみ、他96作者ファイルと全配布internal共有は同一','inheritedAuthorFiles':60,'fullRecheckParts':[504,517,520,522],'newFocusedStartParts':[501,502,503,504,505,508,510],'newStartConditions':28,'newStartFailedConditions':28,'diagnosticStartVisibleConditions':28,'diagnosticScope':'一時DOM styleのみ、作者ファイル変更なし。診断状態を納品版合格と取り違えない。','previousIssues':'r4の4件指摘はすべて解消。forced3colors×3range×2環境はthumb10pxのみから全76〜123px幅の描画に復帰。R504値5末尾の星cropに濃い縁pixelがなくなった。','runtime':'4件のnative+React4形式を再実行。値/preview/reset/controlled/readonly/disabled/required/HEX/エラー解除/色相輪/SVdragは従来通り。ただし値1へ変更できることと、先頭項目へポインターが届くことを明確に分けて新規指摘した。','imagesViewed':[str(f.relative_to(p))for f in sorted((p/'evidence-5').glob('*sheet.jpg'))]+['evidence-5/ceramic-score-rating-portable-max10-selected.png','evidence-5/ceramic-score-rating-portable-rtl-max10.png','evidence-5/ceramic-score-rating-portable-max2-long.png'],'scope':'既存4件の通常/hover/狭幅/RTL/forced、native操作とReactを画像視認。追加7件の先頭・RTL・DOM診断画像も全件視認。特定状態の検査であり無欠陥保証ではない。'}
(p/'review-5.json').write_text(json.dumps({'batch':'B016','round':5,'overall':'changes_required','parts':rows,'coverage':coverage},ensure_ascii=False,indent=2)+'\n')
md='# B016 round 5 独立再検査\n\n3 pass / 7 changes_required。前roundの4指摘は解消したが、全7ratingsにmax10の先頭到達不能を追加検出。100sourcehash終了時一致。\n\n'
for r in rows:md+=f"- R{r['number']} **{r['verdict']}** — {r['note']}\n"
md+='\n中央寄せがgridに残り、LTRは先頭列が負側へ、RTLは右側へ欠ける。Homeで値1になっても選択星は見えず、外向きscrollでは戻せない。28条件すべてで再現。一時DOMでjustify-content:startへ変えると28条件すべて先頭が可視になる。作者は変更していない。\n\n先の検査は値操作と末尾可視を重視し、先頭pointer到達性の確認が不足していた。B015にも同原因を検出しreview-3-addendumへ記録した。証拠はreview-5.json、start-summary-5.jsonとevidence-5。\n';(p/'review-5.md').write_text(md)
p=base/'B015';old=json.loads((p/'review-3.json').read_text());summary=json.loads((p/'start-summary-3.json').read_text());assert not summary['sourceMismatches'];rows=[]
for r in old['parts']:
 rating=r['number']!=490;r['verdict']='changes_required'if rating else 'pass';r['findings']=[finding(r['id'],3)]if rating else [];r['reviewed']['supplementalStartLTRRTL']=rating
 if rating:r['note']='round3の造形・forced修正評価は維持。ただし追加のmax10先頭到達性検査で中央寄せ起因の非可視/欠けを確定した。';r['evidence']+=['measurements-start-3.json','start-summary-3.json']
 rows.append(r)
out={'batch':'B015','round':3,'supplement':'start-accessibility','overall':'changes_required','parts':rows,'coverage':{'scope':'review-3の合格判定に対する追加検査。旧ファイルを消さず、今回の9差戻しで総括を訂正する。','sourceHashesVerified':100,'conditions':36,'inaccessibleFirstConditions':36,'diagnosticStartVisibleConditions':36,'imagesViewed':['evidence-3/start-1-sheet.jpg','evidence-3/start-2-sheet.jpg','evidence-3/start-3-sheet.jpg'],'reason':'初回検査でキーボードの値と末尾を確認したが、先頭ポインター到達性の確認が不足。追加でLTR/RTL・portable/galleryの全9件に同原因を実証。作者無変更、一時DOM start変更は原因診断だけ。'}};(p/'review-3-addendum.json').write_text(json.dumps(out,ensure_ascii=False,indent=2)+'\n');(p/'review-3-addendum.md').write_text('# B015 round 3 追加検査\n\nR490のみpass継続。R491/492/493/494/496/497/498/499/500はchanges_requiredへ訂正。\n\nmax10の先頭1が中央寄せによってスクロール開始端の外へ隠れ、Homeで値1となっても選択が見えずポインターで届かない。9件×LTR/RTL×portable/gallery=36条件で再現。作者source100hashは同一。一時DOMのjustify-content:startだけで36条件すべて先頭が完全可視になった。作者ファイルは変更していない。\n\n前回はキーボード値と末尾可視を確認したが先頭pointer到達性の確認が不足した。旧review-3の履歴を残し、本補足で総括判定を訂正する。実画像と数値はreview-3-addendum.json、start-summary-3.json、evidence-3/start-*-sheet.jpg。\n')
print('saved B016r5 and B015r3addendum')
