import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {chromium} from 'playwright';import {createServer} from 'vite';import {buildCatalog,ROOT} from '../../../scripts/catalog.ts';import {getDelivery} from '../../../src/catalog/delivery.ts';
const batch=process.argv[2],work=path.join(ROOT,'docs/design-renewal'),rows=JSON.parse(fs.readFileSync(work+'/targets.json','utf8')).filter((r:any)=>r.batch===batch&&r.category==='avatars'),parts=buildCatalog(ROOT,rows.map((r:any)=>r.id),{appearance:false}).parts;assert.ok(parts.length);
const server=await createServer({root:ROOT,cacheDir:path.join(work,'batches',batch,'exports','vite-cache-avatars'),configFile:false,optimizeDeps:{entries:[],noDiscovery:true,include:['react','react-dom/client','react/jsx-dev-runtime']},server:{host:'127.0.0.1',port:0,hmr:false,watch:null}});await server.listen();const browser=await chromium.launch({executablePath:'/usr/bin/chromium'}),errors:string[]=[];
try{for(const [format,layout] of [['tsx','portable'],['jsx','portable'],['tsx','original'],['jsx','original']] as const){
 const out=path.join(work,'batches',batch,'exports','react-avatars',format+'-'+layout);fs.mkdirSync(out,{recursive:true});let imports='';
 for(const [part,i] of parts.map((p,i)=>[p,i] as const)){const delivery=getDelivery(part,format,layout);for(const f of delivery.files){const q=path.join(out,part.id,f.name);fs.mkdirSync(path.dirname(q),{recursive:true});fs.writeFileSync(q,f.code)}imports+=`import C${i} from './${part.id}/${delivery.entry}';\n`;}
 fs.writeFileSync(out+'/entry.jsx',`import React,{useState}from'react';import{createRoot}from'react-dom/client';${imports}window.fixtures={};window.changes=[];
const entries=[${parts.map((p,i)=>`{id:${JSON.stringify(p.id)},C:C${i}}`).join(',')}],initialUsers=[{id:'one',name:'Sora Mori',subtitle:'Design',initials:'SM',status:'online'},{id:'two',name:'Rin Aoki',subtitle:'Engineering',initials:'RA',status:'away'},{id:'three',name:'Nao Ueda',subtitle:'Research',initials:'NU',status:'busy'}];
function Fixture({id,C}){const[value,setValue]=useState('one'),[reject,setReject]=useState(false),[disabled,setDisabled]=useState(false),[passive,setPassive]=useState(false),[users,setUsers]=useState(initialUsers),[label,setLabel]=useState('人物一覧');window.fixtures[id]={setValue,setReject,setDisabled,setPassive,setUsers,setLabel};return <section data-part={id}><div data-case="primary"><C value={value} onValueChange={v=>{window.changes.push({id,value:v});if(!reject)setValue(v)}} users={users} disabled={disabled} interactive={!passive} label={label}><input aria-label="React child" defaultValue="retained"/></C></div><div data-case="independent"><C defaultValue="one" users={initialUsers}/></div></section>}
const root=createRoot(document.querySelector('#root'));window.teardown=()=>root.unmount();root.render(<React.StrictMode>{entries.map(e=><Fixture key={e.id} {...e}/>)}</React.StrictMode>);`);
 fs.writeFileSync(out+'/index.html','<!doctype html><html lang="ja"><meta charset="utf-8"><link rel="icon" href="data:,"><style>*{box-sizing:border-box}body{padding:18px;margin:0;background:#181d23;color:white;font:14px Arial}section[data-part]{max-width:420px;margin:32px 0}</style><div id="root"></div><script type="module" src="./entry.jsx"></script>');
 const page=await browser.newPage({viewport:{width:390,height:900}});page.on('pageerror',e=>errors.push(e.message));await page.goto(server.resolvedUrls!.local[0]+path.relative(ROOT,out+'/index.html'));await page.waitForFunction(n=>document.querySelectorAll('[data-sg-kind=avatars][data-sg-reduced]').length===n*2,parts.length);
 for(const part of parts){const h=page.locator(`[data-part="${part.id}"]`),r=h.locator('[data-case=primary] [data-sg-kind=avatars]'),u=h.locator('[data-case=independent] [data-sg-kind=avatars]'),person=(value:string)=>r.locator(`[data-user="${value}"]`),update=async(patch:any)=>{await page.evaluate(({id,patch})=>{for(const [key,value] of Object.entries(patch))(window as any).fixtures[id][key](value)}, {id:part.id,patch});await page.waitForTimeout(30);};
 assert.equal(await person('one').getAttribute('aria-pressed'),'true');await person('two').focus();await person('two').press('Enter');assert.equal(await person('two').getAttribute('aria-pressed'),'true');assert.equal(await u.locator('[data-user=one]').getAttribute('aria-pressed'),'true');assert.equal(await person('two').evaluate(e=>e===document.activeElement),true,part.id+' focused two after selection or label update');await update({setLabel:'更新した人物一覧'});assert.equal(await person('two').evaluate(e=>e===document.activeElement),true,part.id+' focused two after selection or label update');await update({setReject:true});await person('three').press('Space');assert.equal(await person('two').getAttribute('aria-pressed'),'true');assert.equal(await page.evaluate(()=>(window as any).changes.at(-1).value),'three');await update({setReject:false,setValue:'three'});assert.equal(await person('three').getAttribute('aria-pressed'),'true');await update({setDisabled:true});assert.equal(await person('one').isDisabled(),true);await person('one').click({force:true});assert.equal(await person('three').getAttribute('aria-pressed'),'true');await update({setDisabled:false,setPassive:true});assert.equal(await r.locator('button[data-user]').count(),0);assert.equal(await r.locator('div[data-user]').count(),3);await update({setPassive:false});
 const child=r.locator('input[aria-label="React child"]');await child.fill('React child retains edited text');await child.evaluate(e=>e.setSelectionRange(2,5));const childHandle=await child.elementHandle();await update({setLabel:'構造更新',setUsers:[{id:'three',name:'<b>日本語</b>',initials:'NU'}]});assert.equal(await r.locator('.sg-person-name').textContent(),'<b>日本語</b>');assert.equal(await r.locator('.sg-person-name b').count(),0);assert.equal(await child.inputValue(),'React child retains edited text');assert.equal(await child.evaluate((e,original)=>e===original,childHandle),true);assert.deepEqual(await child.evaluate(e=>[e.selectionStart,e.selectionEnd]),[2,5]);await update({setUsers:[]});assert.equal(await r.locator('[data-user]').count(),0);await update({setUsers:[{id:'one',name:'Single user',initials:'SU'}],setValue:'one'});assert.equal(await person('one').getAttribute('aria-pressed'),'true');
 const long=['one','two','three'].map((id,i)=>({id,name:'長い人物名 '+i+' 日本語JapaneseLongUnbrokenNameWithoutWhitespace',subtitle:'長い役職と所属日本語LongSubtitleWithoutWhitespace',initials:'JP'}));await update({setUsers:long});
 for(const dir of ['ltr','rtl'])for(const width of [320,390,768]){await page.setViewportSize({width,height:900});await r.evaluate((e,dir)=>e.dir=dir,dir);await page.evaluate(()=>new Promise<void>(res=>requestAnimationFrame(()=>res())));assert.ok(await r.evaluate(e=>e.scrollWidth<=e.clientWidth+1),part.id+' fits '+width+' '+dir);for(const p of await r.locator('button[data-user]').all()){assert.ok(await p.evaluate(e=>{const r=e.getBoundingClientRect();return r.width>=44&&r.height>=44}),part.id+' native hit');assert.ok(await p.locator('.sg-person-name').evaluate(e=>{const range=document.createRange();range.selectNodeContents(e);return Math.max(...Array.from(range.getClientRects(),r=>r.width))>=64}),part.id+' actual name line width '+width+' '+dir);}}
 await page.emulateMedia({forcedColors:'active',reducedMotion:'reduce'});await person('two').click();assert.equal(await person('two').getAttribute('aria-pressed'),'true');assert.equal(await r.evaluate(e=>e.getAnimations({subtree:true}).length),0);await page.emulateMedia({forcedColors:'none',reducedMotion:'no-preference'});
 }await page.evaluate(()=>(window as any).teardown());assert.equal(await page.locator('[data-part]').count(),0);await page.close();console.log('PASS '+parts.length+' avatars React '+format+' '+layout+' native keyboard/ARIA/controlled accept-reject/default/independent/disabled/passive/props focus/literal data/empty-one/React child DOM selection/long320390768/RTL/forced/reduced/StrictMode cleanup');
}assert.deepEqual(errors,[]);}finally{await browser.close();await server.close();}
