import fs from'node:fs';import path from'node:path';import assert from'node:assert/strict';import{chromium}from'playwright';import{createServer}from'vite';import{buildCatalog,ROOT}from'../../../scripts/catalog.ts';import{getDelivery}from'../../../src/catalog/delivery.ts';
const batch=process.argv[2],work=path.join(ROOT,'docs/design-renewal'),rows=JSON.parse(fs.readFileSync(work+'/targets.json','utf8')).filter((r:any)=>r.batch===batch&&r.category==='links'),parts=buildCatalog(ROOT,rows.map((r:any)=>r.id),{appearance:false}).parts;
const s=await createServer({root:ROOT,server:{host:'127.0.0.1',port:0,hmr:false,watch:{ignored:['**/docs/**']}}});await s.listen();const browser=await chromium.launch({executablePath:'/usr/bin/chromium'}),errors:string[]=[];
try{for(const[format,layout]of[['tsx','portable'],['jsx','portable'],['tsx','original'],['jsx','original']]as const){const out=path.join(work,'batches',batch,'exports','react-links',format+'-'+layout);fs.mkdirSync(out,{recursive:true});let imports='';
 for(const[p,i]of parts.map((p,i)=>[p,i]as const)){const d=getDelivery(p,format,layout);for(const f of d.files){const q=path.join(out,p.id,f.name);fs.mkdirSync(path.dirname(q),{recursive:true});fs.writeFileSync(q,f.code)}imports+=`import C${i} from './${p.id}/${d.entry}';\n`}
 fs.writeFileSync(out+'/entry.jsx',`import React from'react';import{createRoot}from'react-dom/client';${imports}window.calls=[];window.refs={};const entries=[${parts.map((p,i)=>`{id:${JSON.stringify(p.id)},C:C${i}}`).join(',')}];const root=createRoot(document.querySelector('#root'));window.teardown=()=>root.unmount();root.render(<React.StrictMode>{entries.map(({id,C})=><section key={id} data-part={id}><div data-case="native"><C href={'#destination-'+id} ref={e=>window.refs[id]=e} eyebrow="長い日本語の分類とLONGUNBROKENMETADATA" onClick={e=>window.calls.push({id,prevented:e.defaultPrevented})}>長い日本語の移動先とUnbrokenLatinDestinationWithoutWhitespaceの詳細を確認する</C><div id={'destination-'+id}>移動先</div></div><div data-case="blank"><C href="#local" target="_blank" rel="noreferrer" aria-label="別タブの移動先" icon={<svg viewBox="0 0 20 20"><path d="M2 10h16" fill="none" stroke="currentColor"/></svg>}>別の移動先</C></div></section>)}</React.StrictMode>);`);
 fs.writeFileSync(out+'/index.html','<!doctype html><html lang="ja"><meta charset="utf-8"><link rel="icon" href="data:,"><style>*{box-sizing:border-box}body{padding:18px;margin:0;background:#181d23;color:white;font:14px Arial}section{max-width:380px;margin:32px 0}section>div{margin:30px 0}</style><div id="root"></div><script type="module" src="./entry.jsx"></script>');
 const p=await browser.newPage({viewport:{width:390,height:844},reducedMotion:'reduce'});p.on('pageerror',e=>errors.push(e.message));await p.goto(s.resolvedUrls!.local[0]+path.relative(ROOT,out+'/index.html'));await p.waitForFunction(n=>document.querySelectorAll('[data-part]').length===n,parts.length);
 for(const part of parts){const host=p.locator(`[data-part="${part.id}"]`),a=host.locator('[data-case=native] a'),blank=host.locator('[data-case=blank] a');assert.ok(await a.evaluate((e,id)=>e===(window as any).refs[id],part.id),'forwarded native ref');assert.equal(await a.getAttribute('href'),'#destination-'+part.id);await a.focus();await p.keyboard.press('Enter');assert.equal(await p.evaluate(()=>location.hash),'#destination-'+part.id);await a.click();assert.equal(await blank.getAttribute('target'),'_blank');const rel=(await blank.getAttribute('rel'))!.split(' ');assert.ok(rel.includes('noopener')&&rel.includes('noreferrer'));assert.equal(await blank.getAttribute('aria-label'),'別タブの移動先');assert.equal(await blank.locator('.sop-link-sr').innerText(),'（新しいタブで開きます）');assert.equal(await blank.locator('svg').getAttribute('viewBox'),'0 0 20 20');
 }
 assert.equal(await p.evaluate(()=>(window as any).calls.length),parts.length*2);assert.ok(await p.evaluate(()=>(window as any).calls.every((e:any)=>!e.prevented)));
 for(const width of[320,390,768]){await p.setViewportSize({width,height:844});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),format+' '+layout+' fits '+width)}await p.emulateMedia({forcedColors:'active'});assert.ok(await p.locator('.sop-link-label').first().evaluate(e=>getComputedStyle(e).textDecorationLine.includes('underline')));await p.evaluate(()=>(window as any).teardown());assert.equal(await p.locator('[data-part]').count(),0);assert.ok(await p.evaluate(()=>Object.values((window as any).refs).every(v=>v===null)));await p.close();console.log('PASS '+parts.length+' links React '+format+' '+layout+' real href/keyboard/ref/handlers/target/rel/custom icon/long text/forced/StrictMode cleanup');
}assert.deepEqual(errors,[])}finally{await browser.close();await s.close()}
