import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {chromium} from 'playwright';import {createServer} from 'vite';import {buildCatalog,ROOT} from '../../../scripts/catalog.ts';import {getDelivery} from '../../../src/catalog/delivery.ts';
const batch=process.argv[2],work=path.join(ROOT,'docs/design-renewal'),rows=JSON.parse(fs.readFileSync(work+'/targets.json','utf8')).filter((r:any)=>r.batch===batch&&r.category==='badges'),parts=buildCatalog(ROOT,rows.map((r:any)=>r.id),{appearance:false}).parts;assert.ok(parts.length);
const server=await createServer({root:ROOT,cacheDir:path.join(work,'batches',batch,'exports','vite-cache-badges'),configFile:false,optimizeDeps:{entries:[],noDiscovery:true,include:['react','react-dom/client','react/jsx-dev-runtime']},server:{host:'127.0.0.1',port:0,hmr:false,watch:null}});await server.listen();const browser=await chromium.launch({executablePath:'/usr/bin/chromium'}),errors:string[]=[];
try{for(const [format,layout] of [['tsx','portable'],['jsx','portable'],['tsx','original'],['jsx','original']] as const){
 const out=path.join(work,'batches',batch,'exports','react-badges',format+'-'+layout);fs.mkdirSync(out,{recursive:true});let imports='';
 for(const [part,i] of parts.map((p,i)=>[p,i] as const)){const delivery=getDelivery(part,format,layout);for(const f of delivery.files){const q=path.join(out,part.id,f.name);fs.mkdirSync(path.dirname(q),{recursive:true});fs.writeFileSync(q,f.code)}imports+=`import C${i} from './${part.id}/${delivery.entry}';\n`;}
 fs.writeFileSync(out+'/entry.jsx',`import React,{useState}from'react';import{createRoot}from'react-dom/client';${imports}window.refs={};window.controllers={};window.events={};
const entries=[${parts.map((p,i)=>`{id:${JSON.stringify(p.id)},C:C${i}}`).join(',')}];
function Fixture({id,C}){const[disabled,setDisabled]=useState(false),[readOnly,setReadOnly]=useState(false),[long,setLong]=useState(false),[count,setCount]=useState(4),[value,setValue]=useState([]),[reject,setReject]=useState(false);const items=Array.from({length:count},(_,i)=>({value:'v'+i,label:long?'分類 '+i+' 日本語JapaneseLongUnbrokenLabelWithoutWhitespace':'分類 '+i,badge:i===0?'123456789':undefined,disabled:i===2,icon:'spark'}));window.events[id]??={data:[],actions:[]};return <section data-part={id}><button data-disabled onClick={()=>setDisabled(!disabled)}>無効</button><button data-readonly onClick={()=>setReadOnly(!readOnly)}>読み取り専用</button><button data-long onClick={()=>setLong(!long)}>長文</button><button data-one onClick={()=>setCount(1)}>一分類</button><button data-empty onClick={()=>setCount(0)}>空</button><button data-four onClick={()=>setCount(4)}>四分類</button><button data-reject onClick={()=>setReject(!reject)}>拒否</button><div data-case="primary"><C items={items} selectable removable defaultValue={['v1']} disabled={disabled} readOnly={readOnly} onValueChange={v=>window.events[id].data.push(v)} onAction={v=>window.events[id].actions.push(v)} ref={e=>window.refs[id]=e} controllerRef={e=>window.controllers[id]=e}/></div><div data-case="controlled"><C items={items} selectable value={value} onValueChange={v=>{if(!reject)setValue(v)}}/></div></section>}
const root=createRoot(document.querySelector('#root'));window.teardown=()=>root.unmount();root.render(<React.StrictMode>{entries.map(e=><Fixture key={e.id} {...e}/>)}</React.StrictMode>);`);
 fs.writeFileSync(out+'/index.html','<!doctype html><html lang="ja"><meta charset="utf-8"><link rel="icon" href="data:,"><style>*{box-sizing:border-box}body{padding:18px;margin:0;background:#181d23;color:white;font:14px Arial}section[data-part]{max-width:420px;margin:32px 0}</style><div id="root"></div><script type="module" src="./entry.jsx"></script>');
 const page=await browser.newPage({viewport:{width:390,height:900}});page.on('pageerror',e=>errors.push(e.message));await page.goto(server.resolvedUrls!.local[0]+path.relative(ROOT,out+'/index.html'));await page.waitForFunction(n=>document.querySelectorAll('[data-part]').length===n,parts.length);
 for(const part of parts){
  const h=page.locator(`[data-part="${part.id}"]`),r=h.locator('[data-case=primary] [data-foundation]'),c=h.locator('[data-case=controlled] [data-foundation]');const input=(v:string)=>r.locator(`input[data-tag-select="${v}"]`),remove=(v:string)=>r.locator(`button[data-tag-remove="${v}"]`);
  assert.equal(await input('v1').isChecked(),true);await input('v0').focus();await page.keyboard.press('Space');assert.equal(await input('v0').isChecked(),true);assert.equal(await input('v0').evaluate(e=>e===document.activeElement),true,part.id+' focus');await page.keyboard.press('Space');assert.equal(await input('v0').isChecked(),false);assert.equal(await c.locator('input').first().isChecked(),false);assert.equal(await input('v2').isDisabled(),true);assert.equal(await remove('v2').isDisabled(),true);
  await h.locator('[data-readonly]').click();assert.equal(await input('v0').isDisabled(),true);assert.equal(await remove('v0').isDisabled(),true);await remove('v0').click({force:true});assert.equal(await input('v0').count(),1);await h.locator('[data-readonly]').click();assert.equal(await input('v0').isDisabled(),false);
  await h.locator('button[data-disabled]').click();assert.equal(await input('v0').isDisabled(),true);await h.locator('button[data-disabled]').click();await remove('v1').click();assert.equal(await input('v1').count(),0);assert.deepEqual(await page.evaluate(id=>(window as any).events[id].actions,part.id),['v1']);assert.equal(await r.locator('input,button').evaluateAll(es=>es.some(e=>e===document.activeElement)),true);
  const ci=c.locator('input').first();await ci.focus();await page.keyboard.press('Space');assert.equal(await ci.isChecked(),true);assert.equal(await ci.evaluate(e=>e===document.activeElement),true);await h.locator('[data-reject]').click();await ci.focus();await page.keyboard.press('Space');assert.equal(await ci.isChecked(),true);assert.equal(await ci.evaluate(e=>e===document.activeElement),true);await h.locator('[data-reject]').click();
  await h.locator('[data-empty]').click();assert.equal(await r.locator('.ff-tag').count(),0);await h.locator('[data-one]').click();assert.equal(await r.locator('.ff-tag').count(),1);await h.locator('[data-four]').click();assert.equal(await r.locator('.ff-tag').count(),4);await h.locator('[data-long]').click();
  for(const dir of ['ltr','rtl'])for(const width of [320,390,768]){await page.setViewportSize({width,height:900});await r.evaluate((e,dir)=>e.dir=dir,dir);await page.evaluate(()=>new Promise<void>(res=>requestAnimationFrame(()=>res())));assert.ok(await r.evaluate(e=>e.scrollWidth<=e.clientWidth+1),part.id+' fits '+width+' '+dir);assert.ok(await input('v0').locator('..').evaluate(e=>e.getBoundingClientRect().width>=88),part.id+' usable long label width');assert.ok(await input('v0').locator('..').evaluate(e=>{let widest=0;for(const node of e.querySelector('span').childNodes)if(node.nodeType===Node.TEXT_NODE){const range=document.createRange();range.selectNodeContents(node);for(const rect of range.getClientRects())widest=Math.max(widest,rect.width)}return widest>=64}),part.id+' actual long text line width');}
  await page.evaluate(id=>(window as any).controllers[id].setData(['v3']),part.id);assert.equal(await input('v3').isChecked(),true);assert.equal(await input('v0').isChecked(),false);assert.equal(await ci.isChecked(),true);
  await page.emulateMedia({forcedColors:'active',reducedMotion:'reduce'});assert.equal(await r.evaluate(e=>e.getAnimations({subtree:true}).length),0);await page.emulateMedia({forcedColors:'none',reducedMotion:'no-preference'});
 }
 await page.evaluate(()=>(window as any).teardown());assert.equal(await page.locator('[data-part]').count(),0);assert.equal(await page.evaluate(()=>Object.values((window as any).refs).every(v=>v===null)),true);assert.equal(await page.evaluate(()=>Object.values((window as any).controllers).every(v=>v===null)),true);await page.close();console.log('PASS '+parts.length+' badges React '+format+' '+layout+' native checked/Space focus/controlled accept-reject/default/independent/readonly/disabled/items/removal/prop counts/imperative/long320390768/RTL/forced/reduced/refs/StrictMode cleanup');
}assert.deepEqual(errors,[]);}finally{await browser.close();await server.close();}
