import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {chromium} from 'playwright';import {createServer} from 'vite';import {buildCatalog,ROOT} from '../../../scripts/catalog.ts';import {getDelivery} from '../../../src/catalog/delivery.ts';
const batch=process.argv[2],work=path.join(ROOT,'docs/design-renewal'),rows=JSON.parse(fs.readFileSync(work+'/targets.json','utf8')).filter((r:any)=>r.batch===batch),parts=buildCatalog(ROOT,rows.filter((r:any)=>r.category==='accordions').map((r:any)=>r.id),{appearance:false}).parts;
const s=await createServer({root:ROOT,server:{host:'127.0.0.1',port:0,hmr:false,watch:null}});await s.listen();const browser=await chromium.launch({executablePath:'/usr/bin/chromium'}),errors:string[]=[];
try{for(const [format,layout] of [['tsx','portable'],['jsx','portable'],['tsx','original'],['jsx','original']] as const){
 const out=path.join(work,'batches',batch,'exports','react-content',format+'-'+layout);fs.mkdirSync(out,{recursive:true});let imports='';
 for(const[p,i]of parts.map((p,i)=>[p,i]as const)){const d=getDelivery(p,format,layout);for(const f of d.files){const q=path.join(out,p.id,f.name);fs.mkdirSync(path.dirname(q),{recursive:true});fs.writeFileSync(q,f.code)}imports+=`import C${i} from './${p.id}/${d.entry}';\n`}
 fs.writeFileSync(out+'/entry.jsx',`import React,{useState}from'react';import{createRoot}from'react-dom/client';${imports}
 const items=[{value:'one',title:'最初の内容を確認する',subtitle:'FIRST',content:<><p>長い日本語の内容を確認し、任意のネイティブ入力を保持します。</p><label>本文の値<input defaultValue="残す値"/></label><button type="button">本文内の操作</button></>},{value:'two',title:'次の手順を確認する',subtitle:'SECOND',content:<p>本文の差し替えと独立した開閉を確認します。</p>},{value:'three',title:'無効の手順',disabled:true,content:'無効'}];
 function Pair({C,id}){const[v,set]=useState([]);return <section data-part={id}><div data-case="uncontrolled"><C items={items} defaultExpanded={['one']}/></div><div data-case="controlled"><C items={items} expanded={v} onExpandedChange={n=>{window.calls.push({id,n});set(n)}}/></div></section>}
 window.calls=[];const root=createRoot(document.querySelector('#root'));window.teardown=()=>root.unmount();root.render(<React.StrictMode>{[${parts.map((p,i)=>`{id:${JSON.stringify(p.id)},C:C${i}}`).join(',')}].map(e=><Pair key={e.id} {...e}/>)}</React.StrictMode>);`);
 fs.writeFileSync(out+'/index.html','<!doctype html><html lang="ja"><meta charset="utf-8"><link rel="icon" href="data:,"><style>*{box-sizing:border-box}body{padding:12px;margin:0;background:#181d23;color:white;font:14px Arial}section{max-width:380px;margin:30px 0}section>div{margin:15px 0}</style><div id="root"></div><script type="module" src="./entry.jsx"></script>');
 const p=await browser.newPage({viewport:{width:390,height:844},reducedMotion:'reduce'});p.on('pageerror',e=>errors.push(e.message));await p.goto(s.resolvedUrls!.local[0]+path.relative(ROOT,out+'/index.html'));await p.waitForFunction(n=>document.querySelectorAll('[data-part]').length===n,parts.length);
 for(const part of parts){const host=p.locator(`[data-part="${part.id}"]`),un=host.locator('[data-case=uncontrolled]'),co=host.locator('[data-case=controlled]');assert.equal(await un.locator('.sop-acc-material i').count(),18,part.id+' React artwork matches native');assert.equal(await co.locator('.sop-acc-material i').count(),18);
  assert.equal(await un.locator('.sop-accordion-trigger').first().getAttribute('aria-expanded'),'true');await un.locator('.sop-accordion-trigger').nth(1).click();assert.equal(await un.locator('.sop-accordion-trigger').first().getAttribute('aria-expanded'),'false');assert.equal(await un.locator('.sop-accordion-trigger').nth(1).getAttribute('aria-expanded'),'true');await un.locator('.sop-accordion-trigger').first().click();assert.equal(await un.locator('input').inputValue(),'残す値');await un.locator('input').fill('変更した値');await un.locator('.sop-accordion-content button').click();assert.equal(await un.locator('.sop-accordion-trigger').first().getAttribute('aria-expanded'),'true');
  await co.locator('.sop-accordion-trigger').first().focus();await p.keyboard.press('Enter');assert.equal(await co.locator('.sop-accordion-trigger').first().getAttribute('aria-expanded'),'true');await p.keyboard.press('Space');assert.equal(await co.locator('.sop-accordion-trigger').first().getAttribute('aria-expanded'),'false');assert.equal(await co.locator('.sop-accordion-trigger').last().isDisabled(),true);
  const ids=await host.locator('[id]').evaluateAll(es=>es.map(e=>e.id));assert.equal(new Set(ids).size,ids.length,part.id+' independent IDs');
 }
 for(const width of [320,390,768]){await p.setViewportSize({width,height:844});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),format+' '+layout+' fits '+width)}
 assert.equal(await p.evaluate(()=>(window as any).calls.length),parts.length*2);await p.evaluate(()=>(window as any).teardown());assert.equal(await p.locator('[data-part]').count(),0);await p.close();console.log('PASS '+parts.length+' accordion React '+format+' '+layout+' real items/art/native content/controlled/uncontrolled/IDs/disabled/cleanup');
}assert.deepEqual(errors,[]);}finally{await browser.close();await s.close();}
