import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {chromium} from 'playwright';import {createServer} from 'vite';import {buildCatalog,ROOT} from '../../../scripts/catalog.ts';import {getDelivery} from '../../../src/catalog/delivery.ts';
const batch=process.argv[2],work=path.join(ROOT,'docs/design-renewal'),rows=JSON.parse(fs.readFileSync(work+'/targets.json','utf8')).filter((r:any)=>r.batch===batch),parts=buildCatalog(ROOT,rows.map((r:any)=>r.id),{appearance:false}).parts;
const s=await createServer({root:ROOT,server:{host:'127.0.0.1',port:0,hmr:false,watch:{ignored:['**/docs/**']}}});await s.listen();const b=await chromium.launch({executablePath:'/usr/bin/chromium'}),errors:string[]=[];
try{for(const [format,layout] of [['tsx','portable'],['jsx','portable'],['tsx','original'],['jsx','original']] as const){
 const out=path.join(work,'batches',batch,'exports','react-content',format+'-'+layout);fs.mkdirSync(out,{recursive:true});let imports='';
 for(const[p,i]of parts.map((p,i)=>[p,i]as const)){const d=getDelivery(p,format,layout);for(const f of d.files){const q=path.join(out,p.id,f.name);fs.mkdirSync(path.dirname(q),{recursive:true});fs.writeFileSync(q,f.code)}imports+=`import C${i} from './${p.id}/${d.entry}';\n`}
 fs.writeFileSync(out+'/entry.jsx',`import React,{useState}from'react';import{createRoot}from'react-dom/client';${imports}
 const items=[{value:'draft',label:'下書き',description:'編集を続けられます',icon:'D'},{value:'review',label:'レビュー待ち',description:'内容を確認しています',icon:'R'},{value:'published',label:'公開済み',description:'閲覧できる状態です',icon:'P'}];
 function Pair({C,id}){const[v,set]=useState('draft');return <section data-part={id}><form data-case="uncontrolled"><C items={items} defaultValue="draft" name="status" onValueChange={n=>window.calls.push({id,n})}/></form><form data-case="controlled"><C items={items} value={v} name="status" onValueChange={n=>{window.calls.push({id,n});set(n)}}/></form></section>}
 window.calls=[];const root=createRoot(document.querySelector('#root'));window.teardown=()=>root.unmount();root.render(<React.StrictMode>{[${parts.map((p,i)=>`{id:${JSON.stringify(p.id)},C:C${i}}`).join(',')}].map(e=><Pair key={e.id} {...e}/>)}</React.StrictMode>);`);
 fs.writeFileSync(out+'/index.html','<!doctype html><html lang="ja"><meta charset="utf-8"><link rel="icon" href="data:,"><style>*{box-sizing:border-box}body{padding:12px;margin:0;background:#181d23;color:white;font:14px Arial}section{max-width:380px;margin:30px 0}form{margin:15px 0}</style><div id="root"></div><script type="module" src="./entry.jsx"></script>');
 const p=await b.newPage({viewport:{width:390,height:844},reducedMotion:'reduce'});p.on('pageerror',e=>errors.push(e.message));await p.goto(s.resolvedUrls!.local[0]+path.relative(ROOT,out+'/index.html'));await p.waitForFunction(n=>document.querySelectorAll('[data-part]').length===n,parts.length);
 for(const part of parts){const host=p.locator(`[data-part="${part.id}"]`);for(const variant of ['uncontrolled','controlled']){const form=host.locator(`[data-case=${variant}]`),q=form.locator('.sop-select-trigger');assert.equal(await form.locator('[role=option]').count(),3,part.id+' real options');await q.click();await p.keyboard.press('End');await p.keyboard.press('Enter');assert.equal(await form.locator('input').inputValue(),'published');assert.equal(await form.evaluate(e=>new FormData(e as HTMLFormElement).get('status')),'published');assert.equal(await form.locator('[role=option][aria-selected=true]').getAttribute('data-value'),'published');assert.match(await q.innerText(),/公開済み/);
   await p.emulateMedia({forcedColors:'active'});await q.click();const marks=await form.locator('[role=option]').evaluateAll(es=>es.map(e=>({selected:e.getAttribute('aria-selected')==='true',visible:Number(getComputedStyle(e.querySelector('.sop-select-check')!).opacity)>.5,ink:getComputedStyle(e.querySelector('b')!).color})));assert.ok(marks.every(m=>m.selected===m.visible),part.id+' React forced only committed mark');assert.ok(marks.every(m=>m.ink==='rgb(0, 0, 0)'),part.id+' React CanvasText remains black on Canvas');await p.keyboard.press('Escape');await p.emulateMedia({forcedColors:'none'});
  }const ids=await host.locator('[id]').evaluateAll(es=>es.map(e=>e.id));assert.equal(new Set(ids).size,ids.length,part.id+' independent IDs');}
 for(const width of [320,390,768]){await p.setViewportSize({width,height:844});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),format+' '+layout+' fits '+width)}assert.equal(await p.evaluate(()=>(window as any).calls.length),parts.length*2);await p.evaluate(()=>(window as any).teardown());assert.equal(await p.locator('[data-part]').count(),0);assert.equal(await p.locator('.sop-select-popup:popover-open').count(),0);await p.close();console.log('PASS '+parts.length+' select React '+format+' '+layout+' real options/controlled/uncontrolled/form/forced marks/IDs/cleanup');
}assert.deepEqual(errors,[]);}finally{await b.close();await s.close();}
