import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {chromium} from 'playwright';import {createServer} from 'vite';import {buildCatalog,ROOT} from '../../../scripts/catalog.ts';import {getDelivery} from '../../../src/catalog/delivery.ts';
const batch=process.argv[2],work=path.join(ROOT,'docs/design-renewal'),rows=JSON.parse(fs.readFileSync(work+'/targets.json','utf8')).filter((r:any)=>r.batch===batch&&r.category==='numbers'),parts=buildCatalog(ROOT,rows.map((r:any)=>r.id),{appearance:false}).parts;assert.ok(parts.length);
const server=await createServer({root:ROOT,cacheDir:path.join(work,'batches',batch,'exports','vite-cache-numbers'),configFile:false,optimizeDeps:{entries:[],noDiscovery:true,include:['react','react-dom/client','react/jsx-dev-runtime']},server:{host:'127.0.0.1',port:0,hmr:false,watch:null}});await server.listen();const browser=await chromium.launch({executablePath:'/usr/bin/chromium'}),errors:string[]=[];
try{for(const [format,layout] of [['tsx','portable'],['jsx','portable'],['tsx','original'],['jsx','original']] as const){
 const out=path.join(work,'batches',batch,'exports','react-numbers',format+'-'+layout);fs.mkdirSync(out,{recursive:true});let imports='';
 for(const [part,i] of parts.map((p,i)=>[p,i] as const)){const delivery=getDelivery(part,format,layout);for(const f of delivery.files){const q=path.join(out,part.id,f.name);fs.mkdirSync(path.dirname(q),{recursive:true});fs.writeFileSync(q,f.code)}imports+=`import C${i} from './${part.id}/${delivery.entry}';\n`;}
 fs.writeFileSync(out+'/entry.jsx',`import React,{useState}from'react';import{createRoot}from'react-dom/client';${imports}window.refs={};window.controllers={};window.fixtures={};
const entries=[${parts.map((p,i)=>`{id:${JSON.stringify(p.id)},C:C${i}}`).join(',')}];
function Fixture({id,C}){const[value,setValue]=useState(3),[reject,setReject]=useState(false),[disabled,setDisabled]=useState(false),[readOnly,setReadOnly]=useState(false),[long,setLong]=useState(false),[description,setDescription]=useState('');window.fixtures[id]={setDescription};return <section data-part={id}><button data-disabled onClick={()=>setDisabled(!disabled)}>無効</button><button data-readonly onClick={()=>setReadOnly(!readOnly)}>読み取り専用</button><button data-reject onClick={()=>setReject(!reject)}>拒否</button><button data-long onClick={()=>setLong(!long)}>長文</button><form onSubmit={e=>e.preventDefault()} data-case="primary"><C value={value} onValueChange={v=>{if(!reject)setValue(v)}} min={long?-999999:0} max={long?999999:20} step={long?.001:1} disabled={disabled} readOnly={readOnly} label={long?'長い数量日本語LongHeadingWithoutWhitespace':'量を調整'} unit={long?'長い単位日本語LongUnitWithoutWhitespace':'kg'} name="quantity" description={description} ref={e=>window.refs[id]=e}/></form><div data-case="independent"><C defaultValue={3} min={0} max={20} step={1} controllerRef={e=>window.controllers[id]=e}/></div></section>}
const root=createRoot(document.querySelector('#root'));window.teardown=()=>root.unmount();root.render(<React.StrictMode>{entries.map(e=><Fixture key={e.id} {...e}/>)}</React.StrictMode>);`);
 fs.writeFileSync(out+'/index.html','<!doctype html><html lang="ja"><meta charset="utf-8"><link rel="icon" href="data:,"><style>*{box-sizing:border-box}body{padding:18px;margin:0;background:#181d23;color:white;font:14px Arial}section[data-part]{max-width:420px;margin:32px 0}</style><div id="root"></div><script type="module" src="./entry.jsx"></script>');
 const page=await browser.newPage({viewport:{width:390,height:900}});page.on('pageerror',e=>errors.push(e.message));await page.goto(server.resolvedUrls!.local[0]+path.relative(ROOT,out+'/index.html'));await page.waitForFunction(n=>document.querySelectorAll('[data-part]').length===n,parts.length);
 for(const part of parts){
  const h=page.locator(`[data-part="${part.id}"]`),r=h.locator('[data-case=primary] [data-foundation]'),u=h.locator('[data-case=independent] [data-foundation]'),input=r.locator('[data-number]'),plus=r.locator('[data-adjust="1"]'),minus=r.locator('[data-adjust="-1"]');assert.equal(await input.inputValue(),'3');await input.focus();await page.keyboard.press('ArrowUp');assert.equal(await input.inputValue(),'4');assert.equal(await u.locator('[data-number]').inputValue(),'3');await h.locator('[data-reject]').click();await plus.click();assert.equal(await input.inputValue(),'4');await h.locator('[data-reject]').click();
  await input.fill('7');await input.evaluate(e=>e.setSelectionRange(1,1));await page.evaluate(id=>(window as any).fixtures[id].setDescription('編集中の補足更新'),part.id);await page.waitForTimeout(20);assert.equal(await input.inputValue(),'7');assert.deepEqual(await input.evaluate(e=>[e.selectionStart,e.selectionEnd]),[1,1]);await input.press('Escape');assert.equal(await input.inputValue(),'4');await input.fill('5');await input.press('Enter');assert.equal(await input.inputValue(),'5');assert.deepEqual(await h.locator('form').evaluate(e=>Array.from(new FormData(e as HTMLFormElement).entries())),[['quantity','5']]);
  await input.press('Home');assert.equal(await input.inputValue(),'0');assert.equal(await minus.isDisabled(),true);await input.press('End');assert.equal(await input.inputValue(),'20');assert.equal(await plus.isDisabled(),true);await input.press('ArrowDown');assert.equal(await input.inputValue(),'19');await input.fill('invalid');await input.press('Enter');assert.equal(await input.getAttribute('aria-invalid'),'true');await input.press('Escape');assert.equal(await input.inputValue(),'19');
  await h.locator('[data-readonly]').click();assert.equal(await input.evaluate(e=>e.readOnly),true);assert.equal(await plus.isDisabled(),true);await input.press('ArrowUp');assert.equal(await input.inputValue(),'19');await h.locator('[data-readonly]').click();await h.locator('button[data-disabled]').click();assert.equal(await input.isDisabled(),true);await h.locator('button[data-disabled]').click();
  await page.evaluate(id=>(window as any).controllers[id].setData(8),part.id);assert.equal(await u.locator('[data-number]').inputValue(),'8');assert.equal(await input.inputValue(),'19');await h.locator('[data-long]').click();await input.fill('-12345.678');await input.press('Enter');assert.equal(await input.inputValue(),'-12345.678');
  for(const dir of ['ltr','rtl'])for(const width of [320,390,768]){await page.setViewportSize({width,height:900});await r.evaluate((e,dir)=>e.dir=dir,dir);await page.evaluate(()=>new Promise<void>(res=>requestAnimationFrame(()=>res())));assert.ok(await r.evaluate(e=>e.scrollWidth<=e.clientWidth+1),part.id+' fits '+width+' '+dir);assert.equal(await input.evaluate(e=>getComputedStyle(e).direction),'ltr',part.id+' negative order '+dir);assert.equal(await r.locator('[data-number-hint]').evaluate(e=>getComputedStyle(e).direction),'ltr',part.id+' bounds order '+dir);assert.ok(await input.evaluate(e=>{const style=getComputedStyle(e),context=document.createElement('canvas').getContext('2d')!;context.font=style.font;return context.measureText(e.value).width<=e.clientWidth-parseFloat(style.paddingLeft)-parseFloat(style.paddingRight)+1}),part.id+' full negative glyph fits '+width+' '+dir);}
  await page.emulateMedia({forcedColors:'active',reducedMotion:'reduce'});await plus.click();assert.equal(await r.evaluate(e=>e.getAnimations({subtree:true}).length),0);await page.emulateMedia({forcedColors:'none',reducedMotion:'no-preference'});
 }
 await page.evaluate(()=>(window as any).teardown());assert.equal(await page.locator('[data-part]').count(),0);assert.equal(await page.evaluate(()=>Object.values((window as any).refs).every(v=>v===null)),true);assert.equal(await page.evaluate(()=>Object.values((window as any).controllers).every(v=>v===null)),true);await page.close();console.log('PASS '+parts.length+' numbers React '+format+' '+layout+' native keyboard/bounds/controlled accept-reject/default/independent/draft selection/FormData/invalid/Escape/readonly/disabled/imperative/long320390768/RTL/forced/reduced/refs/StrictMode cleanup');
}assert.deepEqual(errors,[]);}finally{await browser.close();await server.close();}
