import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {chromium} from 'playwright';import {createServer} from 'vite';import {buildCatalog,ROOT} from '../../../scripts/catalog.ts';import {getDelivery} from '../../../src/catalog/delivery.ts';
const batch=process.argv[2],work=path.join(ROOT,'docs/design-renewal'),rows=JSON.parse(fs.readFileSync(work+'/targets.json','utf8')).filter((r:any)=>r.batch===batch&&r.category==='breadcrumbs'),parts=buildCatalog(ROOT,rows.map((r:any)=>r.id),{appearance:false}).parts;assert.ok(parts.length);
const server=await createServer({root:ROOT,cacheDir:path.join(work,'batches',batch,'exports','vite-cache-trails'),configFile:false,optimizeDeps:{entries:[],noDiscovery:true,include:['react','react-dom/client','react/jsx-dev-runtime']},server:{host:'127.0.0.1',port:0,hmr:false,watch:null}});await server.listen();const browser=await chromium.launch({executablePath:'/usr/bin/chromium'}),errors:string[]=[];
try{for(const [format,layout] of [['tsx','portable'],['jsx','portable'],['tsx','original'],['jsx','original']] as const){
 const out=path.join(work,'batches',batch,'exports','react-trails',format+'-'+layout);fs.mkdirSync(out,{recursive:true});let imports='';
 for(const [part,i] of parts.map((p,i)=>[p,i] as const)){const delivery=getDelivery(part,format,layout);for(const f of delivery.files){const q=path.join(out,part.id,f.name);fs.mkdirSync(path.dirname(q),{recursive:true});fs.writeFileSync(q,f.code)}imports+=`import C${i} from './${part.id}/${delivery.entry}';\n`;}
 fs.writeFileSync(out+'/entry.jsx',`import React,{useState}from'react';import{createRoot}from'react-dom/client';${imports}window.refs={};window.controllers={};
const entries=[${parts.map((p,i)=>`{id:${JSON.stringify(p.id)},C:C${i}}`).join(',')}];
function Fixture({id,C}){const[count,setCount]=useState(7),[disabled,setDisabled]=useState(false),[disabledItem,setDisabledItem]=useState(false),[long,setLong]=useState(false);const items=Array.from({length:count},(_,i)=>({value:'v'+i,label:long?'長い階層 '+i+' 日本語JapaneseLongUnbrokenLabelWithoutWhitespace':'階層 '+i,href:'#level-'+i,disabled:disabledItem&&i===2}));return <section data-part={id}><button data-disabled onClick={()=>setDisabled(!disabled)}>無効</button><button data-item onClick={()=>setDisabledItem(!disabledItem)}>項目</button><button data-long onClick={()=>setLong(!long)}>長文</button><button data-one onClick={()=>setCount(1)}>一階層</button><button data-empty onClick={()=>setCount(0)}>空</button><button data-three onClick={()=>setCount(3)}>三階層</button><button data-seven onClick={()=>setCount(7)}>七階層</button><div data-case="primary"><C items={items} disabled={disabled} label={long?'現在地を確かめる長い日本語LongUnbrokenHeadingWithoutWhitespace':'現在地を確認'} description={long?'任意の補足SupplementalInformationWithoutWhitespace':''} ref={e=>window.refs[id]=e}/></div><div data-case="independent"><C items={[{value:'a',label:'独立した祖先',href:'#independent'},{value:'b',label:'独立した現在'}]} controllerRef={e=>window.controllers[id]=e}/></div></section>}
const root=createRoot(document.querySelector('#root'));window.teardown=()=>root.unmount();root.render(<React.StrictMode>{entries.map(e=><Fixture key={e.id} {...e}/>)}</React.StrictMode>);`);
 fs.writeFileSync(out+'/index.html','<!doctype html><html lang="ja"><meta charset="utf-8"><link rel="icon" href="data:,"><style>*{box-sizing:border-box}body{padding:18px;margin:0;background:#181d23;color:white;font:14px Arial}section[data-part]{max-width:410px;margin:32px 0}</style><div id="root"></div><script type="module" src="./entry.jsx"></script>');
 const page=await browser.newPage({viewport:{width:390,height:900}});page.on('pageerror',e=>errors.push(e.message));await page.goto(server.resolvedUrls!.local[0]+path.relative(ROOT,out+'/index.html'));await page.waitForFunction(n=>document.querySelectorAll('[data-part]').length===n,parts.length);
 const panelIDs=new Set<string>();
 for(const part of parts){
  const h=page.locator(`[data-part="${part.id}"]`),r=h.locator('[data-case=primary] [data-foundation]'),u=h.locator('[data-case=independent]'),nav=r.locator('.ff-breadcrumb'),more=r.locator('[data-crumb-more]'),panel=r.locator('[data-crumb-menu]');
  const panelID=(await panel.getAttribute('id'))!;assert.ok(!panelIDs.has(panelID));panelIDs.add(panelID);assert.equal(await more.getAttribute('aria-controls'),panelID);assert.equal(await nav.locator('[aria-current=page]').textContent(),'階層 6');
  await more.focus();await page.keyboard.press('Enter');assert.equal(await panel.isVisible(),true);assert.equal(await panel.locator('a').first().evaluate(e=>e===document.activeElement),true);await page.keyboard.press('Escape');assert.equal(await panel.isVisible(),false);assert.equal(await more.evaluate(e=>e===document.activeElement),true);
  await more.click();await panel.locator('a').nth(1).click();assert.ok(page.url().endsWith('#level-2'),part.id+' trusted link');await page.mouse.click(1,1);
  await h.locator('[data-item]').click();await more.click();const blocked=panel.locator('a').nth(1);assert.equal(await blocked.getAttribute('aria-disabled'),'true');assert.equal(await blocked.getAttribute('href'),null);const url=page.url();await blocked.click({force:true});assert.equal(page.url(),url);await page.keyboard.press('Escape');await h.locator('[data-item]').click();
  await h.locator('button[data-disabled]').click();assert.equal(await nav.locator('a[href]').count(),0);assert.equal(await more.isDisabled(),true);await more.click({force:true});assert.equal(await panel.isVisible(),false);await h.locator('button[data-disabled]').click();
  await h.locator('[data-empty]').click();assert.equal(await nav.locator('li').count(),0);await h.locator('[data-one]').click();assert.equal(await more.count(),0);assert.equal(await nav.locator('[aria-current=page]').textContent(),'階層 0');await h.locator('[data-three]').click();assert.equal(await more.count(),0);assert.equal(await nav.locator('a').count(),2);await nav.locator('a').nth(1).click();assert.ok(page.url().endsWith('#level-1'));await h.locator('[data-seven]').click();
  assert.equal(await u.locator('[aria-current=page]').textContent(),'独立した現在');await page.evaluate(id=>(window as any).controllers[id].updateFoundation({items:[{value:'x',label:'独立更新'}]}),part.id);assert.equal(await u.locator('[aria-current=page]').textContent(),'独立更新');assert.equal(await nav.locator('[aria-current=page]').textContent(),'階層 6');
  await h.locator('[data-long]').click();
  for(const dir of ['ltr','rtl'])for(const width of [320,390,768]){
   await page.setViewportSize({width,height:900});await r.evaluate((e,dir)=>e.dir=dir,dir);await page.evaluate(()=>new Promise<void>(res=>requestAnimationFrame(()=>res())));assert.ok(await r.evaluate(e=>e.scrollWidth<=e.clientWidth+1),part.id+' fits '+width+' '+dir);await more.click();assert.equal(await panel.isVisible(),true);assert.ok(await panel.evaluate(e=>{const a=e.getBoundingClientRect();return a.left>=0&&a.right<=innerWidth+1&&e.scrollWidth<=e.clientWidth+1}),part.id+' menu fits '+width+' '+dir);await page.keyboard.press('Escape');
  }
  await page.emulateMedia({forcedColors:'active',reducedMotion:'reduce'});await more.click();assert.equal(await panel.isVisible(),true);assert.equal(await r.evaluate(e=>e.getAnimations({subtree:true}).length),0);await page.emulateMedia({forcedColors:'none',reducedMotion:'no-preference'});
 }
 await page.evaluate(()=>(window as any).teardown());assert.equal(await page.locator('[data-part]').count(),0);assert.equal(await page.locator(':popover-open').count(),0);assert.equal(await page.evaluate(()=>Object.values((window as any).refs).every(v=>v===null)),true);assert.equal(await page.evaluate(()=>Object.values((window as any).controllers).every(v=>v===null)),true);await page.close();console.log('PASS '+parts.length+' trails React '+format+' '+layout+' native links/trusted menu pointer/keyboard/Escape focus/ARIA/unique panels/prop counts/disabled items/disabled/independent state/long320390768/RTL/forced/reduced/refs/open StrictMode cleanup');
}assert.deepEqual(errors,[]);}finally{await browser.close();await server.close();}
