import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {chromium} from 'playwright';import {createServer} from 'vite';import {buildCatalog,ROOT} from '../../../scripts/catalog.ts';import {getDelivery} from '../../../src/catalog/delivery.ts';
const batch=process.argv[2],work=path.join(ROOT,'docs/design-renewal'),rows=JSON.parse(fs.readFileSync(work+'/targets.json','utf8')).filter((r:any)=>r.batch===batch&&r.category==='textboxes'),parts=buildCatalog(ROOT,rows.map((r:any)=>r.id),{appearance:false}).parts;
const s=await createServer({root:ROOT,server:{host:'127.0.0.1',port:0,hmr:false,watch:{ignored:['**/docs/**']}}});await s.listen();const browser=await chromium.launch({executablePath:'/usr/bin/chromium'}),errors:string[]=[];
try{for(const [format,layout] of [['tsx','portable'],['jsx','portable'],['tsx','original'],['jsx','original']] as const){
 const out=path.join(work,'batches',batch,'exports','react-fields',format+'-'+layout);fs.mkdirSync(out,{recursive:true});let imports='';
 for(const[p,i]of parts.map((p,i)=>[p,i]as const)){const d=getDelivery(p,format,layout);for(const f of d.files){const q=path.join(out,p.id,f.name);fs.mkdirSync(path.dirname(q),{recursive:true});fs.writeFileSync(q,f.code)}imports+=`import C${i} from './${p.id}/${d.entry}';\n`}
 fs.writeFileSync(out+'/entry.jsx',`import React,{useState}from'react';import{createRoot}from'react-dom/client';${imports}
 function Pair({C,id}){const[v,set]=useState('');return <section data-part={id}><form data-case="uncontrolled"><C name="native" label="長い日本語の入力名" description="任意の説明を確認します。" defaultValue="残す値" clearable prefix="@" suffix=".dev"/></form><form data-case="controlled"><C name="controlled" label="制御した入力" value={v} onValueChange={n=>{window.calls.push({id,n});set(n)}} clearable/></form><div data-case="password"><C label="パスワード" type="password" defaultValue="password" clearable suffix="KEY"/></div><div data-case="multiline"><C label="本文" multiline autoGrow clearable defaultValue="短文"/></div><div data-case="disabled"><C label="無効" disabled defaultValue="保つ" clearable/></div><div data-case="readonly"><C label="読むだけ" readOnly defaultValue="保つ" clearable/></div></section>}
 window.calls=[];const root=createRoot(document.querySelector('#root'));window.teardown=()=>root.unmount();root.render(<React.StrictMode>{[${parts.map((p,i)=>`{id:${JSON.stringify(p.id)},C:C${i}}`).join(',')}].map(e=><Pair key={e.id} {...e}/>)}</React.StrictMode>);`);
 fs.writeFileSync(out+'/index.html','<!doctype html><html lang="ja"><meta charset="utf-8"><link rel="icon" href="data:,"><style>*{box-sizing:border-box}body{padding:12px;margin:0;background:#181d23;color:white;font:14px Arial}section{max-width:380px;margin:30px 0}section>div,section>form{margin:28px 0}</style><div id="root"></div><script type="module" src="./entry.jsx"></script>');
 const p=await browser.newPage({viewport:{width:390,height:844},reducedMotion:'reduce'});p.on('pageerror',e=>errors.push(e.message));await p.goto(s.resolvedUrls!.local[0]+path.relative(ROOT,out+'/index.html'));await p.waitForFunction(n=>document.querySelectorAll('[data-part]').length===n,parts.length);
 for(const part of parts){const host=p.locator(`[data-part="${part.id}"]`),un=host.locator('[data-case=uncontrolled]'),co=host.locator('[data-case=controlled]'),f=co.locator('.sop-field-control');assert.equal(await un.locator('.sop-field-fx i').count(),4);assert.equal(await un.locator('input').inputValue(),'残す値');await un.locator('input').fill('変更した値');assert.equal(await un.evaluate(e=>new FormData(e as HTMLFormElement).get('native')),'変更した値');await un.locator('.sop-field-clear').click();assert.equal(await un.locator('input').inputValue(),'');
  const geometry=()=>f.evaluate(e=>{const r=e.getBoundingClientRect(),s=e.closest('.sop-field-shell')!.getBoundingClientRect();return{x:r.x-s.x,y:r.y-s.y,w:r.width,h:r.height}});const before=await geometry();await f.fill('制御を保持');assert.deepEqual(await geometry(),before);assert.equal(await co.evaluate(e=>new FormData(e as HTMLFormElement).get('controlled')),'制御を保持');await co.locator('.sop-field-clear').click();assert.equal(await f.inputValue(),'');assert.deepEqual(await geometry(),before);
  const pw=host.locator('[data-case=password]'),pf=pw.locator('input');await pf.focus();await pf.evaluate((e:HTMLInputElement)=>e.setSelectionRange(1,4));const size=await pf.boundingBox();await pw.locator('.sop-field-reveal').click();assert.equal(await pf.getAttribute('type'),'text');assert.deepEqual(await pf.evaluate((e:HTMLInputElement)=>[e.selectionStart,e.selectionEnd]),[1,4]);assert.deepEqual(await pf.boundingBox(),size);const suffix=await pw.locator('.sop-field-suffix').boundingBox(),clear=await pw.locator('.sop-field-clear').boundingBox();assert.ok(suffix!.x+suffix!.width<=clear!.x,part.id+' suffix avoids action buttons');
  const multi=host.locator('[data-case=multiline]'),ta=multi.locator('textarea');const short=(await ta.boundingBox())!.height;await ta.fill('長い本文の内容を保持します。\n'.repeat(25));assert.ok((await ta.boundingBox())!.height>short);assert.equal(await ta.inputValue(),'長い本文の内容を保持します。\n'.repeat(25));assert.ok(await host.locator('[data-case=disabled] input').isDisabled());assert.ok(await host.locator('[data-case=readonly] input').evaluate((e:HTMLInputElement)=>e.readOnly));assert.ok(await host.locator('[data-case=readonly] .sop-field-clear').isDisabled());
  const ids=await host.locator('[id]').evaluateAll(es=>es.map(e=>e.id));assert.equal(new Set(ids).size,ids.length,part.id+' independent IDs');
 }
 for(const width of [320,390,768]){await p.setViewportSize({width,height:844});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),format+' '+layout+' fits '+width)}
 assert.equal(await p.evaluate(()=>(window as any).calls.length),parts.length*2);await p.emulateMedia({forcedColors:'active'});assert.ok(await p.locator('.sop-field-control').first().evaluate(e=>getComputedStyle(e).color!==getComputedStyle(e.closest('.sop-field-shell')!).backgroundColor));await p.evaluate(()=>(window as any).teardown());assert.equal(await p.locator('[data-part]').count(),0);await p.close();console.log('PASS '+parts.length+' fields React '+format+' '+layout+' real props/controlled/uncontrolled/clear/reveal/selection/prefix/suffix/multiline/disabled/IDs/cleanup');
}assert.deepEqual(errors,[]);}finally{await browser.close();await s.close();}
