import {escape as h, identity, seed, owned, lifecycle, announce, pulse, listenReset, clamp, type SignatureAPI} from './core.ts';
import {normalizeHex,hexToRGB,rgbToHex,rgbToHSV,hsvToRGB,readableInk,type HSV,type RGB} from './color-model.ts';
export interface ColorOptions { value?: string; defaultValue?: string; name?: string; label?: string; palette?: string[]; disabled?: boolean; readOnly?: boolean; onValueChange?: (hex: string) => void; }
export interface ColorState { value: string; hsv: HSV; valid: boolean; }
export const colorPalette=['#9BBBD0','#C3A5DC','#E6AE90','#BCD2AE','#E2DCC8','#242D38'];
export function colorMarkup(options: ColorOptions={},prefix='sg-color'){
 const value=normalizeHex(options.value??options.defaultValue??'#A5BCE0')??'#A5BCE0';
 return `<div class="sg-color-panel"><header class="sg-color-heading"><span class="sg-label">${h(options.label??'カラー')}</span><span class="sg-color-swatch" aria-hidden="true"><i></i><i></i><i></i></span></header><div class="sg-color-workspace"><div class="sg-hue-disc" aria-hidden="true"><i></i><b></b></div><div class="sg-color-sv" aria-hidden="true"><span class="sg-color-sv-handle"></span><span class="sg-color-sv-grid"></span></div><div class="sg-color-spectrum" aria-hidden="true">${Array.from({length:12},(_,i)=>`<i style="--h:${i*30};--i:${i}"></i>`).join('')}</div></div><div class="sg-color-controls"><label class="sg-color-axis"><span>HUE</span><input type="range" data-channel="h" min="0" max="359" step="1" aria-label="色相"><output data-axis="h"></output></label><label class="sg-color-axis"><span>SAT</span><input type="range" data-channel="s" min="0" max="100" step="1" aria-label="彩度"><output data-axis="s"></output></label><label class="sg-color-axis"><span>LIGHT</span><input type="range" data-channel="v" min="0" max="100" step="1" aria-label="明度"><output data-axis="v"></output></label></div><div class="sg-color-rgb">${['r','g','b'].map((c,i)=>`<label class="sg-rgb-channel" style="--channel:${i}"><span>${c.toUpperCase()}</span><input type="range" data-channel="${c}" min="0" max="255" step="1" aria-label="${({r:'赤',g:'緑',b:'青'})[c]}"><output data-axis="${c}"></output></label>`).join('')}</div><div class="sg-color-palette" role="group" aria-label="カラーパレット"></div><div class="sg-color-entry"><label for="${prefix}-hex">HEX</label><input id="${prefix}-hex" data-hex type="text" inputmode="text" spellcheck="false" autocomplete="off" aria-label="16進カラーコード" aria-describedby="${prefix}-error" value="${value}"><input type="color" data-native aria-label="標準カラーピッカー" value="${value}"><input type="hidden" data-color-value ${options.name?`name="${h(options.name)}"`:''} value="${value}"></div><p data-sg-error id="${prefix}-error" role="status"></p></div>`;
}
export function createColor(root:HTMLElement,provided:ColorOptions={}):SignatureAPI<ColorOptions,ColorState>{
 let options=seed(root,provided),value=normalizeHex(options.value??options.defaultValue??'#A5BCE0')??'#A5BCE0',hsv=rgbToHSV(hexToRGB(value)),valid=true;
 const life=lifecycle(root),host=owned(root),prefix=identity('sg-color');host.innerHTML=colorMarkup(options,prefix);
 const hex=host.querySelector<HTMLInputElement>('[data-hex]')!,hidden=host.querySelector<HTMLInputElement>('[data-color-value]')!,native=host.querySelector<HTMLInputElement>('[data-native]')!,error=host.querySelector<HTMLElement>('[data-sg-error]')!;
 function palette(){const list=options.palette??colorPalette;host.querySelector('.sg-color-palette')!.innerHTML=list.map(c=>normalizeHex(c)).filter((c):c is string=>!!c).map(c=>`<button type="button" data-swatch="${c}" style="--swatch:${c}" aria-label="${c}" aria-pressed="${c===value}"><span></span></button>`).join('');}
 function paint(syncText=true){
  host.querySelector('.sg-color-heading .sg-label')!.textContent=options.label??'カラー';
  root.style.setProperty('--sg-color',value);root.style.setProperty('--sg-hue',String(hsv[0]));root.style.setProperty('--sg-s',`${hsv[1]*100}%`);root.style.setProperty('--sg-v',`${(1-hsv[2])*100}%`);root.style.setProperty('--sg-color-ink',readableInk(value));
  const rgb=hexToRGB(value);const channels:Record<string,number>={h:hsv[0],s:hsv[1]*100,v:hsv[2]*100,r:rgb[0],g:rgb[1],b:rgb[2]};
  for(const input of host.querySelectorAll<HTMLInputElement>('[data-channel]')){input.value=String(Math.round(channels[input.dataset.channel!]));input.disabled=!!(options.disabled||options.readOnly);host.querySelector<HTMLOutputElement>(`[data-axis=${input.dataset.channel}]`)!.textContent=input.value;}
  if(syncText)hex.value=value;hidden.value=value;native.value=value;hex.disabled=!!options.disabled;hex.readOnly=!!options.readOnly;native.disabled=!!(options.disabled||options.readOnly);hidden.disabled=!!options.disabled;hidden.name=options.name??'';
  host.querySelectorAll<HTMLButtonElement>('[data-swatch]').forEach(b=>{b.setAttribute('aria-pressed',String(b.dataset.swatch===value));b.disabled=!!(options.disabled||options.readOnly);});
 }
 function commit(next:string,preserveHue=false){const normalized=normalizeHex(next);if(!normalized||options.disabled||options.readOnly)return;valid=true;error.textContent='';hex.removeAttribute('aria-invalid');
  const requested=normalized;if(options.value===undefined){value=requested;if(!preserveHue){const converted=rgbToHSV(hexToRGB(value));if(converted[1]===0)converted[0]=hsv[0];hsv=converted;}}else hsv=rgbToHSV(hexToRGB(value));
  options.onValueChange?.(requested);paint();announce(root,{value,requested});
 }
 host.addEventListener('input',event=>{const input=event.target as HTMLInputElement;if(input===native){commit(input.value);return;}const channel=input.dataset.channel;if(!channel)return;const n=Number(input.value);if(['h','s','v'].includes(channel)){hsv=[...hsv];hsv[channel==='h'?0:channel==='s'?1:2]=channel==='h'?n:n/100;commit(rgbToHex(hsvToRGB(hsv)),true);}else{const rgb=hexToRGB(value);rgb['rgb'.indexOf(channel)]=n;commit(rgbToHex(rgb));}},{signal:life.signal});
 function submitHex(){const n=normalizeHex(hex.value);if(n)commit(n);else{valid=false;hex.setAttribute('aria-invalid','true');error.textContent='#RGB または #RRGGBB で入力してください。';}}
 hex.addEventListener('change',submitHex,{signal:life.signal});hex.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.isComposing){e.preventDefault();submitHex();}if(e.key==='Escape'){e.preventDefault();hex.value=value;error.textContent='';valid=true;hex.removeAttribute('aria-invalid');}},{signal:life.signal});
 host.addEventListener('click',e=>{const b=(e.target as Element).closest<HTMLElement>('[data-swatch]');if(b){commit(b.dataset.swatch!);pulse(root,'color');}},{signal:life.signal});
 let pointer:number|null=null;
 function point(e:PointerEvent,area:HTMLElement){const r=area.getBoundingClientRect();if(!r.width||!r.height)return;hsv=[...hsv];if(area.classList.contains('sg-hue-disc')){const dx=e.clientX-r.left-r.width/2,dy=e.clientY-r.top-r.height/2;hsv[0]=(Math.atan2(dy,dx)*180/Math.PI+90+360)%360;}else{hsv[1]=clamp((e.clientX-r.left)/r.width,0,1);hsv[2]=1-clamp((e.clientY-r.top)/r.height,0,1);}commit(rgbToHex(hsvToRGB(hsv)),true);}
 for(const area of host.querySelectorAll<HTMLElement>('.sg-color-sv,.sg-hue-disc')){
  area.addEventListener('pointerdown',e=>{if(options.disabled||options.readOnly||e.button!==0||!e.isPrimary)return;pointer=e.pointerId;area.setPointerCapture(pointer);point(e,area);},{signal:life.signal});
  area.addEventListener('pointermove',e=>{if(pointer===e.pointerId&&!options.disabled&&!options.readOnly)point(e,area);},{signal:life.signal});
  const stop=()=>{pointer=null;};area.addEventListener('pointerup',stop,{signal:life.signal});area.addEventListener('pointercancel',stop,{signal:life.signal});area.addEventListener('lostpointercapture',stop,{signal:life.signal});
 }
 function reset(){if(options.value===undefined)value=normalizeHex(options.defaultValue??'#A5BCE0')??'#A5BCE0';hsv=rgbToHSV(hexToRGB(value));error.textContent='';valid=true;hex.removeAttribute('aria-invalid');paint();}
 listenReset(root,life.signal,reset);palette();paint();
 return {getState:()=>({value,hsv:[...hsv],valid}),reset,update(next){if(life.dead)return;const paletteChanged=next.palette!==undefined&&next.palette!==options.palette;options={...options,...next};if(next.value!==undefined){const n=normalizeHex(next.value);if(n&&n!==value){value=n;hsv=rgbToHSV(hexToRGB(n));}}if(paletteChanged)palette();paint(document.activeElement!==hex);},destroy:life.destroy,setPaused:life.setPaused};
}
