import {escape as h, safeURL, seed, owned, lifecycle, announce, pulse, uniqueItems, type SignatureAPI} from './core.ts';
export interface TimelineItem { id:string; title:string; description?:string; date?:string; dateTime?:string; status?:'done'|'active'|'pending'; href?:string; meta?:string; }
export interface TimelineOptions { items?:TimelineItem[]; label?:string; expanded?:string[]; defaultExpanded?:string[]; disabled?:boolean; onExpandedChange?:(ids:string[])=>void; }
export interface TimelineState { expanded:string[]; count:number; }
export function timelineMarkup(options:TimelineOptions={}) {
 const items=uniqueItems(options.items??[]),expanded=options.expanded??options.defaultExpanded??[];
 return `<section class="sg-timeline"><header class="sg-timeline-head"><span class="sg-kicker">${h(options.label??'履歴')}</span><span class="sg-timeline-count">${String(items.length).padStart(2,'0')}</span></header><ol class="sg-timeline-list">${items.map((item,i)=>`<li class="sg-event" data-event="${h(item.id)}" data-status="${h(item.status??'pending')}" style="--event:${i}"><span class="sg-event-route" aria-hidden="true"><i></i><b></b></span><time class="sg-event-time" ${item.dateTime?`datetime="${h(item.dateTime)}"`:''}>${h(item.date??String(i+1).padStart(2,'0'))}</time><div class="sg-event-main"><details ${expanded.includes(item.id)?'open':''}><summary ${options.disabled?'tabindex="-1" aria-disabled="true"':''}><span class="sg-event-heading">${h(item.title)}</span><span class="sg-event-status">${({done:'完了',active:'進行中',pending:'予定'})[item.status??'pending']}</span><span class="sg-event-chevron" aria-hidden="true">+</span></summary><div class="sg-event-body"><p>${h(item.description??'')}</p>${item.meta?`<span class="sg-event-meta">${h(item.meta)}</span>`:''}${safeURL(item.href)?`<a href="${h(safeURL(item.href))}" class="sg-event-link">詳細を見る <span aria-hidden="true">↗</span></a>`:''}</div></details></div></li>`).join('')}</ol>${items.length?'':'<p class="sg-sub">履歴はまだありません。</p>'}</section>`;
}
export function createTimeline(root:HTMLElement,provided:TimelineOptions={}):SignatureAPI<TimelineOptions,TimelineState>{
 let options=seed(root,provided),items=uniqueItems(options.items??[]),expanded=[...(options.expanded??options.defaultExpanded??[])];
 const life=lifecycle(root),host=owned(root);let painting=false;
 function paint(){painting=true;host.querySelectorAll<HTMLElement>('[data-event]').forEach(e=>{const d=e.querySelector('details')!;d.open=expanded.includes(e.dataset.event!);const sum=d.querySelector('summary')!;sum.tabIndex=options.disabled?-1:0;sum.setAttribute('aria-disabled',String(!!options.disabled));});painting=false;}
 function render(){host.innerHTML=timelineMarkup({...options,items,expanded});paint();}
 host.addEventListener('click',event=>{const target=(event.target as Element).closest('summary');if(!target)return;if(options.disabled){event.preventDefault();return;}event.preventDefault();const id=target.closest<HTMLElement>('[data-event]')!.dataset.event!;const next=expanded.includes(id)?expanded.filter(x=>x!==id):[...expanded,id];if(options.expanded===undefined)expanded=next;options.onExpandedChange?.(next);paint();pulse(root,'event');announce(root,{expanded:[...expanded],requested:next});},{signal:life.signal});
 // details/summary retains native keyboard behaviour and can be rendered without JS.
 host.addEventListener('toggle',event=>{if(painting||life.dead)return;const detail=event.target as HTMLDetailsElement;if(detail.tagName!=='DETAILS')return;const id=detail.closest<HTMLElement>('[data-event]')?.dataset.event;if(!id)return;const should=expanded.includes(id);if(detail.open!==should)detail.open=should;},{capture:true,signal:life.signal});
 render();
 return {getState:()=>({expanded:[...expanded],count:items.length}),reset(){if(options.expanded===undefined)expanded=[...(options.defaultExpanded??[])];paint();},update(next){if(life.dead)return;const rebuild=next.items!==undefined&&next.items!==options.items||next.label!==undefined&&next.label!==options.label;options={...options,...next};items=uniqueItems(options.items??[]);if(next.expanded)expanded=[...next.expanded];expanded=expanded.filter(id=>items.some(i=>i.id===id));if(rebuild)render();else paint();},destroy:life.destroy,setPaused:life.setPaused};
}
