import {escape as h, seed, owned, lifecycle, announce, pulse, uniqueItems, identity, listenReset, arrowSVG, checkSVG, type SignatureAPI} from './core.ts';
export interface WizardStep { id:string; title:string; description?:string; fields?:{name:string;label:string;placeholder?:string;required?:boolean;type?:'text'|'email'|'textarea'}[]; }
export interface WizardOptions { steps?:WizardStep[]; current?:string; defaultCurrent?:string; disabled?:boolean; allowJump?:boolean; label?:string; beforeNext?:(step:string,values:Record<string,string>)=>boolean|string|Promise<boolean|string>; onStepChange?:(id:string)=>void; onComplete?:(values:Record<string,string>)=>void; }
export interface WizardState { current:string; index:number; count:number; busy:boolean; complete:boolean; values:Record<string,string>; }
export function wizardMarkup(options:WizardOptions={},prefix='sg-wizard'){
 const steps=uniqueItems(options.steps??[]),current=options.current??options.defaultCurrent??steps[0]?.id??'',index=steps.findIndex(s=>s.id===current);
 return `<section class="sg-wizard" aria-label="${h(options.label??'手順')}" data-wizard><div class="sg-wizard-meter" aria-hidden="true"><svg viewBox="0 0 100 100"><circle cx="50" cy="50" r="43"/><circle class="sg-wizard-meter-fill" cx="50" cy="50" r="43" pathLength="100"/></svg><span data-wizard-count>${String(index+1).padStart(2,'0')}</span><small>/ ${String(steps.length).padStart(2,'0')}</small></div><ol class="sg-wizard-nav" role="list">${steps.map((s,i)=>`<li style="--step:${i}" data-wizard-step="${h(s.id)}"><button type="button" data-step-target="${h(s.id)}" aria-controls="${prefix}-panel-${i}" ${s.id===current?'aria-current="step"':''}><span class="sg-step-index"><b>${String(i+1).padStart(2,'0')}</b>${checkSVG}</span><span class="sg-step-title">${h(s.title)}</span><span class="sg-step-shape" aria-hidden="true"><i></i><i></i><i></i></span></button></li>`).join('')}</ol><div class="sg-wizard-panels">${steps.map((s,i)=>`<section class="sg-wizard-panel" id="${prefix}-panel-${i}" data-step-panel="${h(s.id)}" ${s.id!==current?'hidden':''}><div class="sg-wizard-page-art" aria-hidden="true"><i></i><i></i><i></i></div><h3>${h(s.title)}</h3><p>${h(s.description??'')}</p><div class="sg-wizard-fields">${(s.fields??[]).map((f,j)=>`<label for="${prefix}-f-${i}-${j}"><span>${h(f.label)}${f.required?' <small>必須</small>':''}</span>${f.type==='textarea'?`<textarea id="${prefix}-f-${i}-${j}" data-field="${h(f.name)}" name="${h(f.name)}" placeholder="${h(f.placeholder??'')}" ${f.required?'required':''}></textarea>`:`<input id="${prefix}-f-${i}-${j}" type="${f.type==='email'?'email':'text'}" data-field="${h(f.name)}" name="${h(f.name)}" placeholder="${h(f.placeholder??'')}" ${f.required?'required':''}>`}</label>`).join('')}</div></section>`).join('')}${steps.length?'':'<p class="sg-sub">手順がありません。</p>'}</div><div class="sg-wizard-error" data-wizard-error role="status"></div><footer class="sg-wizard-footer"><button type="button" data-wizard-prev class="sg-wizard-back">← 戻る</button><span class="sg-wizard-progress" aria-hidden="true"><i></i></span><button type="button" data-wizard-next class="sg-wizard-next"><span data-next-label>次へ</span>${arrowSVG}</button></footer><p class="sg-sr" data-wizard-status role="status"></p></section>`;
}
export function createWizard(root:HTMLElement,provided:WizardOptions={}):SignatureAPI<WizardOptions,WizardState>{
 let options=seed(root,provided),steps=uniqueItems(options.steps??[]),current=options.current??options.defaultCurrent??steps[0]?.id??'',busy=false,complete=false,token=0;
 if(!steps.some(s=>s.id===current))current=steps[0]?.id??'';
 const host=owned(root),life=lifecycle(root);const prefix=identity('sg-wizard');let pendingFocus:{owner:HTMLElement;context:HTMLElement;step:string;temporary:boolean}|null=null;
 function values(){return Object.fromEntries([...host.querySelectorAll<HTMLInputElement|HTMLTextAreaElement>('[data-field]')].map(f=>[f.dataset.field!,f.value]));}
 function index(){return Math.max(0,steps.findIndex(s=>s.id===current));}
 function paint(){const n=index();root.style.setProperty('--sg-step-index',String(n));root.style.setProperty('--sg-step-rows',String(Math.max(1,steps.length)));host.querySelector('[data-wizard]')?.setAttribute('aria-label',options.label??'手順');root.dataset.sgComplete=String(complete);root.dataset.sgBusy=String(busy);root.style.setProperty('--sg-step-p',String(steps.length>1?n/(steps.length-1):1));
 host.querySelectorAll<HTMLElement>('[data-wizard-step]').forEach((li,i)=>{li.dataset.stepState=i<n?'done':i===n?'current':'future';const b=li.querySelector<HTMLButtonElement>('button')!;b.disabled=!!options.disabled||busy||(!options.allowJump&&i>n);if(i===n)b.setAttribute('aria-current','step');else b.removeAttribute('aria-current');});
 host.querySelectorAll<HTMLElement>('[data-step-panel]').forEach(panel=>{const hidden=panel.dataset.stepPanel!==current;panel.hidden=hidden;panel.inert=hidden;});
 host.querySelectorAll<HTMLInputElement|HTMLTextAreaElement>('[data-field]').forEach(f=>{f.disabled=!!options.disabled||busy;const step=steps.find(s=>s.id===f.closest<HTMLElement>('[data-step-panel]')?.dataset.stepPanel);f.required=step?.id===current&&!!step.fields?.find(spec=>spec.name===f.dataset.field)?.required;});
 const back=host.querySelector<HTMLButtonElement>('[data-wizard-prev]')!,next=host.querySelector<HTMLButtonElement>('[data-wizard-next]')!;
 back.disabled=!!options.disabled||busy||n===0;next.disabled=!!options.disabled||busy||!steps.length||complete;host.querySelector('[data-next-label]')!.textContent=busy?'確認中…':complete?'完了':n===steps.length-1?'完了':'次へ';
 host.querySelector('[data-wizard-count]')!.textContent=String(steps.length?n+1:0).padStart(2,'0');
 }
 function render(previous:Record<string,string>={},preserve=false){
  const active=document.activeElement instanceof HTMLElement&&host.contains(document.activeElement)?document.activeElement:null,oldFields=[...host.querySelectorAll<HTMLInputElement|HTMLTextAreaElement>('[data-field]')],key=(f:HTMLElement)=>(f.closest<HTMLElement>('[data-step-panel]')?.dataset.stepPanel??'')+'\0'+f.dataset.field,focusedField=active?.matches('[data-field]')?active as HTMLInputElement|HTMLTextAreaElement:null,focusedKey=focusedField?key(focusedField):null,ordinal=focusedField?oldFields.indexOf(focusedField):-1,targetStep=active?.closest<HTMLElement>('[data-step-target]')?.dataset.stepTarget;
  const fresh=wizardMarkup({...options,steps,current},prefix);
  if(!preserve)host.innerHTML=fresh;else{
   const draft=document.createElement('div');draft.innerHTML=fresh;
   const nodeKey=(node:Node)=>{if(!(node instanceof Element))return null;return node.getAttribute('data-step-panel')?'panel:'+node.getAttribute('data-step-panel'):node.getAttribute('data-wizard-step')?'step:'+node.getAttribute('data-wizard-step'):node.matches('label')?'field-label:'+node.querySelector<HTMLElement>('[data-field]')?.dataset.field:node.getAttribute('data-field')?'field:'+node.getAttribute('data-field'):null;};
   const compatible=(old:Node,next:Node)=>old.nodeType===next.nodeType&&(!(old instanceof Element)||next instanceof Element&&old.tagName===next.tagName&&(!(old instanceof HTMLInputElement)||next instanceof HTMLInputElement&&old.type===next.type))&&nodeKey(old)===nodeKey(next);
   function reconcile(parent:HTMLElement,nextParent:HTMLElement){
    const candidates=[...parent.childNodes],used=new Set<Node>();let cursor=parent.firstChild;
    for(const next of [...nextParent.childNodes]){
     const match=candidates.find(old=>!used.has(old)&&compatible(old,next));
     const node=match??next.cloneNode(true);used.add(node);
     if(node!==cursor){const move=(parent as HTMLElement&{moveBefore?:(node:Node,child:Node|null)=>void}).moveBefore;if(match&&move)move.call(parent,node,cursor);else parent.insertBefore(node,cursor);}
     if(match instanceof HTMLElement&&next instanceof HTMLElement){for(const attr of [...match.attributes])if(!next.hasAttribute(attr.name))match.removeAttribute(attr.name);for(const attr of [...next.attributes])if(match.getAttribute(attr.name)!==attr.value)match.setAttribute(attr.name,attr.value);if(!(match instanceof HTMLInputElement)&&!(match instanceof HTMLTextAreaElement))reconcile(match,next);}
     else if(match&&match.nodeValue!==next.nodeValue)match.nodeValue=next.nodeValue;
     cursor=node.nextSibling;
    }
    for(const old of candidates)if(!used.has(old))old.parentNode?.removeChild(old);
   }
   reconcile(host,draft);
  }
  host.querySelectorAll<HTMLInputElement|HTMLTextAreaElement>('[data-field]').forEach(f=>{if(!oldFields.includes(f)&&f.dataset.field! in previous)f.value=previous[f.dataset.field!];});paint();
  if(!preserve||!active)return;
  const fields=[...host.querySelectorAll<HTMLInputElement|HTMLTextAreaElement>('[data-field]')].filter(f=>!f.disabled&&!f.closest('[hidden]')),same=focusedKey?fields.find(f=>key(f)===focusedKey):null,buttons=[...host.querySelectorAll<HTMLButtonElement>('[data-step-target]')],button=targetStep?buttons.find(b=>b.dataset.stepTarget===targetStep&&!b.disabled):null,target=same??(focusedField?fields[Math.min(Math.max(0,ordinal),fields.length-1)]:button);
  if(target)target.focus({preventScroll:true});else if(focusedField||targetStep){const heading=host.querySelector<HTMLElement>('[data-step-panel]:not([hidden]) h3')??host.querySelector<HTMLElement>('[data-wizard]');if(heading){heading.tabIndex=-1;heading.focus({preventScroll:true});}}
 }
 function focusCurrent(){const target=(!complete?host.querySelector<HTMLInputElement|HTMLTextAreaElement>('[data-step-panel]:not([hidden]) [data-field]:not(:disabled)'):null)??host.querySelector<HTMLElement>('[data-step-panel]:not([hidden]) h3')??host.querySelector<HTMLElement>('[data-wizard]');if(target){if(!target.matches('[data-field]'))target.tabIndex=-1;target.focus({preventScroll:true});}}
 function releasePending(restore=false){const pending=pendingFocus;pendingFocus=null;if(!pending)return;const ownedFocus=pending.context.isConnected&&document.activeElement===pending.context;if(pending.temporary)pending.context.removeAttribute('tabindex');if(!restore||!ownedFocus)return;if(!complete&&current===pending.step&&pending.owner.isConnected&&!pending.owner.matches(':disabled')&&!pending.owner.closest('[hidden]'))pending.owner.focus({preventScroll:true});else focusCurrent();}
 function setStep(id:string){const oldFocus=document.activeElement instanceof HTMLElement&&host.contains(document.activeElement)?document.activeElement:null;if(options.current===undefined)current=id;complete=false;options.onStepChange?.(id);paint();if(!busy&&oldFocus&&(oldFocus.matches(':disabled')||!!oldFocus.closest('[hidden]')))focusCurrent();pulse(root,'step');announce(root,{current,requested:id});host.querySelector('[data-wizard-status]')!.textContent=`${index()+1} / ${steps.length}：${steps[index()]?.title??''}`;}
 async function next(){if(busy||options.disabled||!steps.length||complete)return;const active=host.querySelector<HTMLElement>('[data-step-panel]:not([hidden])');const invalid=[...active?.querySelectorAll<HTMLInputElement|HTMLTextAreaElement>('[data-field]')??[]].find(f=>!f.checkValidity());if(invalid){invalid.reportValidity();invalid.focus();return;}
  const own=++token,owner=document.activeElement instanceof HTMLElement&&host.contains(document.activeElement)?document.activeElement:null,context=host.querySelector<HTMLElement>('[data-wizard]');if(owner&&context)pendingFocus={owner,context,step:current,temporary:!context.hasAttribute('tabindex')};busy=true;paint();if(pendingFocus&&document.activeElement!==owner){context!.tabIndex=-1;context!.focus({preventScroll:true});}const err=host.querySelector<HTMLElement>('[data-wizard-error]')!;err.textContent='';
  try{const result=options.beforeNext?await options.beforeNext(current,values()):true;if(life.dead||own!==token)return;if(result!==true){err.textContent=typeof result==='string'?result:'入力内容を確認してください。';return;}const n=index();if(n===steps.length-1){complete=true;options.onComplete?.(values());announce(root,{current,complete:true,values:values()});host.querySelector('[data-wizard-status]')!.textContent='手順が完了しました。';}else setStep(steps[n+1].id);
  }catch(error){if(!life.dead&&own===token)err.textContent=error instanceof Error?error.message:'確認処理に失敗しました。';}finally{if(!life.dead&&own===token){busy=false;paint();releasePending(true);}}
 }
 host.addEventListener('click',event=>{const target=event.target as Element;if(target.closest('[data-wizard-next]'))void next();else if(target.closest('[data-wizard-prev]')&&!busy&&!options.disabled&&steps.length)setStep(steps[Math.max(0,index()-1)].id);else{const b=target.closest<HTMLButtonElement>('[data-step-target]');if(b&&!b.disabled)setStep(b.dataset.stepTarget!);}},{signal:life.signal});
 host.addEventListener('keydown',event=>{if(event.key==='Enter'&&!(event.target instanceof HTMLTextAreaElement)&&(event.target as Element).matches('[data-field]')&&!event.isComposing){event.preventDefault();void next();}},{signal:life.signal});
 function reset(){if(life.dead)return;const wasFocused=host.contains(document.activeElement);releasePending();token++;busy=false;complete=false;if(options.current===undefined)current=steps.some(step=>step.id===options.defaultCurrent)?options.defaultCurrent!:steps[0]?.id??'';render();if(wasFocused)focusCurrent();}
 listenReset(root,life.signal,reset);render();
 return {getState:()=>({current,index:index(),count:steps.length,busy,complete,values:values()}),reset,update(nextOptions){if(life.dead)return;const oldFocus=document.activeElement instanceof HTMLElement&&host.contains(document.activeElement)?document.activeElement:null;const stepChanged=nextOptions.current!==undefined&&nextOptions.current!==current,rebuild=nextOptions.steps!==undefined&&nextOptions.steps!==options.steps;const oldValues=rebuild?values():{};if(rebuild||nextOptions.current!==undefined&&nextOptions.current!==current){token++;busy=false;complete=false;}options={...options,...nextOptions};steps=uniqueItems(options.steps??[]);if(nextOptions.current!==undefined)current=nextOptions.current;if(!steps.some(s=>s.id===current))current=steps[0]?.id??'';if(rebuild)render(oldValues,true);else paint();if(!busy&&pendingFocus)releasePending(true);else if(!busy&&oldFocus&&(stepChanged||oldFocus.matches(':disabled')||!!oldFocus.closest('[hidden]')))focusCurrent();},destroy(){token++;releasePending();life.destroy();},setPaused:life.setPaused};
}
