import {escape as h, seed, owned, lifecycle, announce, pulse, uniqueItems, identity, listenReset, arrowSVG, checkSVG, type SignatureAPI} from './core.ts';
export interface WizardStep { id:string; title:string; description?:string; fields?:{name:string;label:string;placeholder?:string;required?:boolean;type?:'text'|'email'|'textarea'}[]; }
export interface WizardOptions { steps?:WizardStep[]; current?:string; defaultCurrent?:string; disabled?:boolean; allowJump?:boolean; label?:string; beforeNext?:(step:string,values:Record<string,string>)=>boolean|string|Promise<boolean|string>; onStepChange?:(id:string)=>void; onComplete?:(values:Record<string,string>)=>void; }
export interface WizardState { current:string; index:number; count:number; busy:boolean; complete:boolean; values:Record<string,string>; }
export function wizardMarkup(options:WizardOptions={},prefix='sg-wizard'){
 const steps=uniqueItems(options.steps??[]),current=options.current??options.defaultCurrent??steps[0]?.id??'',index=steps.findIndex(s=>s.id===current);
 return `<section class="sg-wizard" aria-label="${h(options.label??'手順')}" data-wizard><div class="sg-wizard-meter" aria-hidden="true"><svg viewBox="0 0 100 100"><circle cx="50" cy="50" r="43"/><circle class="sg-wizard-meter-fill" cx="50" cy="50" r="43" pathLength="100"/></svg><span data-wizard-count>${String(index+1).padStart(2,'0')}</span><small>/ ${String(steps.length).padStart(2,'0')}</small></div><ol class="sg-wizard-nav">${steps.map((s,i)=>`<li style="--step:${i}" data-wizard-step="${h(s.id)}"><button type="button" data-step-target="${h(s.id)}" aria-controls="${prefix}-panel-${i}" ${s.id===current?'aria-current="step"':''}><span class="sg-step-index"><b>${String(i+1).padStart(2,'0')}</b>${checkSVG}</span><span class="sg-step-title">${h(s.title)}</span><span class="sg-step-shape" aria-hidden="true"><i></i><i></i><i></i></span></button></li>`).join('')}</ol><div class="sg-wizard-panels">${steps.map((s,i)=>`<section class="sg-wizard-panel" id="${prefix}-panel-${i}" data-step-panel="${h(s.id)}" ${s.id!==current?'hidden':''}><div class="sg-wizard-page-art" aria-hidden="true"><i></i><i></i><i></i></div><h3>${h(s.title)}</h3><p>${h(s.description??'')}</p><div class="sg-wizard-fields">${(s.fields??[]).map((f,j)=>`<label for="${prefix}-f-${i}-${j}"><span>${h(f.label)}${f.required?' <small>必須</small>':''}</span>${f.type==='textarea'?`<textarea id="${prefix}-f-${i}-${j}" data-field="${h(f.name)}" name="${h(f.name)}" placeholder="${h(f.placeholder??'')}" ${f.required?'required':''}></textarea>`:`<input id="${prefix}-f-${i}-${j}" type="${f.type==='email'?'email':'text'}" data-field="${h(f.name)}" name="${h(f.name)}" placeholder="${h(f.placeholder??'')}" ${f.required?'required':''}>`}</label>`).join('')}</div></section>`).join('')}${steps.length?'':'<p class="sg-sub">手順がありません。</p>'}</div><div class="sg-wizard-error" data-wizard-error role="status"></div><footer class="sg-wizard-footer"><button type="button" data-wizard-prev class="sg-wizard-back">← 戻る</button><span class="sg-wizard-progress" aria-hidden="true"><i></i></span><button type="button" data-wizard-next class="sg-wizard-next"><span data-next-label>次へ</span>${arrowSVG}</button></footer><p class="sg-sr" data-wizard-status role="status"></p></section>`;
}
export function createWizard(root:HTMLElement,provided:WizardOptions={}):SignatureAPI<WizardOptions,WizardState>{
 let options=seed(root,provided),steps=uniqueItems(options.steps??[]),current=options.current??options.defaultCurrent??steps[0]?.id??'',busy=false,complete=false,token=0;
 if(!steps.some(s=>s.id===current))current=steps[0]?.id??'';
 const host=owned(root),life=lifecycle(root);const prefix=identity('sg-wizard');
 function values(){return Object.fromEntries([...host.querySelectorAll<HTMLInputElement|HTMLTextAreaElement>('[data-field]')].map(f=>[f.dataset.field!,f.value]));}
 function index(){return Math.max(0,steps.findIndex(s=>s.id===current));}
 function paint(){const n=index();host.querySelector('[data-wizard]')?.setAttribute('aria-label',options.label??'手順');root.dataset.sgComplete=String(complete);root.dataset.sgBusy=String(busy);root.style.setProperty('--sg-step-p',String(steps.length>1?n/(steps.length-1):1));
 host.querySelectorAll<HTMLElement>('[data-wizard-step]').forEach((li,i)=>{li.dataset.stepState=i<n?'done':i===n?'current':'future';const b=li.querySelector<HTMLButtonElement>('button')!;b.disabled=!!options.disabled||busy||(!options.allowJump&&i>n);if(i===n)b.setAttribute('aria-current','step');else b.removeAttribute('aria-current');});
 host.querySelectorAll<HTMLElement>('[data-step-panel]').forEach(panel=>{const hidden=panel.dataset.stepPanel!==current;panel.hidden=hidden;panel.inert=hidden;});
 host.querySelectorAll<HTMLInputElement|HTMLTextAreaElement>('[data-field]').forEach(f=>{f.disabled=!!options.disabled||busy;const step=steps.find(s=>s.id===f.closest<HTMLElement>('[data-step-panel]')?.dataset.stepPanel);f.required=step?.id===current&&!!step.fields?.find(spec=>spec.name===f.dataset.field)?.required;});
 const back=host.querySelector<HTMLButtonElement>('[data-wizard-prev]')!,next=host.querySelector<HTMLButtonElement>('[data-wizard-next]')!;
 back.disabled=!!options.disabled||busy||n===0;next.disabled=!!options.disabled||busy||!steps.length||complete;host.querySelector('[data-next-label]')!.textContent=busy?'確認中…':complete?'完了':n===steps.length-1?'完了':'次へ';
 host.querySelector('[data-wizard-count]')!.textContent=String(steps.length?n+1:0).padStart(2,'0');
 }
 function render(previous:Record<string,string>={}){host.innerHTML=wizardMarkup({...options,steps,current},prefix);host.querySelectorAll<HTMLInputElement|HTMLTextAreaElement>('[data-field]').forEach(f=>{if(f.dataset.field! in previous)f.value=previous[f.dataset.field!];});paint();}
 function setStep(id:string){if(options.current===undefined)current=id;complete=false;options.onStepChange?.(id);paint();pulse(root,'step');announce(root,{current,requested:id});host.querySelector('[data-wizard-status]')!.textContent=`${index()+1} / ${steps.length}：${steps[index()]?.title??''}`;}
 async function next(){if(busy||options.disabled||!steps.length||complete)return;const active=host.querySelector<HTMLElement>('[data-step-panel]:not([hidden])');const invalid=[...active?.querySelectorAll<HTMLInputElement|HTMLTextAreaElement>('[data-field]')??[]].find(f=>!f.checkValidity());if(invalid){invalid.reportValidity();invalid.focus();return;}
  const own=++token;busy=true;paint();const err=host.querySelector<HTMLElement>('[data-wizard-error]')!;err.textContent='';
  try{const result=options.beforeNext?await options.beforeNext(current,values()):true;if(life.dead||own!==token)return;if(result!==true){err.textContent=typeof result==='string'?result:'入力内容を確認してください。';return;}const n=index();if(n===steps.length-1){complete=true;options.onComplete?.(values());announce(root,{current,complete:true,values:values()});host.querySelector('[data-wizard-status]')!.textContent='手順が完了しました。';}else setStep(steps[n+1].id);
  }catch(error){if(!life.dead&&own===token)err.textContent=error instanceof Error?error.message:'確認処理に失敗しました。';}finally{if(!life.dead&&own===token){busy=false;paint();}}
 }
 host.addEventListener('click',event=>{const target=event.target as Element;if(target.closest('[data-wizard-next]'))void next();else if(target.closest('[data-wizard-prev]')&&!busy&&!options.disabled&&steps.length)setStep(steps[Math.max(0,index()-1)].id);else{const b=target.closest<HTMLButtonElement>('[data-step-target]');if(b&&!b.disabled)setStep(b.dataset.stepTarget!);}},{signal:life.signal});
 host.addEventListener('keydown',event=>{if(event.key==='Enter'&&!(event.target instanceof HTMLTextAreaElement)&&(event.target as Element).matches('[data-field]')&&!event.isComposing){event.preventDefault();void next();}},{signal:life.signal});
 function reset(){token++;busy=false;complete=false;if(options.current===undefined)current=options.defaultCurrent??steps[0]?.id??'';render();}
 listenReset(root,life.signal,reset);render();
 return {getState:()=>({current,index:index(),count:steps.length,busy,complete,values:values()}),reset,update(nextOptions){if(life.dead)return;const rebuild=nextOptions.steps!==undefined&&nextOptions.steps!==options.steps;const oldValues=rebuild?values():{};if(rebuild||nextOptions.current!==undefined&&nextOptions.current!==current){token++;busy=false;complete=false;}options={...options,...nextOptions};steps=uniqueItems(options.steps??[]);if(nextOptions.current!==undefined)current=nextOptions.current;if(!steps.some(s=>s.id===current))current=steps[0]?.id??'';if(rebuild)render(oldValues);else paint();},destroy(){token++;life.destroy();},setPaused:life.setPaused};
}
