import json,hashlib
from pathlib import Path
p=Path(__file__).parent;root=p.parents[3];inp=json.loads((p/'review-input-2.json').read_text());checks={f:hashlib.sha256((root/f).read_bytes()).hexdigest()==h for f,h in inp['sourceHashes'].items()};data=json.loads((p/'measurements-2.json').read_text())
notes={404:'薄い羽根の縦端と上下一線へ再構成し、旧緑の厚い階段から別の選択機構になった。番号と選択面が安定し、狭幅でも列を維持。',405:'太い額縁を除き、選択番号から下へ続くしおりの切込みに意味を集めた。数値に対する独自性が読み取れる。',408:'大きい前後操作を上段に置き、番号列を補助へ下げた。続けて読む用途が他 B と配置から区別できる。',409:'前後キーと番号列が一段の細いツールバーになり、狭い領域向けの用途差が成立。実root222pxではLTR/RTLの選択とフォーカスが収まる。',410:'明朝のノンブルと大きい現在数値、下段の前後操作で読み物のページ末尾として独立した設計になった。',414:'石の面を少しずつずらし、細い枝で到達面へ接続するため旧メニュー一覧より階層を読める。hover文字色だけ修正が必要。',416:'続き紙のミシン目を保ち、現在位置を一段進めた接続で親と到達先を分けた。素材と経路表示の関係が成立。',418:'縫い線が親リンクの脇を通り、下の到達面の綴じ目へ入る。単なる横罫一覧から経路の終点を示す構造へ改善。',423:'各段の小さな輪と連続線が階層をたどる道筋として読め、文字へ近づく大きな横棒は解消。展開メニューのhover文字色を修正したい。',428:'小さな親パスと次行の現在見出しを分け、詳細ページに添える用途が独立した。長い階層名のメニュー内収まりは未完成。'}
findings={414:[dict(kind='contrast',description='親リンク Home のhover完了後、文字rgb(89,111,75)が実際の石の面rgb(223,231,209)上で4.338953:1。13px。portable/gallery一致。通常時6.389:1から低下する。',recommendation='石の面を背景としてhover文字も4.5:1以上に保つ。文字色を維持し下線でhoverを示す方法でもよい。',evidence=['contrast-summary-2.json','evidence-2/breadcrumbs-portable-base-sheet.jpg','measurements-2.json'])],423:[dict(kind='contrast',description='展開メニューの Objects にhoverすると13px文字rgb(136,95,123)と面rgb(250,230,243)で4.453118:1。portable/gallery一致。',recommendation='実際のメニュー面に対して4.5:1以上へhover文字色を調整する。',evidence=['contrast-summary-2.json','evidence-2/breadcrumbs-portable-menus-sheet.jpg','measurements-breadcrumbs-2.json'])],428:[dict(kind='overflow',description='省略メニューを320pxで開き、空白なしの階層名 LongUnbrokenProjectIdentifier1234567890 を2回連結すると折り返されず、panel clientWidth238 / scrollWidth447。文字末尾が面の右へportable205.48px/gallery206.32pxはみ出し、画像では末尾が欠ける。',recommendation='メニュー内リンクにoverflow-wrap:anywhereと縮小可能な幅を設定し、名前全体を読めるようにする。LTR/RTL/forcedでも確認する。',evidence=['evidence-2/soft-location-trail-portable-longcheck-expanded-long-menu.png','measurements-breadcrumbs-long-2.json'])]}
parts=[]
for row in data:
 if row['mode']!='portable':continue
 n=row['number'];cat=row['category'];ev=[f'evidence-2/{cat}-{mode}-base-sheet.jpg' for mode in ['portable','gallery']];ev += [f'evidence-2/{cat}-{mode}-'+('222' if cat=='pagination' else 'menus')+'-sheet.jpg' for mode in ['portable','gallery']]
 parts.append(dict(id=row['id'],number=n,verdict='changes_required' if n in findings else 'pass',note=notes[n],findings=findings.get(n,[]),evidence=ev,reviewed=['round2 frozen portable','actual gallery CSS + frozen init fixture','rest/hover entry/exit/reentry/returned','320 viewport / long label / RTL / forced / reduced', 'root222 LTR/RTL 1000 pages current999; update2 without stale focus; scale .75; Tab; Enter; pointer; disabled; readonly' if cat=='pagination' else 'collapsed menu / hover link / long name / Enter navigation / Escape focus return / disabled']))
r=dict(batch='B012',round=2,overall='changes_required',parts=parts,coverage={'parts':10,'pass':7,'changes_required':3,'sourceHashesMatchAtFinalization':all(checks.values()),'changedAfterCapture':[f for f,v in checks.items() if not v],'viewedSheets':sorted(str(f.relative_to(p)) for f in (p/'evidence-2').glob('*-sheet.jpg')),'paginationClarification':'初期試験のparent222はsnapshot余白により実root174pxだった。R409はその幅でwindow30pxとなり44px対象を全表示できない。実root222pxへ揃えた追加試験は全5件通過。API値更新で既存focus1000を保持した試験ではfocusが優先されるため、選択保持の測定はblur後に分離。','scope':'上記の特定状態と対象の実操作・実画像検査であり、無欠陥保証ではない。造形判断と再現不具合を分けた。'},evidence=['measurements-2.json','measurements-pagination-222-2.json','measurements-pagination-native-2.json','measurements-breadcrumbs-2.json','measurements-breadcrumbs-long-2.json','contrast-summary-2.json'])
(p/'review-2.json').write_text(json.dumps(r,ensure_ascii=False,indent=2)+'\n')
lines=['# B012 round2 独立検査','', '**changes_required — 7件 pass / 3件差戻し。**','', '全10件を凍結portableと実galleryで検査。作者は変更していない。10枚の比較画像と候補の個別画像を視認した。Aの造形・Bの用途差はいずれも今回の方向で成立。再現した残存問題は下記3件。','']
for part in parts:
 lines += [f"## R{part['number']:03} {part['id']} — {part['verdict']}",'',part['note'],'']
 for f in part['findings']:lines += [f"- **{f['kind']}**: {f['description']} 改善案: {f['recommendation']}"]
 lines += ['', '証拠: '+', '.join(f'[{Path(e).name}]({e})' for e in part['evidence']),'']
lines += ['## 検査条件','', '- 全件: 通常、hover入口/解除/再進入、320px、長文、RTL、forced/reduced。','- ページ送り: 実root222px、1000中999、更新2、LTR/RTL、scale .75、Tab、外側scroll保持。Enterで3、前クリックで2へ更新。disabled全操作無効、readonlyは2維持。','- パンくず: 省略メニュー、親リンクhover、長い階層名、Enterリンク移動、Escapeで閉じて省略ボタンへfocus復帰。disabled時リンクとボタン無効。','- 初期R409候補は親幅222pxが実root174pxになった条件。実root222pxの全表示試験は通過。既存フォーカスを優先する動作と選択表示を混同しないようblur後の更新も測定。','- コントラストは疑似要素の実背景面を含めた。特定条件の検査であり、無欠陥保証ではない。']
(p/'review-2.md').write_text('\n'.join(lines)+'\n');print('saved',len(parts),'parts; hashes match',all(checks.values()))
