from pathlib import Path
import json,hashlib
p=Path(__file__).parent;m=json.load(open(p/'review-input-10.json'));bad=[f for f,h in m['sourceHashes'].items()if hashlib.sha256(Path(f).read_bytes()).hexdigest()!=h];assert not bad;(p/'hash-verification-final-10.json').write_text(json.dumps({'authorHashesMatched':100,'sharedHashesMatched':1,'mismatches':bad},indent=2)+'\n')
a=json.load(open(p/'measurements-context-10.json'));b=json.load(open(p/'measurements-navigation-10.json'));c=json.load(open(p/'measurements-react-context-10.json'));d=json.load(open(p/'measurements-react-navigation-10.json'));assert [len(a),len(b),len(c),len(d)]==[8,12,20,28];assert not any(r.get('error')or r.get('errors')or any(not x['pass']for x in r.get('checks',[]))for r in a+b+c+d)
finds={n:[]for n in[643,648,649,650,656,658,659,660,664,668]}
def f(kind,description,recommendation,evidence):return dict(kind=kind,description=description,recommendation=recommendation,evidence=evidence)
for n,ratio in [(648,2.433),(649,2.264),(650,2.359)]:finds[n].append(f('auxiliary_text_readability',f'有効操作を示すESCが8px/opacity0.5で、通常の実背景合成コントラスト{ratio}:1。gallery/portableのrest/hover/解除後で同値。説明/shortcut/分類にも9pxの既定規則が残る（R648通常説明12px、R650通常分類13px以外）。forcedでもESC8px/opacity0.5、説明/分類/キー9px。disabled候補とは別の可読性問題。','ESCのopacityを解除し十分なコントラストへ。説明・分類・キーは12px程度以上を基準に整理し、forcedでも同じ可読性を維持する。',['contrast-summary-10.json','measurements-readability-10.json','evidence-10/readability-sheet.jpg']))
finds[648].append(f('long_description_clipping','320pxで長い説明LongUnbrokenDescription12345678901234567890がpanel外へ37.234375pxはみ出し、LTR右/RTL左が切れる。gallery/portableとも通常配色で再現。12px化した説明の長語折返しがない。','説明のmin-widthとoverflow-wrapを明示し、文字を小さくして収めず長語を折返す。',['measurements-readability-10.json','evidence-10/soft-resource-context-portable-ltr-normal-readability.png','evidence-10/soft-resource-context-portable-rtl-normal-readability.png']))
finds[659].append(f('selected_description_contrast','選択行の補足14pxが#806957/実面#e8dcc3で3.792:1。hover行も約4.354:1。gallery/portable・通常/モバイル、定常rest/hover/解除で確認。','選択/hover面に対して補足を4.5:1以上へ。',['measurements-pixel-contrast-10.json','evidence-10/open-bracket-navigation-gallery-rest.png']))
finds[660].append(f('default_brand_orphan_character','標準ブランドFieldworkが実gallery通常root458.5pxでFieldwor/kに分断される。portable通常464pxでは1行だが、320px viewport/root222pxでも末尾kが孤立。24px文字Range高さ67.39px（1行35px）。','見開き左列に標準名の最低幅を確保。狭幅はブランドと開閉操作の配置を分け、通常名が一文字だけ次行へ落ちないようにする。',['measurements-navigation-10.json','evidence-10/book-jacket-navigation-gallery-rest.png','evidence-10/book-jacket-navigation-portable-narrow.png']))
finds[668].append(f('dock_many_item_readability','dockに6項目と長い名称を渡すと、320pxで日本語1文字/英字1〜2文字の縦列になる。portable通常の名称Range幅14px・高さ710.11px、forced幅13.02px・高さ274.81px。galleryでも同形。外枠内のscrollWidth検査だけでは発見できない可読幅不足。','項目の最低幅を確保し、折返し列または横スクロールへ。狭幅では1列など読める構成にし、6項目・長文・両方向・forcedで確認。',['measurements-layouts-10.json','measurements-layout-gallery-10.json','evidence-10/soft-section-navigation-layout-dock-320-forced.png','evidence-10/soft-section-navigation-gallery-layout-dock-320-forced.png']))
notes={643:'リボンの折返し/外帯/二股末端が紙面の前後を示し、B標準面との構造差が成立。native・焦点・長文・配布を維持。',648:'資料名と入口を分けるBの用途差は成立。説明切れと補助文字の可読性を修正。',649:'行のまま開く簡潔な用途は成立。8〜9pxの補助文字とESCの淡さを修正。',650:'資料の分類と明朝の名称という用途差は成立。補助文字の小ささとESCの淡さを修正。',656:'現在地の余白欄と連番目次が題字を支える便箋構造。展開/モバイルでも読み順を維持。',658:'地点の輪・縫い経路・折面が行先を連続した地図へ組み、Bのカード列から分離する。各配置と操作を維持。',659:'独立した支持面と対角の受け、開いた隙間が成立。選択/hover補足のコントラストを修正。',660:'表紙/背/本文/折返しの前後関係は成立。実面の説明5.398:1・hover4.688:1でコントラスト疑義は解消。標準ブランドの末尾孤立だけ修正。',664:'支柱・受けの短い接点・独立陶プレートが読め、単なる丸いカード列から構造的に分離。各配置/モバイル/forced/操作を維持。',668:'説明付き区画を読むBとして成立。dockの6項目/長名で項目幅が潰れる点を修正。'}
targets=[r for r in json.load(open('docs/design-refinement-225/targets.json'))if r['batch']=='B021'];parts=[]
for r in targets:
 n=r['number'];parts.append(dict(id=r['id'],number=n,verdict='changes_required'if finds[n]else'pass',note=notes[n],findings=finds[n],evidence=['evidence-10/sheet-'+r['id']+'.jpg','measurements-context-10.json'if n<656 else'measurements-navigation-10.json','measurements-react-context-10.json'if n<656 else'measurements-react-navigation-10.json'],reviewed={'round':10,'actualGallery':True,'portable':True,'hoverEntryExitReentry':True,'narrow320LongRTL':True,'forcedReduced':True,'native':True,'react4Formats':True,'ABVisualComparison':True}))
coverage={'authorHashesMatched':100,'sharedHashesMatched':1,'contextPrimaryRows':8,'navigationPrimaryNativeRows':12,'nativeChecks':292,'reactPartsFormats':40,'reactChecks':192,'navigationLayoutConditions':192,'dockGalleryConditions':8,'contextReadabilityConditions':24,'contextShortFocusConditions':32,'imagesViewed':['context4 primary sheets /48 states','navigation6 portable sheets /36 states','navigation6 gallery sheets /24 states','navigation6 layout sheets /48 states','React3 sheets /20 opened/forced images','readability sheet /6 normal LTRRTL images','R648 normalLTR/RTL clipping images','R660 gallery normal close','R668 portable/gallery forced dock close','R664 portable forced and header-forced close'],'pendingRequiredMeasurements':[],'limitations':['A構造の評価と再現する表示不具合を区別した。','B3の8〜9pxは可読性のレビュー判断、ESCコントラストは数値による不足。','R660 gradientを無視する単純合成値は不採用。実画像背景とCSSのgradient位置で補足5.398/hover4.688を確認。画素最頻値が文字色になるbrand測定1:1も不採用。','native初回fixtureはonNavigate falseが選択まで取消すと誤解し、hidden旧flyoutのhrefもdisabled検査へ混入。仕様に合わせ修正後292checksを再実行。','native detailsは項目更新後もopenを保持するため、再クリックで閉じるfixtureを補正して再実行。','React長文/全layout全組合せは未実行。同作者CSSをgallery/portableで実査。','特定状態のChromium検査であり無欠陥保証ではない。']}
(p/'review-10.json').write_text(json.dumps(dict(batch='B021',round=10,overall='changes_required',parts=parts,coverage=coverage),ensure_ascii=False,indent=2)+'\n');lines=['# B021 round 10 独立検査','','4 pass / 6 changes_required。R648/R649/R650/R659/R660/R668を差戻す。作者・共有ソースは検査担当未変更。','','| ID | 判定・根拠 |','|---|---|']+[f'| R{x["number"]} | {x["verdict"]}: {x["note"]} |'for x in parts];lines+=['','Aのリボン、余白欄と目次、縫い経路、独立支持面、見開き、陶支柱は、同カテゴリBと並べて構造の差を確認。今回は構造再設計の差戻しではなく、文字の可読性と幅の配分を修正する。','','gallery/portable native292 checks、React4形式×10件192 checksが成功。navigation192配置条件、dock実gallery8条件、context可読性24条件を追加し、枠内に収まるだけでなく読める幅を実画像で判断。作者100+共有1 hashが凍結入力と一致。必須未完なし。改善案・証拠・限界は[review-10.json](review-10.json)。'];(p/'review-10.md').write_text('\n'.join(lines)+'\n');print('B021r10 saved 4pass6changes')
