import {createCore,heading,syncHeading,q,escape,svg,uniqueId,makeOverlay,type FoundationConfig,type FoundationOptions,type FoundationController,type Notice} from './core.ts';
export function renderToast(_o:FoundationOptions):string{return `<div data-toast-example hidden></div><div class="ff-toast-stack" data-toast-stack></div>`;}
export function mountToast(root:HTMLElement,config:FoundationConfig,options:FoundationOptions={}):FoundationController {
 const c=createCore(root,config,options);if(!root.querySelector('[data-toast-stack]'))root.innerHTML=renderToast(c.options);
 const stack=q<HTMLElement>(root,'[data-toast-stack]');stack.setAttribute('popover','manual');stack.hidden=true;
 type Entry={id:string;el:HTMLElement;timer:number;remaining:number;started:number;hover:boolean;focus:boolean;notice:Notice};const entries:Entry[]=[];
 function stop(e:Entry){if(e.timer){clearTimeout(e.timer);e.timer=0;e.remaining=Math.max(0,e.remaining-(performance.now()-e.started));}}
 function start(e:Entry){if(c.dead||e.hover||e.focus||document.hidden||e.remaining<=0||e.notice.duration===0)return;e.started=performance.now();e.timer=window.setTimeout(()=>dismiss(e.id),e.remaining);}
 function dismiss(id?:string){for(const e of [...entries])if(!id||e.id===id){stop(e);const focused=e.el.contains(document.activeElement);e.el.remove();entries.splice(entries.indexOf(e),1);if(focused)root.querySelector<HTMLElement>('[data-notify]')?.focus();}if(!entries.length){try{stack.hidePopover();}catch{}stack.hidden=true;}}
 function notify(notice:Notice):string {if(c.dead)return '';const id=uniqueId('sop-notice'),el=document.createElement('div');el.className='ff-notice';el.dataset.tone=notice.tone??'info';el.setAttribute('role',notice.tone==='error'?'alert':'status');el.setAttribute('aria-atomic','true');
  el.innerHTML=`<span class="ff-notice-icon" aria-hidden="true">${svg(notice.tone==='success'?'check':'info')}</span><div class="ff-notice-copy"><strong>${escape(notice.title)}</strong><p>${escape(notice.description)}</p>${notice.actionLabel?`<button type="button" class="ff-inline-action" data-notice-action>${escape(notice.actionLabel)}</button>`:''}</div><button type="button" data-notice-close class="ff-icon-button" aria-label="通知を閉じる">${svg('close')}</button>`;
  const duration=notice.duration??c.options.duration??5500;const entry:Entry={id,el,timer:0,remaining:Math.max(0,duration),started:0,hover:false,focus:false,notice:{...notice,duration}};entries.push(entry);stack.append(el);stack.hidden=false;try{stack.showPopover();}catch{}
  q(el,'[data-notice-close]').addEventListener('click',()=>dismiss(id));el.querySelector('[data-notice-action]')?.addEventListener('click',()=>{notice.onAction?.();dismiss(id);});
  el.addEventListener('pointerenter',()=>{entry.hover=true;stop(entry);});el.addEventListener('pointerleave',()=>{entry.hover=false;start(entry);});el.addEventListener('focusin',()=>{entry.focus=true;stop(entry);});el.addEventListener('focusout',()=>queueMicrotask(()=>{entry.focus=el.contains(document.activeElement);if(!entry.focus)start(entry);}));
  while(entries.length>Math.max(1,c.options.maxNotices??3))dismiss(entries[0].id);start(entry);return id;
 }
 c.on(document,'visibilitychange',()=>entries.forEach(e=>document.hidden?stop(e):start(e)));
 c.sync=()=>{syncHeading(c);const b=root.querySelector<HTMLButtonElement>('[data-notify]');if(b)b.disabled=!!c.options.disabled;};
 c.cleanup(()=>dismiss());c.notify=notify;c.dismiss=dismiss;c.sync('initial');return c;
}
export function renderHint(o:FoundationOptions):string {return heading(o)+`<button type="button" class="ff-action ff-hint-trigger" data-hint-trigger>${svg('info')} <span>${escape(o.interactive?'詳しく見る':'ポインターを重ねる')}</span> ${svg('spark')}</button><div class="ff-floating ff-hint-panel" data-hint-panel><div class="ff-hint-heading">${svg('spark')}<strong>${escape(o.label??'光を、やわらかく。')}</strong></div><p data-hint-content>${escape(o.content??'必要な情報を、必要な場所に。操作の前に、意図と使い方を確認できます。')}</p>${o.interactive?'<div class="ff-hint-facts"><span>品質</span><strong>Standard</strong><span>設定</span><strong>自動調整</strong></div><label class="ff-hint-checkbox"><input type="checkbox">この設定を使う</label><button type="button" class="ff-action" data-hint-action>適用する →</button>':''}</div>`;}
export function mountHint(root:HTMLElement,config:FoundationConfig,options:FoundationOptions={}):FoundationController {
 const c=createCore(root,config,options);if(!root.querySelector('[data-hint-trigger]'))root.innerHTML=renderHint(c.options);
 const trigger=q<HTMLButtonElement>(root,'[data-hint-trigger]'),panel=q<HTMLElement>(root,'[data-hint-panel]'),uid=uniqueId('sop-hint');panel.id=uid;
 const overlay=makeOverlay(c,panel,trigger,c.options.placement??'top');let closeTimer=0;
 function show(){clearTimeout(closeTimer);overlay.show();if(c.options.interactive){trigger.setAttribute('aria-expanded','true');}else{trigger.setAttribute('aria-describedby',uid);trigger.removeAttribute('aria-expanded');}}
 function hide(){clearTimeout(closeTimer);overlay.hide();if(!c.options.interactive){trigger.removeAttribute('aria-describedby');trigger.removeAttribute('aria-expanded');}}
 const later=()=>{clearTimeout(closeTimer);closeTimer=window.setTimeout(()=>{if(!root.contains(document.activeElement))hide();},160);};
 c.on(trigger,'pointerenter',()=>{if(!c.options.interactive)show();});c.on(trigger,'pointerleave',()=>{if(!c.options.interactive)later();});c.on(trigger,'focus',()=>{if(!c.options.interactive)show();});
 c.on(trigger,'click',()=>overlay.open?hide():show());c.on(panel,'pointerenter',()=>clearTimeout(closeTimer));c.on(panel,'pointerleave',()=>{if(!c.options.interactive)later();});
 c.on(root,'focusout',()=>queueMicrotask(()=>{if(!c.dead&&!root.contains(document.activeElement))hide();}));
 c.on(document,'pointerdown',event=>{if(overlay.open&&!root.contains(event.target as Node))hide();},{capture:true});
 c.on(document,'keydown',event=>{const e=event as KeyboardEvent;if(e.key==='Escape'&&overlay.open){e.preventDefault();e.stopPropagation();const inside=panel.contains(document.activeElement);hide();if(inside)trigger.focus();}},{capture:true});
 const action=panel.querySelector('[data-hint-action]');if(action)c.on(action,'click',()=>{c.options.onAction?.();hide();trigger.focus();});
 c.sync=()=>{syncHeading(c);trigger.disabled=!!c.options.disabled;panel.setAttribute('role',c.options.interactive?'dialog':'tooltip');panel.setAttribute('aria-label',c.options.label??'補足');if(c.options.interactive){trigger.setAttribute('aria-controls',uid);trigger.setAttribute('aria-haspopup','dialog');}q(panel,'[data-hint-content]').textContent=c.options.content??'必要な情報を、必要な場所に。操作の前に、意図と使い方を確認できます。';if(c.options.disabled)hide();};
 c.show=show;c.hide=hide;c.cleanup(()=>clearTimeout(closeTimer));c.sync('initial');return c;
}
export function renderProgress(o:FoundationOptions):string {return heading(o)+`<div class="ff-progress-visual"><div class="ff-progress-track" aria-hidden="true"><span class="ff-progress-fill"></span></div><div class="ff-progress-ring" aria-hidden="true"><svg viewBox="0 0 120 120"><circle class="ff-ring-base" cx="60" cy="60" r="51"/><circle class="ff-ring-value" cx="60" cy="60" r="51" pathLength="100"/></svg></div><output class="ff-reading" data-progress-reading>0<small>%</small></output></div><progress data-progress max="100" value="0" class="ff-sr" aria-label="${escape(o.label)}"></progress><div class="ff-process-steps" aria-hidden="true"><span>01 準備</span><span>02 処理</span><span>03 完了</span></div>`;}
export function mountProgress(root:HTMLElement,config:FoundationConfig,options:FoundationOptions={}):FoundationController {
 const c=createCore(root,config,options,v=>typeof v==='number'&&Number.isFinite(v)?v:0);if(!root.querySelector('[data-progress]'))root.innerHTML=renderProgress(c.options);
 c.sync=()=>{syncHeading(c);const o=c.options,min=o.min??0,max=Math.max(min+0.00001,o.max??100),n=Math.max(min,Math.min(max,Number(c.data))),p=100*(n-min)/(max-min);root.style.setProperty('--ff-progress',String(p));root.dataset.indeterminate=String(!!o.indeterminate);const progress=q<HTMLProgressElement>(root,'[data-progress]');progress.max=max-min;progress.setAttribute('aria-label',o.label??'進捗');if(o.indeterminate)progress.removeAttribute('value');else progress.value=n-min;const text=q(root,'[data-progress-reading]');text.innerHTML=o.indeterminate?'…':`${Math.round(p)}<small>%</small>`;root.querySelectorAll<HTMLElement>('.ff-process-steps span').forEach((step,i)=>step.dataset.active=String(p>=[0,35,100][i]));};c.sync('initial');return c;
}
export function renderLoader(o:FoundationOptions):string {return heading(o)+`<div class="ff-loader-art" aria-hidden="true"><div class="ff-orbit o1"></div><div class="ff-orbit o2"></div><div class="ff-orbit o3"></div><span class="ff-loader-core"></span><div class="ff-loader-bars">${Array.from({length:12},(_,i)=>`<i style="--i:${i}"></i>`).join('')}</div></div><span class="ff-loader-label" role="status" data-loader-label>${escape(o.content??'読み込み中…')}</span>`;}
export function mountLoader(root:HTMLElement,config:FoundationConfig,options:FoundationOptions={}):FoundationController {const c=createCore(root,config,options);if(!root.querySelector('[data-loader-label]'))root.innerHTML=renderLoader(c.options);c.sync=()=>{syncHeading(c);q(root,'[data-loader-label]').textContent=c.options.content??'読み込み中…';root.setAttribute('aria-busy',String(!c.options.paused));};c.sync('initial');return c;}
