import {createCore,heading,syncHeading,q,escape,svg,asStrings,uniqueId,makeOverlay,type FoundationConfig,type FoundationOptions,type FoundationController,type FoundationValue} from './core.ts';
export function pageItems(page:number,total:number):(number|'…')[]{const count=Math.max(1,Math.floor(total)),current=Math.min(count,Math.max(1,Math.floor(page)));if(count<=7)return Array.from({length:count},(_,i)=>i+1);const visible=new Set([1,count,current-1,current,current+1]);if(current<=3)[2,3,4,5].forEach(v=>visible.add(v));if(current>=count-2)[count-4,count-3,count-2,count-1].forEach(v=>visible.add(v));const sorted=[...visible].filter(n=>n>=1&&n<=count).sort((a,b)=>a-b),result:(number|'…')[]=[];sorted.forEach((n,i)=>{if(i&&n-sorted[i-1]>1)result.push('…');result.push(n);});return result;}
export function renderPagination(o:FoundationOptions):string{return heading(o)+`<nav class="ff-pages" data-pages aria-label="${escape(o.label??'ページ切り替え')}"></nav><div class="ff-page-info" data-page-info></div>`;}
export function mountPagination(root:HTMLElement,config:FoundationConfig,options:FoundationOptions={}):FoundationController {
 const normalize=(v:FoundationValue,o:FoundationOptions):FoundationValue=>Math.min(Math.max(1,Math.floor(o.totalPages??12)),Math.max(1,Math.floor(Number(v)||1)));
 const c=createCore(root,config,options,normalize);if(!root.querySelector('[data-pages]'))root.innerHTML=renderPagination(c.options);const nav=q(root,'[data-pages]');
 c.sync=()=>{syncHeading(c);const o=c.options,total=Math.max(1,Math.floor(o.totalPages??12)),page=Number(c.data);
  const control=(n:number,label:string,body:string,disabled=false)=>o.hrefForPage?`<a ${disabled||o.disabled?'aria-disabled="true"':`href="${escape(o.hrefForPage(n))}"`} data-page="${n}" aria-label="${escape(label)}" ${n===page&&label===`ページ ${n}`?'aria-current="page"':''}>${body}</a>`:`<button type="button" data-page="${n}" aria-label="${escape(label)}" ${disabled||o.disabled?'disabled':''} ${n===page&&label===`ページ ${n}`?'aria-current="page"':''}>${body}</button>`;
  nav.innerHTML=control(Math.max(1,page-1),'前のページ','‹',page===1)+pageItems(page,total).map(item=>item==='…'?'<span class="ff-ellipsis" aria-hidden="true">…</span>':control(item,`ページ ${item}`,String(item).padStart(2,'0'))).join('')+control(Math.min(total,page+1),'次のページ','›',page===total);
  q(root,'[data-page-info]').innerHTML=`<strong>${String(page).padStart(2,'0')}</strong><span>/ ${total} PAGES</span>`;
 };
 c.on(nav,'click',event=>{const e=event as MouseEvent,el=(e.target as Element).closest<HTMLElement>('[data-page]');if(!el||el.getAttribute('aria-disabled')==='true')return;if(el.tagName==='A'&&(e.metaKey||e.ctrlKey||e.shiftKey||e.altKey||e.button!==0))return;if(el.tagName!=='A')c.send(Number(el.dataset.page));else c.options.onDataChange?.(Number(el.dataset.page));});c.sync('initial');return c;
}
export function renderBreadcrumbs(o:FoundationOptions):string{return heading(o)+`<nav class="ff-breadcrumb" aria-label="${escape(o.label??'現在の場所')}"><ol data-breadcrumbs></ol></nav><div class="ff-floating ff-crumb-menu" data-crumb-menu></div>`;}
export function mountBreadcrumbs(root:HTMLElement,config:FoundationConfig,options:FoundationOptions={}):FoundationController {
 const c=createCore(root,config,options);if(!root.querySelector('[data-breadcrumbs]'))root.innerHTML=renderBreadcrumbs(c.options);const list=q(root,'[data-breadcrumbs]'),panel=q<HTMLElement>(root,'[data-crumb-menu]');panel.id=uniqueId('sop-trail');let overlay:ReturnType<typeof makeOverlay>|undefined;
 function link(index:number){const item=(c.options.items??[])[index],last=index===(c.options.items?.length??0)-1;return last?`<span aria-current="page">${escape(item.label)}</span>`:`<a ${item.disabled||c.options.disabled?'aria-disabled="true" tabindex="-1"':`href="${escape(item.href??'#')}"`}>${escape(item.label)}</a>`;}
 c.sync=()=>{syncHeading(c);overlay?.destroy();overlay=undefined;const items=c.options.items??[],collapse=items.length>4;
  list.innerHTML=items.map((_,i)=>collapse&&i>0&&i<items.length-2?i===1?`<li><button class="ff-crumb-more" type="button" data-crumb-more aria-controls="${panel.id}" aria-label="途中の階層を表示" aria-expanded="false">…</button></li>`:'':`<li>${i===0?svg('home'):''}${link(i)}</li>`).join('');
  panel.innerHTML=collapse?items.slice(1,-2).map((_,i)=>link(i+1)).join(''):'';
 };
 c.on(list,'click',event=>{const button=(event.target as Element).closest<HTMLElement>('[data-crumb-more]');if(button){if(!overlay)overlay=makeOverlay(c,panel,button);if(overlay.open)overlay.hide();else{overlay.show();panel.querySelector<HTMLElement>('a')?.focus();}}const link=(event.target as Element).closest('a[aria-disabled="true"]');if(link)event.preventDefault();});
 c.on(document,'pointerdown',event=>{if(overlay?.open&&!root.contains(event.target as Node))overlay.hide();},{capture:true});c.on(root,'focusout',()=>queueMicrotask(()=>{if(!c.dead&&!root.contains(document.activeElement))overlay?.hide();}));c.on(document,'keydown',event=>{const e=event as KeyboardEvent;if(e.key==='Escape'&&overlay?.open){e.stopPropagation();e.preventDefault();overlay.hide();root.querySelector<HTMLElement>('[data-crumb-more]')?.focus();}},{capture:true});c.sync('initial');return c;
}
export function renderBadges(o:FoundationOptions):string{return heading(o)+`<div class="ff-tags" data-tags role="group" aria-label="${escape(o.label??'タグ')}"></div><p class="ff-footnote" data-tags-hint>${o.removable?'×からタグを取り除けます。':o.selectable?'複数のタグを選択できます。':'状態を、ひと目で。'}</p>`;}
export function mountBadges(root:HTMLElement,config:FoundationConfig,options:FoundationOptions={}):FoundationController {
 const c=createCore(root,config,options,v=>asStrings(v));if(!root.querySelector('[data-tags]'))root.innerHTML=renderBadges(c.options);const body=q(root,'[data-tags]');let items=[...(c.options.items??[])],itemsRef=c.options.items;
 c.sync=reason=>{syncHeading(c);const o=c.options;if(o.items!==itemsRef||reason==='reset'){items=[...(o.items??[])];itemsRef=o.items;}
  body.innerHTML=items.map(item=>`<span class="ff-tag" data-selected="${asStrings(c.data).includes(item.value)}">${o.selectable?`<label><input type="checkbox" data-tag-select="${escape(item.value)}" ${asStrings(c.data).includes(item.value)?'checked':''} ${o.disabled||item.disabled?'disabled':''}><span>${svg(item.icon??'spark')}${escape(item.label)}</span></label>`:`<span>${svg(item.icon??'spark')}${escape(item.label)}</span>`}${item.badge?`<small>${escape(item.badge)}</small>`:''}${o.removable?`<button type="button" data-tag-remove="${escape(item.value)}" aria-label="${escape(item.label)} を削除" ${o.disabled||item.disabled?'disabled':''}>${svg('close')}</button>`:''}</span>`).join('');
  q(root,'[data-tags-hint]').textContent=o.removable?'×からタグを取り除けます。':o.selectable?'複数のタグを選択できます。':'状態を、ひと目で。';
 };
 c.on(body,'change',event=>{const input=event.target;if(input instanceof HTMLInputElement){const values=asStrings(c.data);c.send(input.checked?[...values,input.dataset.tagSelect!]:values.filter(v=>v!==input.dataset.tagSelect));}});
 c.on(body,'click',event=>{const button=(event.target as Element).closest<HTMLElement>('[data-tag-remove]');if(!button||c.options.disabled)return;const value=button.dataset.tagRemove!;c.options.onAction?.(value);if(!c.options.controlled){items=items.filter(i=>i.value!==value);c.send(asStrings(c.data).filter(v=>v!==value));}body.querySelector<HTMLElement>('button,input')?.focus();});c.sync('initial');return c;
}
