"""Final, category-specific open-state refinements; canonical source owns the result."""
from pathlib import Path
import json,re
patches={}
def add(cat,id,css):patches[(cat,id)]=css
add('popups','proscenium-dialog','''$ .sop-popup-shell{display:grid;grid-template-columns:165px minmax(0,1fr);gap:18px 25px;padding:25px;background:linear-gradient(90deg,#715e4a33 0 200px,#252732 200px)}$ .sop-popup-top{grid-column:1 / -1;margin:0;padding-bottom:14px;border-bottom:1px solid var(--pp-line)}$ .sop-popup-intro{grid-column:1;grid-row:2 / 4;margin:0;border:0;padding:15px 0}$ .sop-popup-intro h2{font:38px/1.2 Georgia;letter-spacing:0}$ .sop-popup-body{grid-column:2;grid-row:2;padding-top:17px}$ .pp-callout{background:#7e6b6233;border:1px solid var(--pp-line);padding:23px;line-height:2;box-shadow:inset 0 0 0 6px #252732}$ .sop-popup-footer{grid-column:2;grid-row:3;margin:0;padding-top:15px;flex-wrap:wrap;justify-content:start}@media(max-width:560px){$ .sop-popup-shell{grid-template-columns:1fr;background:#252732}$ .sop-popup-intro,$ .sop-popup-body,$ .sop-popup-footer{grid-column:1;grid-row:auto}$ .sop-popup-intro h2{font-size:30px}}''')
add('popups','bifold-dialog','''$ .sop-popup-shell{display:grid;grid-template-columns:36px minmax(0,1fr);gap:18px 20px;padding:26px;background:linear-gradient(90deg,#9dae8977 0 61px,#e4e2ce 61px)}$ .sop-popup-top{grid-column:1;grid-row:1 / 4;display:flex;flex-direction:column-reverse;align-items:center;justify-content:space-between;margin:0;padding:0;border:0}$ .sop-popup-kicker{writing-mode:vertical-rl;font:11px Consolas;letter-spacing:2px}$ .sop-popup-close{border-radius:1px;width:30px;height:30px}$ .sop-popup-intro,$ .sop-popup-body,$ .sop-popup-footer{grid-column:2;margin:0}$ .sop-popup-intro h2{font:34px/1.25 Georgia;letter-spacing:0}$ .pp-callout{background:repeating-linear-gradient(0deg,transparent 0 26px,#78915c22 27px 28px),#e8e8d3;border:0;border-top:1px dashed var(--pp-line);border-bottom:1px dashed var(--pp-line);padding:22px 8px}$ .sop-popup-footer{padding:17px 0 0;background:transparent;justify-content:space-between}$ .sop-popup-primary{border-radius:0;box-shadow:3px 3px #61765733}@media(max-width:560px){$ .sop-popup-shell{grid-template-columns:30px minmax(0,1fr);gap:15px;padding:20px 17px;background:linear-gradient(90deg,#9dae8977 0 49px,#e4e2ce 49px)}$ .sop-popup-intro h2{font-size:27px}}''')
add('popups','oculus-dialog','''$ .sop-popup-window{width:min(460px,calc(100vw - 36px));border-radius:48% 48% 14px 14px;border:3px double #9fc7ce}$ .sop-popup-shell{padding:50px 30px 25px;background:radial-gradient(ellipse at 50% 0,#7db8c533,transparent 70%),#182e39;border-radius:inherit;text-align:center}$ .sop-popup-top{justify-content:center;margin-bottom:20px;padding:0}$ .sop-popup-close{position:absolute;right:0;top:0;width:31px;height:31px}$ .sop-popup-intro{padding:0;border:0;margin-bottom:25px}$ .sop-popup-intro h2{font:33px/1.25 Georgia;letter-spacing:0;max-width:300px;margin:0 auto 17px}$ .sop-popup-intro p{font-size:11px}$ .pp-callout{padding:23px 19px;background:#7197a333;border:0;border-top:1px solid #9fc7ce88;border-bottom:1px solid #9fc7ce88;border-radius:40% 40% 0 0;text-align:center}$ .sop-popup-footer{justify-content:center;border:0;gap:14px;margin-top:23px;padding-top:0}$ .sop-popup-primary,$ .sop-popup-secondary{border-radius:30px;padding:13px 20px;min-height:48px}@media(max-width:560px){$ .sop-popup-shell{padding:48px 22px 23px}$ .sop-popup-intro h2{font-size:28px}}''')
add('popups','hinged-case-dialog','''$ .sop-popup-window{border:0;border-left:12px solid #83937d;border-right:9px solid #83937d;border-radius:3px;box-shadow:inset 0 0 0 1px #c8cfb4,0 30px 80px #000b}$ .sop-popup-shell{padding:27px 26px;background:#2a302b;box-shadow:inset 0 7px #81927a88,inset 0 -7px #81927a88}$ .sop-popup-top{border-bottom:0;padding-bottom:0;margin-bottom:25px}$ .sop-popup-kicker{border:1px solid #96a28c;padding:9px 13px;background:#55624b;font-size:10px}$ .sop-popup-close{border-radius:2px;border:2px solid #8c9b86;background:#1a251b}$ .sop-popup-intro{border:0;padding:0}$ .sop-popup-intro h2{font:32px/1.25 Georgia;letter-spacing:0}$ .sop-popup-body{padding:7px;background:#1a251b;border:1px solid #7e9178;box-shadow:inset 0 4px #0d180e}$ .pp-callout{background:#45523f;border:0;border-left:3px solid #aebda5;padding:21px;line-height:2}$ .sop-popup-footer{display:grid;grid-template-columns:90px minmax(0,1fr);gap:14px;border-top:0;margin-top:22px;padding:0}$ .sop-popup-primary{min-height:55px;font-size:14px;border-radius:2px;box-shadow:0 4px #18231a}$ .sop-popup-secondary{border:0;border-bottom:1px solid #93a38a;border-radius:0}''')
add('popups','tension-sheet-dialog','''$ .sop-popup-window{border:0;border-radius:0;box-shadow:0 30px 90px #0009;background:#312c35}$ .sop-popup-shell{padding:30px 31px 28px;background:#312c35;border-top:2px solid #b29ac0;border-bottom:2px solid #b29ac0}$ .sop-popup-shell:before,$ .sop-popup-shell:after{content:"";position:absolute;left:0;top:0;bottom:0;width:8px;background:repeating-linear-gradient(0deg,transparent 0 30px,#b29ac0 31px 32px);pointer-events:none}$ .sop-popup-shell:after{left:auto;right:0}$ .sop-popup-top{margin-bottom:23px;border:0;padding:0}$ .sop-popup-intro{border:0;padding:0;margin-bottom:24px}$ .sop-popup-intro h2{font:44px/1.2 Georgia;letter-spacing:-1px}$ .pp-callout{background:transparent;border:0;border-left:1px solid #b29ac0;border-right:1px solid #b29ac0;padding:19px 23px;line-height:2}$ .sop-popup-footer{justify-content:space-between;padding-top:23px;border-top:1px solid #b29ac066}$ .sop-popup-primary{background:transparent;color:var(--pp-ink);border:0;border-bottom:2px solid #b29ac0;border-radius:0;min-width:180px;justify-content:space-between;font-size:15px}$ .sop-popup-secondary{border:0;border-radius:0;padding-inline:0}@media(max-width:560px){$ .sop-popup-intro h2{font-size:31px}$ .sop-popup-primary{min-width:0}}''')

add('datepickers','calendar-placket','''$ .ff-date-fields{padding:12px;border-top:8px double var(--ff-line);background:transparent}$ .ff-date-fields input{font:15px Consolas}$ .ff-calendar{border:0;border-left:10px solid var(--ff-line);border-radius:0;padding:17px;background:#263e54}$ .ff-calendar-header{align-items:start;border-bottom:4px double var(--ff-line);padding:5px 0 18px}$ .ff-calendar-header strong{font:23px Georgia;letter-spacing:0}$ .ff-calendar-header button{border-radius:0;width:26px;height:36px}$ .ff-weekdays{padding:8px 0;border-bottom:1px solid var(--ff-line)}$ .ff-calendar-grid button{font:14px Georgia;height:40px;border-radius:0;border-bottom:1px solid #7b9caf44}$ .ff-calendar-grid button[data-selected=true]{border-top:3px solid #cbdfe4;border-bottom:7px solid #658ca3;background:#9fbcca;color:#193747;transform:translateY(-2px)}$ .ff-calendar footer{border-top:4px double var(--ff-line);padding-top:15px}''')
add('datepickers','two-leaf-calendar','''$[data-date-mode=range] .ff-date-fields{background:transparent;border:0;gap:0 10px;padding:12px 0;border-top:1px solid var(--ff-line);border-bottom:1px solid var(--ff-line)}$[data-date-mode=range] .ff-date-fields input{background:#584463;padding:12px 7px;border:0;border-bottom:4px solid #9d7cad;font:13px Consolas}$ .ff-calendar{background:#35263f;border:0;border-left:2px solid #b89cc8;border-right:2px solid #b89cc8;border-radius:0;padding:17px}$ .ff-calendar-header strong{font:20px Georgia;letter-spacing:2px}$ .ff-calendar-grid [role=row]{border-bottom:5px solid #241e2c;gap:0;padding:4px 0;background:#a48eb315}$ .ff-calendar-grid [role=row]:nth-child(2n){background:#ad87c329;box-shadow:inset 0 2px #d7b9e122}$ .ff-calendar-grid button{height:38px;border-radius:0;margin:0;font:13px Georgia}$ .ff-calendar-grid button[data-selected=true]{background:#c5afd5;border-top:3px solid #efe3ee;border-bottom:3px solid #8f6fa2;color:#382845}$ .ff-calendar-grid button[data-between=true]{background:#ad92c266;border-top:1px solid #d8c4df}''')
add('datepickers','lunette-calendar','''$ .ff-date-fields{padding:15px 12px 10px;border-radius:40px 40px 3px 3px;background:linear-gradient(#608d8033,#1b352e)}$ .ff-date-fields input{font:17px Georgia;letter-spacing:1px;text-align:center}$ .ff-calendar{background:radial-gradient(at 50% 0,#91bc9f33,transparent 70%),#1e3e33;border:1px solid #8cb7a5;border-radius:50px 50px 4px 4px;padding:24px 17px 17px}$ .ff-calendar-header{padding:5px 0 16px;border-bottom:1px solid #91b99c66}$ .ff-calendar-header strong{font:20px Georgia;letter-spacing:1px}$ .ff-calendar-grid button{height:36px;border-radius:50%;font:12px Georgia;border:1px solid #98c4ac33;background:#a0bea312;box-shadow:inset 0 1px #c1d4b822}$ .ff-calendar-grid button[data-selected=true]{background:radial-gradient(at 35% 20%,#d7e9ce,#789f8c);border:3px double #dbeada;color:#183b2c;box-shadow:0 3px 9px #0005}$ .ff-calendar footer{padding-top:15px;border-top:3px double #83ad9a}''')
add('datepickers','appointment-card-calendar','''$ .ff-date-fields{min-height:72px;padding:12px 15px;border:0;border-left:12px solid var(--ff-line);background:repeating-linear-gradient(0deg,transparent 0 21px,#af927044 22px 23px),#3d3529}$ .ff-date-fields input{font:18px Georgia;letter-spacing:0}$ .ff-calendar{background:#453a2c;border:0;border-top:8px solid var(--ff-line);border-radius:0;padding:20px}$ .ff-calendar-header strong{font:22px Georgia;letter-spacing:0}$ .ff-weekdays{border-top:1px dashed var(--ff-line);border-bottom:1px dashed var(--ff-line);padding:8px 0}$ .ff-calendar-grid button{font:13px Georgia;height:36px;border-radius:0;border-bottom:1px solid #b59b7044}$ .ff-calendar-grid button[data-selected=true]{background:#dbc497;color:#3f3425;border:2px solid #91724b;box-shadow:3px 3px 0 #1e271b66;transform:rotate(-5deg)}$ .ff-time-picker{margin-top:19px;border-top:4px double var(--ff-line);padding-top:13px}$ .ff-time-heading strong{font:31px Georgia}$ .ff-time-column{background:#302b24;border-radius:0;border:0;border-top:1px solid var(--ff-line);border-bottom:1px solid var(--ff-line)}$ .ff-time-column button{border-radius:0;font:14px Georgia;border-bottom:1px dashed #a98d6744}''')
add('datepickers','slotted-time-calendar','''$ .ff-date-fields{border:0;border-left:9px solid var(--ff-line);border-right:9px solid var(--ff-line);padding:17px 12px;background:linear-gradient(#132c3e,#29485e)}$ .ff-date-fields input{font:28px Consolas;text-align:center;letter-spacing:3px}$ .ff-calendar{border:5px double #91afc4;border-radius:2px;background:#233e52;padding:20px}$ .ff-time-heading{align-items:center;padding:0 0 17px;border-bottom:5px double #809fb5}$ .ff-time-heading strong{font:35px Consolas;letter-spacing:2px;color:#d7e2df}$ .ff-time-columns{gap:17px;padding-top:12px}$ .ff-time-column{border:0;border-left:5px solid #7d9bb1;border-right:5px solid #7d9bb1;border-radius:0;box-shadow:inset 0 7px 14px #031c2f;background:linear-gradient(#081e33,#294d65,#081e33)}$ .ff-time-column button{font:18px Consolas;min-height:44px;border:0;border-top:1px solid #9fb7c433;border-bottom:3px solid #102e46;border-radius:0}$ .ff-time-column button[aria-selected=true]{background:#789eaf;border-top:4px solid #b7d0d4;border-bottom:4px solid #385a77;color:#152f42}''')
add('datepickers','stamp-grid-calendar','''$ .ff-date-fields{padding:12px;border:1px dashed #8da877;background:#edf0d8;box-shadow:4px 4px #9ba87855}$ .ff-date-fields input{font:16px Georgia}$ .ff-calendar{background:#edf0d8;border:3px double #8fa576;border-radius:0;padding:16px}$ .ff-calendar-header{border-bottom:1px dashed #8fa576;padding-bottom:18px}$ .ff-calendar-header strong{font:22px Georgia;letter-spacing:0}$ .ff-calendar-grid [role=row]{gap:5px;padding:3px 0}$ .ff-calendar-grid button{font:15px Georgia;height:39px;background:#d7dfbc;border:1px dashed #89a26b;border-radius:0;box-shadow:2px 2px #7f935c33;margin:0}$ .ff-calendar-grid button[data-selected=true]{background:#547148;color:#f0f1d8;border:3px double #bfd1a5;transform:rotate(-4deg);box-shadow:3px 3px #7f935c55}$ .ff-weekdays{font:10px Georgia;padding-block:7px}''')
add('datepickers','signal-box-calendar','''$ .ff-date-fields{padding:17px 12px;border:0;border-top:5px solid #a387b1;border-bottom:5px solid #a387b1;background:repeating-linear-gradient(90deg,#372944 0 29px,#9d7eae22 30px 31px)}$ .ff-date-fields input{font:19px Consolas;letter-spacing:-1px}$ .ff-calendar{background:#32233f;border:0;border-top:12px solid #836291;border-bottom:12px solid #836291;border-radius:0;padding:18px}$ .ff-calendar-header strong{font:17px Consolas;letter-spacing:1px;border:1px solid #9c7dad;padding:10px 12px;background:#251c33}$ .ff-calendar-grid button{height:35px;font:12px Consolas;border:1px solid #836a9544;border-radius:2px;background:#493252;box-shadow:inset 0 1px #b38dc133}$ .ff-calendar-grid button[data-selected=true]{background:#c3a8d2;color:#322244;border:2px solid #e0c5e7;box-shadow:0 0 0 2px #251933}$ .ff-time-picker{padding:15px 0 0;border-top:5px double #9672a6;margin-top:16px}$ .ff-time-heading strong{font:30px Consolas;letter-spacing:2px}$ .ff-time-column{border-radius:0;border:2px solid #876492;background:#241833;box-shadow:inset 0 3px #0f0c19}$ .ff-time-column button{font:14px Consolas;border:1px solid #93739e33;border-radius:1px;margin:5px 0;background:#65487122}''')
add('datepickers','stepped-date-calendar','''$[data-date-mode=range] .ff-date-fields{grid-template-columns:minmax(0,1fr) 38px;grid-template-areas:"start action" "divider action" "end action";padding:15px 10px;gap:3px 15px;border:0;border-left:7px solid #b1c795;border-radius:0;background:#2c4a2c}$[data-date-mode=range] .ff-date-fields input[data-date="0"]{grid-area:start;text-align:left;font:16px Georgia;padding:5px 0;border-bottom:1px solid #91ad7f}$[data-date-mode=range] .ff-date-fields input[data-date="1"]{grid-area:end;text-align:left;font:16px Georgia;padding:5px 0;border-bottom:1px solid #91ad7f}$[data-date-mode=range] .ff-date-fields [data-date-separator]{grid-area:divider;justify-self:start;font-size:12px}$[data-date-mode=range] .ff-date-fields [data-calendar-toggle]{grid-area:action;align-self:center}$ .ff-calendar{background:#233e27;border:0;border-left:7px solid #9fb783;border-right:1px solid #9fb783;border-radius:0;padding:20px 16px}$ .ff-calendar-header strong{font:20px Georgia;letter-spacing:0}$ .ff-calendar-grid [role=row]{gap:2px;border-bottom:4px solid #182e20;padding:3px 0}$ .ff-calendar-grid button{font:13px Georgia;height:35px;border-radius:0;background:#40593c;border-bottom:2px solid #729666;margin:0}$ .ff-calendar-grid button[data-between=true]{background:#6e8f53;border-bottom:5px solid #a3bd86;color:#ecf0d8}$ .ff-calendar-grid button[data-selected=true]{background:#c2d2a2;border-bottom:7px solid #8dab6b;color:#284424;transform:translateY(-3px)}''')
add('datepickers','dial-caption-calendar','''$ .ff-date-fields{position:relative;display:flex;flex-direction:column;justify-content:center;width:178px;height:178px;max-width:100%;margin:auto;border:7px double #8fb5bc;border-radius:50%;padding:32px 20px;background:radial-gradient(at 40% 30%,#81a4aa,#143640 72%);box-shadow:inset 0 0 0 8px #213e46,inset 0 0 0 9px #91b4bb,0 6px 20px #0005}$ .ff-date-fields input{width:110px;max-width:100%;min-height:40px;flex:none;font:26px Georgia;text-align:center;letter-spacing:2px;padding:0;color:#e0ebdf}$ .ff-date-fields [data-calendar-toggle]{position:absolute;bottom:17px;left:calc(50% - 15px);width:30px;height:30px;min-width:30px;border:1px solid #aacbc8;border-radius:50%;background:#1c3c46}$ .ff-date-fields [data-calendar-toggle] svg{width:15px;height:15px}$ .ff-calendar{background:#1e3b46;border:2px solid #7b9ea7;border-radius:50px 50px 4px 4px;padding:23px 18px 17px}$ .ff-time-heading{flex-direction:column;align-items:center;gap:13px;border-bottom:1px solid #8baaad;padding-bottom:19px}$ .ff-time-heading strong{font:28px Georgia;width:108px;height:108px;display:grid;place-items:center;border:5px double #b2c9bf;border-radius:50%;box-shadow:inset 0 0 0 7px #274953;background:radial-gradient(at 30% 20%,#769798,#143640)}$ .ff-time-columns{padding-top:15px;gap:14px}$ .ff-time-column{border:0;border-left:1px solid #91aeb0;border-right:1px solid #91aeb0;border-radius:0;background:#183a43}$ .ff-time-column button{font:15px Georgia;border:0;border-bottom:1px solid #8ea5a744;border-radius:0;min-height:39px}''')

if any('Open-state review: category-specific anatomy.' in (Path('src/parts')/cat/id/'styles.css').read_text(encoding='utf-8') for cat,id in patches):
 print('Open-state refinements already exist; canonical source remains untouched.');raise SystemExit(0)
for (cat,id),css in patches.items():
 part=Path('src/parts')/cat/id;file=part/'styles.css';s=file.read_text(encoding='utf-8')
 scope=('.sop-popup' if cat=='popups' else '.sop-foundation')+'.sop-'+id
 file.write_text(s+'\n/* Open-state review: category-specific anatomy. */\n'+css.replace('$',scope)+'\n',encoding='utf-8')
out=Path('docs/expansion-30-2026-10-06');p=out/'refined-parts.json';rows=json.loads(p.read_text(encoding='utf-8'))
for cat,id in patches:
 if not any(d['id']==id for d in rows):rows.append({'category':cat,'id':id})
p.write_text(json.dumps(rows,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
# Keep prose faithful to the circular window rather than the earlier corner treatment.
part=Path('src/parts/popups/oculus-dialog');meta=json.loads((part/'meta.json').read_text(encoding='utf-8'));old=meta['description'];desc='円形の採光面に内容を集め、丸い操作面から次の確認へ進む。';meta.update(description=desc,tagline=desc,tags=[t.replace(old,desc)for t in meta['tags']]);(part/'meta.json').write_text(json.dumps(meta,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
for p in [part/'prompt.md',part/'usage.md',part/'styles.css']:p.write_text(p.read_text(encoding='utf-8').replace(old,desc),encoding='utf-8')
p=out/'designs.json';specs=json.loads(p.read_text(encoding='utf-8'));next(d for d in specs if d['id']=='oculus-dialog')['description']=desc;p.write_text(json.dumps(specs,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
p=out/'tools/report.py';p.write_text(p.read_text(encoding='utf-8').replace('75点',str(len(rows))+'点'),encoding='utf-8')
print('Final open-state compositions:',len(patches),'total reviewed refinements',len(rows))
