"""One-time visual review corrections. Canonical files remain under src/parts."""
from pathlib import Path
import json,re
root=Path('src/parts'); report=Path('docs/expansion-30-2026-10-06')
changes={}
def add(cat,id,css): changes[(cat,id)]=css

# The hidden radio occupies no grid cell. Text, number, selection mark do.
add('radios','comparison-choice','$ .ff-choice{grid-template-columns:minmax(0,1fr) auto 18px}$ .ff-choice-copy{grid-column:1;grid-row:1}$ .ff-choice-badge{grid-column:2;grid-row:1}$ .ff-choice-check{grid-column:3;grid-row:1}')
# Two practical finders: inline labels versus a spacious leading search gutter.
add('comboboxes','label-pair-finder','$ .ff-combo-shell{border:0;border-bottom:2px solid var(--ff-accent);border-radius:0;background:transparent}$ .ff-option{display:grid;grid-template-columns:25px minmax(0,1fr) auto 16px;align-items:start}$ .ff-option-icon{grid-row:1 / 3}$ .ff-option>span:nth-child(2){display:flex;flex-wrap:wrap;align-items:baseline;gap:12px}$ .ff-option>span:nth-child(2) small{margin:0;flex:1;min-width:100px}')
add('comboboxes','wide-label-finder','$ .ff-combo-shell{min-height:64px;padding-left:52px;position:relative}$ .ff-combo-icon{position:absolute;inset:0 auto 0 0;width:40px;display:grid;place-items:center;border-right:1px solid var(--ff-line)}$ .ff-option{padding:17px 12px}$ .ff-option>span:nth-child(2) strong{font-size:14px}')
add('hints','braced-note-popover','$ .ff-hint-trigger{background:transparent;gap:16px;box-shadow:inset 3px 0 var(--ff-accent),inset -3px 0 var(--ff-accent);min-width:142px}$ .ff-hint-heading{border-bottom:1px solid var(--ff-line);padding-bottom:12px}$ .ff-hint-facts{grid-template-columns:1fr 1fr;gap:8px 20px;padding:16px 0}$ .ff-hint-facts span{font:9px Consolas;letter-spacing:1px}$ .ff-hint-facts strong{font:22px Georgia;grid-row:2}$ .ff-hint-checkbox{padding-top:12px;border-top:1px solid var(--ff-line)}')
add('hints','pocket-note-popover','$ .ff-hint-trigger{border-radius:0 0 22px 22px;box-shadow:0 5px 0 var(--ff-base);padding:16px 20px}$ .ff-hint-panel{border-radius:0 0 36px 36px;border-top:10px solid var(--ff-accent)}$ .ff-hint-heading{justify-content:center}$ .ff-hint-facts{background:var(--ff-base);padding:15px;border-radius:0 0 20px 20px}')
add('hints','fact-note-popover','$ .ff-hint-trigger{padding:8px 12px;border-radius:4px;min-height:36px}$ .ff-hint-facts{display:grid;grid-template-columns:64px minmax(0,1fr);gap:12px;border-top:1px solid var(--ff-line);border-bottom:1px solid var(--ff-line);padding:13px 0}$ .ff-hint-facts strong{font:12px Arial;text-align:left}')

# A launcher is a functional entrance, not fourteen recoloured posters.
add('commands','docket-command','$ .wb-command-launcher{display:grid;grid-template-columns:38px minmax(0,1fr);gap:12px;min-height:0;padding:16px;border-left-width:12px}$ .wb-command-symbol{margin:0;width:32px;height:32px}$ .wb-launch-copy strong{font:21px Georgia}$ .wb-command-launch{grid-column:1 / -1;margin-top:4px}$ .wb-command-list{padding-left:24px;border-left:12px solid var(--wb-line)}$ .wb-command-group{font:11px Georgia;border-bottom:1px dashed var(--wb-line)}$ .wb-command-option{border:0;border-bottom:1px solid var(--wb-line);border-radius:0}$ .wb-command-icon{border-radius:0;background:var(--wb-bg)}')
add('commands','shelf-command','$ .wb-command-launcher{min-height:0;display:flex;flex-wrap:wrap;align-items:end;gap:15px;border:0;border-bottom:12px solid var(--wb-line);background:transparent}$ .wb-command-symbol{margin:0;width:50px;height:50px}$ .wb-launch-copy{flex:1;min-width:160px}$ .wb-command-launch{margin-top:0}$ .wb-command-list{padding:20px;display:flex;flex-direction:column;gap:3px}$ .wb-command-option{margin-bottom:12px;box-shadow:0 6px 0 var(--wb-bg),0 7px 0 var(--wb-line);padding:16px 12px}$ .wb-command-copy strong{font:16px Georgia}')
add('commands','pressboard-command','$ .wb-command-launcher{min-height:0;padding:28px 17px 15px;background:repeating-linear-gradient(0deg,transparent 0 27px,#bba98322 28px 29px),var(--wb-bg)}$ .wb-command-symbol{position:absolute;right:12px;top:12px;transform:rotate(10deg)}$ .wb-launch-copy strong{max-width:65%;font:29px Georgia;line-height:1}$ .wb-command-launch{background:var(--wb-bg);margin-top:17px;border-style:dashed}$ .wb-command-list{padding:8px 26px;background:repeating-linear-gradient(0deg,transparent 0 29px,#d3b88215 30px 31px)}$ .wb-command-option{border:0;border-bottom:1px dashed var(--wb-line);border-radius:0}$ .wb-command-copy strong{font:17px Georgia}$ .wb-command-icon{border:0;border-bottom:3px solid var(--wb-accent)}')
add('commands','corner-gate-command','$ .wb-command-launcher{min-height:0;padding:20px;display:grid;grid-template-columns:1fr 48px;gap:14px;border:0;background:transparent;box-shadow:inset 3px 3px var(--wb-line),inset -3px -3px var(--wb-line)}$ .wb-command-symbol{grid-column:2;grid-row:1;width:44px;height:70px;margin:0;border-radius:0 0 24px 24px}$ .wb-launch-copy{grid-column:1;grid-row:1}$ .wb-command-launch{grid-column:1 / -1;margin:0;border:0;border-left:5px solid var(--wb-accent);background:var(--wb-bg)}$ .wb-command-list{padding:16px 30px}$ .wb-command-option{border:0;border-left:3px solid var(--wb-line);border-bottom:3px solid var(--wb-line);border-radius:0;margin:0 0 10px}$ .wb-command-option[aria-selected=true]{border-left-width:10px;padding-left:7px}')
add('commands','call-sign-command','$ .wb-command-launcher{min-height:0;padding:12px;display:flex;flex-wrap:wrap;align-items:center;gap:12px;border:0;border-radius:54px 54px 12px 12px}$ .wb-command-symbol{width:62px;height:62px;margin:0;border-radius:50%;box-shadow:inset 0 0 0 6px var(--wb-bg),inset 0 0 0 7px var(--wb-line)}$ .wb-launch-copy{flex:1;min-width:140px}$ .wb-launch-copy strong{font:20px Arial;letter-spacing:1px}$ .wb-command-launch{margin:0;border-radius:25px;min-height:42px}$ .wb-command-option{border:0;gap:20px;padding:18px 12px}$ .wb-command-icon{width:45px;height:45px;border-radius:50%;box-shadow:inset 0 0 0 5px var(--wb-bg),inset 0 0 0 6px var(--wb-line)}$ .wb-command-copy strong{letter-spacing:1px}$ .wb-command-option[aria-selected=true]{border-bottom:3px solid var(--wb-accent)}')
add('commands','monogram-command','$ .wb-command-launcher{min-height:0;padding:15px;display:grid;grid-template-columns:70px minmax(0,1fr);gap:15px;border:0;border-top:1px solid var(--wb-line);border-bottom:1px solid var(--wb-line);background:transparent}$ .wb-command-symbol{grid-row:1 / 3;width:70px;height:100%;margin:0;min-height:80px;transform:none;border-radius:0}$ .wb-command-symbol svg{width:42px;height:42px}$ .wb-launch-copy strong{font:23px Georgia}$ .wb-command-launch{margin:0;grid-column:2;min-width:0}$ .wb-command-list{padding:18px}$ .wb-command-option{padding:16px;gap:20px;border:0;border-bottom:1px solid var(--wb-line);border-radius:0}$ .wb-command-icon{width:49px;height:49px;transform:rotate(-8deg)}$ .wb-command-copy strong{font:18px Georgia}')
add('commands','stepped-list-command','$ .wb-command-launcher{min-height:0;background:transparent;border:0;padding:0 0 0 20px}$ .wb-command-symbol{display:none}$ .wb-launch-copy{padding:12px;border-left:3px solid var(--wb-line);background:var(--wb-bg)}$ .wb-launch-copy strong{font:22px Georgia}$ .wb-command-launch{margin:8px 0 0 -20px;width:calc(100% + 20px);border-radius:0;min-height:54px}$ .wb-command-group{padding-left:5px}$ .wb-command-option{margin-bottom:7px;border-left:7px solid var(--wb-line);border-radius:0}$ .wb-command-option:nth-of-type(3n){margin-left:18px}$ .wb-command-option:nth-of-type(3n + 2){margin-left:9px}')
add('commands','cradle-command','$ .wb-command-launcher{min-height:0;border-radius:85px 85px 8px 8px;padding:24px 16px 12px;text-align:center}$ .wb-command-symbol{margin:0 auto 12px;width:52px;height:52px;border-radius:50%}$ .wb-launch-copy strong{font:26px Georgia}$ .wb-command-launch{border-radius:35px 35px 4px 4px;margin-top:14px;min-height:53px}$ .wb-command-option{border-radius:27px 27px 3px 3px;padding:18px 15px;background:var(--wb-bg);border-bottom:4px solid var(--wb-line);margin-bottom:10px}$ .wb-command-copy strong{font:16px Georgia}$ .wb-command-group{text-align:center;border-bottom:1px solid var(--wb-line);margin-bottom:9px}')
add('commands','typecase-command','$ .wb-command-launcher{min-height:0;display:grid;grid-template-columns:1fr auto;gap:14px;padding:15px;border:1px solid var(--wb-line);border-bottom-width:5px}$ .wb-command-symbol{display:none}$ .wb-command-launch{grid-column:2;grid-row:1;width:44px;min-height:44px;margin:0;padding:10px;align-self:center}$ .wb-command-launch>span,$ .wb-command-launch kbd{position:absolute;width:1px;height:1px;overflow:hidden;clip-path:inset(50%)}$ .wb-launch-copy strong{font:26px Georgia}$ .wb-command-list{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px;align-content:start;padding:14px}$ .wb-command-group{grid-column:1 / -1;padding:8px 0;border-bottom:1px solid var(--wb-line)}$ .wb-command-option{display:grid;grid-template-columns:32px minmax(0,1fr);gap:8px;border:1px solid var(--wb-line);padding:13px;border-radius:0;align-content:start}$ .wb-command-copy{grid-column:1 / -1}$ .wb-command-option kbd{grid-column:2;grid-row:1;justify-self:end}$ .wb-command-next{position:absolute;right:8px;bottom:6px}$ .wb-command-copy strong{font:15px Georgia}')
add('commands','bay-window-command','$ .wb-command-launcher{min-height:0;display:grid;grid-template-columns:46px minmax(0,1fr);gap:12px;padding:18px;background:linear-gradient(90deg,#9eb7cd22 0 60px,transparent 60px),var(--wb-bg);border:1px solid var(--wb-line);border-right-width:8px}$ .wb-command-symbol{margin:0;width:38px;height:38px}$ .wb-command-launch{margin:0;grid-column:2;grid-row:2}$ .wb-launch-copy{grid-column:2}$ .wb-command-option{padding:17px;border:2px solid var(--wb-line);border-left:8px solid var(--wb-line);margin-bottom:10px;border-radius:0;background:linear-gradient(90deg,#a0bdcb22,transparent 120px)}$ .wb-command-icon{border:0;border-right:1px solid var(--wb-line);padding-right:8px;width:38px}')
add('commands','oblique-action-command','$ .wb-command-launcher{min-height:0;display:flex;flex-wrap:wrap;gap:14px;padding:22px 20px 15px;border:0;border-left:10px solid var(--wb-line);background:linear-gradient(115deg,#987db52b,transparent 65%),var(--wb-bg)}$ .wb-command-symbol{width:50px;height:50px;transform:rotate(-12deg);margin:0;align-self:center}$ .wb-launch-copy{flex:1;min-width:140px}$ .wb-command-launch{margin:0;clip-path:polygon(9px 0,100% 0,calc(100% - 9px) 100%,0 100%);padding-inline:21px}$ .wb-command-option{border-radius:0;border:0;border-right:8px solid var(--wb-line);margin-bottom:9px;transform:skewX(-3deg);background:var(--wb-bg);padding:17px}$ .wb-command-option>*{transform:skewX(3deg)}$ .wb-command-option[aria-selected=true]{border-left:3px solid var(--wb-accent);border-right-color:var(--wb-accent)}')
add('commands','cabled-command','$ .wb-command-launcher{min-height:0;padding:14px 14px 14px 28px;border:0;background:transparent;border-left:1px solid var(--wb-accent)}$ .wb-command-symbol{position:absolute;left:-10px;top:18px;width:20px;height:20px;background:var(--wb-bg);border:2px solid var(--wb-accent);border-radius:50%;margin:0}$ .wb-command-symbol svg{width:12px;height:12px}$ .wb-launch-copy strong{font:21px Arial}$ .wb-command-launch{margin-top:13px;background:var(--wb-bg);border:1px solid var(--wb-line);border-radius:25px}$ .wb-command-list{padding-left:34px;position:relative;border-left:1px solid var(--wb-accent);margin:0 18px}$ .wb-command-option{overflow:visible;border:0;border-bottom:1px solid var(--wb-line);border-radius:0;padding:14px 8px}$ .wb-command-option:after{content:"";position:absolute;width:22px;height:1px;left:-34px;top:50%;background:var(--wb-line)}$ .wb-command-icon{border-radius:50%;width:24px;height:24px}')
add('commands','shortcut-column-command','$ .wb-command-launcher{min-height:0;padding:14px;display:grid;grid-template-columns:1fr 86px;gap:12px}$ .wb-command-symbol{display:none}$ .wb-launch-copy strong{font:20px Arial;letter-spacing:0}$ .wb-command-launch{grid-column:2;grid-row:1;display:flex;flex-direction:column;justify-content:center;margin:0;min-height:82px;width:100%;gap:5px}$ .wb-command-launch kbd{font-size:12px}$ .wb-command-option kbd{min-width:54px;min-height:32px;display:grid;place-items:center;margin-left:15px;border-radius:2px;background:var(--wb-bg)}$ .wb-command-copy strong{font:13px Arial}')
add('commands','description-first-command','$ .wb-command-launcher{min-height:0;padding:16px 0;background:transparent;border:0;border-bottom:1px solid var(--wb-line);border-radius:0}$ .wb-command-symbol{display:none}$ .wb-launch-copy strong{font:24px Arial;letter-spacing:0}$ .wb-command-launch{margin-top:15px;min-height:52px;border-radius:4px}$ .wb-command-option{border:0;border-bottom:1px solid var(--wb-line);border-radius:0;padding:17px 10px}$ .wb-command-icon{display:none}$ .wb-command-copy strong{font-size:15px}$ .wb-command-copy small{font-size:12px;line-height:1.6;max-width:34em}$ .wb-command-group{font:11px Arial;letter-spacing:0}')

# Menu anatomy: handles, glyph gutters, action groups and checked rows, not poster skins.
add('contextmenus','groove-action-context','$ .wb-context-target{background:transparent;border:0;border-bottom:4px solid var(--wb-line);min-height:100px}$ .wb-context-panel{padding:6px 6px 6px 40px;background:linear-gradient(90deg,#152e3b 0 33px,#305564 33px);border-left:3px solid var(--wb-line)}$ .wb-menu-glyph{margin-left:-33px;color:var(--wb-accent)}$ .wb-context-items button{border-radius:0;padding:12px 8px;min-height:47px}$ .wb-menu-glyph:after{display:none}')
add('contextmenus','hanger-action-context','$ .wb-context-target{min-height:115px;align-items:start;padding-top:25px;border-top-width:12px}$ .wb-context-object{border-radius:2px;transform:rotate(-7deg);margin-top:-14px}$ .wb-context-panel{padding:22px 10px 10px;border-top:12px solid var(--wb-line)}$ .wb-context-items button{border:1px solid var(--wb-line);border-bottom-width:4px;border-radius:0;margin-bottom:9px;padding:13px}$ .wb-menu-glyph{border:1px solid var(--wb-line);width:28px;height:28px;border-radius:0}')
add('contextmenus','petrol-label-context','$ .wb-context-target{min-height:115px;border-radius:50px 4px 4px 50px;padding-left:15px}$ .wb-context-object{border-radius:50%;width:54px;height:54px;box-shadow:none}$ .wb-context-panel{border-radius:35px 4px 4px 35px;padding:12px 7px 12px 18px}$ .wb-context-items button{border-bottom:1px dotted var(--wb-line);border-radius:24px 3px 3px 24px;padding:12px 10px}$ .wb-menu-glyph{width:29px;height:29px;border:1px solid var(--wb-line);border-radius:50%}')
add('contextmenus','cut-corner-context','$ .wb-context-target{min-height:100px;background:transparent;border-left:0;border-top:0;border-bottom:2px solid var(--wb-line);border-radius:0}$ .wb-context-panel{border:0;border-top:3px solid var(--wb-line);border-right:12px solid var(--wb-line);border-radius:0;padding:10px}$ .wb-context-items button{padding:14px;border:0;border-left:2px solid var(--wb-line);border-bottom:1px solid var(--wb-line);border-radius:0;margin-bottom:6px}$ .wb-menu-glyph{border:0}')
add('contextmenus','ledger-spur-context','$ .wb-context-target{min-height:116px;border-left-width:18px;background:repeating-linear-gradient(0deg,transparent 0 23px,#5d794522 24px 25px),var(--wb-bg)}$ .wb-context-panel{border-left:20px solid var(--wb-line);padding:12px;background:repeating-linear-gradient(0deg,transparent 0 43px,#536d4122 44px 45px),var(--wb-bg)}$ .wb-context-items button{border-radius:0;border:0;border-bottom:1px dashed var(--wb-line);min-height:45px}$ .wb-menu-copy strong{font-family:Georgia}')
add('contextmenus','double-sill-context','$ .wb-context-target{min-height:90px;border:0;border-top:1px solid var(--wb-line);border-bottom:7px double var(--wb-line);background:transparent}$ .wb-context-panel{border-top:8px double var(--wb-line);border-bottom:8px double var(--wb-line);border-radius:0;padding:12px 8px}$ .wb-context-items button{border-top:1px solid var(--wb-line);border-bottom:5px double var(--wb-line);border-radius:0;margin:8px 0;min-height:42px}$ .wb-menu-glyph{border:0}')
add('contextmenus','crosshair-action-context','$ .wb-context-target{min-height:125px;display:grid;grid-template-columns:48px minmax(0,1fr) 34px;border:0;background:transparent;box-shadow:inset 0 0 0 1px var(--wb-line)}$ .wb-context-panel{padding:15px;border-radius:0;background:linear-gradient(90deg,transparent 31px,#a1b58722 32px 33px,transparent 34px),var(--wb-bg)}$ .wb-context-items button{border:0;border-bottom:1px solid var(--wb-line);border-radius:0;min-height:51px;padding-inline:6px}$ .wb-menu-glyph{border:1px solid var(--wb-line);width:21px;height:21px;border-radius:0}$ .wb-context-heading{border-bottom:3px double var(--wb-line)}')
add('contextmenus','arc-label-context','$ .wb-context-target{min-height:125px;display:grid;grid-template-columns:46px minmax(0,1fr);gap:12px;border-radius:36px 36px 4px 4px}$ .wb-context-open{grid-column:2;justify-self:start;width:60px;height:24px;border-radius:20px}$ .wb-context-panel{border-radius:40px 40px 4px 4px;padding:23px 9px 12px}$ .wb-context-items button{border-radius:28px 28px 3px 3px;border:1px solid var(--wb-line);margin:8px 0;padding:14px 11px}$ .wb-menu-glyph{border-radius:50%;border:1px solid var(--wb-line);width:26px;height:26px}')
add('contextmenus','rail-brace-context','$ .wb-context-target{min-height:100px;border:0;border-left:2px solid var(--wb-line);padding-left:30px;background:transparent}$ .wb-context-panel{border:0;border-left:3px solid var(--wb-line);border-right:3px solid var(--wb-line);padding:6px 15px;border-radius:0}$ .wb-context-items button{border:0;border-top:1px solid var(--wb-line);border-bottom:1px solid var(--wb-line);margin:8px 0;border-radius:0;padding:13px 8px}$ .wb-menu-glyph{border:0;border-right:1px solid var(--wb-line);padding-right:7px;width:26px}')
add('contextmenus','folded-label-context','$ .wb-context-target{min-height:100px;background:transparent;border:0;border-bottom:12px solid var(--wb-line);padding:18px 12px}$ .wb-context-panel{border-left:14px solid var(--wb-line);border-radius:0;padding:10px 8px}$ .wb-context-items button{border:0;border-bottom:1px dashed var(--wb-line);border-right:5px solid var(--wb-line);border-radius:0;padding:12px;margin-bottom:8px}$ .wb-context-items button:focus{border-right-width:12px;padding-right:5px}')
add('contextmenus','chamfer-tool-context','$ .wb-context-target{min-height:100px;border:0;border-right:6px solid var(--wb-line);background:transparent}$ .wb-context-panel{border:4px solid var(--wb-line);padding:10px 8px;border-radius:3px}$ .wb-context-items button{min-height:52px;border:1px solid var(--wb-line);border-radius:3px;margin-bottom:7px;box-shadow:inset 0 2px #d8e0e422,0 3px #091b28;gap:14px}$ .wb-menu-glyph{border:0;border-radius:2px;background:#64819733;width:31px;height:31px}')
add('contextmenus','thin-step-context','$ .wb-context-target{min-height:95px;background:transparent;border:0;border-left:5px solid var(--wb-line);padding:13px 17px}$ .wb-context-panel{padding:13px;border:0;border-right:8px solid var(--wb-line)}$ .wb-context-items button{margin:8px 0;border:0;border-bottom:2px solid var(--wb-line);border-radius:0;padding:13px 7px;background:transparent}$ .wb-context-items button:nth-child(2){margin-left:7px;width:calc(100% - 7px)}$ .wb-context-items button:nth-child(3){margin-left:14px;width:calc(100% - 14px)}$ .wb-menu-glyph{border:0;border-bottom:2px solid var(--wb-line);width:24px;height:25px}')
add('contextmenus','shortcut-rail-context','$ .wb-context-target{min-height:85px;padding:14px;border-radius:4px}$ .wb-context-panel{padding:5px;border-radius:4px}$ .wb-context-items button{min-height:40px;border-radius:2px;border:0;border-left:2px solid transparent}$ .wb-context-items button:focus{border-left-color:var(--wb-accent);background:#a1b6d018}$ .wb-menu-glyph{border:0;width:22px}')
add('contextmenus','explained-action-context','$ .wb-context-target{min-height:94px;padding:14px 4px;background:transparent;border:0;border-bottom:1px solid var(--wb-line)}$ .wb-context-object{width:28px;height:35px;box-shadow:none;border:0}$ .wb-context-panel{padding:10px;border-radius:8px}$ .wb-context-items button{padding:13px 8px;min-height:47px;border-bottom:1px solid var(--wb-line);border-radius:0}$ .wb-menu-copy small{font-size:11px;line-height:1.6}$ .wb-menu-glyph{border:0;width:21px}')

# Table identity lives in the reading system as well as its outside frame.
add('tables','ledger-spine-table','$ .wb-data-heading{display:block;border-bottom:0;padding-left:10px}$ .wb-data-heading h3{font-size:32px;margin-bottom:9px}$ .wb-data-total{display:inline-block;margin-top:12px;padding:7px 0;border-top:1px solid var(--wb-line)}$ .wb-data-toolbar{padding-left:10px}$ th{font:12px Georgia;text-transform:none}$ tbody td{padding-block:24px}$ td[data-first-column] .wb-cell-text{font:15px Georgia}$ td[data-align=end] .wb-cell-text{font:18px Consolas}$ .wb-cell-progress>span{height:3px}$ .wb-data-footer{border-top:3px double var(--wb-line)}')
add('tables','floating-row-table','$ .wb-table-scroll{padding:0 8px}$ table{border-collapse:separate;border-spacing:0 13px}$ .wb-data-frame{border:0;background:transparent;padding:0}$ .wb-data-heading{padding:18px 12px;background:#25435c;border-left:4px solid var(--wb-accent)}$ .wb-data-toolbar{padding:14px 12px}$ th{background:transparent;border:0;font:10px Consolas}$ td{padding-block:22px}$ td[data-first-column] .wb-cell-text{font-size:15px}$ .wb-cell-badge{padding:7px 12px;border-radius:30px;border:1px solid var(--wb-line)}$ .wb-cell-progress{flex-direction:column;align-items:end;gap:5px}$ .wb-cell-progress>span{width:70px;min-width:70px;flex:none;height:5px}$ .wb-data-footer{border:1px solid var(--wb-line);border-radius:3px}')
add('tables','numeric-deck-table','$ th[data-column=size],$ th[data-column=progress]{background:#6b527c;font:12px Consolas;border-bottom:4px solid var(--wb-accent)}$ td[data-column=size]{background:#523968;border-bottom:1px solid var(--wb-line)}$ td[data-column=size] .wb-cell-text{font:28px Georgia;letter-spacing:-1px}$ td[data-column=progress]{background:#433054}$ .wb-cell-progress{flex-direction:column;align-items:end;gap:8px}$ .wb-cell-progress b{font:20px Consolas}$ .wb-cell-progress>span{min-width:80px;flex:none}$ .wb-data-total{font:15px Consolas;background:#6d537e;padding:12px}$ tbody td{padding-block:23px}')
add('tables','column-bay-table','$ .wb-data-heading{display:grid;grid-template-columns:minmax(0,1fr) 58px;padding:24px 17px}$ .wb-data-total{font:10px Consolas;line-height:1.8;border-left:1px solid var(--wb-line);padding:10px;text-align:center}$ th{padding-block:24px;font:12px Georgia;vertical-align:bottom;border-top:6px solid var(--wb-line)}$ th:nth-child(odd){border-top-width:12px}$ tbody td{padding-block:23px}$ tbody td:nth-child(2){box-shadow:inset 4px 0 #102e1988}$ .wb-cell-badge{display:block;text-align:center;font:11px Georgia;border:0;border-top:1px solid var(--wb-line);border-bottom:1px solid var(--wb-line)}$ .wb-cell-progress{gap:8px}$ .wb-cell-progress>span{height:4px}')
add('tables','tension-grid-table','$ .wb-data-frame{background:transparent;border:0;border-left:1px solid var(--wb-line);border-right:1px solid var(--wb-line)}$ .wb-data-heading{padding:22px 14px;border-top:3px double var(--wb-line)}$ .wb-data-heading h3{font:30px Arial;letter-spacing:-1px}$ th{background:transparent;border-top:1px solid var(--wb-line);font:10px Consolas}$ tbody td{background:transparent;padding-block:27px;border-right:1px solid var(--wb-line)}$ .wb-cell-badge{border:0;border-radius:0;background:transparent;padding:0 0 3px;border-bottom:2px solid var(--wb-accent);font:12px Consolas}$ .wb-cell-progress>span{height:2px}$ .wb-data-footer{padding-top:23px;border-bottom:3px double var(--wb-line)}')
add('tables','dated-card-table','$ .wb-data-heading{padding:24px 20px;border-bottom:6px double var(--wb-line)}$ .wb-data-heading h3{font:32px Georgia}$ .wb-data-total{font:11px Georgia;transform:rotate(-6deg);border:2px solid var(--wb-line);padding:10px}$ .wb-data-toolbar{background:#d2dfb9;padding:14px 20px}$ .wb-table-search{max-width:100%;border:0;border-bottom:1px solid var(--wb-line);background:transparent}$ th{padding-block:16px;font:12px Georgia;letter-spacing:1px}$ tbody td{padding-block:23px;background:repeating-linear-gradient(0deg,transparent 0 23px,#6c874d11 24px 25px),#e2e9c8}$ .wb-cell-progress{flex-direction:column;gap:5px;align-items:start}$ .wb-cell-progress>span{height:3px;flex:none;width:75px;min-width:75px}$ .wb-cell-progress b{font:12px Georgia}')
add('tables','slotted-record-table','$ .wb-data-heading{display:flex;align-items:center;padding:16px 18px;border-bottom:10px double var(--wb-line)}$ .wb-data-heading h3{font:22px Consolas;letter-spacing:-1px}$ .wb-data-total{writing-mode:vertical-rl;font:10px Consolas;letter-spacing:2px}$ th{font:12px Consolas;padding-block:23px;background:linear-gradient(#68899e,#375c76)}$ tbody td{padding-block:22px;border-bottom:4px solid #12344a;box-shadow:inset 0 2px #a1c0cb11}$ td[data-column=size] .wb-cell-text{font:20px Consolas;border-bottom:1px solid var(--wb-line);padding-bottom:6px}$ .wb-cell-progress>span{height:16px;box-shadow:inset 0 3px #07253788}$ .wb-cell-progress i{background:repeating-linear-gradient(90deg,#a9c7cf 0 4px,#6b919e 4px 7px)}')
add('tables','stepped-header-table','$ .wb-data-heading{display:block;padding:25px 22px 15px}$ .wb-data-heading h3{font:34px Georgia;max-width:200px;line-height:1.1}$ .wb-data-total{display:inline-block;margin-top:13px;border:0;border-left:4px solid var(--wb-line);padding:5px 9px}$ .wb-data-toolbar{margin-left:18px;padding:14px;border-left:4px solid var(--wb-line)}$ th:nth-child(2n){background:#795b8d;border-bottom-width:8px}$ tbody td{padding-block:23px}$ .wb-cell-badge{font:12px Georgia;border-left:5px solid var(--wb-line);padding:8px}$ .wb-cell-progress{flex-direction:column;align-items:end;gap:8px}$ .wb-cell-progress>span{height:7px;width:80px;min-width:80px;flex:none}')
add('tables','margin-ledger-table','$ .wb-data-frame{border-left-width:30px}$ .wb-data-heading{padding:20px 12px;background:transparent}$ .wb-data-heading h3{font:30px Georgia;line-height:1.2}$ .wb-data-toolbar{padding:8px 12px 20px}$ th{background:transparent;border:0;border-bottom:3px double var(--wb-line);font:11px Georgia}$ tbody td{padding-block:24px;border-right:0;border-bottom:1px dashed var(--wb-line)}$ td[data-first-column]{border-left:4px solid var(--wb-line)}$ td[data-first-column] .wb-cell-text{font:16px Georgia}$ .wb-cell-badge{background:transparent;font:11px Georgia;letter-spacing:1px}$ .wb-cell-progress>span{height:2px}$ .wb-data-footer{border-top:0;font-family:Georgia}')
add('tables','row-marker-table','$ .wb-data-frame{border:0;background:transparent}$ .wb-data-heading{padding:18px 13px;border-left:3px solid var(--wb-line);background:transparent}$ .wb-data-heading h3{font:26px Arial;letter-spacing:-.5px}$ .wb-data-toolbar{background:transparent;margin-left:13px;padding:15px 0;border-top:0}$ th{background:transparent;border:0;border-bottom:1px solid var(--wb-line);padding-block:12px}$ tbody td{background:transparent;border-bottom:1px solid var(--wb-line);padding-block:23px}$ tbody tr:nth-child(2n) td{background:#a9c7dc0b}$ tbody tr[data-selected=true] td:first-child{box-shadow:inset 10px 0 var(--wb-accent)}$ .wb-cell-badge{background:transparent;border-radius:0;padding:0;font-size:12px;border-bottom:2px solid var(--wb-line)}$ .wb-data-footer{border-top:0;border-bottom:3px solid var(--wb-line)}')
add('tables','folio-drawer-table','$ .wb-data-heading{display:block;border-bottom:0;padding:25px 20px 12px}$ .wb-data-heading h3{font:31px Georgia;line-height:1.1;max-width:190px}$ .wb-data-total{font:13px Georgia;border-bottom:2px solid var(--wb-line);display:inline-block;margin-top:13px;padding-bottom:7px}$ .wb-data-toolbar{padding:10px 20px 18px}$ th{font:12px Georgia;border-top:3px solid var(--wb-line);padding-block:18px}$ td{padding-block:25px}$ td[data-first-column] .wb-cell-text{font:15px Georgia}$ .wb-cell-badge{padding:6px 11px;font:11px Georgia;border-top:1px solid var(--wb-line);border-bottom:4px solid #1a221baa}$ .wb-data-footer{border-bottom:5px solid var(--wb-line)}')
add('tables','border-weave-table','$ .wb-data-heading{padding:22px 15px;border-bottom:3px dashed var(--wb-line)}$ .wb-data-heading h3{font:28px Georgia;letter-spacing:1px}$ .wb-data-toolbar{background:#a588b016;padding:18px 15px}$ th{background:transparent;border-top:1px dashed var(--wb-line);border-bottom:4px solid var(--wb-line);font:11px Consolas}$ tbody td{padding-block:26px;border-bottom:1px dashed var(--wb-line);border-right:4px solid #a283b433}$ tbody tr:nth-child(2n) td{border-bottom:4px solid #a283b444;background:#aa80bb12}$ .wb-cell-badge{font:12px Georgia;letter-spacing:.5px}$ .wb-cell-progress>span{height:12px;border:1px dashed var(--wb-line)}$ .wb-cell-progress i{background:repeating-linear-gradient(90deg,#c1a3cf 0 3px,#735681 3px 5px)}')

# Wizard progress can be understood without the repeated three-card header.
add('wizards','railhead-workflow','$ .sg-wizard{display:grid;grid-template-columns:62px minmax(0,1fr);gap:20px;padding:20px;background:transparent;border:0;border-left:8px solid var(--sg-line)}$ .sg-wizard-nav{display:flex;flex-direction:column;margin:0;padding:0;gap:24px;border:0;position:relative}$ .sg-wizard-nav:before{content:"";position:absolute;top:20px;bottom:20px;left:26px;width:1px;background:var(--sg-line)}$ .sg-wizard-nav button{position:relative;background:transparent;min-height:62px;border:0;padding:5px}$ .sg-step-index{position:relative;background:var(--sg-bg);border-radius:50%;width:34px;height:34px;font:14px Georgia}$ .sg-wizard-panels{grid-column:2;grid-row:1;padding:15px 0;border:0}$ .sg-wizard-panel h3{font:34px Georgia}$ .sg-wizard-footer{grid-column:1 / -1;border-top:1px solid var(--sg-line);padding-top:15px}')
add('wizards','fabrication-workflow','$ .sg-wizard{padding:18px;background:linear-gradient(#b0c5d011 0 60px,transparent 60px),var(--sg-bg);border:4px solid var(--sg-line)}$ .sg-wizard-nav{gap:0;margin-bottom:24px;counter-reset:stage}$ .sg-wizard-nav button{min-height:77px;border-right:3px solid var(--sg-bg);border-radius:0;padding:10px}$ .sg-step-index{width:38px;height:24px;border:1px solid var(--sg-line);border-radius:1px;font:15px Consolas}$ .sg-step-title{font:9px Consolas;letter-spacing:1px}$ .sg-wizard-panel h3{font:30px Consolas}$ .sg-wizard-fields input{border:2px solid var(--sg-line);border-radius:0;box-shadow:inset 0 4px #081e2c88;padding:16px}$ .sg-wizard-footer{border-top:6px double var(--sg-line);padding-top:15px}')
add('wizards','caption-stage-workflow','$ .sg-wizard{background:transparent;border:0;border-top:2px solid var(--sg-line);padding:23px 15px}$ .sg-wizard-nav{padding-bottom:20px;gap:18px;border-bottom:1px dashed var(--sg-line)}$ .sg-wizard-nav button{padding:0;min-height:70px;border:0;background:transparent}$ .sg-step-index{width:auto;height:auto;font:31px Georgia;background:transparent;border:0;border-radius:0}$ .sg-step-title{font:10px Georgia;letter-spacing:1px}$ .sg-wizard-panels{border:0;padding:20px 0}$ .sg-wizard-panel h3{font:36px Georgia;line-height:1.1}$ .sg-wizard-fields input{background:transparent;border:0;border-bottom:2px solid var(--sg-line);border-radius:0;padding:14px 0}$ .sg-wizard-footer{border-top:1px solid var(--sg-line);padding-top:16px}')
add('wizards','notched-module-workflow','$ .sg-wizard-nav{gap:12px;margin-bottom:26px}$ .sg-wizard-nav button{padding:15px 4px;min-height:90px;display:flex;flex-direction:column;gap:10px;border-radius:0;clip-path:polygon(0 0,100% 0,100% 80%,80% 100%,0 100%)}$ .sg-step-index{font:23px Georgia;width:auto;height:auto;background:transparent;border:0}$ .sg-wizard-panels{padding:20px;border:1px solid var(--sg-line);border-right:7px solid var(--sg-line);background:#16302144}$ .sg-wizard-panel h3{font:28px Georgia}$ .sg-wizard-footer{margin-top:20px;border-left:3px solid var(--sg-line);padding-left:12px}')
add('wizards','outline-room-workflow','$ .sg-wizard{display:grid;grid-template-columns:minmax(0,1fr) 42px;gap:15px;padding:20px;border:1px solid var(--sg-line);box-shadow:none;background:transparent}$ .sg-wizard-nav{grid-column:2;grid-row:1;display:flex;flex-direction:column;gap:10px;margin:0;border:0;padding:0}$ .sg-wizard-nav button{min-height:58px;padding:4px;background:transparent;border:1px solid var(--sg-line)}$ .sg-step-title{font-size:8px}$ .sg-wizard-panels{grid-column:1;grid-row:1;padding:16px;border:1px solid var(--sg-line)}$ .sg-wizard-panel h3{font:28px Arial}$ .sg-wizard-footer{grid-column:1 / -1;padding-top:12px;border-top:1px solid var(--sg-line)}')
add('wizards','corner-anchor-workflow','$ .sg-wizard{background:transparent;border:0;padding:22px;border-left:2px solid var(--sg-line);border-bottom:2px solid var(--sg-line)}$ .sg-wizard-nav{display:flex;justify-content:start;align-items:start;gap:18px;margin-bottom:25px;border:0;padding:0}$ .sg-wizard-nav button{background:transparent;border:0;padding:4px 0;min-height:60px;display:flex;flex-direction:column;align-items:start;gap:7px}$ .sg-step-index{font:22px Georgia;width:36px;height:36px;border-radius:0;border-left:1px solid var(--sg-line);border-bottom:1px solid var(--sg-line)}$ .sg-wizard-panel h3{font:33px Georgia}$ .sg-wizard-fields input{border:0;border-left:3px solid var(--sg-line);border-bottom:1px solid var(--sg-line);border-radius:0;padding:13px;background:transparent}$ .sg-wizard-next{border-radius:0;box-shadow:3px 3px var(--sg-bg),4px 4px var(--sg-line)}')
add('wizards','paper-console-workflow','$ .sg-wizard{padding:23px;border:0;border-left:15px solid #9aac80;border-radius:0;background:repeating-linear-gradient(0deg,transparent 0 29px,#65815311 30px 31px),#e5ead0}$ .sg-wizard-nav{display:flex;justify-content:space-between;gap:6px;border-top:0;border-bottom:3px double var(--sg-line);padding:0 0 14px}$ .sg-wizard-nav button{display:flex;flex-direction:row;gap:7px;min-height:42px;padding:5px;border:0;background:transparent}$ .sg-step-index{font:12px Consolas;border-radius:0;width:24px;height:24px;background:#bacf9e}$ .sg-step-title{font:11px Georgia}$ .sg-wizard-panel h3{font:34px Georgia}$ .sg-wizard-fields input{border-radius:0;background:#f6f6e3;border:0;border-bottom:2px solid #789262;padding:14px 10px}$ .sg-wizard-footer{border-top:1px dashed #809969;padding-top:13px}')
add('wizards','swing-board-workflow','$ .sg-wizard{background:transparent;border:0;border-top:5px double var(--sg-line);padding:22px 10px}$ .sg-wizard-nav{gap:10px;margin-bottom:23px;align-items:start;padding:0;border:0}$ .sg-wizard-nav button{min-height:76px;border-top:7px solid var(--sg-line);border-radius:0;padding-top:13px;transform:rotate(-5deg);transform-origin:50% 0;box-shadow:0 4px 0 #18301c}$ .sg-wizard-nav li:nth-child(2) button{transform:rotate(4deg)}$ .sg-wizard-nav li:nth-child(3) button{transform:rotate(-3deg)}$ .sg-wizard-nav button[aria-current=step]{transform:rotate(0);border-top-color:var(--sg-a)}$ .sg-wizard-panels{padding:21px 15px;background:var(--sg-bg);border-left:1px solid var(--sg-line);border-right:1px solid var(--sg-line)}$ .sg-wizard-panel h3{font:29px Georgia}')
add('wizards','swept-chapter-workflow','$ .sg-wizard-nav{gap:0;margin:0 -10px 24px;padding:0;border-bottom:0}$ .sg-wizard-nav button{display:flex;flex-direction:column-reverse;justify-content:center;gap:8px;min-height:78px;border:0;border-radius:0;background:transparent;transform:skewY(-4deg);border-bottom:5px solid var(--sg-line)}$ .sg-wizard-nav button>*{transform:skewY(4deg)}$ .sg-step-title{font:13px Georgia}$ .sg-step-index{background:none;border:0;font:10px Consolas;height:16px}$ .sg-wizard-panel h3{font:35px Georgia;line-height:1.1}$ .sg-wizard-fields input{border:0;border-bottom:3px solid var(--sg-line);border-radius:0;background:#15354144;padding:16px}$ .sg-wizard-footer{border-top:1px solid var(--sg-line);padding-top:16px}')
add('wizards','hinge-rail-workflow','$ .sg-wizard{grid-template-columns:34px minmax(0,1fr);gap:15px;border:0;border-left:16px solid #8d7454;background:transparent;padding:20px 10px}$ .sg-wizard-nav{gap:18px}$ .sg-wizard-nav button{min-height:62px;position:relative;border:0;padding:0;background:transparent}$ .sg-step-index{font:12px Georgia;width:24px;height:24px;border-radius:50%;background:#4d4132;border:1px solid var(--sg-line)}$ .sg-step-title{font:8px Georgia}$ .sg-wizard-panels{background:var(--sg-bg);border:0;border-left:3px double var(--sg-line);padding:20px 14px}$ .sg-wizard-panel h3{font:28px Georgia}$ .sg-wizard-footer{grid-column:1 / -1;border-top:3px double var(--sg-line);padding-top:16px}')

add('pagination','upper-deck-pages','$ .ff-pages{padding:0;background:transparent;border:0;border-top:1px solid var(--ff-line);border-bottom:5px double var(--ff-line);gap:6px;padding-block:15px 20px}$ .ff-pages a,$ .ff-pages button{border-radius:0 0 10px 10px;min-height:44px;border:1px solid var(--ff-line);background:transparent}$ .ff-pages [aria-current]{transform:translateY(15px);min-height:52px;border-radius:0;background:#b79acd}$ .ff-page-info{border:0;padding-top:25px;font-size:13px}')
add('pagination','cog-register-pages','$ .ff-pages{border:0;background:transparent;border-top:6px double var(--ff-line);border-bottom:6px double var(--ff-line);padding-block:11px;gap:0}$ .ff-pages a,$ .ff-pages button{border-right:5px solid var(--ff-base);border-left:1px solid var(--ff-line);border-top:0;border-bottom:0;border-radius:0;min-height:51px;box-shadow:inset 0 9px #ae986c,inset 0 12px #332b21;background:#51482e;font:13px Consolas}$ .ff-pages [aria-current]{box-shadow:inset 0 9px #e3cca0,inset 0 12px #332b21;background:#a99167;color:#222819}$ .ff-page-info{font-family:Consolas}')
add('pagination','split-level-pages','$ .ff-pages{border:0;background:transparent;border-top:1px solid var(--ff-line);border-bottom:1px solid var(--ff-line);padding:15px 0 22px;gap:6px}$ .ff-pages a,$ .ff-pages button{border:0;border-bottom:4px solid var(--ff-line);border-radius:0;min-height:45px;background:transparent}$ .ff-pages [data-page]:nth-child(2n){transform:translateY(10px)}$ .ff-pages [aria-current]{background:#b5c99a;color:#20301d;border-top:3px solid var(--ff-line);border-bottom-width:9px;transform:translateY(-5px)}')
add('badges','disc-tab-tag','$ .ff-tag{background:transparent;border:0;border-bottom:1px solid var(--ff-line);border-radius:0;padding-left:0;gap:9px;min-height:38px}$ .ff-tag svg{width:25px;height:25px;background:#345d71;border:2px solid var(--ff-line);border-radius:50%;padding:4px}$ .ff-tag small{background:#345d71;border:0;border-radius:50%;padding:4px;min-width:22px;min-height:22px;display:grid;place-items:center}$ .ff-tag[data-selected=true]{background:transparent;border-bottom:3px solid var(--ff-accent)}')
add('badges','fold-line-tag','$ .ff-tag{border:0;border-bottom:5px solid #985a77;border-radius:0;padding:10px 12px 14px;transform:skewY(-4deg);background:linear-gradient(transparent 65%,#9f658555 65%),#5d3c52}$ .ff-tag:nth-child(2){transform:skewY(4deg)}$ .ff-tag>*{transform:skewY(4deg)}$ .ff-tag svg{display:none}$ .ff-tag[data-selected=true]{border-bottom-color:var(--ff-accent)}')
add('badges','chamfered-tag','$ .ff-tag{background:transparent;border:1px solid var(--ff-line);border-radius:0;clip-path:none;padding:8px 13px;border-left:8px solid var(--ff-line);position:relative}$ .ff-tag:before{content:"";position:absolute;right:0;top:0;width:8px;height:8px;background:var(--ff-line);clip-path:polygon(0 0,100% 0,100% 100%)}$ .ff-tag small{border-left:1px solid var(--ff-line);padding-left:8px}$ .ff-tag[data-selected=true]{background:#6b9494;border-left-color:var(--ff-accent)}')
add('ratings','segmented-seal-rating','$ .sg-rating-scale{gap:0;border-top:1px solid var(--sg-line);border-bottom:1px solid var(--sg-line);padding:12px 0}$ .sg-rating-unit{border-right:1px solid var(--sg-line)}$ .sg-rating-unit:last-child{border-right:0}$ .sg-rating-form{border:1px solid var(--sg-line);box-shadow:none;border-radius:50%;width:30px;height:30px;transform:none;background:transparent}$ .sg-rating-unit[data-filled=true] .sg-rating-form{background:#76a9a6;border:3px double #cce2d7}$ .sg-rating-number{font:9px Consolas;letter-spacing:1px}')

add('uploads','clip-frame-dropzone','$ .ff-dropzone{padding:28px 25px 22px 66px;min-height:155px;background:transparent;border:0;border-left:8px double var(--ff-line);border-right:8px double var(--ff-line);border-top:1px solid var(--ff-line);border-bottom:1px solid var(--ff-line)}$ .ff-upload-symbol{left:15px;right:auto;top:35px;width:32px;height:45px;transform:rotate(-8deg)}$ .ff-dropzone strong{font:22px Georgia}$ [data-upload-limits]{margin-top:22px;padding-top:8px;border-top:1px solid var(--ff-line)}')
add('uploads','seam-pocket-dropzone','$ .ff-dropzone{min-height:172px;padding:32px 23px 42px;border-radius:5px 5px 52px 52px;border:1px dashed var(--ff-line);border-top:12px solid var(--ff-line);background:radial-gradient(ellipse at bottom,#8b745b55,transparent 80%),#493d31}$ .ff-upload-symbol{right:18px;top:22px;transform:rotate(7deg)}$ .ff-dropzone strong{font:20px Georgia}$ [data-upload-limits]{border-bottom:1px dashed var(--ff-line);padding-bottom:12px}')
add('uploads','file-berth-dropzone','$ .ff-dropzone{display:flex;flex-direction:column;align-items:center;justify-content:center;text-align:center;min-height:185px;border:0;border-bottom:9px solid var(--ff-line);border-radius:80px 80px 3px 3px;background:linear-gradient(#38513a,#203c2a)}$ .ff-upload-symbol{position:relative;top:auto;right:auto;order:-1;margin:0 auto 16px;width:45px;height:55px;border-radius:22px 22px 3px 3px;box-shadow:none}$ .ff-dropzone strong{font:20px Georgia}$ [data-upload-limits]{margin-top:16px}')
add('uploads','apron-dropzone','$ .ff-dropzone{padding:21px;min-height:155px;border:0;border-top:8px double var(--ff-line);border-bottom:14px solid var(--ff-line);background:transparent;border-radius:0}$ .ff-dropzone strong{font:22px Georgia;max-width:150px;line-height:1.2}$ .ff-upload-symbol{width:44px;height:44px;border-radius:50%;border:3px double var(--ff-line);top:24px;right:20px}$ [data-upload-limits]{border-top:1px solid var(--ff-line);padding-top:11px;margin-top:26px}')
add('uploads','offset-crate-dropzone','$ .ff-dropzone{display:grid;grid-template-columns:minmax(0,1fr) 45px;gap:12px;min-height:140px;box-shadow:8px 8px var(--ff-base),9px 9px var(--ff-line);border:1px solid var(--ff-line);padding:22px;background:transparent}$ .ff-dropzone strong{font:25px Georgia;grid-column:1;grid-row:1}$ .ff-upload-symbol{position:relative;inset:auto;grid-column:2;grid-row:1 / 3;transform:none;height:60px;width:40px}$ .ff-dropzone>span:not(.ff-upload-symbol){grid-column:1;grid-row:2}$ [data-upload-limits]{grid-column:1 / -1;border-top:1px dashed var(--ff-line);padding-top:10px}')
add('uploads','file-list-dropzone','$ .ff-dropzone{padding:15px 54px 15px 15px;min-height:75px;display:flex;flex-wrap:wrap;gap:8px;background:transparent;border:0;border-bottom:1px solid var(--ff-line);border-radius:0}$ .ff-dropzone strong{font:13px Arial}$ .ff-dropzone>span:not(.ff-upload-symbol){font:11px Arial}$ [data-upload-limits]{width:100%;margin:0}$ .ff-upload-symbol{top:20px;right:5px;border:0;background:transparent;width:28px;height:28px}$ .ff-upload-file{border:0;border-bottom:1px solid var(--ff-line);border-radius:0;padding:14px 0;background:transparent}')

add('colors','spectral-register','$ .sg-color-panel{display:grid;grid-template-columns:minmax(0,1fr) 48px;gap:18px;padding:20px;border-left:0;border-top:8px solid var(--sg-line);border-bottom:1px solid var(--sg-line);background:transparent}$ .sg-color-heading{grid-column:1 / -1}$ .sg-color-workspace{grid-column:1;min-height:155px;height:155px}$ .sg-color-controls{grid-column:1;grid-row:3}$ .sg-color-palette{grid-column:2;grid-row:2 / 4;display:flex;flex-direction:column;justify-content:space-between;gap:8px;padding:0;border:0}$ .sg-color-palette button{width:32px;height:32px;border-radius:50%}$ .sg-color-entry{grid-column:1 / -1}')
add('colors','chromatic-windowpane','$ .sg-color-panel{background:transparent;border:0;border-left:2px solid var(--sg-line);border-right:2px solid var(--sg-line);padding:21px 16px}$ .sg-color-workspace{height:170px;background-blend-mode:normal;box-shadow:inset 0 0 0 6px #7594aa88;border:0;border-radius:50% 50% 0 0}$ .sg-color-controls{padding:17px 0;border:0;border-top:5px double var(--sg-line);margin-top:15px}$ .sg-color-palette{border-top:1px solid var(--sg-line);padding-top:15px}$ .sg-color-palette button{width:27px;height:27px;border-radius:50%}')
add('colors','gradient-desk','$ .sg-color-panel{display:grid;grid-template-columns:44px minmax(0,1fr);gap:17px;padding:22px;border:0;background:transparent;border-bottom:7px double var(--sg-line)}$ .sg-color-heading{grid-column:1 / -1}$ .sg-color-workspace{grid-column:2;height:160px;margin:0}$ .sg-color-controls{grid-column:2;padding:0;border:0}$ .sg-color-palette{grid-column:1;grid-row:2 / 4;display:flex;flex-direction:column;justify-content:space-between;padding:0;border:0;gap:8px}$ .sg-color-palette button{width:27px;height:27px;border-radius:2px;box-shadow:3px 3px #7b63944d}$ .sg-color-entry{grid-column:1 / -1}')
add('colors','color-plate-trio','$ .sg-color-panel{padding:22px;background:transparent;border:0;border-top:2px solid var(--sg-line)}$ .sg-color-workspace{height:135px;box-shadow:none;border:1px solid var(--sg-line);border-radius:0}$ .sg-color-controls{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px;margin-top:16px;padding:0;border:0}$ .sg-color-axis{display:flex;flex-direction:column;gap:13px;border:1px solid var(--sg-line);padding:13px 7px;background:#7b9f7133}$ .sg-color-axis>span,$ .sg-color-axis output{font:9px Consolas}$ .sg-color-axis input{width:100%;margin:0}$ .sg-color-palette{padding-top:18px;border-top:0}$ .sg-color-entry{margin-top:16px;border-top:3px double var(--sg-line)}')

def main():
 if any('Final visual review:' in p.read_text(encoding='utf-8') for p in root.rglob('styles.css')):
  print('Canonical files include later refinements; this provisional patch is not reapplied.');return
 for (cat,id),css in changes.items():
  file=root/cat/id/'styles.css';s=file.read_text(encoding='utf-8');kind=re.search(r'class="([^"]+)',(file.parent/'markup.html').read_text(encoding='utf-8'))[1].split()[0];scope='.'+kind+'.sop-'+id
  marker='/* Visual review: composition and state separation. */'
  if marker in s:s=s[:s.index(marker)]
  file.write_text(s+'\n'+marker+'\n'+css.replace('$',scope)+'\n',encoding='utf-8')
 # Preserve the full rectangular SV interaction map inside the new workspaces.
 for id in ['spectral-register','chromatic-windowpane','gradient-desk','color-plate-trio']:
  file=root/'colors'/id/'styles.css';s=file.read_text(encoding='utf-8');s+='\n.sop-sig.sop-'+id+' .sg-color-workspace .sg-color-sv{height:100%;min-height:0}\n';file.write_text(s,encoding='utf-8')
 # Truthful classification and description in each public channel.
 for id,cat,desc in [('ruled-caption-field','textboxes',None),('current-location-trail','breadcrumbs','現在地を一つの面に分け、経路と到着地点を読み分ける。')]:
  part=root/cat/id;meta=json.loads((part/'meta.json').read_text(encoding='utf-8'))
  if desc:
   old=meta['description'];meta.update(description=desc,tagline=desc,tags=[t.replace(old,desc) for t in meta['tags']]);(part/'meta.json').write_text(json.dumps(meta,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
   for p in [part/'prompt.md',part/'usage.md',part/'styles.css']:
    s=p.read_text(encoding='utf-8');p.write_text(s.replace(old,desc),encoding='utf-8')
   specs=json.loads((report/'designs.json').read_text(encoding='utf-8'));next(d for d in specs if d['id']==id)['description']=desc;(report/'designs.json').write_text(json.dumps(specs,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
  else:
   p=part/'prompt.md';s=p.read_text(encoding='utf-8').replace('Aタイプ','Bタイプ').replace('Type A','Type B');p.write_text(s,encoding='utf-8')
 (report/'refined-parts.json').write_text(json.dumps([{'category':cat,'id':id}for cat,id in changes],ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
 print('Refined',len(changes),'individual compositions')
if __name__=='__main__':main()
