"use strict";
const fs = require('node:fs');
const path = require('node:path');
const {ROOT, ts, bundle, transpile} = require('./compiler.cjs');
const {validateArchivePath} = require('../src/shared/archive.js');
const read = name => fs.readFileSync(path.join(ROOT, name), 'utf8');
const write = (name, code) => {const p = path.join(ROOT, name); fs.mkdirSync(path.dirname(p), {recursive:true}); fs.writeFileSync(p, code);};
const registry = JSON.parse(read('src/catalog/registry.json'));
const FORMAT_PAIRS = {tsx: 'tsx', jsx: 'tsx', ts: 'ts', js: 'ts'};
/** Export paths must be local to the downloaded component package, never src/ internals. */
function exportCode(code, language, format, name) {
  code = code.replace(/(['"])(?:\.\.\/)+shared\/([^'"\n]+)\1/g, (_, q, dep) => `${q}./${dep}${q}`)
             .replace(/(['"])\.\.\/styles\.css\1/g, (_, q) => `${q}./styles.css${q}`);
  if ((format === 'js' || format === 'jsx') && /\.(ts|tsx)$/.test(name)) {
    code = transpile(code, name, ts.ModuleKind.ESNext, ts.JsxEmit.Preserve);
    // Native browser ESM requires the .js extension. Bundler-based React imports may omit it.
    code = code.replace(/(from\s+|import\s*)(['"])(\.\.?\/[^'"\n]+)\2/g, (all, prefix, q, dep) => {
      if (format === 'js' && !path.posix.extname(dep)) return `${prefix}${q}${dep}.js${q}`;
      return all;
    });
  }
  if (format === 'js' && language === 'html') code = code.replaceAll('./main.ts', './main.js');
  return code;
}
function build() {
  fs.rmSync(path.join(ROOT, 'packages'), {recursive:true, force:true});
  const parts = [];
  const seen = new Set();
  const mounts = [];
  for (const base of registry) {
    validateArchivePath(base);
    const meta = JSON.parse(read(`${base}/meta.json`));
    if (!/^[a-z][a-z0-9-]*$/.test(meta.id) || seen.has(meta.id)) throw new Error(`Invalid or duplicate part ID: ${meta.id}`);
    seen.add(meta.id);
    const files = {};
    const layout = JSON.parse(read(`${base}/exports.json`));
    for (const [format, inputFormat] of Object.entries(FORMAT_PAIRS)) {
      files[format] = layout[inputFormat].map(file => {
        validateArchivePath(file.name); validateArchivePath(file.source);
        const name = (format === 'js' || format === 'jsx') ? file.name.replace(/\.tsx$/, '.jsx').replace(/\.ts$/, '.js') : file.name;
        const code = exportCode(read(file.source), file.language, format, file.name);
        const language = name.endsWith('.jsx') ? 'jsx' : name.endsWith('.js') ? 'javascript' : file.language;
        return {name, code, language, group: file.group};
      });
    }
    const preview = {
      'index.html': read(`${base}/demo/index.html`),
      'styles.css': read(`${base}/demo/frame.css`) + read(`${base}/styles.css`),
      'app.js': bundle(`${base}/demo/main.ts`)
    };
    const part = {...meta, markup: read(`${base}/markup.html`), usage: read(`${base}/usage.md`), prompt: read(`${base}/prompt.md`), files, preview};
    parts.push(part);
    mounts.push(`${JSON.stringify(meta.id)}:require(${JSON.stringify('../' + base.slice(4) + '/vanilla/init.ts')}).init`);
    for (const [format, list] of Object.entries(files)) {
      for (const file of list) write(`packages/${meta.id}/${format}/${file.name}`, file.code);
      write(`packages/${meta.id}/${format}/README.md`, part.usage);
      write(`packages/${meta.id}/${format}/PROMPT.md`, `# ${meta.name} / ${format.toUpperCase()}\n\n${part.prompt}\n\n## 使い方\n${part.usage}\n\n## ソースコード\n` + list.map(f => `\n### ${f.name}\n\n\`\`\`${f.language}\n${f.code}\n\`\`\`\n`).join(''));
    }
    for (const [name, text] of Object.entries(preview)) write(`packages/${meta.id}/preview/${name}`, text);
  }
  parts.sort((a,b) => a.order - b.order);
  write('src/catalog/registry.generated.js', '/* Generated by scripts/build.cjs. Edit registry.json instead. */\nexports.mounts = {\n' + mounts.join(',\n') + '\n};\n');
  write('assets/catalog.js', '/* Generated from src/parts. */\nwindow.SOP_CATALOG = ' + JSON.stringify(parts).replaceAll('<', '\\u003c') + ';\n');
  write('assets/styles.css', '/* Generated from component styles + gallery.css. */\n' + parts.map(p => p.files.ts.find(f => f.name === 'styles.css').code).join('\n') + '\n' + read('src/app/gallery.css'));
  write('assets/app.js', bundle('src/app/gallery.js'));
  for (const name of ['prism.js', 'jszip.js']) write(`assets/vendor/${name}`, read(`vendor/${name}`));
  write('index.html', read('src/index.html'));
  fs.rmSync(path.join(ROOT, 'dist'), {recursive:true, force:true});
  fs.mkdirSync(path.join(ROOT, 'dist'), {recursive:true});
  fs.copyFileSync(path.join(ROOT, 'index.html'), path.join(ROOT, 'dist/index.html'));
  fs.cpSync(path.join(ROOT, 'assets'), path.join(ROOT, 'dist/assets'), {recursive:true});
  fs.writeFileSync(path.join(ROOT, 'dist/.nojekyll'), '');
  console.log(`Built ${parts.length} parts / ${parts.length * 4} formats / ${parts.reduce((n,p)=>n+Object.values(p.files).reduce((m,f)=>m+f.length,0),0)} source files. No single-file HTML generated.`);
  return parts;
}
if (require.main === module) build();
module.exports = {build, exportCode};
