"use strict";
const fs = require('node:fs');
const path = require('node:path');
const ts = require('typescript');
const ROOT = path.resolve(__dirname, '..');
const relative = file => path.relative(ROOT, file).split(path.sep).join('/');
function resolveFile(from, request) {
  if (!request.startsWith('.')) throw new Error(`External runtime dependency is not bundled: ${request}`);
  const base = path.resolve(path.dirname(from), request);
  const candidates = [base, ...['.ts', '.js', '.tsx', '.jsx'].map(ext => base + ext)];
  const file = candidates.find(f => fs.existsSync(f) && fs.statSync(f).isFile());
  if (!file || !file.startsWith(ROOT + path.sep)) throw new Error(`Missing local dependency: ${relative(from)} -> ${request}`);
  return file;
}
function transpile(code, filename, module = ts.ModuleKind.CommonJS, jsx = ts.JsxEmit.React) {
  const result = ts.transpileModule(code, {fileName: filename, reportDiagnostics: true,
    compilerOptions: {target: ts.ScriptTarget.ES2022, module, jsx, esModuleInterop: true, newLine: ts.NewLineKind.LineFeed}});
  const errors = (result.diagnostics || []).filter(d => d.category === ts.DiagnosticCategory.Error);
  if (errors.length) throw new Error(errors.map(d => ts.flattenDiagnosticMessageText(d.messageText, '\n')).join('\n'));
  return result.outputText;
}
/** Build a small, deterministic, offline-capable bundle from local JS/TS modules. */
function bundle(entry) {
  const modules = new Map();
  function visit(file) {
    const id = relative(file);
    if (modules.has(id)) return id;
    modules.set(id, '');
    let code = transpile(fs.readFileSync(file, 'utf8'), file);
    code = code.replace(/require\((['"])([^'"\n]+)\1\)/g, (_, quote, request) => {
      const dependency = resolveFile(file, request);
      return `require(${JSON.stringify(visit(dependency))})`;
    });
    modules.set(id, code);
    return id;
  }
  const id = visit(path.resolve(ROOT, entry));
  return '/* Generated from src/ by npm run build. Do not edit this file. */\n' +
    "(function(){'use strict';const modules={\n" +
    [...modules].map(([name, code]) => `${JSON.stringify(name)}:function(module,exports,require){\n${code}\n}`).join(',\n') +
    '\n};const cache={};function require(id){if(cache[id])return cache[id].exports;const module=cache[id]={exports:{}};if(!modules[id])throw new Error(\'Unknown module \'+id);modules[id](module,module.exports,require);return module.exports;}require(' + JSON.stringify(id) + ');})();\n';
}
module.exports = {ROOT, ts, bundle, transpile, relative};
