import json,hashlib
root='docs/design-refinement-225/batches/B001';m=json.load(open(root+'/measurements-complete-1.json'));manifest=json.load(open(root+'/review-input-1.json'));assert all(hashlib.sha256(open(root+'/snapshot/round-1/source/'+p.split('/')[3]+'/'+('/'.join(p.split('/')[4:])),'rb').read()).hexdigest()==h for p,h in manifest['sourceHashes'].items())
notes={24:'上下の罫線はhoverでもskewせず、蛇腹のみ0.65→1へ補間する。入口・解除・再進入に途中値があり、本文移動0px。Aの紙面と収納の構造を維持。320px・長見出し・動き軽減・強制色も確認。非操作装飾なのでキーボード起動は対象外。',30:'旧矩形box-shadowは通常/hoverともnone。抜き型の面と下紙の回転は残り、入口・解除・再進入に途中値がある。本文移動0px。320pxの下紙の装飾上の張出しは本文を切らず、ページ横溢れなし。非操作装飾なのでキーボード起動は対象外。',89:'公開済みの主ラベルは旧1.07:1から7.27:1へ改善。320px・長ラベル・Enter選択とEscape・強制色は機能する。ただし10pxの補助文はhover/active背景で4.19:1となるため、通常文字4.5:1を満たす色調整が必要。',182:'未選択文字#eff2eeをhover/解除/再進入でも保持し、面#526870との比率5.21:1。320pxで各セルが等幅（portable102.5px、gallery75px）。長ラベルはセル内に折り返す。縦指定も全セル等幅・82px高で成立。矢印キー選択、reduced/forcedを確認。',422:'展開メニューObjectsはhoverでも#e6eff4を保持し、面#28485eとの比率8.27:1。下線で状態を示し文字移動0px。320px/長文/強制色を確認。Enterで開いてリンクへfocus、Escapeで閉じる。'}
parts=[]
for n in [24,30,89,146,147,148,149,150,182,422]:
 rows=[r for r in m['data'] if r['number']==n];assert len(rows)==2 and not any(r.get('error') for r in rows)
 note=notes.get(n,'矢印translateは入口40msで0と2pxの途中、hoverで2px/-2px、解除/再進入も途中値を通り復帰する。350msのtranslate transitionを実測。文字・クリック領域は固定。320px/長ラベル、キーボードfocus outline、reducedでanimationなし、forcedの可読性を確認。Bの既存の密度・形状を維持。')
 finding=[]
 if n==89:finding=[{'kind':'contrast','severity':'moderate','status':'reproduced','description':'hover/active時の補助文「閲覧できる状態です」は10px、前景rgb(168,183,197) #a8b7c5、背景rgb(59,78,96) #3b4e60でコントラスト4.1907:1。主ラベルは7.2665:1へ改善したが、小さい通常文字の4.5:1に未達。','scope':'実galleryで補助文のcomputed色を実測。portableも同じCSS変数と色、背景を確認。未選択の候補をhoverすると再現し、data-active保持中も続く。','suggestion':'暗い候補面の構造を保ち、補助文字を少し明るくするかactive面を少し暗くして4.5:1以上にする。','evidence':['measurements-89-1.json','evidence-1/outline-row-select-gallery-hover.png','snapshot/round-1/source/outline-row-select/styles.css']}]
 parts.append({'id':rows[0]['id'],'number':n,'verdict':'changes_required' if n==89 else 'pass','note':note,'findings':finding,'evidence':['measurements-complete-1.json']+list(dict.fromkeys(p for r in rows for p in r['evidence']))})
r={'batch':'B001','round':1,'overall':'changes_required','parts':parts,'counts':{'pass':9,'changes_required':1},'reviewer':'Independent reviewer','sourceHashesVerified':True,'snapshot':'snapshot/round-1/index.html','coverage':{'parts':10,'modes':['frozen portable','actual gallery with matching author hashes'],'states':['normal','hover entry 40ms','hover','exit 60ms','reentry 60ms','returned','320px','long labels','keyboard as applicable','prefers-reduced-motion','forced-colors'],'imagesVisuallyReviewed':True},'limitations':['実測した状態と対象についての判定であり、全入力・全ブラウザの無欠陥保証ではない。','React固有の実行経路は今回の実ブラウザ検査対象外。','galleryのR089は幅変更時に閉じた後、開き直して狭幅・長文・強制色を再検査した。']}
json.dump(r,open(root+'/review-1.json','w'),ensure_ascii=False,indent=2)
with open(root+'/review-1.md','w') as f:
 f.write('# B001 / round 1 独立検査\n\n判定：**changes_required**（9件 pass、1件 changes_required）。\n\n凍結portableと実galleryの著者hash一致を検査開始時に確認。round1凍結ソースのhashも照合済み。終了時には主担当がR089のround2修正を開始したため、現在の著者全件一致は主張しない。著者ファイルは編集していない。\n\n## 修正が必要な一点\n\nR089 outline-row-select の小さい補助文は、hover/activeで #a8b7c5 / #3b4e60、**4.19:1**。主ラベルは **7.27:1** へ改善したが、10pxの通常文字の4.5:1に未達。補助色またはactive面を微調整してほしい。デザインの主観ではなくcomputed色からの再現結果。\n\n## 個別判定\n\n')
 for p in parts:f.write(f"- R{p['number']:03} {p['id']}: **{p['verdict']}** — {p['note']}\n")
 f.write('\n## 証拠・範囲\n\n20経路（10件×portable/gallery）の測定は measurements-complete-1.json。画像は evidence-1/。通常、hover入口/解除/再進入、狭幅、長文、強制色を視認し、動き軽減とkeyboardを実操作・computedで確認した。R182の縦指定も追加確認済み。\n\n全入力・全ブラウザの無欠陥保証ではない。React固有の実行経路は今回は未実行。過去の合格は今回判定の根拠にしていない。\n')
print(r['counts'])
