from pathlib import Path
import json,hashlib
from PIL import Image,ImageChops
p=Path(__file__).parent;m=json.load(open(p/'review-input-5.json'));bad=[f for f,h in m['sourceHashes'].items()if hashlib.sha256(Path(f).read_bytes()).hexdigest()!=h];assert not bad;(p/'hash-verification-final-5.json').write_text(json.dumps({'matched':len(m['sourceHashes']),'mismatches':bad},indent=2)+'\n')
a=json.load(open(p/'measurements-5.json'));b=json.load(open(p/'measurements-react-5.json'));assert len(a)==10 and len(b)==24;assert not any(r.get('error')or r.get('errors')or any(not c['pass']for c in r.get('checks',[]))for r in a+b)
pixels=[]
for r in json.load(open(p/'measurements-steady-seams-5.json')):
 id=r['id'];mode='forced'if r['forced']else'normal';aa=Image.open(p/'evidence-5'/f'{id}-steady-seam-{mode}-start.png').convert('RGB');bb=Image.open(p/'evidence-5'/f'{id}-steady-seam-{mode}-end.png').convert('RGB');d=ImageChops.difference(aa,bb);pixels.append({'id':id,'mode':mode,'changedPixelsAbove10':sum(1 for x in d.getdata()if max(x)>10)})
(p/'seam-summary-5.json').write_text(json.dumps(pixels,indent=2)+'\n')
notes={701:'六つのアーチ/厚い側面/床の足が奥行きの回廊を作る。筒の伸縮R696とは主構造が分離。',708:'厚い羽根と中心空隙を連動させる構造はAとして成立。旧偶数羽根の色規則が周期端の色飛びを起こす。',710:'上下の実流路と中央仕切り、逆向きの小片が明快。輪が重なる旧形を解消し、B待機列と機構が異なる。',717:'三段の外側蝶番/両開き戸/中央の把手が同じ開き角で連動。単なる折板反復とは分離。',728:'細い囲いの内部を明るさが順送する小型待機列。中央配置とstatus12pxを維持し、Aの立体機構と用途が異なる。'}
parts=[]
for t in json.load(open('docs/design-refinement-225/targets.json')):
 if t['batch']!='B023':continue
 n=t['number'];finds=[]
 if n==708:finds=[{'kind':'animation_loop_color_discontinuity','description':'旧:nth-child(even)のborder-color:#93b3b4が新羽根にも残る。奇数は明るい縁/濃い側面、偶数は単色の縁。60度送りの終了直前と次周期開始で位置集合は同じだが、その場の縁/側面色が交代する。定常4000ms対7999.9msでRGB差10超の画素1890。forcedは同色で差0。','recommendation':'旧偶数色規則を削除または新しい6羽根の全境界色を統一して六回対称にする。終了直前と開始を画素でも比較する。','evidence':['measurements-steady-seams-5.json','seam-summary-5.json','evidence-5/segment-orbit-loader-seam-normal-start.png','evidence-5/segment-orbit-loader-seam-normal-end.png']}]
 parts.append(dict(id=t['id'],number=n,verdict='changes_required'if finds else'pass',note=notes[n],findings=finds,evidence=[f'evidence-5/sheet-{t["id"]}-normal.jpg',f'evidence-5/sheet-{t["id"]}-forced.jpg','measurements-5.json','measurements-react-5.json'],reviewed={'round':5,'actualGallery':True,'portable':True,'hoverEntryExitReentry':True,'phase6AndLoopBoundary':True,'narrow320RTL':True,'longStatus':t['category']=='loaders','forcedReducedPaused':True,'react4Formats':True,'ABVisualComparison':True}))
coverage={'sourceHashesMatched':len(m['sourceHashes']),'nativeLifecycleChecks':50,'reactChecks':32,'reactPlacements':20,'primaryRows':10,'loopBoundaryConditions':10,'imagesViewed':['5 normal sheets (12 states each)','5 forced sheets (8 states each)','gallery20 images','React15 images','R708 seam pair','R728 seam pair','R710 portable rest close'],'pendingRequiredMeasurements':[],'limitations':['nativeフォーム/入力/選択を持たない装飾とローダー。ライフサイクル・status更新・停止/再開・reduced・destroyを確認。','周期比較は初回正delayの待機を除外して定常周期を比較。slim初回待機のopacity差を周期飛びとは判定しない。','初回fixtureはornament destroyが既存属性を復元する仕様を誤りnullと比較。復元前属性を保存する正しい比較へ修正し全50checks再実行。','初回Reactfixtureのchildrenは内部dangerouslySetInnerHTMLと競合。余分なchildren/無関係イベントを外して4形式再実行しpageerror0/unmount残存0。','Chromiumの指定状態検査であり無欠陥保証ではない。']}
r=dict(batch='B023',round=5,overall='changes_required',parts=parts,coverage=coverage);(p/'review-5.json').write_text(json.dumps(r,ensure_ascii=False,indent=2)+'\n');lines=['# B023 round 5 独立検査','','4 pass / 1 changes_required。R708の周期端の色飛びを修正。','','| ID | 判定・根拠 |','|---|---|']+[f'| R{x["number"]} | {x["verdict"]}: {x["note"]} |'for x in parts]+['','gallery/portable50ライフサイクルchecks、React4形式32checks成功。通常/forcedの6位相と周期終了直前を視認し、他4件の定常周期は画素差10超が0。R708は位置が一致しても旧偶数色の非対称が残る。作者/共有は検査担当未変更。詳細は[review-5.json](review-5.json)。'];(p/'review-5.md').write_text('\n'.join(lines)+'\n');print('4 pass 1 changes_required saved')
